### ISSUE TITLE
Feature request: set option to auto delete spot if it received 'x' number of spam reports

### ISSUE THREAD

**Issue by kooimens** [spotweb/spotweb#105]

**Comment by mesa57** [comment]
An option to hide those spots from the view would be just as effective.

**Comment by Wally73** [comment]
imo a very bad idea since some ppl just like to click on the report button if they can't leech something 

its better to use blacklist ;)

**Comment by kooimens** [comment]
I think hiding those spots would not been just as effective because then external apps, using spotweb as indexer, can still pick up those spots, right?

**Comment by mesa57** [comment]
Depends on how it is implemented.

**Comment by kooimens** [comment]
I concluded that my blacklist/whitelist were old. Updated with this guide:
https://github.com/spotweb/spotweb/wiki/Fix-blacklist-and-whitelist-problems
Everything works fine now. Closing, since @Wally73 is right, the best way to do is using the blacklist.
Not sure why the pull request to fix this isn't in the master release yet?

**Comment by Sweepr** [comment]
One could also use this in a PHP script which is triggered by a cron.

You could change the number to anything you like and put this in a cronjob to automatically remove spots that have 5+ reports for example, adjust to your own needs

DELETE FROM spots WHERE reportcount >= 5;
