### ISSUE TITLE
Too many open connections

### ISSUE THREAD

**Issue by MrHappy** [spotweb/spotweb#106]
I'm using the master-repo and I'm getting the following errors continuously.
Last retrieve at 12/05/15 23:00:39
Retrieving new Spots from server sslreader.eweka.nl...
SpotWeb v0.67.28.31 on PHP v5.6.16 crashed

Fatal error occured while connecting to the newsserver:
  (502) Authentication rejected [response: "Too many connections"] [response: ""]

#0 D:\Spotweb\lib\services\Nntp\Services_Nntp_Engine.php(120): Services_Nntp_Engine->connect()
#1 D:\Spotweb\lib\services\Retriever\Services_Retriever_Base.php(112): Services_Nntp_Engine->selectGroup('free.pt')
#2 D:\Spotweb\lib\services\Retriever\Services_Retriever_Base.php(280): Services_Retriever_Base->connect(Array)
#3 D:\Spotweb\retrieve.php(154): Services_Retriever_Base->perform()
#4 {main}

Finished retrieving spots.

However, when I check the open connections on my router to Eweka I see 1 open connection (of the 8 connections I am allowed to have).
The 1 open connection is a TIME_WAIT from spotweb to Eweka.

How can I fix this?

(Downloading does work btw, right after checking the above)

--edit--
Sometimes I do get a bit further and I receive this message:

Last retrieve at 12/05/15 23:00:39
Retrieving new Spots from server sslreader.eweka.nl...
Appr. Message count:    2721197
First message number:   2
Last message number:    2721199
Current article number: 2721181

Retrieving 2721181 till 2721200SpotWeb v0.67.28.31 on PHP v5.6.16 crashed

Fatal error occured while connecting to the newsserver:
  (502) Authentication rejected [response: "Too many connections"] [response: ""]

#0 D:\Spotweb\lib\services\Nntp\Services_Nntp_Engine.php(120): Services_Nntp_Engine->connect()
#1 D:\Spotweb\lib\services\Nntp\Services_Nntp_Engine.php(77): Services_
Nntp_Engine->selectGroup('free.pt')
#2 D:\Spotweb\lib\services\Nntp\Services_Nntp_Engine.php(284): Services_Nntp_Engine->registerError(Object(NntpException))
#3 D:\Spotweb\lib\services\Nntp\Services_Nntp_SpotReading.php(160): Services_Nntp_Engine->getHeader('<RtQekE6gmH0u11...')
#4 D:\Spotweb\lib\services\Retriever\Services_Retriever_Spots.php(398):  ] Services_Nntp_SpotReading->readFullSpot('RtQekE6gmH0u11j...')
#5 D:\Spotweb\lib\services\Retriever\Services_Retriever_Base.php(227): Services_Retriever_Spots->process(Array, '2721181', 2721200, 1449356034.6111)
#6 D:\Spotweb\lib\services\Retriever\Services_Retriever_Base.php(319): Services_Retriever_Base->loopTillEnd('2721181', '1000')
#7 D:\Spotweb\retrieve.php(154): Services_Retriever_Base->perform()
#8 {main}

Finished retrieving spots.

**Comment by Sweepr** [comment]
It say's exactly what it means, (502) Authentication rejected response: "Too many connections", which means your Usenetserver is denying you access, maybe because of too many frequent requests, ratelimiting, contact your USP

**Comment by MrHappy** [comment]
Weird thing is if I ran out of connections (attempts) then why does downloading work? 
They suggested it might have something to do with timeouts.
Though I doubt that...

**Comment by Sweepr** [comment]
I see your trying to download using sslreader.eweka.nl, did your try to download using there normal server on port 119?

**Comment by MrHappy** [comment]
tried that too, didn't make any difference...

**Comment by Sweepr** [comment]
I don't know if this is still an active topic, but basically the "WAIT" states mean that one side closed the connection but the final confirmation of the close is pending.

Maybe you could check your config and disable the KeepAlive option to Off and set a Timeout to 300 seconds, for Apache these apply:

httpd.conf:

      Timeout 300
      KeepAlive Off

**Comment by mesa57** [comment]
No feedback. Closing issue.
