### ISSUE TITLE
Undefined offset and Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by MrHappy** [spotweb/spotweb#107]
I'm getting the following errors...
I have no idea what might be missing/wrong..
Anyone an idea?

Calculating how many spots are new
Notice: Undefined offset: 9 in D:\Spotweb\lib\services\Search\Services_Search_QueryParser.php on line 97

Warning: Invalid argument supplied for foreach() in D:\Spotweb\lib\services\Search\Services_Search_QueryParser.php on line 97

Notice: Undefined offset: 9 in D:\Spotweb\lib\services\Search\Services_Search_QueryParser.php on line 121

Warning: Invalid argument supplied for foreach() in D:\Spotweb\lib\services\Search\Services_Search_QueryParser.php on line 121

Notice: Undefined offset: 9 in D:\Spotweb\lib\services\Search\Services_Search_QueryParser.php on line 97

Warning: Invalid argument supplied for foreach() in D:\Spotweb\lib\services\Search\Services_Search_QueryParser.php on line 97

Notice: Undefined offset: 9 in D:\Spotweb\lib\services\Search\Services_Search_QueryParser.php on line 121

Warning: Invalid argument supplied for foreach() in D:\Spotweb\lib\services\Search\Services_Search_QueryParser.php on line 121

Notice: Undefined offset: 9 in D:\Spotweb\lib\services\Search\Services_Search_QueryParser.php on line 121

Warning: Invalid argument supplied for foreach() in D:\Spotweb\lib\services\Search\Services_Search_QueryParser.php on line 121

**Comment by Sweepr** [comment]
We need some more information. OS? PHP version?

**Comment by MrHappy** [comment]
Ahh sorry, I thought I put them in it...
Here it is: Windows 2012R2 and SpotWeb v0.67.28.31 on PHP v5.6.16.

**Comment by MrHappy** [comment]
Did a new pull and recreated ownsettings.php, all seems fine now.

**Comment by MrHappy** [comment]
Nope, same errors still exist...

**Comment by MrHappy** [comment]
Haven't had the errors for over a day now.
The filters were the cause of the errors...
