### ISSUE TITLE
Categories give a Load error! (error) on MS IIS

### ISSUE THREAD

**Issue by Rouzax** [spotweb/spotweb#108]
I'm setting up Spotweb on a Microsoft IIS 8.5 with PHP 5.6
There are already several other PHP web applications running in that IIS instance without issue.
Spotweb seems to completely works except the categories.
![image](https://cloud.githubusercontent.com/assets/4103090/11688935/bca3a4d6-9e8f-11e5-80ab-72ff177e96e1.png)

I get an error code 500 in my IIS log
```
2015-12-09 15:24:54 192.168.2.2 GET / page=catsjson&search[tree]=&_=1449674694272 80 -  HTTP/1.1 Mozilla/5.0+(Windows+NT+6.3;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/47.0.2526.80+Safari/537.36 http://test.xyz.zyx/ 500 0 0 93
```

**Comment by Sweepr** [comment]
500 Internal server error, probably due to wrong permissions or something timing out on your webserver.. re-check your configuration.

**Comment by Rouzax** [comment]
It's not an authentication or rights issue I've checked. 
There seems to give an error on the category php file on one of the foreach statements on the end. 

Will try to do some more debugging tomorrow, would appreciate if you could open the issue again.

**Comment by Rouzax** [comment]
i also get the error:
Notice: Undefined index: a in SpotCategories.php on line 582

**Comment by Rouzax** [comment]
There seems to be a difference in the pages requested.
This is on IIS
`GET / page=catsjson&search[tree]=&_=1449837540761 HTTP/1.1 500`
This is on Apache
`GET /?page=catsjson&search[tree]=&_=1449837361918 HTTP/1.1 200`

**Comment by Sweepr** [comment]
I can't be of any further help on this issue because i lack IIS knowledge, maybe a dedicated IIS help forum could be of more assistance

**Comment by Rouzax** [comment]
The problem was the PHP version :smile: 
I had version 5.6.0 and after upgrading to 5.6.16 it worked.

Did run into another snag after I updated PHP and MySQL. It appears that Spotweb with MySQL 5.7 is unable to create the database see https://github.com/spotweb/spotweb/issues/110
