### ISSUE TITLE
Issues installing on NGinx

### ISSUE THREAD

**Issue by thejrose1984** [spotweb/spotweb#109]
OS - FreeNAS / FreeBSD 9
Web - Nginx 1.8.1
PHP - 5.6

Followed the instructions on what packages to install, but get a blank page when I go to http://[ip_address]/install.php

Config file here:
spotweb.conf = http://pastebin.com/2ju0DMRJ

Here's what I see in the access log:
[12/Dec/2015:14:56:23 -0500] "GET /install.php HTTP/1.1" 500 5 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0"

Nothing in the error log

**Comment by thejrose1984** [comment]
???

**Comment by Sweepr** [comment]
Looks like install.php script does not have the correct rights to execute,

**Comment by thejrose1984** [comment]
Not sure I follow since the install.php is (a) owned by www and (b) has execute permissions turned on for user, group, and other

If my nginx config file is missing something, please advise as I have not been successful at deploying spotweb...

**Comment by Sweepr** [comment]
Please double check and veryify your fastcgi settings in your config.

Also take a look if this might help?

**Comment by Sweepr** [comment]
http://stackoverflow.com/questions/15423500/nginx-showing-blank-php-pages

**Comment by thejrose1984** [comment]
Reviewed URL previously and gave it a second look to be safe.
Updated conf file...still no dice...

http://pastebin.com/FrbVbk8L

**Comment by Sweepr** [comment]
After the change you restarted the nginx service ofcourse?

**Comment by thejrose1984** [comment]
of course

**Comment by Sweepr** [comment]
Think it's a good idea to start figuring out why the error log does not show any error's, because there are.. we need to known which error is finds in order the go further, without the exact error it's fishing for a needle in the haystack.

**Comment by thejrose1984** [comment]
True, but the other issue is I have my php.ini file set to log errors and it doesn't...

**Comment by Sweepr** [comment]
Check this out:

**Comment by Sweepr** [comment]
https://blog.ed.gs/2012/10/16/php-fpm-error-logging-to-nginx/

**Comment by thejrose1984** [comment]
Did that and restarted php-fpm as well as nginx...no change in error log details...

**Comment by Sweepr** [comment]
Think this could be this problem " FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, "  

Did you verify fastcgi is listening on 127.0.0.1:9000 ?

**Comment by thejrose1984** [comment]
according to /usr/local/etc/php-fpm.conf it is listening on 127.0.0.1:9000

**Comment by thejrose1984** [comment]
root@spotweb:/ # sockstat -4 | grep 9000
www      php-fpm    41567 0  tcp4   127.0.0.1:9000        *:*
www      php-fpm    41566 0  tcp4   127.0.0.1:9000        *:*
root     php-fpm    41565 8  tcp4   127.0.0.1:9000        *:*

**Comment by thejrose1984** [comment]
No error messages today, but still can't run install PHP script...

**Comment by thejrose1984** [comment]
![test](https://cloud.githubusercontent.com/assets/7573083/11875589/6c98d072-a4b3-11e5-939f-0314190dc61c.png)

**Comment by thejrose1984** [comment]
I also tried serving on apache 2.4, but they yielded issues as well (different than what nginx yields)...

**Comment by Sweepr** [comment]
serving on apache 2.4 what happens when you go to 192.168.1.208/install.php

**Comment by thejrose1984** [comment]
Different error regarding permissions...

It's either a PHP issue or the way it's specified in the nginx conf file...

**Comment by Sweepr** [comment]
What is the exact error you see?

**Comment by mesa57** [comment]
No answer, closing issue.
