### ISSUE TITLE
[Feature Request] - Make it possible to use HTTPS to send nzb's to NZBGet

### ISSUE THREAD

**Issue by Rouzax** [spotweb/spotweb#111]
I'm using valid SSL certificates from https://letsencrypt.org/ on all my sites.
But when I want to configure spotweb to send the nzb files with the option "Call NZBGet through HTTP by Spotweb" I can't use port 443.
![image](https://cloud.githubusercontent.com/assets/4103090/11777981/e16bbdec-a251-11e5-9c3e-012415ddb699.png)
When I change back to port 80 it works but it would be more secure to not send a plain text password.

The error in my backend from php is:

```
[14-Dec-2015 10:56:09 Europe/Belgrade] ERROR: Could not decode json-data for NZBGet method 'status', http returncode: 700 / Operation timed out after 15000 milliseconds with 0 bytes received
[14-Dec-2015 10:56:11 Europe/Belgrade] ERROR: Could not decode json-data for NZBGet method 'status', http returncode: 700 / Operation timed out after 15000 milliseconds with 0 bytes received
[14-Dec-2015 10:56:12 Europe/Belgrade] ERROR: Could not decode json-data for NZBGet method 'status', http returncode: 700 / Operation timed out after 14922 milliseconds with 0 bytes received
```

**Comment by guyspronck** [comment]
I'm looking into this, fairly easy to add as far as I can tell. Probably adding a checkbox for it, I will try to get it done this weekend.

Unrelated to this, a different username than 'nzbget' actually does work, even though it tells you it doesn't.

**Comment by mesa57** [comment]
Nice. I do not have the ability to test an ssl connection to nzbget, that's why this is still open.

**Comment by guyspronck** [comment]
Haha, I run my Nzbget on SSL, so it is in my own best interest to add this ;)

**Comment by guyspronck** [comment]
Sorry for the late update, I have been very busy last couple of months. I'll try to get to this issue asap.

**Comment by dbbdark** [comment]
i changed :

/lib/services/NzbHandler/Services_NzbHandler_Nzbget.php

and changed:

$this->_url = "http://" . $nzbget['host'] . ":" . $nzbget['port'] . "/jsonrpc";
to
$this->_url = "https://" . $nzbget['host'] . ":" . $nzbget['port'] . "/jsonrpc";

And i enter 
hostname: ip
port : 6789 ( i changed the ssl port to the main port )
username : robert
pass : *****

And tested and works for me

**Comment by Sweepr** [comment]
Added the option to choose SSL or not.

![image](https://user-images.githubusercontent.com/2857865/64062351-963c6300-cbe5-11e9-9eb8-b8fd6dbdfe8e.png)
