### ISSUE TITLE
Error 500 on IIS/Windows 2012R2 (PHP 5.6.16)

### ISSUE THREAD

**Issue by MrHappy** [spotweb/spotweb#112]
Some spots give an error 500.
Looks like the spots with html tags, but no cdata in the xml (I think...)
If I google the title and 'spotweb' there are sites which are able to show the spot.
For example 'the nightmare before christmas' (messageid QAwvnrfbg3EWhJHVgHIRR@spot.net)

When I remark line https://github.com/Spotweb/Spotweb/blob/master/lib/SpotTemplateHelper.php#L564
the spot gets loaded, but all smileys are missing.

How can I fix this

**Comment by mesa57** [comment]
Spot opens fine here (debian / apache / php 5.6)

**Comment by MrHappy** [comment]
Nice to know it works well on Lnux... 
But how do I get it to open on Windows as well??

**Comment by Rouzax** [comment]
@MrHappy I'm running on Windows 2012R2 with IIS and the spot you are refering to opens correctly.

MySQL: 5.6.28
PHP: 5.6.16
WIndows: Server 2012R2
IIS: 8.5

**Comment by MrHappy** [comment]
Weird, maybe it has something to do with settings in php.ini or php-modules...
I will try that out when I reinstall the server... 
Thanks anyway for your reaction.

Date: Tue, 29 Dec 2015 02:49:16 -0800

**Comment by Rouzax** [comment]
These are my enabled PHP modules in IIS
![image](https://cloud.githubusercontent.com/assets/4103090/12033971/7d2c6cca-ae2a-11e5-8f22-ed6bd1f4d6db.png)
If you need anything else let me know.
