### ISSUE TITLE
MySQL DB engine for spots table is MyISAM

### ISSUE THREAD

**Issue by Rouzax** [spotweb/spotweb#113]
All tables have InnoDB as engine why is the spots table per default configured as a MyISAM?
![image](https://cloud.githubusercontent.com/assets/4103090/12033128/f13ca18a-ae1f-11e5-89b5-33d480f1cab5.png)

**Comment by mesa57** [comment]
Space usage of a MyIsam table is easier to manage since a MyIsam table is a seperate file opposed to InnoDB which places all tables in a single file.

**Comment by Rouzax** [comment]
@mesa57 not necessarily if you have innodb_file_per_table enabled

**Comment by Fossil01** [comment]
Can we safely change the spots table to InnoDB?

**Comment by mesa57** [comment]
You can try, but no guarantees as the spots table use myisam fts for lookup query's.
I think it is different implemented on InnoDB (and even not present there in older MySQL versions).

**Comment by Fossil01** [comment]
I just did it. Still seems to work fine. MariaDB 10.1
