### ISSUE TITLE
Sickbeard query gives no result on cat search

### ISSUE THREAD

**Issue by Zeagle88** [spotweb/spotweb#117]
Hi,

Since I password protected my Spotweb installation via .htaccess, Sickbeard doesn't find any new episodes anymore.
I can go to my spotweb and download the manually, but Sickbeard can't.
Sickbeard also doesn't log any errors.

This is my .htaccess:

-----------
RewriteEngine on  
RewriteCond %{REQUEST_URI} !api/  
RewriteRule api/?$ index.php?page=newznabapi [QSA]
RewriteRule details/([^/]+) index.php?page=getspot&messageid=$1 [L]

AuthType Basic
AuthName "Login Required"
AuthUserFile C:\XAMPP\.htpasswd
require valid-user
Require local
Require host local
Require ip 192.168.1
Require ip 127.0.0.1

-----------

Running Apache 2.4.17, PHP 5.6.14 & MySQL 5.0.11
Both my Sickbeard & Spotweb are running on localhost, with different ports.
Anyway to resolve this?

With kind regards.

**Comment by mesa57** [comment]
Sickbeard should use a correct api key to communicate with spotweb. An api key is sufficient, no password is needed. So first check you're api key configurations.

**Comment by Zeagle88** [comment]
The API key is correct.
Sickbeard used to work, but since I password protected my Spotweb installation, it doesn't work anymore.

**Comment by Zeagle88** [comment]
As an example, I added DC's Legends Of Tomorrow in Sickbeard:
http://i.imgur.com/4b5vvKg.jpg
As you can see, it does not find episode 1.
When I search in my Spotweb:
http://i.imgur.com/Fgxymji.jpg
There are three spots (of which I downloaded one manually).

Sickbeard doesn't log any errors, so I think the connection with the API is OK, but there is a problem with the .htaccess restriction.

**Comment by Sweepr** [comment]
Why did you do that?

You could also limit for known ip's only

**Comment by mesa57** [comment]
Of course, when you make the spotweb url protected with a password via .htaccess, sickbeard won't be able to reach spotweb anymore. So don't do that. You can use the user/password protection in spotweb itself, that won't deny access via the api key.

**Comment by Zeagle88** [comment]
@Sweepr, Because I want to access my spotweb from everywhere with a username & password, only in my local network without username & password.

@mesa57, so I need to make my spotweb public, and to download the nzb's you need to login into spotweb itself?
The problem is, when I do that, the spotweb installation is visible to everyone who knows the URL (or stumble upon it), and where I live this could be dangerous for the anti-piracy thingys...

**Comment by mesa57** [comment]
No, you can secure spotweb in a way the only people with an account can login.

**Comment by Zeagle88** [comment]
I changed my .htaccess, replaced the Require ip with the following lines:
<If "%{REMOTE_ADDR} != '127.0.0.1'">
  AuthType Basic
  AuthName "Restricted Area"
  AuthUserFile C:\XAMPP.htpasswd
  require valid-user
</If>

Now when I go to http://127.0.0.1:8082 (path to Spotweb), I don't need to put in a username & password.
When I go to http://localhost:8082, I need to put in a username & password.
When I go to http://192.168.1.109:8082 (from my PC to the IP of my server where Spotweb is installed), I need to put in a username & password.
When I go to my external IP (from outside of my local network), I need to put in a username & password.

This is OK for me, but when I go to my Sickbeard, search for the episode of Legends of Tomorrow, I still get the red cross...
In Sickbeard my spotweb installation Site URL is http://127.0.0.1:8082/

**Comment by Zeagle88** [comment]
OK, reinstalled Spotweb, now when I force SickBeard to search for the episode, I get the following logs:

2016-01-22 16:05:49 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Unable to find a download for DC's Legends of Tomorrow - 1x01 - Pilot (1)
2016-01-22 16:05:43 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Clearing Spotweb cache and updating with new information
2016-01-22 16:05:42 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching Spotweb for DC's Legends of Tomorrow - 1x01 - Pilot (1)
2016-01-22 16:05:42 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Searching for DC's Legends of Tomorrow - 1x01 - Pilot (1)
2016-01-22 16:05:42 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Beginning manual search for DC's Legends of Tomorrow - 1x01 - Pilot (1)

So SickBeard does make connection to my Spotweb installation, but for some reason doesn't find anything. Is this a SickBeard issue?

**Comment by mesa57** [comment]
You try to find a spot which is not there. In the debug log of sickbeard you can find the call that sickbeard does to spotweb, copy that to you're browser and look at the results.

**Comment by Zeagle88** [comment]
Weird, when I manually search in Spotweb, I find 3 spots, and when I paste the link from the debug log, I find nothing.

**Comment by mesa57** [comment]
Look at difference between the sickbeard search and you're manual search.

**Comment by Zeagle88** [comment]
Hmm, this is my Sickbeard API call: http://SpotwebIP/api?q=DCs.Legends.of.Tomorrow&apikey=APIKEY&limit=100&t=tvsearch&season=1&ep=1&maxage=500&cat=5030%2C5040

When I remove "&cat=5030%2C5040" from the Spotweb API URL, I get 2 spots.
In SickBeard I specified to download HD Quality, and the spots I get when I remove the cat parameter are "DCs Legends of Tomorrow S01E01 720p HDTV X264-DIMENSION (NEW)" and "DCs Legends of Tomorrow S01E01 720p HDTV X264".
As far as I know, those are HD-versions.
Is it because the poster of the spot selected the wrong category then?

**Comment by mesa57** [comment]
You're query with the cat parameter returns 2 results on my spotweb. Have you installed the last commit, there we're some corrections for sickbeard & sonarr in there ?

**Comment by Zeagle88** [comment]
Yes I did a clean install, downloaded the master repository and installed from scratch.

**Comment by mesa57** [comment]
Could you try with the original .htaccess ? To make sure that doesn't influence things. And I hope you made a recent copy of the master branche, it was updated about 3 months ago.

**Comment by Zeagle88** [comment]
I downloaded the master repository today again to do a clean install, incl. the original htaccess.

**Comment by mesa57** [comment]
There must be a difference between my (2) spotweb installations, which deliver the expected results, and yours. My installations are indeed from the same current branch. However they are both running under debian / php 5.6 
But I cannot imagine that would matter. The problem is not reproducable here.

**Comment by Zeagle88** [comment]
I use XAMPP, which has Apache 2.4.17, PHP 5.6.14 & MySQL 5.0.11-dev.
I'm running a Windows server cause I use the same PC as my media center.

**Comment by mesa57** [comment]
In spotweb there is no normal way to add extra categories. So they answer is no.
You can do a short test on http://spotweb.mesa57.nl with api key 008eae5d84d373ab559bf4b3a033b78e

I will delete that account tomorrow again.

**Comment by Zeagle88** [comment]
Your link indeed gives the two spots.
I tried the commit you linked, and this one gives the spots, so I'll keep using this one, thanks! :)

**Comment by mesa57** [comment]
I will further look into this issue.
