### ISSUE TITLE
Issue with conecting to Spotweb website

### ISSUE THREAD

**Issue by mvdiggele** [Spotweb/Spotweb#12]
Hi there, 

I am getting below errors. What could i be doing wrong? 

OS: Linux/Ubuntu

Notice: Undefined index: userid in /var/www/spotweb/lib/SpotSecurity.php on line 140

Notice: Undefined index: prefs in /var/www/spotweb/lib/services/User/Services_User_Authentication.php on line 138

Notice: Undefined index: userid in /var/www/spotweb/lib/services/User/Services_User_Authentication.php on line 70

Notice: Undefined index: prefs in /var/www/spotweb/index.php on line 63

Notice: Undefined index: prefs in /var/www/spotweb/index.php on line 64

Notice: Undefined index: userid in /var/www/spotweb/index.php on line 73

Notice: Undefined index: userid in /var/www/spotweb/index.php on line 371

Warning: require(templates//SpotTemplateHelper_.php): failed to open stream: No such file or directory in /var/www/spotweb/lib/SpotClassAutoload.php on line 54

Fatal error: require(): Failed opening required 'templates//SpotTemplateHelper_.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/spotweb/lib/SpotClassAutoload.php on line 54

A thanks in advance!

Marc

**Comment by Sweepr** [comment]
No respons in over a month, closing this.
