### ISSUE TITLE
SickRage can't use the "newznab" api, spotweb returns an unfiltered list of results

### ISSUE THREAD

**Issue by p0psicles** [spotweb/spotweb#120]
I'm trying to get sr working with spotweb.

It seems that sr by default uses the ep=xx parameter to filter on the episode it's searching for.
But then spotweb returns an unfiltered lists of results.

When disabling the episode parsing in SpotPage_newznabapi.php at least it returns a filtered list based on the q= parameter.

With this change i've managed to get it working: https://github.com/p0psicles/spotweb/commit/4e034c32052f752423c58c117e3df3ea4d847526

I do have to mention that I needed to make another change to get spotweb working on my installation. Maybe that change caused the issue. But as I don't have access to another spotweb, i can't test it.
https://github.com/p0psicles/spotweb/commit/3ea26df9027f1f0610cc8d8826059c5bac93085d

With the changes above, and configuring the category id 5000 in sr, is kind of works.

**Comment by Wally73** [comment]
your url's are broken
and php 5.4x?? thats very ancient

**Comment by p0psicles** [comment]
from INSTALL:
* PHP v5.3 or higher (modules required: curl, DOM, gettext, mbstring, xml, zip, zlib, gd, openssl)

And my url's are commits, should be direct linked to the commit.

**Comment by mesa57** [comment]
A change of that kind is very dangerous as more than one client type uses the newsnab api, like sonarr, sickbeard and of cause sickrage. So it should be carefully tested agains all client and maybe also different versions of those clients. 
You also say the episode select doesn't work. But on what shownames does it not work ? Maybe the problem is in the showname ?

**Comment by p0psicles** [comment]
Okay, I just double checked. But sickrage follows the newznab api verry strictly now.
Searches are always done through tvdbid and ep, and the addtional paramaters like: api?apikey=apikey&tvdbid=266189&season=2&maxage=1100&cat=5000&limit=100&t=tvsearch&offset=0&ep=22. Where cat is configurable.

Strangly this gives back all results. Where i would expect none, because of the bad indexing of spotweb. Maybe someone can test this query on another spotweb installation?

What would be the options, to make spotweb usefull again within sr?

**Comment by mesa57** [comment]
The TVDBID parm is not (yet) supported in the master branch of spotweb. 
So it cannot find the showname and hence, cannot select an episode.
