### ISSUE TITLE
Change preferences and Settings pages don't work

### ISSUE THREAD

**Issue by prutseltje** [spotweb/spotweb#121]
When i want to change settings, the preferences and settings pages won't work.

'error while loading this page, you wil be returned automaticly to the mainview '

I have tried with chrome and safari on osx, 
Chrome and edge on windows 10.

**Comment by WzL** [comment]
I experience the same behaviour, using a clean git clone from master
branche, fresh installation inc. a clean empty mysql database.

At first i thought it was a local configuration error, but when there are
more users experiencing the same behaviour, is this coincedence?
Op 30 jan. 2016 21:49 schreef "Rob Nieuwenhuizen" <notifications@github.com

**Comment by prutseltje** [comment]
Did a fresh git clone with clean database. No difference, same issues :(

**Comment by mesa57** [comment]
Cannot reproduce until now. Please specify environment.

**Comment by WzL** [comment]
Debian stretch (9)
PHP 5.6.17-3
Nginx 1.9.9
PHP5-fpm fcgi using local socket
MySQL 14.14

All installed on the same machine.
Op 30 jan. 2016 22:32 schreef "mesa57" <notifications@github.com>:

**Comment by prutseltje** [comment]
Debian Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux
Debian Jessie 8.3, default packages.

Apache log:
192.168.10.138 - - [30/Jan/2016:22:45:27 +0100] "GET /?page=edituserprefs&userid=3 HTTP/1.1" 200 4676
192.168.10.138 - - [30/Jan/2016:22:45:29 +0100] "GET / HTTP/1.1" 200 9686
192.168.10.138 - - [30/Jan/2016:22:45:29 +0100] "GET /edituserpreftab-2 HTTP/1.1" 404 304

**Comment by mesa57** [comment]
Ok, thanks confirmed now. It is possible to access the settings, but the screen looks bad, and if you click on any option yoi get the error.

**Comment by WzL** [comment]
Yes, correct!
Op 30 jan. 2016 22:52 schreef "mesa57" <notifications@github.com>:

**Comment by mesa57** [comment]
![2016-01-30_2254](https://cloud.githubusercontent.com/assets/6350469/12698726/8add473e-c7a4-11e5-8171-912e6c7cb039.png)
![2016-01-30_2254_001](https://cloud.githubusercontent.com/assets/6350469/12698727/8ae31c36-c7a4-11e5-84de-e49ece9ca442.png)

**Comment by mesa57** [comment]
Solved by undoing a previous change. (pull request #92)

**Comment by prutseltje** [comment]
Confirm the bug is closed.
