### ISSUE TITLE
Services_MediaInformation_Imdb preg_match doesnt seem to work

### ISSUE THREAD

**Issue by blaataap** [spotweb/spotweb#123]
Not sure if this is due a new html on the imdb website or something else changed but line 26 in Services_MediaInformation_Imdb.php doesnt match. I fabricated this: `preg_match('/<h1 itemprop="name" class="">([^\<]*)<span/ms', $imdb, $movieTitle);` and works but need expert to look and submit it :-)

**Comment by mesa57** [comment]
You can fork the repository to you're own, apply the change and create a pull request.
That gives us the abelity to review the change and you're contribution  :smile:

**Comment by blaataap** [comment]
Hah well im pretty sure my solution isnt water tight and yea i dont have any experience in forking etc... rather let someone else do it.

**Comment by mesa57** [comment]
You are never to old to learn :wink:

**Comment by dsadsdadsadsadsds** [comment]
If you want to, you could do this using the Github interface

**Comment by abeesh** [comment]
I had better luck with the following code.
preg_match ('<meta property=\'og:title\' content="([^\<]*)" />', $imdb, $movieTitle);

**Comment by mesa57** [comment]
I've tested this. Last propositon is much to generic. The first regex works, but partially. It extracts the imdb title, but encode html characters prevent the title from being found in spotweb (this was investigated with an api call from somebody reporting the problem on spot-net forum).
Some code extra code change is needed here too.

**Comment by abeesh** [comment]
Looks like the github form ate away actual regex. I have updated the comment.

**Comment by mesa57** [comment]
That property contains the file as well as the year. Spotweb already extracts the year from an other field, so I am not sure this will work in all cases. But at least it does not contain any encoded html characters.

**Comment by mesa57** [comment]
Could you both test my changes from the mesa57/spotweb-master repository ?

**Comment by abeesh** [comment]
It is working for me.

**Comment by mesa57** [comment]
Thanks ! @blaataap : it would be nice if you execute a test too. :smile:

**Comment by blaataap** [comment]
Tested and works!

**Comment by mesa57** [comment]
Ok, I am going to issue a pull request to merge with master then.
