### ISSUE TITLE
NotifyMyAndroid class not PHP7 ready

### ISSUE THREAD

**Issue by CptChaos** [spotweb/spotweb#124]
Hi there,

I just updated spotweb and saw most issues with Spotweb on PHP7 being solved. Really nice and really quick too! Unfortunatly, I found that another class isn't quite ready for PHP7;

```
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; NotifyMyAndroid has a deprecated constructor in /var/www/spotweb/lib/notifications/nma/class.nma.php on line 3
```

Another quick and easy fix; on line 30 of https://github.com/spotweb/spotweb/blob/master/lib/notifications/nma/class.nma.php#L30, the name of the function should be changed to __construct( ;)

**Comment by Sweepr** [comment]
Could you create a pull request for this?

**Comment by CptChaos** [comment]
I'm quite noob at Github, sorry...

**Comment by mesa57** [comment]
Merged pull request. I am closing this issue.
