### ISSUE TITLE
PHP7 readiness

### ISSUE THREAD

**Issue by dsadsdadsadsadsds** [spotweb/spotweb#125]
Just a general heads up - please be sure to not manually patch anything in the vendor/ subdirectory. Those are generic libraries imported from other projects and it should be much nicer to just update those to their more recent versions instead of baically forking them.

**Comment by mesa57** [comment]
Agreed, but this is no real issue isn't it ?

**Comment by dsadsdadsadsadsds** [comment]
They removed the private messaging from github a long while ago so this is the easiest way to communicate something :)
