### ISSUE TITLE
Use search operators

### ISSUE THREAD

**Issue by Rouzax** [spotweb/spotweb#132]
It would be nice if we can use the search and define for instance that I only want results that have both words so `and` and `or`.

**Comment by Sweepr** [comment]
Could you explain a little bit more on the purpose and why it could be usefull?

**Comment by Rouzax** [comment]
If I want to search for `Rescue Rangers` I will get all results back that either contain `Rescue` **or** `Rangers` while I would like to be able to search for `Rescue` **and** `Rangers`.
Something like `Rescue+Rangers`
![image](https://cloud.githubusercontent.com/assets/4103090/13378656/66c0a01a-de0d-11e5-9837-f08f71d1ee40.png)
Does it make sense what I'm trying to accomplish?

**Comment by mesa57** [comment]
Funny thing is that in spotnet the default is AND whilest in spotweb it is OR

**Comment by hagst** [comment]
use for and "Rescue Rangers"

**Comment by Rouzax** [comment]
That will only show results where both words are always in that order and together, although I agree that in this example it would work. 
However there are also instances that you would like to search for multiple words and only see results where all words are present.

**Comment by DirtyDutch** [comment]
Add a + in front of your word, this will force that both words are in it.

**Comment by Rouzax** [comment]
@DirtyDutch, thanks that seems to work.

**Comment by mesa57** [comment]
Resolved then.

**Comment by Rouzax** [comment]
Could this be opened again?
I'm running in to a similar situation as before but now I want to search for spots that contain `+Rescue +Rangers` OR `+Chip +Dale`
In the current design the additional search queries are always `AND`
![image](https://cloud.githubusercontent.com/assets/4103090/23464637/09843b00-fe96-11e6-9abc-82d84964daab.png)

**Comment by mesa57** [comment]
In MySQL fts search OR is just nothing. So have you tried something like this : 
`(+chip +magazin) (+creed +2016)`

**Comment by Rouzax** [comment]
That works 😃

**Comment by mesa57** [comment]
? You can use the save search as filter option ....

**Comment by Rouzax** [comment]
But that doesn't work if I change the URL from AND to OR.
It doesn't really matter, your query works.
