### ISSUE TITLE
Personal disposes and comment linking

### ISSUE THREAD

**Issue by mesa57** [spotweb/spotweb#133]
Spotnet V2 and spotnet >= 1.8.5.8 support removing of spots by sending a dispose message with the message id of the spot to be removed, but signed with the private key of the sender. 
The public key is in the header, just as with self-signed spots. 
Both clients limit spots to be deleted to the spotter who placed the original spot. 
On top of that spotnet 1.8.5.8 : 
- Only permits spots to be deleted when not older then five days
- Puts the message-id's of deleted spots which are replaced by a news spot in the x-xml header in 
```
<prevspots><spot>{messageid}</spot><spot>{messageid}</spot>...</prevspots> 
```
for purpose of comments to be shown from the deleted spot in the followup spot.

It would be very nice if spotweb supports the protocol changes, at least for retrieve

**Comment by Wally73** [comment]
i like ;)

**Comment by mesa57** [comment]
@Wally73 Pull request is pending. Could you review ?

**Comment by Wally73** [comment]
mm i have no idea how to merge something which isnt in the main branch yet
(and i do hope there were no db changes as i have innodb completely
disabled on my box)

**Comment by mesa57** [comment]
Wally,
 
Maybe you can download the last commit of my repo, mesa57/spotweb-master ?
Copy the db-settings php file, and it should work.
There are no database changes.
 
Grtz.

  _____  

Van: Wally73 [mailto:notifications@github.com] 
Verzonden: zaterdag 26 maart 2016 19:41
Aan: spotweb/spotweb
CC: mesa57
Onderwerp: Re: [spotweb] Personal disposes and comment linking (#133)


mm i have no idea how to merge something which isnt in the main branch yet
(and i do hope there were no db changes as i have innodb completely
disabled on my box)

On Sat, Mar 26, 2016 at 7:37 PM, mesa57 <notifications@github.com> wrote:

> @Wally73 <https://github.com/Wally73> Pull request is pending. Could you
> review ?
>
> -
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/spotweb/spotweb/issues/133#issuecomment-201909940>
>


-
You are receiving this because you authored the thread.
Reply to this email directly or view
<https://github.com/spotweb/spotweb/issues/133#issuecomment-201910138> it on
GitHub
<https://github.com/notifications/beacon/AGDmhcpk5vbstOApW7SkwWUUa6FFxitYks5
pxX2pgaJpZM4Hkhqc.gif> 

  _____  

Geen virus gevonden in dit bericht.
Gecontroleerd door AVG - www.avg.com
Versie: 2016.0.7497 / Virusdatabase: 4545/11883 - datum van uitgifte:
03/25/16
