### ISSUE TITLE
Retrieve broken DSM6 (RC) Synology

### ISSUE THREAD

**Issue by schumi2004** [spotweb/spotweb#135]
Since i upgraded retrieve is broken.

root@DS715:/volume1/web/spotweb# /usr/bin/php /volume1/web/spotweb/retrieve.php PHP Fatal error:  Undefined class constant 'MYSQL_ATTR_FOUND_ROWS' in /volume1/web/spotweb/lib/dbeng/dbeng_pdo_mysql.php on line 28

Fatal error: Undefined class constant 'MYSQL_ATTR_FOUND_ROWS' in /volume1/web/spotweb/lib/dbeng/dbeng_pdo_mysql.php on line 28
root@DS715:/volume1/web/spotweb# su /usr/bin/php /volume1/web/spotweb/retrieve.php
su: user /usr/bin/php does not exist
root@DS715:/volume1/web/spotweb# sudo /usr/bin/php /volume1/web/spotweb/retrieve.php
PHP Fatal error:  Undefined class constant 'MYSQL_ATTR_FOUND_ROWS' in /volume1/web/spotweb/lib/dbeng/dbeng_pdo_mysql.php on line 28

Fatal error: Undefined class constant 'MYSQL_ATTR_FOUND_ROWS' in /volume1/web/spotweb/lib/dbeng/dbeng_pdo_mysql.php on line 28

Changed everything to 755 without luck.

**Comment by mesa57** [comment]
I think you're mysql pdo extension for php needs updating.

**Comment by mesa57** [comment]
Btw., just today I ran into EXACT the same issue : 
- Debian upgraded itself from wheezy to jessie
- It broke php5 + apache
- Removed apache + php5 and reInstalled
Started spotweb :  
Fatal error: Undefined class constant 'MYSQL_ATTR_FOUND_ROWS' in /volume1/web/spotweb/lib/dbeng/dbeng_pdo_mysql.php on line 28

Then I installed the PHP5 extensions needed for MYSQL and others : 

apt-get -y install php5-mysqlnd php5-curl php5-gd php5-intl php-pear php5-imagick php5-imap php5-mcrypt php5-memcache php5-pspell php5-recode php5-snmp php5-sqlite php5-tidy php5-xmlrpc php5-xsl

And the error was gone.

**Comment by WzL** [comment]
after some testing I only changed my retrieve crontab entry from

/usr/bin/php /var/www/html/spotweb/retrieve.php

to

/usr/bin/php5 /var/www/html/spotweb/retrieve.php

Which did the job also after running into the same issues as described by
yourself!

2016-03-25 13:13 GMT+01:00 mesa57 <notifications@github.com>:

**Comment by manuelvanrijn** [comment]
for me the location of php was `/usr/local/bin/php56`
