### ISSUE TITLE
Spotweb newznab api returns Can't use method return value in write context (php 5.4)

### ISSUE THREAD

**Issue by dakink** [spotweb/spotweb#137]
Running spotweb on Centos 7
Server version: Apache/2.4.6 (CentOS)
Server built:   Nov 19 2015 21:43:13

PHP 5.4.16 (cli) (built: Jun 23 2015 21:17:27)

In the /lib/page/SpotPage_newznabapi.php there are three checks using !empty, which apparently fails on php < 5.5. 

Perhaps we can replace "if (!empty($tvInfo->getTitle()))" with just if "($tvInfo->getTitle())" which does seem to be parsed correctly in php < 5/5.

**Comment by mesa57** [comment]
I would appreciate if you give a screenshot of the error and a copy of the api call performed.

**Comment by Wally73** [comment]
why do you use such ancient php version???

**Comment by dakink** [comment]
![screenshot error](https://cloud.githubusercontent.com/assets/17966027/13905703/bf4b4328-eec7-11e5-80d9-f5bc4df190e3.png) error in screenshot.

The Api call itself is just the test page (so api?t=c). No real clue what the underlying request is.

As for php5.4, that's still the standard version for Centos, and should be alright for the requirements (PHP 5). Debian and Ubuntu are farther ahead with 5.6 and 5.5 respectively.

**Comment by dakink** [comment]
The rules which contain !empty within SpotPage_newznabapi.php are 173, 185 and 187

**Comment by mesa57** [comment]
In case you want to upgrade : 
https://www.centos.org/forums/viewtopic.php?f=48&t=52586&start=20#p236954

**Comment by dakink** [comment]
yeah, I found the update page. Just thought that this might be something for legacy systems as well.

**Comment by mesa57** [comment]
Aanpassing zit nu in de laatste pull request
