### ISSUE TITLE
missing collections option 

### ISSUE THREAD

**Issue by Wally73** [spotweb/spotweb#145]
after https://github.com/spotweb/spotweb/commit/c6ad15db10fb4c1b4808246ee25c7182ac72c5a7 

i don't have collections anymore (before that i had them) i don't know if that is only on my end

**Comment by mesa57** [comment]
Enlighten me. What do you mean by collections ?

**Comment by Sweepr** [comment]
In your settings under retrieve did you enable 

Create collections of multiple spots?

![untitled](https://cloud.githubusercontent.com/assets/2857865/14361384/e22f1f4a-fcfa-11e5-8a8f-5b3489edf9fd.png)

**Comment by Wally73** [comment]
that option under settings/retrieve is gone

**Comment by Sweepr** [comment]
Did you switch from Media branch to Master branch?

**Comment by Wally73** [comment]
i've never been on media branch i've always have been using master afaik

**Comment by Sweepr** [comment]
Because afaik the collections option has only been in Media branch.

**Comment by Wally73** [comment]
mmm that is strange (and sucks as i miss that now )

**Comment by Sweepr** [comment]
Perhaps you did a git of the master branch and by mistake overwritten the media installation?

**Comment by mesa57** [comment]
Look like it. Wally73 previously reported that he got trouble in mergin, which was resolved by a git --hard reset

**Comment by Wally73** [comment]
mm i did a git stash, git pull after i noticed mesa57 had merged those Personal disposes and comment linking 
after that i got a shit load of merge issues which i had to fix with git fetch --all, git reset --hard and then git pull 

if i was on the media branch git pull should have said i was already up to date, as latest commit in media was jan 25

**Comment by CptChaos** [comment]
Not sure if I can post it here or wether or not a new issue would be better: The media branche doesn't have the PHP7 fixes which are in master. #127 is one of those fixes, not sure which issues are also applicable. :)

**Comment by Wally73** [comment]
will switch to media tomorrow then (as i love that collections option) 
i hope Personal disposes and comment linking  can be merged into media branch then too ;)

**Comment by mesa57** [comment]
It is not possible to merge the changes into the media branche. 
If I create a pull request there are multiple conflicts.
I don't have the (git) experience to solve them.

**Comment by Sweepr** [comment]
@mesa57.

Your right, a 1 on 1 merge is not possible since the media code is different on too many levels compared to the master branch.

We could try to manually edit the changes into media and debug from there.

**Comment by mesa57** [comment]
Pfff, that's a 2 month's fulltime job unless you find a php professional ;)

**Comment by CptChaos** [comment]
Most PHP7 errors are about methods with the same name as the class. :) So I guess most of the 'fixes' are copy/pasties from the respective classes. :)

**Comment by mesa57** [comment]
@CptChaos It is not about PHP7 alone, but make a merge of the most recent master branch into the media branche. 
Personally I do not like at all to maintain 2 versions of the same software. There should be always one and only one stable version.

**Comment by CptChaos** [comment]
Jep, totally agree with that! :)

**Comment by mesa57** [comment]
@Wally73 : @Sweepr updated the media branch, so you should be able to check it out and test :smile:

**Comment by Wally73** [comment]
i can try ;)
what is the git command again to switch branches?

**Comment by mesa57** [comment]
http://stackoverflow.com/questions/1783405/checkout-remote-git-branch
