### ISSUE TITLE
nzbget failure

### ISSUE THREAD

**Issue by kalmma** [spotweb/spotweb#15]
When I select the nzbget option in the user settings I get when logging in webiterface error below. 

Fatal error: Call to undefined function curl_init () in /var/www/html/Spotweb/lib/services/Providers/Services_Providers_Http.php on line 190

When I then remove this setting via the admin account, I can log in again. 

NZBget the option does not work anymore. 

This is since I have one new installation done today with a new pull from the git.

**Comment by suheyl** [comment]
What was the issue? Because I have the same now. I can't find it... Worked always

**Comment by thctlo** [comment]
install php-curl ( php5-curl or php7.0-curl )

**Comment by Ziglar1** [comment]
Spotweb installed on: Synology
Sonarr had the same problem getting posts. 
goto: synology > webstation> php settings > open php5.6 and php7 then check the box in front of "curl"
