### ISSUE TITLE
PHP Notice:  Array to string conversion in templates/we1rdo/editsettings.inc.php on line 24

### ISSUE THREAD

**Issue by vinzz73** [spotweb/spotweb#151]
This error is shown on top of the settings page.

Using most recent version pulled from git:

Your branch is up-to-date with 'origin/master'

This is line 24:

` 24     $tmpArDiff = array_diff_assoc($nntp_post, $nntp_nzb);                   `

**Comment by mesa57** [comment]
Please specify OS, Mysql version and php version.

**Comment by vinzz73** [comment]
PHP 5.6.19
MariaDB 10.1.13
Debian Jessie

**Comment by mesa57** [comment]
My Debian Jessie lists php 5.6.17 as highest version ?

**Comment by vinzz73** [comment]
I use 5.6.19

**Comment by mesa57** [comment]
As I cannot reproduce this error you may try you're self to change this line 3 in index.php

error_reporting(E_ALL & ~E_WARNING);

to

error_reporting(E_ALL & ~E_WARNING & ~E_NOTICE);

**Comment by dsadsdadsadsadsds** [comment]
Did you ever _downgrade_ from a Spotweb version? Eg you changed from the media branch back to master? or did you ever change the database yourselves?

Could you try running ``upgrade-db.php`` to see if it fixes this ? It basically means (most likely, that is) your NTTP setings are corrupt in the database.

**Comment by mesa57** [comment]
@dsadsdadsadsadsds Agreed. But maybe it is possible to leave them empty on install ?

**Comment by vinzz73** [comment]
I used the old database, so it must be that. upgrade-db.php did not help. Thanks.

**Comment by vinzz73** [comment]
Any chance to repair it ? I'd like to keep the database..

**Comment by mesa57** [comment]
Is you're spotweb starting normally ?

**Comment by vinzz73** [comment]
Yes everything works normally including api push to Sabnzbd.

 

Van: mesa57 [mailto:notifications@github.com] 
Verzonden: dinsdag 12 april 2016 20:46
Aan: spotweb/spotweb <spotweb@noreply.github.com>
CC: vinzz73 <vincent.pieper@gmail.com>
Onderwerp: Re: [spotweb/spotweb] PHP Notice: Array to string conversion in templates/we1rdo/editsettings.inc.php on line 24 (#151)

 

Is you're spotweb starting normally ?

**Comment by mesa57** [comment]
Please check you're newsserver settings.

**Comment by vinzz73** [comment]
Very good, I saved the server settings once again, and the notice
disappears.Ran the upgrade-db script once again to be sure, and all set.
Thanks.

**Comment by mesa57** [comment]
Thanks for reporting back.
