### ISSUE TITLE
Media branch - revert the revert please

### ISSUE THREAD

**Issue by dsadsdadsadsadsds** [spotweb/spotweb#155]
Hi,

In order to be able to open a new PR with the media branch changes, you would need to revert the revert. A current new PR will not introduce my changes though as it basically will be aplied, then immediately reverted by your later commit.

Please see: https://stackoverflow.com/questions/7099833/how-to-revert-a-merge-commit-thats-already-pushed-to-remote-branch for a better explanation

@Sweepr

**Comment by mesa57** [comment]
Is it not possible to goto the closed pull request and revert from there ?

**Comment by Sweepr** [comment]
Is this ok?

https://github.com/spotweb/spotweb/pull/156

**Comment by dsadsdadsadsadsds** [comment]
I am not sure what you have done but my guess is you just made a commit without actually reverting the history. 

The problem is basically this -- all commits have a unique identifier (eg sha1 one), and my commits are already in your repository, you just overwrote the changes with your revert.

My pull request will see that my commit-ids have already been applied, and they will not be applied once again.

You would need to actually go back in time with this repo if we want to create a proper timeline with appropriate commiter names.

**Comment by Sweepr** [comment]
@dsadsdadsadsadsds, i pulled the request, then reverted that pull, and then reverted that..  so what i understand from you is that any change to the branch that was made inbetween the reverts should checked?

**Comment by Fossil01** [comment]
Anyone care to explain what the difference is between master and media branches?

**Comment by mesa57** [comment]
Media branch has an option to sort files into collections. That's the main difference.

**Comment by dsadsdadsadsadsds** [comment]
In other words, it is a lot cooler!

**Comment by dsadsdadsadsadsds** [comment]
But of course! It's the greatest and latest -- but on a serious note -- it does have a lot of "new development" (collections, TheMovieDB integration partly finished) which will really add a lot of value to the code.

**Comment by mesa57** [comment]
@team : please give you're opinion on this

**Comment by GeoffreyDijkstra** [comment]
@mesa57 It should be merged, that's for certain. But not now, I like a working merge first. Maybe @dsadsdadsadsadsds has time to merge it locally, fix spotweb and make a PR, because I don't have lots of time atm.
