### ISSUE TITLE
spotweb crashes on processing collections

### ISSUE THREAD

**Issue by eboman** [spotweb/spotweb#157]
Often the task to retrieve new spots crashes on the collections with the following error 

Creating collections starting from 1577555, , done  
Calculating how many spots are new                                                                                                                                                    

SpotWeb v0.68.29.32 on PHP v5.6.17 crashed                                                                                                                                            

Fatal error occured retrieving reports:  
  42S22: 1054: Unknown column 'mc.title' in 'where clause' (SQLSTATE[42S22]: Column not found: 1054 Unknown column 'mc.title' in 'where clause')                                      
#0 /volume1/web/spotweb/lib/dbeng/dbeng_pdo.php(123): dbeng_pdo->exec('SELECT COUNT(1)...', Array)
#1 /volume1/web/spotweb/lib/dao/Base/Dao_Base_Spot.php(637): dbeng_pdo->singleQuery('SELECT COUNT(1)...')
#2 /volume1/web/spotweb/lib/services/Actions/Services_Actions_CacheNewSpotCount.php(158): Dao_Base_Spot->getSpotCount('( (mc.title = '...')
#3 /volume1/web/spotweb/retrieve.php(180): Services_Actions_CacheNewSpotCount->cacheNewSpotCount()
#4 {main}

**Comment by eboman** [comment]
running the same script over and over will finally result in a completed session

**Comment by dsadsdadsadsadsds** [comment]
Do you happen to have an collection in your customer filters, @eboman ?

**Comment by dsadsdadsadsadsds** [comment]
I've added a fix in my current fork.

**Comment by eboman** [comment]
Yes i have a collectie in my filters

**Comment by Wally73** [comment]
then you're on the media branch

**Comment by Sweepr** [comment]
Closing, already fixed and no longer an active bug.
