### ISSUE TITLE
Spotweb error handling on invalid XML

### ISSUE THREAD

**Issue by mesa57** [spotweb/spotweb#161]
But a question: if I open a spot with XML error, a catch on the index.php catches that error and tries to echo the exception. However: that is not what I see, just a message box displaying there was an error and you will return to the page.

If I look at the serverlogs something dreadfull then goes on. It tries to do the open spot page call over and over again in an endless loop.
More over, if I open an other spot, endless errors are appended to the comment list.

  Is there any way to improve this error handling ?

**Comment by mesa57** [comment]
@dsadsdadsadsadsds example of such a spot : 
+bluezone +corporation +cinematic
The oldest one.

**Comment by dsadsdadsadsadsds** [comment]
The error handling in the frontend of Spotweb (the PHP and the HTML+JS parts) is really sucky. 

Someone might want to consider a few changes to this:

1. We currently use a sort of hacked-up PJAX-like code. Perhaps this should be fully replaced with a real PJAX implementation to prevent us from reinventing the wheel. The PJAX parts could be done fully frontend.

2. If we get an error (exception) we should return an JSON with the error in it (or just HTML) and display  it properly. Currently we discard the error.
