### ISSUE TITLE
Spam comment poster

### ISSUE THREAD

**Issue by Sweepr** [spotweb/spotweb#164]
Is there anything we can do to prevent this annoying comment poster from spamming comments in the erotic category?

Tsa arAnusDeStrontGrotNeukendeTyfusFlikkerTeringHomoVergasserDe1e

He is constantly adapting his name and changing his ID.

**Comment by Sweepr** [comment]
12069 rows deleted. (Query took 9.6300 sec)
DELETE FROM `commentsfull` WHERE `fromhdr` LIKE '%Stront%' OR '%Anus%' OR '%Flikker%'

![index](https://cloud.githubusercontent.com/assets/2857865/15292784/0f73b0a8-1b85-11e6-8c37-2bd797f0de37.jpg)

**Comment by mesa57** [comment]
He should be on the blacklist ?
Btw. he is using spotweb for his comments. And also regular changes his user (spotweb create a new user modulus). 
In spotnet we are now introducing a feature to block the whole spotweb instance by blocking the the spotweb server key.

**Comment by Sweepr** [comment]
Yes, i've put this guy and a few others on the blacklist many times but constantly come's back.

**Comment by mesa57** [comment]
That's because it is very easy in spotweb to change the userkey by just creating a new user.
Blacklisting the serverkey certainly helps. In spotnet all his comments are now blacklisted.

**Comment by Sweepr** [comment]
Where can i find that serverkey?

**Comment by mesa57** [comment]
Every (spotweb) comment includes a x-server-key xml in the headers.
The server key is in the spotweb settings table.
