### ISSUE TITLE
add feature top downloads

### ISSUE THREAD

**Issue by WagoL** [spotweb/spotweb#165]
Could it be possible to show the most downloaded items per category?

**Comment by mesa57** [comment]
The spotnet protocoll is not aware of downloads that are done. In spotweb only you're personal downloads are (optional) registered.

**Comment by WagoL** [comment]
So when I press "Download NZB" this doesnt get logged somewhere?

**Comment by Sweepr** [comment]
Yes it does,.. but only for your account.

**Comment by WagoL** [comment]
mhhm too bad. Thanks anyway.

**Comment by Wally73** [comment]
most of the nzbs are dummy's anyway so no use :p
