### ISSUE TITLE
Don't see green 'W'

### ISSUE THREAD

**Issue by vinzz73** [spotweb/spotweb#168]
I have an install I keep up to date using git and php db-update. I noticed I dont see the green W next to a posters' name, that is visible in a fresh install.

<span class="markGreen">W</span>

Anyone?

**Comment by Wally73** [comment]
you need to enable external white/black list

**Comment by vinzz73** [comment]
I see, is it this config setting?

https://github.com/spotweb/spotweb/wiki/Fix-blacklist-and-whitelist-problems

**Comment by mesa57** [comment]
Those are the settings included in the last version of spotweb.

**Comment by Wally73** [comment]
![671f7df5822a8ec016f285ea9f1b097e](https://cloud.githubusercontent.com/assets/2582289/15626537/337a3b16-24c7-11e6-922c-2b789ed7b436.png)

enable that

**Comment by vinzz73** [comment]
I still had the old urls:
![knipsel](https://cloud.githubusercontent.com/assets/17639498/15626593/6ea055f8-24c8-11e6-959c-cd61bb877fcf.JPG)
Updated, and now all good.

As I had a cronjob for retrieval, I did not notice this error output:

![knipsel](https://cloud.githubusercontent.com/assets/17639498/15626600/a65b3422-24c8-11e6-8dbd-796d63b62cf9.JPG)

**Comment by mesa57** [comment]
Ok, I am going to close this issue.
