### ISSUE TITLE
Some wiki pages cleared

### ISSUE THREAD

**Issue by RickDB** [Spotweb/Spotweb#17]
Seems some Wiki pages are now empty, was using them before as an reference for new users (keyboard shortcuts etc..) so would be great if they can make a comeback :+1: 
Few examples of cleared pages:

https://github.com/spotweb/spotweb/wiki/Performance-tips
https://github.com/spotweb/spotweb/wiki/Sneltoetsen

and most links that refer to the wiki on the site below:

http://www.spot-net.nl/spotweb/handleiding/

**Comment by Muis** [comment]
They may be archived on archive.org, that way they don't have to be rewritten.

**Comment by RickDB** [comment]
Sadly it didn't get cached completely:

https://web.archive.org/web/20130821141614/https://github.com/spotweb/spotweb/wiki

Perhaps Github kept some revisions and can restore them manually?

**Comment by hagst** [comment]
https://github.com/spot-net/spotweb/wiki still has a los of the pages.

**Comment by RickDB** [comment]
Thanks!
Gonna restore a few of the basic how to pages from that, maybe the wiki pages should be made private and only allow a select few to edit/delete them it in the future?

**Comment by Muis** [comment]
Thanks Rick for restoring the wiki!
