### ISSUE TITLE
[Feature Request] Adding Pushover to Notifications

### ISSUE THREAD

**Issue by Maverine** [spotweb/spotweb#170]
Would that be possible ? https://pushover.net/api

Thanks in advance

**Comment by Mickroz** [comment]
you can use email for that, just create a pushover app, and let spotweb notify by email and use this as your email:
userkey+a=appkey@api.pushover.net

@mesa57 https://pushover.net/faq#library-php

**Comment by Klumper** [comment]
> you can use email for that, just create a pushover app, and let spotweb notify by email and use this as your email:
userkey+a=appkey@api.pushover.net

I've tried this, but my spotweb doesn't seem to be sending an e-mail. not even to a regular e-mail adress. Does anyone have a idea why spotweb isn't sending e-mails at all?

Thanks

**Comment by Mickroz** [comment]
spotweb uses PHP mail, so if it's not sending email at all, you should look in that direction.

**Comment by Klumper** [comment]
Thanks for the quick response. I've been looking into the PHP mail but can't get it to work.. I've tried PHPmailer and Sendmail, nothing works..

**Comment by GeoffreyDijkstra** [comment]
The problem of php's `mail()` function is that it depends on how your server/host is configured. PHPmailer uses a direct connection if possible and otherwise falls back to php's `mail()` function. Are you running spotweb on windows or linux?

**Comment by Wally73** [comment]
https://www.google.nl/search?q=php+mail+with+gmail


On Tue, Aug 30, 2016 at 2:36 PM, Geoffrey Dijkstra <notifications@github.com

**Comment by mesa57** [comment]
There's a generic problem with notifications which I was looking into before my holiday

**Comment by Sweepr** [comment]
Work is in progress to implement phpmailer so closing this.

Further discussion can be done here if needed:
https://github.com/spotweb/spotweb/issues/497
