### ISSUE TITLE
Php crash

### ISSUE THREAD

**Issue by casiej** [spotweb/spotweb#171]
Every time i try to retrieve i get a php crash:
```


SpotWeb v0.67.28.31 on PHP v7.0.7-4+deb.sury.org~xenial+1 crashed

Fatal error occured retrieving reports:
  Unknown SchemaNotUpgradedException



#0 /var/www/spotweb/lib/Bootstrap.php(119): CustomException->__construct()
#1 /var/www/spotweb/lib/Bootstrap.php(49): Bootstrap->validate(Object(Services_Settings_Base))
#2 /var/www/spotweb/retrieve.php(20): Bootstrap->boot()
#3 {main}

PHP Notice:  Undefined variable: retriever in /var/www/spotweb/retrieve.php on line 313
PHP Fatal error:  Uncaught Error: Call to a member function quit() on null in /var/www/spotweb/retrieve.php:313
Stack trace:
#0 {main}
  thrown in /var/www/spotweb/retrieve.php on line 313
```
I'm using Ubuntu 16.04 and working on the master branch

**Comment by mesa57** [comment]
Could you execute upgrade-db.php once ?

**Comment by casiej** [comment]
```
Updating schema..(pdo_mysql)
	Validating spots(messaged)
	Validating spots(poster)
	Validating spots(title)
		Modifying column title (type) on spots


SpotWeb crashed

Database schema or settings upgrade failed:
   01000: 1265: Data truncated for column 'title' at row 132179


#0 /var/www/spotweb/lib/dbstruct/SpotStruct_mysql.php(223): dbeng_pdo->rawExec('ALTER TABLE spo...')
#1 /var/www/spotweb/lib/dbstruct/SpotStruct_abs.php(161): SpotStruct_mysql->modifyColumn('title', 'spots', 'VARCHAR(128)', NULL, false, 'utf8', 'type')
#2 /var/www/spotweb/lib/dbstruct/SpotStruct_abs.php(346): SpotStruct_abs->validateColumn('title', 'spots', 'VARCHAR(128)', NULL, false, 'utf8')
#3 /var/www/spotweb/lib/services/Upgrade/Services_Upgrade_Base.php(42): SpotStruct_abs->updateSchema()
#4 /var/www/spotweb/upgrade-db.php(44): Services_Upgrade_Base->database()
```

**Comment by mesa57** [comment]
Ok, thanks. Is this a new installation or an excisting one ?

**Comment by casiej** [comment]
a excisting one. It is displaying just fine but won't retrieve anymore.

**Comment by mesa57** [comment]
Thats because of this error : 
Database schema or settings upgrade failed:
   01000: 1265: Data truncated for column 'title' at row 132179

Which can only happen if you're title column now is more van 128 chars ? :confused:

**Comment by casiej** [comment]
Ow oke. Not much experience with php or mysql. Any way to fix this by editing the database?

**Comment by mesa57** [comment]
Ehhhh, you can try to delete the row 132179 from the spots table ?
Tell me please, what did you change before this error happened ?

**Comment by casiej** [comment]
evertime I remove a entry it gives a crash from te post next to it.. This will be a clean install i presume?
I think the problem first came up after a release update of ubuntu. But the strange thing is that it worked for some days but now this is happening

**Comment by mesa57** [comment]
Yes, indeed strange. What version of mysql or mariadb are you using ?

**Comment by casiej** [comment]
mysql  Ver 14.14 Distrib 5.7.12

**Comment by casiej** [comment]
if i switch to the media branch and do a upgrade-db i get this:
`Updating schema..(pdo_mysql)
	Validating spots(messageid)
	Validating spots(poster)
	Validating spots(title)
	Validating spots(tag)
	Validating spots(category)
	Validating spots(subcata)
	Validating spots(subcatb)
	Validating spots(subcatc)
	Validating spots(subcatd)
	Validating spots(subcatz)
	Validating spots(stamp)
	Validating spots(reversestamp)
	Validating spots(filesize)
	Validating spots(moderated)
	Validating spots(commentcount)
	Validating spots(spotrating)
	Validating spots(reportcount)
	Validating spots(spotterid)
	Validating spots(editstamp)
	Validating spots(editor)
	Validating spots(collectionid)
	Validating spotsfull(messageid)
	Validating spotsfull(verified)
	Validating spotsfull(usersignature)
	Validating spotsfull(userkey)
	Validating spotsfull(xmlsignature)
	Validating spotsfull(fullxml)
	Validating usenetstate(infotype)
	Validating usenetstate(curarticlenr)
	Validating usenetstate(curmessageid)
	Validating usenetstate(lastretrieved)
	Validating usenetstate(nowrunning)
	Validating commentsxover(messageid)
	Validating commentsxover(nntpref)
	Validating commentsxover(spotrating)
	Validating commentsxover(moderated)
	Validating commentsxover(stamp)
	Validating reportsxover(messageid)
	Validating reportsxover(fromhdr)
		Modifying column fromhdr (type) on reportsxover
	Validating reportsxover(keyword)
	Validating reportsxover(nntpref)
	Validating spotstatelist(messageid)
	Validating spotstatelist(ouruserid)
	Validating spotstatelist(download)
	Validating spotstatelist(watch)
	Validating spotstatelist(seen)
	Validating commentsfull(messageid)
	Validating commentsfull(fromhdr)
	Validating commentsfull(stamp)
	Validating commentsfull(usersignature)
	Validating commentsfull(userkey)
	Validating commentsfull(spotterid)
	Validating commentsfull(hashcash)
	Validating commentsfull(body)
	Validating commentsfull(verified)
	Validating commentsfull(avatar)
	Validating settings(name)
	Validating settings(value)
	Validating settings(serialized)
	Validating commentsposted(ouruserid)
	Validating commentsposted(messageid)
	Validating commentsposted(inreplyto)
	Validating commentsposted(randompart)
	Validating commentsposted(rating)
	Validating commentsposted(body)
	Validating commentsposted(stamp)
	Validating spotsposted(messageid)
	Validating spotsposted(ouruserid)
	Validating spotsposted(stamp)
	Validating spotsposted(title)
	Validating spotsposted(tag)
	Validating spotsposted(category)
	Validating spotsposted(subcats)
	Validating spotsposted(filesize)
	Validating spotsposted(fullxml)
	Validating reportsposted(ouruserid)
	Validating reportsposted(messageid)
	Validating reportsposted(inreplyto)
	Validating reportsposted(randompart)
	Validating reportsposted(body)
	Validating reportsposted(stamp)
	Validating usersettings(userid)
	Validating usersettings(privatekey)
	Validating usersettings(publickey)
	Validating usersettings(avatar)
	Validating usersettings(otherprefs)
	Validating users(username)
	Validating users(firstname)
	Validating users(passhash)
	Validating users(lastname)
	Validating users(mail)
	Validating users(apikey)
	Validating users(lastlogin)
	Validating users(lastvisit)
	Validating users(lastread)
	Validating users(lastapiusage)
	Validating users(deleted)
	Validating sessions(sessionid)
	Validating sessions(userid)
	Validating sessions(hitcount)
	Validating sessions(lasthit)
	Validating sessions(ipaddr)
	Validating sessions(devicetype)
	Validating securitygroups(name)
	Validating grouppermissions(groupid)
	Validating grouppermissions(permissionid)
	Validating grouppermissions(objectid)
	Validating grouppermissions(deny)
	Validating usergroups(userid)
	Validating usergroups(groupid)
	Validating usergroups(prio)
	Validating notifications(userid)
	Validating notifications(stamp)
	Validating notifications(objectid)
	Validating notifications(type)
	Validating notifications(title)
	Validating notifications(body)
	Validating notifications(sent)
	Validating filters(userid)
	Validating filters(filtertype)
	Validating filters(title)
	Validating filters(icon)
	Validating filters(torder)
	Validating filters(tparent)
	Validating filters(tree)
	Validating filters(valuelist)
	Validating filters(sorton)
	Validating filters(sortorder)
	Validating filters(enablenotify)
	Validating filtercounts(userid)
	Validating filtercounts(filterhash)
	Validating filtercounts(currentspotcount)
	Validating filtercounts(lastvisitspotcount)
	Validating filtercounts(lastupdate)
	Validating spotteridblacklist(spotterid)
	Validating spotteridblacklist(ouruserid)
	Validating spotteridblacklist(idtype)
	Validating spotteridblacklist(origin)
	Validating spotteridblacklist(doubled)
	Validating cache(resourceid)
	Validating cache(cachetype)
	Validating cache(stamp)
	Validating cache(metadata)
	Validating cache(ttl)
	Validating moderatedringbuffer(messageid)
	Validating permaudit(stamp)
	Validating permaudit(userid)
	Validating permaudit(permissionid)
	Validating permaudit(objectid)
	Validating permaudit(result)
	Validating permaudit(ipaddr)
	Validating debuglog(stamp)
	Validating debuglog(microtime)
	Validating debuglog(level)
	Validating debuglog(message)
	Validating mastercollections(title)
	Validating mastercollections(year)
	Validating mastercollections(lateststamp)
	Validating mastercollections(latestspotid)
	Validating mastercollections(cattype)
	Validating mastercollections(tmdb_id)
	Validating mastercollections(tvrage_id)
	Validating collections(mcid)
	Validating collections(season)
	Validating collections(episode)
	Validating collections(partscurrent)
	Validating collections(partstotal)
	Validating tmdb_info(tmdb_id)
	Validating tmdb_info(tmdb_collection_id)
	Validating tmdb_info(tmdb_collection_name)
	Validating tmdb_info(budget)
	Validating tmdb_info(homepage)
	Validating tmdb_info(imdb_id)
	Validating tmdb_info(tmdb_title)
	Validating tmdb_info(overview)
	Validating tmdb_info(popularity)
	Validating tmdb_info(release_date)
	Validating tmdb_info(revenue)
		Modifying column revenue (type) on tmdb_info
	Validating tmdb_info(runtime)
	Validating tmdb_info(tagline)
	Validating tmdb_info(vote_average)
	Validating tmdb_info(vote_count)
	Validating tmdb_info(last_retrieve)
	Validating tmdb_trailers(tmdb_id)
	Validating tmdb_trailers(name)
	Validating tmdb_trailers(size)
	Validating tmdb_trailers(source)
	Validating tmdb_trailers(type)
		Modifying column type (charset) on tmdb_trailers
	Validating tmdb_credits(tmdb_credit_id)
	Validating tmdb_credits(name)
	Validating tmdb_cast(tmdb_id)
	Validating tmdb_cast(tmdb_credit_id)
	Validating tmdb_cast(tmdb_cast_id)
	Validating tmdb_cast(character_name)
	Validating tmdb_cast(sort_order)
	Validating tmdb_cast(profile_path)
	Validating tmdb_crew(tmdb_id)
	Validating tmdb_crew(tmdb_credit_id)
	Validating tmdb_crew(department)
	Validating tmdb_crew(job)
	Validating tmdb_crew(profile_path)
	Validating tmdb_images(tmdb_id)
	Validating tmdb_images(image_type)
	Validating tmdb_images(aspect_ratio)
	Validating tmdb_images(file_path)
	Validating tmdb_images(height)
	Validating tmdb_images(width)
	Validating index idx_spots_1
	Validating index idx_spots_2
	Validating index idx_spots_3
	Validating index idx_spots_4
	Validating index idx_spots_5
	Validating FTS idx_fts_spots
	Validating index idx_usenetstate_1
	Validating index idx_spotsfull_1
	Validating index idx_commentsfull_1
	Validating index idx_commentsxover_1
	Validating index idx_commentsxover_2
	Validating index idx_reportsxover_1
	Validating index idx_reportsxover_2
	Validating index idx_reportsposted_1
	Validating index idx_reportsposted_2
	Validating index idx_reportspostedrel_1
	Validating index idx_commentsposted_1
	Validating index idx_commentspostedrel_1
	Validating index idx_spotsposted_1
	Validating index idx_spotspostedrel_1
	Validating index idx_settings_1
	Validating index idx_usersettings_1
	Validating index idx_users_1
	Validating index idx_users_2
	Validating index idx_users_3
	Validating index idx_users_4
	Validating index idx_sessions_1
	Validating index idx_sessions_2
	Validating index idx_sessions_3
	Validating index idx_sessionsrel_1
	Validating index idx_spotstatelist_1
	Validating index idx_spotstatelistrel_1
	Validating index idx_securitygroups_1
	Validating index idx_grouppermissions_1
	Validating index idx_usergroups_1
	Validating index idx_usergroupsrel_1
	Validating index idx_notifications_1
	Validating index idx_notifications_2
	Validating index idx_filters_1
	Validating index idx_filtercounts_1
	Validating index idx_spotteridblacklist_1
	Validating index idx_spotteridblacklist_2
	Validating index idx_cache_1
	Validating index idx_cache_2
	Validating index idx_moderatedringbuffer_1
	Validating index idx_mastercollections_1
	Validating index idx_collections_1
	Validating index idx_tmdbinfo_1
	Validating index idx_tmdbtrailers_1
	Validating index idx_tmdbcredits_1
	Validating index idx_tmdbcast_1
	Validating index idx_tmdbcrew_1
	Validating index idx_tmdbimages_1
Schema update done
Updating settings
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Crypt_Hash has a deprecated constructor in /var/www/spotweb/vendor/phpseclib/Crypt/Hash.php on line 85
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Crypt_RSA has a deprecated constructor in /var/www/spotweb/vendor/phpseclib/Crypt/RSA.php on line 251
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Math_BigInteger has a deprecated constructor in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 193
Settings update done
Updating users
Users' update done
Performing basic analysis of database tables
Basic database optimalisation done`

But when i do a retrieve i get this:
`root@:/var/www/spotweb# php retrieve.php 
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Net_NNTP_Client has a deprecated constructor in /var/www/spotweb/NNTP/Client.php on line 87
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Net_NNTP_Protocol_Client has a deprecated constructor in /var/www/spotweb/NNTP/Protocol/Client.php on line 131
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Crypt_Hash has a deprecated constructor in /var/www/spotweb/vendor/phpseclib/Crypt/Hash.php on line 85
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Crypt_RSA has a deprecated constructor in /var/www/spotweb/vendor/phpseclib/Crypt/RSA.php on line 251
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Math_BigInteger has a deprecated constructor in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 193


retriever.php is already running, pass '--reallyforce' to ignore this warning.
root@:/var/www/spotweb# php retrieve.php  --reallyforce
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Net_NNTP_Client has a deprecated constructor in /var/www/spotweb/NNTP/Client.php on line 87
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Net_NNTP_Protocol_Client has a deprecated constructor in /var/www/spotweb/NNTP/Protocol/Client.php on line 131
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Crypt_Hash has a deprecated constructor in /var/www/spotweb/vendor/phpseclib/Crypt/Hash.php on line 85
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Crypt_RSA has a deprecated constructor in /var/www/spotweb/vendor/phpseclib/Crypt/RSA.php on line 251
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Math_BigInteger has a deprecated constructor in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 193
Last retrieve at Mon 13 Jun 2016 12:00:05 PM CEST
Retrieving new Spots from server news.sunnyusenet.com...
Appr. Message count: 	1240311
First message number:	2360233
Last message number:	3600544
Current article number:	3599570

Retrieving 3599570 till 3600071 (parsed: 500, in DB: 1, signed: 490, invalid: 10, rtntn.skip: 0, mod: 0, full: 0, total: 501)PHP Fatal error:  Uncaught Error: Call to undefined function mb_convert_encoding() in /var/www/spotweb/lib/dao/Base/Dao_Base_Spot.php:435
Stack trace:
#0 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Spots.php(605): Dao_Base_Spot->addSpots(Array, Array)
#1 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(227): Services_Retriever_Spots->process(Array, '3599570', 3600071, 1466027559.6756)
#2 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(319): Services_Retriever_Base->loopTillEnd(3600071, '500')
#3 /var/www/spotweb/retrieve.php(155): Services_Retriever_Base->perform()
#4 {main}
  thrown in /var/www/spotweb/lib/dao/Base/Dao_Base_Spot.php on line 435`

**Comment by mesa57** [comment]
Sorry,I don't support the media branche. One branch is enough work.
I advise a complete reinstall.

**Comment by casiej** [comment]
After clean install i still get this error at first retrieve. Did a fresh clone of the master branch
`php retrieve.php 
Last retrieve at Thu 01 Jan 1970 01:00:00 AM CET
Retrieving new Spots from server news.sunnyusenet.com...
Appr. Message count: 	1208875
First message number:	2391971
Last message number:	3600846
Current article number:	2391971

Retrieving 2391971 till 2396972 (parsed: 5001, in DB: 0, signed: 1380, invalid: 3294, rtntn.skip: 0, mod: 327, full: 0, total: 5001)PHP Fatal error:  Uncaught Error: Call to undefined function mb_convert_encoding() in /var/www/spotweb/lib/dao/Base/Dao_Base_Spot.php:441
Stack trace:
#0 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Spots.php(608): Dao_Base_Spot->addSpots(Array, Array)
#1 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(227): Services_Retriever_Spots->process(Array, '2391971', 2396972, 1466108772.1265)
#2 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(319): Services_Retriever_Base->loopTillEnd(2396972, '5000')
#3 /var/www/spotweb/retrieve.php(154): Services_Retriever_Base->perform()
#4 {main}
  thrown in /var/www/spotweb/lib/dao/Base/Dao_Base_Spot.php on line 441`

**Comment by mesa57** [comment]
Different error. It points to mb_string not installed or activated in you're php installation.

**Comment by casiej** [comment]
Ow strange it was installed. But its a bug in 16.04 for some people that it is disabled by upgrading
Thanks, is receiving now!

**Comment by casiej** [comment]
Everything works fine now. Thanks for the help!

**Comment by mesa57** [comment]
Thanks for reporting back. I'll close this issue.
