### ISSUE TITLE
Php 7.0.7 Mysql 5.7.13 unable to retrieve spots

### ISSUE THREAD

**Issue by basnagel** [spotweb/spotweb#172]
I have a FreeBSD 10.3 jail with spotweb in it.
Previous mysql version worked, i updated to 5.7 and I got the following error.
 
potWeb v0.67.28.31 on PHP v7.0.7 crashed

Fatal error occured retrieving reports:
  HY000: 1785: Statement violates GTID consistency: Updates to non-transactional tables can only be done in either autocommitted statements or single-statement transactions, and never in the same statement as updates to transactional tables.

#0 /usr/local/www/nginx/spotweb/lib/dbeng/dbeng_pdo.php(74): dbeng_pdo->exec('DELETE FROM spo...', Array)
#1 /usr/local/www/nginx/spotweb/lib/dao/Mysql/Dao_Mysql_Spot.php(18): dbeng_pdo->modify('DELETE FROM spo...')
#2 /usr/local/www/nginx/spotweb/lib/services/Retriever/Services_Retriever_Spots.php(628): Dao_Mysql_Spot->removeSpots(Array)
#3 /usr/local/www/nginx/spotweb/lib/services/Retriever/Services_Retriever_Base.php(227): Services_Retriever_Spots->process(Array, 6070717, 6072718, 1466184763.7361)
#4 /usr/local/www/nginx/spotweb/lib/services/Retriever/Services_Retriever_Base.php(319): Services_Retriever_Base->loopTillEnd(6072718, '2000')
#5 /usr/local/www/nginx/spotweb/retrieve.php(154): Services_Retriever_Base->perform()
#6 {main}

Finished retrieving spots.

Searching for this error: violates GTID consistency I found out that somewhere during mqsql history.
I disabled that feature in mqsql without succes
After restart this was enabled again.

Also came into some issues with binlog, I am disabling this at the moment to check if it works.
http://mindspill.net/computing/linux-notes/disable-mysql-binary-logging/

Now retrieve is running much longer than previous so i have hope.
It worked.
(note: for the new mysql update i had to change a setting considering allowed MB for a setting, not sure what is was:( Thinking about it, might be the binlog size)

**Comment by mesa57** [comment]
Just this afternoon I performed a test with spotweb running in Ubuntu 16, PHP 7 and MySQL 5.7
Everything run's fine (and very fast compared to php 5.6 / mysql 5.6). 
So there must be something wrong with you're installation.

**Comment by ghz-maniac** [comment]
Having the same issue in a Jail in Freenas - 9.10
Fatal error occured retrieving reports:                                         
  HY000: 1785: Statement violates GTID consistency: Updates to non-transactional
 tables can only be done in either autocommitted statements or single-statement 
transactions, and never in the same statement as updates to transactional tables

**Comment by basnagel** [comment]
Disable, the Bin Log in Mysql server

**Comment by mesa57** [comment]
In my Ubuntu installation is is indeed default off.

**Comment by ghz-maniac** [comment]
Thanks! - that solved the issue, must have missed this in my haste to get my new setup working :)
