### ISSUE TITLE
Running spotweb on HTTPS reverse proxy, spotweb internal URL's point to HTTP

### ISSUE THREAD

**Issue by piejanssens** [spotweb/spotweb#176]
This results in no CSS, no JS, because all these URL's are being called with HTTP and the most recent browsers refuse to mix HTTP on HTTPS. See screenshot. 
When I click on "Change preferences" it opens the page with HTTP and then the CSS/JS is loaded, but at this point the connection is not secure...

![](https://cdn.pbrd.co/images/1k0zYrp8N.png)

**Comment by piejanssens** [comment]
I'm quite sure this is caused by "<base href="**http**://xxxxxx.synology.me/spotweb/">"

**Comment by WzL** [comment]
Which reverse proxy is used? Does the reverse proxy perform ssl offloading?

Op 27 jul. 2016 8:57 a.m. schreef "Pieter Janssens" <
notifications@github.com>:

**Comment by piejanssens** [comment]
Looking at this code I think I just need to set the base URL myself in some config file. 
https://github.com/spotweb/spotweb/blob/f07ff36a1926176d99276daf5bd619b5ebbf0ea7/lib/SpotTemplateHelper.php#L135

I forgot I ever did that (long time ago when I wasn't using my haproxy).

**Comment by piejanssens** [comment]
Now looking a bit further I see that it should compose the base URL automatically. So there is a bug or at least a misconfiguration on my behalf somewhere. https://github.com/spotweb/spotweb/blob/0b163a61d476e64e3ffcefe369b5db1a4bdafd97/settings.php#L31

**Comment by piejanssens** [comment]
Also see http://stackoverflow.com/questions/11650640/why-isnt-serverhttps-set-to-1

**Comment by piejanssens** [comment]
But why are you using that anyway? 
You can just do <base href="//working.url.using.the.current.protocol">

**Comment by LeeThompson** [comment]
I'm having a similar issue with reverse proxy (IIS 7.5) with spotweb running on Apache 2.4, CSS and JS seem to be malfunctioning but what's odd is if I reference the css directly `http://[myserver]/spotweb/?page=statics&type=css&mod=1470926106` it looks fine.

**Comment by piejanssens** [comment]
@LeeThompson Try the applying the change shown in #177

**Comment by LeeThompson** [comment]
@piejanssens that worked! thanks

**Comment by mesa57** [comment]
I will merge the mentioned pull with the risc that we have to immediatly undo it if somebody complaints.
