### ISSUE TITLE
php7 on ubuntu 16.04

### ISSUE THREAD

**Issue by glenhartwig** [spotweb/spotweb#180]
update.sh is giving an error because it tries to use /usr/bin/php5 which is not installed.
Ubuntu 16.04 is using php7 so I changed it to /usr/bin/php7.0 (/usr/bin/php also works).
Should the script be updated for use with other versions of php or is there a reason for using php5?

**Comment by mesa57** [comment]
You may add an export var for the php path, but set this default to php5 as mainstream is still using php5

**Comment by Wally73** [comment]
just change your local one ;)

**Comment by mesa57** [comment]
Yeah, thats possible. But if you look at the script there are already 2 variables to be filled in. A third one could be added. So I want to encourage @glenhartwig to do that and create a pull request.
