### ISSUE TITLE
Newznab API GET Action Type is Out of Spec

### ISSUE THREAD

**Issue by NeilBetham** [spotweb/spotweb#187]
Hello,

The GET action type for the Newznab API is currently returning 302s to a Spotweb URI for downloading a NZB. This does not follow the Newznab specification which [indicates](http://newznab.readthedocs.io/en/latest/misc/api/#get) the requested NZB be in the body of the response. This isn't a huge deal but it does make for extra work on the consumer's end to make sure to follow redirects if there are any.

**Comment by Wally73** [comment]
no issues here with getting nzb's from spotweb into my sabnzb from sickrage

**Comment by NeilBetham** [comment]
In most cases indexers are handling it on their own by following the redirect. But in the process of testing my own consumer, and testing it against a Spotweb instance, it didn't work off the bat because it was not following the redirect. Which I didn't implement because it's not a response defined by the Newznab specification.

**Comment by NeilBetham** [comment]
One of the other complications of this issue is that the response from the Spotweb endpoint that is redirected to then returns a different error type if the there was a problem finding the NZB.
