### ISSUE TITLE
Question: innodb_file_per_table and the spots table being MyIsam

### ISSUE THREAD

**Issue by just-Addict** [spotweb/spotweb#189]
As in the subject, I was going through the section on performance tips and came across the suggestion to use innodb_file_per_table. However, the spots table in both my two main spotweb databases were created as MyIsam tables. Which would make using this option rather pointless I think since this does not apply to MyIsam tables if I understood correctly.

So, I was considering converting the spots tables in those databases to InnoDB format, but I am not sure if this could cause issues later on. Since MyIsam does not support transactions there are obviously no commit/rollback scenarios in code handling the spot table so I'm not sure if converting to InnoDB is advisable or not in this case.

Any comments?

**Comment by Sweepr** [comment]
Not sure why they are still MyIsam, on my test environment i used `ALTER TABLE spotsENGINE=InnoDB; ` and `ALTER TABLE sessions ENGINE=InnoDB;` to convert those table's to InnoDB so both are now converted to InnoDB, see how things roll from here..

**Comment by mesa57** [comment]
Prior to mysql 5.6, full text search (which is important in spotweb) was not supported for InnoDB tables.
As there are still people using old mysql versions this configuration has stayed.

**Comment by Sweepr** [comment]
@mesa57, that's correct, so if you have mysql 5.6 you could safely convert to InnoDB.
