### ISSUE TITLE
Notify My Android notifications sent in Dutch instead of English

### ISSUE THREAD

**Issue by mbirth** [Spotweb/Spotweb#19]
I set my user account to English language but NMA notifications arrive in Dutch, like this:

<blockquote><strong>1 nieuwe spots beschikbaar in filter "Walking Dead"</strong><br />

Walking Dead heeft 1 spots beschikbaar</blockquote>

This is with the current 96a688f341 revision.

**Comment by Blauwbek** [comment]
That is because of a lack of translations in the templates
https://github.com/Spotweb/Spotweb/tree/master/templates/notifications
I'll look into it.

**Comment by Sweepr** [comment]
I have translated the entire notifications folder as of now.

Closing the issue.
