### ISSUE TITLE
SSL enabled on newsserver on Ubuntu 16.04 error

### ISSUE THREAD

**Issue by ThEWiZ76** [spotweb/spotweb#190]
Just did a clean install on a new server, satisfied all the dependencies in the install.php but now I cannot retrieve any spots over SSL due to some weird certificate verification error:

/usr/bin/php retrieve.php
Last retrieve at Thu 01 Jan 1970 01:00:00 AM CET
Retrieving new Spots from server news.tweaknews.nl...
PHP Warning:  stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /var/www/html/spotweb/NNTP/Protocol/Client.php on line 725
PHP Warning:  stream_socket_client(): Failed to enable crypto in /var/www/html/spotweb/NNTP/Protocol/Client.php on line 725
PHP Warning:  stream_socket_client(): unable to connect to ssl://news.tweaknews.nl:563 (Unknown error) in /var/www/html/spotweb/NNTP/Protocol/Client.php on line 725
SpotWeb v0.67.28.31 on PHP v7.0.8-0ubuntu0.16.04.3 crashed

Fatal error occured while connecting to the newsserver:
  (-1) Error while connecting to server (server did not respond) [response: ""] [response: ""]

#0 /var/www/html/spotweb/lib/services/Nntp/Services_Nntp_Engine.php(120): Services_Nntp_Engine->connect()
#1 /var/www/html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(112): Services_Nntp_Engine->selectGroup('free.pt')
#2 /var/www/html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(280): Services_Retriever_Base->connect(Array)
#3 /var/www/html/spotweb/retrieve.php(154): Services_Retriever_Base->perform()
#4 {main}

Finished retrieving spots.

**Comment by mesa57** [comment]
certificate verify failed : lijkt me een tweaknews probleem. Dan maar zonder ssl.

**Comment by ThEWiZ76** [comment]
Nope, I have the exact same installation and settings on Ubuntu 14.04. I think it has some connection with the newer php version on 16.04 or something like that

Last retrieve at Sat 29 Oct 2016 10:30:15 PM CEST
Retrieving new reports from server news.tweaknews.nl...
Appr. Message count:    228683
First message number:   27
Last message number:    228710
Current article number: 228710

Processed a total of 0 reports
Finished retrieving reports.

https://gyazo.com/591233479293c61879775cb4303b31c3

**Comment by mesa57** [comment]
I have no problems whatsoever retrieving spots with SSL via supernews.

**Comment by mesa57** [comment]
Btw. do you have the latest version of spotweb ?

**Comment by ThEWiZ76** [comment]
Yes, did a fresh pull during the installation yesterday...

**Comment by mesa57** [comment]
Ok, in a previous pull an SSL problem was solved, but indeed not this one.
I cannot reproduce this error as I have no subscription with Tweaknews.

**Comment by ThEWiZ76** [comment]
I think curl is used to fetch stuff? I saw this thread that states that this could help:
Then turn off certificate verification (CURLOPT_SSL_VERIFYPEER -> false)

http://stackoverflow.com/questions/6400300/https-and-ssl3-get-server-certificatecertificate-verify-failed-ca-is-ok

I know this is not the most secure option to do, but we are not sending any banking or credit card info...

**Comment by mesa57** [comment]
Curl is not used for NNTP communication. PHP-sockets is.

**Comment by ThEWiZ76** [comment]
tested the same settings on the same server in Sabnzbd, no problems. Don't know if it is any help.

**Comment by GeoffreyDijkstra** [comment]
@ThEWiZ76 I also had problems with SSL when PHP7(.0.0) was just released. But I'm using the latest version now on which it runs fine, Ubuntu however doesn't have the latest PHP7(.0.12) included yet. So I suggest adding this repo: `sudo add-apt-repository ppa:ondrej/php` which has PHP7 updates ASAP and run `apt-get update` and `apt-get upgrade`.

(SIDE NOTE: Using this ^ repo you can also install PHP5 back in the latest Ubuntu)

Let me know if it worked! 😄

**Comment by mesa57** [comment]
If not, you can try to change nnyp\protocol\client.php at line 705 and add / change : 

```
        $contextOptions = ['ssl' => ['verify_peer' => false]];
        $context = stream_context_create($contextOptions);

    	// Open Connection
    	$R = stream_socket_client($transport . '://' . $host . ':' . $port, $errno, $errstr, $timeout,STREAM_CLIENT_CONNECT, $context);

```

**Comment by GeoffreyDijkstra** [comment]
I like to add that you only should do this as a final solution, because it's to have it enabled. Also I know TweakNews works with it enabled on my machine.

**Comment by mesa57** [comment]
@GeoffreyDijkstra : You're added to the testteam :wink:

**Comment by ThEWiZ76** [comment]
@GeoffreyDijkstra tested with the alternate php version, no luck unfortunately!

@mesa57 Looked at the code here (https://github.com/spotweb/spotweb/blob/master/NNTP/Protocol/Client.php) it does not seem logical to add that code there to that file. I've added it on line 723. I'm just pointing this out as a reference for other users that may have the same problems and want to try that fix.

anyways, the second option fixed it, thanks guys!
