### ISSUE TITLE
PHP Timeout In DBENG_PDO

### ISSUE THREAD

**Issue by LeeThompson** [spotweb/spotweb#191]
I'm getting this on nearly every run of ``retrieve.php``.

``PHP Fatal error:  Maximum execution time of 120 seconds exceeded in X:\Public\HTTPD\APPS\spotweb\lib\dbeng\dbeng_pdo.php on line 57``

What's extra weird is my ``php.ini`` value for ``max_execution_time`` is 600.

EDIT:
For clarity:

The above fatal error is occuring in PHP's log file.
Windows 7 (x64)
PHP 7.0.11 (x64)

**Comment by Sweepr** [comment]
Are you sure bash is using the same PHP version?

Maybe you did not change the global php.ini

**Comment by LeeThompson** [comment]
I'm on Windows (Windows 7 x64), php interpreter is php 7.0.11 (x64).    What's also strange is `max_execution_time` is usually ignored when in CLI.

**Comment by GeoffreyDijkstra** [comment]
Did you allready tried to set it to unlimited, like default in cli with
adding set_time_limit(0) to the top of retrieve.php?

Op 3 nov. 2016 07:27 schreef "Lee Thompson" <notifications@github.com>:

**Comment by LeeThompson** [comment]
Added `set_time_limit(0)` to `retrieve.php`, no change.

**Comment by mesa57** [comment]
It is a timeout when executing sql on you're database. I would check you're DB installation.

**Comment by LeeThompson** [comment]
@mesa57 I don't think so, otherwise it wouldn't error `max_execution_time` in php's log and I'd be having problems with newznab on the same database engine.      Does Spotnab override the ini settings anywhere?

**Comment by mesa57** [comment]
Time limit is set to 120 in services_retriever_base, _spots, _reports and _comments
You could also try to limit the nr. of headers retrieved at one time.

**Comment by LeeThompson** [comment]
@mesa57 thanks, I've changed those 4 locations to use "600" just to see how bad it breaks.

**Comment by mesa57** [comment]
Feel free, but you are the first reporting this problem.

**Comment by LeeThompson** [comment]
@mesa57 ... I'm surprised.   I just started using spotweb this week so it's doing a lot of back-filling, seems an odd design to hardwire it with the time limits.

It's not really going that slowly just doing a lot, excerpt:

```
Retrieving 14061359 till 14066360, found 5001 comments in 25.4 seconds
Retrieving 14066360 till 14071361, found 5001 comments in 28.51 seconds
Retrieving 14071361 till 14076362, found 5001 comments in 9.9 seconds
Retrieving 14076362 till 14081363, found 5001 comments in 34.25 seconds
Retrieving 14081363 till 14086364, found 5001 comments in 27.34 seconds
Retrieving 14086364 till 14091365, found 4999 comments in 10.93 seconds
Retrieving 14091365 till 14096366, found 4999 comments in 9.67 seconds
Retrieving 14096366 till 14101367, found 5001 comments in 32 seconds
Retrieving 14101367 till 14106368, found 5001 comments in 33.43 seconds
Retrieving 14106368 till 14111369, found 5001 comments in 27.05 seconds
Retrieving 14111369 till 14116370, found 5001 comments in 10.93 seconds
Retrieving 14116370 till 14121371, found 5000 comments in 17.63 seconds
Retrieving 14121371 till 14126372, found 5001 comments in 34.94 seconds
```

(It is running on the same box that's been running newznab for several years so the slowdowns are probably when the newznab release processing is hitting.)

**Comment by LeeThompson** [comment]
It's also an odd design that if the script is terminated (by php or something else) that you have to do the --force parameter because it thinks it's still running (because it's keeping track of that in the database, strange, strange place for that.)

**Comment by mesa57** [comment]
Many people run retrieve.php time triggered, for instance from crontab. The mechanism in place is to prevent that retrieve run's parallel if they overlap in time.

**Comment by LeeThompson** [comment]
I have it set up in the Windows equivelent (task scheduler) but it's set not to run it if it's already running.

**Comment by just-Addict** [comment]
I've ran into the exact same timeout problem when installing from scratch, and the processing times around ~30 seconds for each batch of 5000 comments is about the same I was seeing and still see. 

Also found I still had to keep using the --force argument in cron tasks to get around issues when it dies on the statistics (which seems to happen regularly...)

**Comment by mesa57** [comment]
The --force is only needed when there is a relatively short time between consecutive runs of retrieve.
After a certain period (I do not know the exact time by hard), the force is not needed any more.
So as example : if you have a gap op 15 mins. between consicutive run's the force option is not needed, even if some run's crash.
