### ISSUE TITLE
Missed Localizations

### ISSUE THREAD

**Issue by LeeThompson** [spotweb/spotweb#192]
in ``templates\we1rdo\includes\filters.inc.php`` some text is still hardcoded.

line 188: "`<h4>Sorteren op:</h4>`" should be "`<h4><?php echo _('Sort on:'); ?></h4>`"

``scripts.js`` has some as well.

**Comment by GeoffreyDijkstra** [comment]
I suggest that you make a PR's for things like this.

**Comment by LeeThompson** [comment]
I haven't done many of those, I'll do my best though.

**Comment by LeeThompson** [comment]
Moved to https://github.com/spotweb/spotweb/issues/225
