### ISSUE TITLE
Unable to add comments

### ISSUE THREAD

**Issue by Adam1986** [spotweb/spotweb#193]
Good morning,

I am finding I am unable to add comments onto SpotWeb.

I am getting some errors in NGINX error log and PHP5.6-FPM.log.

This is running NGINX and PHP 5.6.

These are the errors:

PHP5.6-FPM.log:

> [03-Nov-2016 09:30:43] WARNING: [pool www] chPild 9900 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491"
> [03-Nov-2016 09:30:43] WARNING: [pool www] child 9900 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491"
> [03-Nov-2016 09:30:43] WARNING: [pool www] child 9900 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3422"
> [03-Nov-2016 09:30:43] WARNING: [pool www] child 9900 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3423"
> [03-Nov-2016 09:30:43] WARNING: [pool www] child 9900 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491"
> [03-Nov-2016 09:30:43] WARNING: [pool www] child 9900 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491"
> [03-Nov-2016 09:30:43] WARNING: [pool www] child 9900 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491"
> [03-Nov-2016 09:30:43] WARNING: [pool www] child 9900 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491"
> [03-Nov-2016 09:30:43] WARNING: [pool www] child 9900 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3422"
> [03-Nov-2016 09:30:43] WARNING: [pool www] child 9900 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3423"
> [03-Nov-2016 09:30:43] WARNING: [pool www] child 9900 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3422"
> [03-Nov-2016 09:30:43] WARNING: [pool www] child 9900 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3423"
> [03-Nov-2016 09:30:43] WARNING: [pool www] child 9900 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 21 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491"
> [03-Nov-2016 09:30:43] WARNING: [pool www] child 9900 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491"
> [03-Nov-2016 09:30:43] WARNING: [pool www] child 9900 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491"
> [03-Nov-2016 09:30:43] WARNING: [pool www] child 9900 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 21 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491"
> [03-Nov-2016 09:30:43] WARNING: [pool www] child 9900 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491"
> [03-Nov-2016 09:30:43] WARNING: [pool www] child 9900 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 21 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491"
> [03-Nov-2016 09:30:43] WARNING: [pool www] child 9900 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491"
> [03-Nov-2016 09:30:43] WARNING: [pool www] child 9900 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 21 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491"
> [03-Nov-2016 09:30:43] WARNING: [pool www] child 9900 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491"
> [03-Nov-2016 09:30:43] WARNING: [pool www] child 9900 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 21 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491"
> [03-Nov-2016 09:30:43] WARNING: [pool www] child 9900 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491"
> [03-Nov-2016 09:30:43] WARNING: [pool www] child 9900 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 21 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491"
> [03-Nov-2016 09:30:43] WARNING: [pool www] child 9900 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491"
> [03-Nov-2016 09:30:43] WARNING: [pool www] child 9900 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined offset: 21 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491"

This goes on and on and its pretty much the same for NGINX log:

> 2016/11/03 09:14:25 [error] 9816#0: *1 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491
> PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491
> PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491
> PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491
> PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3422
> PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3423
> PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3422
> PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3423
> PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491
> PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491
> PHP message: PHP Notice:  Undefined offset: 20 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 21 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 23 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 24 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 25 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 26 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 27 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line
> 2016/11/03 09:14:25 [error] 9816#0: *1 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined offset: 42 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset:" while reading upstream, client: x.x.x.x, server: domain.com, request: "POST /?page=postcomment HTTP/1.1", upstream: "fastcgi://unix:/run/php/php5.6-fpm.sock:", host: "domain.com", referrer: "https://domain.com/?page=index&search[tree]=cat0_z0,cat0_z1,cat0_z2,cat0_z3,&search[value][]=Title%3A%3D%3A3d"
> 2016/11/03 09:14:25 [error] 9816#0: *1 FastCGI sent in stderr: " 43 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 44 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 45 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 46 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 47 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 48 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 49 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 50 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 51 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 52 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 53 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 54 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 55 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 56 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 57 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 58 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 59 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined o
> 2016/11/03 09:14:25 [error] 9816#0: *1 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined offset: 73 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 74 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 75 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 76 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 77 in /var/www/spotweb/v" while reading upstream, client: x.x.x.x, server: domain.com, request: "POST /?page=postcomment HTTP/1.1", upstream: "fastcgi://unix:/run/php/php5.6-fpm.sock:", host: "domain.com", referrer: "https://domain.com/?page=index&search[tree]=cat0_z0,cat0_z1,cat0_z2,cat0_z3,&search[value][]=Title%3A%3D%3A3d"
> 2016/11/03 09:14:25 [error] 9816#0: *1 FastCGI sent in stderr: "endor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 78 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 79 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 80 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 81 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 82 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 83 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 84 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 85 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 86 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 87 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 88 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 89 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 90 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 91 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 92 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 93 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 94 in /var/www/spo
> 2016/11/03 09:14:25 [error] 9816#0: *1 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined offset: 104 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 105 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 106 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 107 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 108 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 109 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 110 in /var/www/spotweb/vendor/phpseclib/Math/BigInteger.php on line 1031
> PHP message: PHP Notice:  Undefined offset: 111 in /var/www/spotweb/vendor/phpseclib/M" while reading upstream, client: x.x.x.x, server: domain.com, request: "POST /?page=postcomment HTTP/1.1", upstream: "fastcgi://unix:/run/php/php5.6-fpm.sock:", host: "domain.com", referrer: "https://domain.com/?page=index&search[tree]=cat0_z0,cat0_z1,cat0_z2,cat0_z3,&search[value][]=Title%3A%3D%3A3d"
> 2016/11/03 09:14:25 [error] 9816#0: *1 FastCGI sent in stderr: "ath/BigInteger.php on line 1031

Can anybody help?
Thanks

**Comment by GeoffreyDijkstra** [comment]
Which provider are you using?

**Comment by Adam1986** [comment]
Cheapnews, but also just tried using Supernews as the server for posting and it made no difference?

Thanks

**Comment by GeoffreyDijkstra** [comment]
Never tried either of them, but will take a look later today.
Do you know if Cheapnews / Supernews supports posting?

@mesa57 You can assign this to me if you like.

**Comment by Adam1986** [comment]
Supernews definitely supports posting, I am pretty sure Cheapnews does but would need to confirm.

Thanks for looking into this.

**Comment by mesa57** [comment]
This prob. an error calculating the usersignature of the comment.
Are you using php openssl ?

**Comment by Sweepr** [comment]
You could try to download the latest release phpseclib and extract/replace it in the existing directory.

See if that solve's it.

**Comment by GeoffreyDijkstra** [comment]
This one of the reasons why we need composer for spotweb.

**Comment by Adam1986** [comment]
Just sussed it, I hadn't installed PHP-GMP - Now comments are adding.

Now the only other issue I am having is using the NZB 360 App from my Android phone to send to SAB, nothing happens at all.  If I test it on my test SpotWeb site which happens to be running on Windows it works perfectly fine.

Send to SAB works fine within the actual site though, bit confusing.
