### ISSUE TITLE
API URL Returned Incorrectly

### ISSUE THREAD

**Issue by Adam1986** [spotweb/spotweb#197]
Got something strange going on with my new install of Spotweb on my Ubuntu install now.

In Firefox I get a blank page with no API results, but Chrome does return information but the URL is wrong.

It's been returned like this - Notice the two trailing slashes at the start of each link?

```
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/" version="2.0">
<channel>
<atom:link href="//sw.domain.com/api" rel="self" type="application/rss+xml"/>
<title>Spotweb Index</title>
<description>Spotweb Index API Results</description>
<link>//sw.domain.com/</link>
<language>en-gb</language>
<webMaster>admin@domain.com</webMaster>
<category/>
<image>
<url>//sw.domain.com/images/spotnet.gif</url>
<title>Spotweb Index</title>
<link>//domain.com/</link>
<description>SpotWeb Index API Results</description>
</image>
<newznab:response offset="0" total="13"/>
```

This is my NGINX Configuration:

```
server {
       listen 80;
       return 301 https://$host$request_uri;
}
server { listen 443; ssl on; ssl_certificate /etc/nginx/ssl/bundle.crt; ssl_certificate_key /etc/nginx/ssl/cert.key;
    server_name sw.domain.com;
    root /var/www/spotweb;
    index index.html index.htm index.php;
    location / {
        satisfy any;
        if ($uri !~ "api/"){
                rewrite /api/?$ /index.php?page=newznabapi last;
        }
    location ~ \.php$ {
                include fastcgi_params;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass unix:/var/run/php/php5.6-fpm.sock;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}

```
Any ideas what is going on here?

Thanks

**Comment by mesa57** [comment]
Can you look at this pull request if that is maybe causing the issue or maybe solves it when installed ?
I have no reverse nginx proxy installed, so I cannot test.
https://github.com/spotweb/spotweb/pull/177

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by WzL** [comment]
I can not understand how I can test this? I have similar setup with last version of SW but i do not understand how to test this behaviour?!

**Comment by Adam1986** [comment]
Hi Mesa57,

Thanks for your reply, the thing is I am not using any reverse proxy in nginx for Spotweb, it is a straight forward server block running as SSL, so I am not sure it is the issue you mention?

Thanks

**Comment by Adam1986** [comment]
Hi Mesa57,

Thanks for your reply, the thing is I am not using any reverse proxy in nginx for Spotweb, it is a straight forward server block running as SSL, so I am not sure it is the issue you mention?

Thanks

**Comment by Adam1986** [comment]
Just to update you,

I have altered the line within settings.php with the older version and this now appears to be working.

I will do some further testing but this definitely looks much better.

Thanks

**Comment by mesa57** [comment]
Change is reverted.
