### ISSUE TITLE
.htaccess blocks web related resources.

### ISSUE THREAD

**Issue by Mickroz** [spotweb/spotweb#198]
my spotweb updated last night , and now images set in the css file aren't loading anymore.
after deleting the .htaccess files, it worked again.
templates/.htaccess
templates/we1rdo/img/.htaccess

**Comment by mesa57** [comment]
Thanks for reporting Mickroz.

**Comment by GeoffreyDijkstra** [comment]
@mesa57 I will do this one :)

**Comment by GeoffreyDijkstra** [comment]
@Mickroz Can you tell me which CSS file? Or all inside the template dir?

**Comment by Mickroz** [comment]
all i guess, i had to delete both .htaccess files mentioned above to get it to work.
owh templates/we1rdo/css/.htaccess too, failed to load templates/we1rdo/css/images/ui-icons_222222_256x240.png, so i guess templates/we1rdo/js/.htaccess will fail too?

**Comment by GeoffreyDijkstra** [comment]
Well I set them up in a certain way, so I guess only one is creating the trouble. But I'll fix this ASAP.

**Comment by Mickroz** [comment]
smileys load without a problem tho

**Comment by GeoffreyDijkstra** [comment]
@Mickroz I removed/modified those .htaccess files because it depends to much on Apache configuration , so it should be fixed when you update spotweb.

**Comment by Mickroz** [comment]
fixed! thanks!
