### ISSUE TITLE
retrieve.php not working

### ISSUE THREAD

**Issue by pjanzen** [spotweb/spotweb#204]
Hi All,

On a fresh Ubuntu 16.04.1 LTS with php7 the retrieve.php is telling me:

root@mysql1:/var/www/html/spotweb# php retrieve.php
Unable to connect to database: No database settings have been entered, please use the 'install.php' wizard to install and configure Spotweb.
If you are upgrading from an earlier version of Spotweb, please consult https://github.com/spotweb/spotweb/wiki/Frequently-asked-questions/ first

Now obviously I have run the http://<host>/spotweb/install.php (twice), the output is all ok and the the dbsettings.inc.php is created. The frontend is working fine and the user is also allowed to connect to the database.

(not to worry, this is NOT the actual password)
root@mysql1:/var/www/html/spotweb# cat dbsettings.inc.php

```
<?php
$dbsettings['engine'] = 'pdo_mysql';
$dbsettings['host'] = 'localhost';
$dbsettings['dbname'] = 'spotweb';
$dbsettings['user'] = 'spotweb';
$dbsettings['pass'] = 'slipTongQuig1';
```

```
root@mysql1:/var/www/html/spotweb# mysql spotweb -h 127.0.0.1 -u spotweb -pslipTongQuig1
mysql: [Warning] Using a password on the command line interface can be insecure.
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 74
Server version: 5.7.16-0ubuntu0.16.04.1 (Ubuntu)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
```

Any idea what could cause this issue? Is spotweb php7 ready?

Thanks for any response.
Paul.

**Comment by Sweepr** [comment]
cat dbsettings.inc.php

$dbsettings['host'] = 'localhost'

Did you try editing $dbsettings['host'] = '127.0.0.1' ?

**Comment by Sweepr** [comment]
Since this is working? 

mysql spotweb -h 127.0.0.1 -u spotweb -pslipTongQuig1

**Comment by pjanzen** [comment]
Just updated the dbsettings.inc.php file

$dbsettings['host'] = '127.0.0.1';

Same result, webpage is working but retrieve.php is not.

> root@mysql1:/var/www/html/spotweb# php retrieve.php
> Unable to connect to database: No database settings have been entered, please use the 'install.php' wizard to install and configure Spotweb.
> If you are upgrading from an earlier version of Spotweb, please consult https://github.com/spotweb/spotweb/wiki/Frequently-asked-questions/ first

**Comment by Sweepr** [comment]
And dbsettings.inc.php file is located in the spotweb root directory?

**Comment by pjanzen** [comment]
Yup file is there.

```
root@mysql1:/var/www/html/spotweb# ls -la
total 264
drwxr-xr-x 13 www-data www-data  4096 Nov  4 19:30 .
drwxr-xr-x  3 root     root      4096 Nov  4 18:30 ..
drwxr-xr-x  2 www-data www-data  4096 Nov  4 18:30 bin
drwxr-xr-x  3 www-data www-data  4096 Nov  4 18:53 cache
-rw-r--r--  1 www-data www-data   698 Nov  4 18:30 composer.json
-rw-r--r--  1 www-data www-data 64753 Nov  4 18:30 composer.lock
-rw-r--r--  1 www-data www-data   184 Nov  4 19:30 dbsettings.inc.php
-rw-r--r--  1 www-data www-data   185 Nov  4 18:43 dbsettings.inc.php.old
lrwxrwxrwx  1 www-data www-data    18 Nov  4 18:30 favicon.ico -> images/favicon.ico
drwxr-xr-x  8 www-data www-data  4096 Nov  4 18:30 .git
-rw-r--r--  1 www-data www-data   483 Nov  4 18:30 .gitattributes
-rw-r--r--  1 www-data www-data   255 Nov  4 18:30 .gitignore
-rw-r--r--  1 www-data www-data   149 Nov  4 18:30 .htaccess
drwxr-xr-x  3 www-data www-data  4096 Nov  4 18:30 images
-rw-r--r--  1 www-data www-data 16272 Nov  4 18:30 index.php
-rw-r--r--  1 www-data www-data 17590 Nov  4 18:30 install.php
drwxr-xr-x  8 www-data www-data  4096 Nov  4 18:30 js
drwxr-xr-x 13 www-data www-data  4096 Nov  4 18:30 lib
-rwxr-xr-x  1 www-data www-data  1488 Nov  4 18:30 LICENSE.md
drwxr-xr-x  3 www-data www-data  4096 Nov  4 18:30 locales
-rwxr-xr-x  1 www-data www-data 20924 Nov  4 18:30 notifications.xml
-rw-r--r--  1 www-data www-data  2858 Nov  4 18:30 README.md
-rwxr-xr-x  1 www-data www-data 10674 Nov  4 18:30 retrieve.php
-rw-r--r--  1 www-data www-data   549 Nov  4 18:30 .scrutinizer.yml
-rwxr-xr-x  1 www-data www-data  8977 Nov  4 18:30 settings.php
drwxr-xr-x  7 www-data www-data  4096 Nov  4 18:30 templates
drwxr-xr-x  2 www-data www-data  4096 Nov  4 18:30 tests
-rwxr-xr-x  1 www-data www-data 25633 Nov  4 18:30 usenetservers.xml
drwxr-xr-x  3 www-data www-data  4096 Nov  4 18:30 utils
drwxr-xr-x 13 www-data www-data  4096 Nov  4 18:30 vendor
```

```
root@mysql1:/var/www/html/spotweb# pwd
/var/www/html/spotweb

```
```
root@mysql1:/var/www/html/spotweb# ls -la dbsettings.inc.php
-rw-r--r-- 1 www-data www-data 184 Nov  4 19:30 dbsettings.inc.php
```

**Comment by Sweepr** [comment]
Did you try to run retrieve from the spotweb frontend?

**Comment by pjanzen** [comment]
Ok, for some reason php retrieve.php is unable to determine where it lives. The result is that lib/Bootstrap.php is unable to open dbsettings.inc.php. I have updated 2 things in lib/Bootstrap.php and that is:
line 81: @include "/var/www/html/spotweb/dbsettings.inc.php"; 
line 166: require "/var/www/html/spotweb/settings.php";

And in settings.php
Line 42: $settings['openssl_cnf_path'] = "/var/www/html/spotweb/lib/openssl/openssl.cnf";

Things are starting to work again...
(not quite there yet)

Retrieving new Spots from server news.eu.supernews.com...
PHP Warning:  stream_socket_client(): Peer certificate CN=`news.supernews.com' did not match expected CN=`news.eu.supernews.com' in /var/www/html/spotweb/vendor/gdwebs/nntp/src/Protocol/Client.php on line 725
PHP Warning:  stream_socket_client(): Failed to enable crypto in /var/www/html/spotweb/vendor/gdwebs/nntp/src/Protocol/Client.php on line 725
PHP Warning:  stream_socket_client(): unable to connect to ssl://news.eu.supernews.com:563 (Unknown error) in /var/www/html/spotweb/vendor/gdwebs/nntp/src/Protocol/Client.php on line 725
SpotWeb v0.67.28.31 on PHP v7.0.8-0ubuntu0.16.04.3 crashed

**Comment by mesa57** [comment]
@GeoffreyDijkstra : this is due to the last (composer) commit.
Could you fix this please.

**Comment by pjanzen** [comment]
last error is solved. this was due to a wrong password.

**Comment by pjanzen** [comment]
Now that php retrieve.php is more or less working again, I have the following problem.

```
PHP Fatal error:  Uncaught Error: Call to undefined function mb_convert_encoding() in /var/www/html/spotweb/lib/dao/Base/Dao_Base_Spot.php:407
Stack trace:
#0 /var/www/html/spotweb/lib/services/Retriever/Services_Retriever_Spots.php(608): Dao_Base_Spot->addSpots(Array, Array)
#1 /var/www/html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(227): Services_Retriever_Spots->process(Array, 1844953, 1849954, 1478286123.441)
#2 /var/www/html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(319): Services_Retriever_Base->loopTillEnd(1849954, '5000')
#3 /var/www/html/spotweb/retrieve.php(152): Services_Retriever_Base->perform()
#4 {main}
  thrown in /var/www/html/spotweb/lib/dao/Base/Dao_Base_Spot.php on line 407
```

**Comment by pjanzen** [comment]
Ok, the above error looks like a missing package..

```
sudo apt-get install php7.0-mbstring 
sudo service php7.0-fpm restart
```

Solved the problem for me.

**Comment by Tom620** [comment]
@pjanzen I got the same errors. Followed your directions and it worked for me.

Thanks :)

**Comment by Adam1986** [comment]
Just done a git pull to update from the issues that I had earlier with the API not working and now face exactly the same problem as you with retrieve.php not working!

I manually made the changes to the files you referred to and retrieve appears to be run but then finishes with a bunch of errors, oopsy!

```
HP Warning:  imagettftext(): Could not find/open font in /var/www/spotweb/vendor/jean-damien/pchart/class/pDraw.class.php on line 1023
PHP Warning:  imagettfbbox(): Could not find/open font in /var/www/spotweb/vendor/jean-damien/pchart/class/pImage.class.php on line 211
PHP Warning:  imagettftext(): Could not find/open font in /var/www/spotweb/vendor/jean-damien/pchart/class/pDraw.class.php on line 1023
PHP Warning:  imagettfbbox(): Could not find/open font in /var/www/spotweb/vendor/jean-damien/pchart/class/pImage.class.php on line 211
PHP Warning:  imagettftext(): Could not find/open font in /var/www/spotweb/vendor/jean-damien/pchart/class/pDraw.class.php on line 1023
PHP Warning:  imagettfbbox(): Could not find/open font in /var/www/spotweb/vendor/jean-damien/pchart/class/pImage.class.php on line 211
PHP Warning:  imagettftext(): Could not find/open font in /var/www/spotweb/vendor/jean-damien/pchart/class/pDraw.class.php on line 1023
PHP Warning:  imagettfbbox(): Could not find/open font in /var/www/spotweb/vendor/jean-damien/pchart/class/pImage.class.php on line 211
PHP Warning:  imagettftext(): Could not find/open font in /var/www/spotweb/vendor/jean-damien/pchart/class/pDraw.class.php on line 1023
PHP Warning:  imagettfbbox(): Could not find/open font in /var/www/spotweb/vendor/jean-damien/pchart/class/pImage.class.php on line 211
PHP Warning:  imagettftext(): Could not find/open font in /var/www/spotweb/vendor/jean-damien/pchart/class/pDraw.class.php on line 1023
PHP Warning:  imagettfbbox(): Could not find/open font in /var/www/spotweb/vendor/jean-damien/pchart/class/pImage.class.php on line 211
PHP Warning:  imagettfbbox(): Could not find/open font in /var/www/spotweb/vendor/jean-damien/pchart/class/pImage.class.php on line 211
PHP Warning:  imagettftext(): Could not find/open font in /var/www/spotweb/vendor/jean-damien/pchart/class/pDraw.class.php on line 1023
Finished creating statistics

PHP Warning:  require(templates/notifications/retriever_finished.inc.php): failed to open stream: No such file or directory in /var/www/spotweb/lib/SpotNotificationTemplate.php on line 29
PHP Fatal error:  require(): Failed opening required 'templates/notifications/retriever_finished.inc.php' (include_path='.:/usr/share/php') in /var/www/spotweb/lib/SpotNotificationTemplate.php on line 29

```

**Comment by mesa57** [comment]
The only change which is really neaded is in line 10 of retrieve.php
Remove chdir(__DIR__ . '/../');

**Comment by Mickroz** [comment]
And please stop moving files back and for, alot of us run cronjobs on retrieve.php.

**Comment by mesa57** [comment]
Sorry, the commit from geoffry moved the file to /bin but for the sake of those cronjobs I demanded it to move back. He thought a warning should be sufficient.

**Comment by Mickroz** [comment]
Np, just leave them where they are now ;)

**Comment by Adam1986** [comment]
The latest git pull fixes the retrieve.php within the PHP CLI, but it doesn't work for me retrieving spots via the web page.

Removing **#!/usr/bin/php** from retrieve.php fixes it.

Thanks

**Comment by mesa57** [comment]
@Adam1986 : could you test if retrieve.php from this repo https://github.com/mesa57/spotweb works for you ?

**Comment by Adam1986** [comment]
Hi Mesa, will try it at the next opportunity I get! 

Thanks

**Comment by Adam1986** [comment]
OK the retrieve.php from your repo works absolutely fine in the CLI and via the web site.   Just waiting for the next CRON to run to make sure that works OK, will let you know in the next half hour.

**Comment by Adam1986** [comment]
Yup the from ran through fine as well :-)

**Comment by WzL** [comment]
Please create pull request or merge to Master. My crontab retrieve.php is experiencing the same error, so no updates any more using spotweb. I tested the fix code from mesa57 and retrieve.php functioned again as expected.

**Comment by mesa57** [comment]
Merged.

**Comment by sojab0on** [comment]
H:\Web\spotweb.sojab0on.nl>C:\"Program Files\PHP\v7.0\php.exe" retrieve.php --force


SpotWeb v0.68.29.32 on PHP v7.0.21 crashed

Fatal error occured retrieving reports:
  Unknown SchemaNotUpgradedException



#0 H:\Web\spotweb.sojab0on.nl\lib\Bootstrap.php(136): CustomException->__construct()
#1 H:\Web\spotweb.sojab0on.nl\lib\Bootstrap.php(62): Bootstrap->validate(Object(Services_Settings_Base))
#2 H:\Web\spotweb.sojab0on.nl\retrieve.php(11): Bootstrap->boot()
#3 {main}

PHP Notice:  Undefined variable: retriever in H:\Web\spotweb.sojab0on.nl\retrieve.php on line 304
PHP Fatal error:  Uncaught Error: Call to a member function quit() on null in H:\Web\spotweb.sojab0on.nl\retrieve.php:304
Stack trace:
#0 {main}

Is what i get hen i try to retrive in cmd have tried upgrade db but that fails
atabase schema or settings upgrade failed:
   42S22: 1054: Unknown column 'content' in 'where clause'

with this error 
what can i do to fix that

**Comment by pjanzen** [comment]
You should create a new issue, this issue is closed in 2016...
