### ISSUE TITLE
Amount of new spots are not dispayed after a fresh retrieve anymore.

### ISSUE THREAD

**Issue by WzL** [spotweb/spotweb#210]
A few weeks back I moved from a closed system (authentication portal done by SpotWeb) to an open system (authentication done by reversed proxy). Since that moment I get all new spots in bold, which is as designed but the number of updates won't appear any more left of each of the category's. I played around with cache, emptying it, adding or removing the anonymous user to different groups but I have not found the magic button. 

What i want is no authentiction so open spotweb to everyone and the number of updates since the last visit of the anon user, how can i restore this behaviour?

**Comment by Sweepr** [comment]
The option you are referring to is called:
"Count new spots in filter list" this option is usually set in "preferences"

**Comment by WzL** [comment]
Ok thanks. Strangely it was enabled this option. but after i disabled it, and reactivated it the counting was there again after a fresh retrieve. Thanks!
