### ISSUE TITLE
Memory limit not properly detected in install.php

### ISSUE THREAD

**Issue by GeoffreyDijkstra** [spotweb/spotweb#211]
![bug](https://cloud.githubusercontent.com/assets/17547877/20041507/7846b62a-a46a-11e6-837f-60f74250b219.PNG)

**Comment by mbirth** [comment]
Could it be that it's set to `-1` for "no limit"?

**Comment by GeoffreyDijkstra** [comment]
@mbirth Nope it's set to 512M in php.ini

**Comment by GeoffreyDijkstra** [comment]
@Sweepr A PHP 7 issue is possible, will take a look later on.

**Comment by Sweepr** [comment]
If you look closely.. my memory limit say's 128M.. your say's 512MB, i think the B i causing a calculation error.

**Comment by GeoffreyDijkstra** [comment]
Everything above 128M should result in a OK.

**Comment by mbirth** [comment]
Yup, it's not PHP7.

![screenshot from 2016-11-06 22-07-01](https://cloud.githubusercontent.com/assets/130302/20041695/5d2edacc-a46d-11e6-9783-456a941f0179.png)

**Comment by Sweepr** [comment]
What is the value set in your php.ini?

memory_limit = 512MB

or

memory_limit = 512M

**Comment by mbirth** [comment]
`return_bytes()` checks for the letter:

```php
    function return_bytes($val) {
        $val = trim($val);
        $last = strtolower($val[strlen($val)-1]);
        switch($last) {
            // The 'G' modifier is available since PHP 5.1.0
            case 'g':
                $val *= 1024;
            case 'm':
                $val *= 1024;
            case 'k':
                $val *= 1024;
        }
        return $val;
    } # return_bytes
```

And it only checks the very last character.

**Comment by Sweepr** [comment]
Yes, you are right, that's weird.

Also notice your PHP version is newer.

**Comment by mbirth** [comment]
> Also notice your PHP version is newer.

Yes, because @GeoffreyDijkstra seems to be on Ubuntu 16.04 and I'm on 16.10 already. But the syntax for the `memory_limit` never was with the `B` included. It seems to be a typo in his config.

**Comment by GeoffreyDijkstra** [comment]
Ah seems to be a bug in my ini indeed, however PHP did accept this. So never noticed 😄

**Comment by mesa57** [comment]
Merged
