### ISSUE TITLE
Undefined index userid

### ISSUE THREAD

**Issue by GeoffreyDijkstra** [spotweb/spotweb#212]
Everytime when I want to complete the spotweb install I get this notice, it isn't harmfull because spotweb works if you continue but it isn't nice 😄

![bug](https://cloud.githubusercontent.com/assets/17547877/20041579/bfb52126-a46b-11e6-8ba6-e1cffc1f4824.PNG)

**Comment by mbirth** [comment]
The `getData` method doesn't test if the requested `$field` exists in `$this->_data` and it seems the field `userid` didn't exist at that point. A test should be added which returns `null` (or `false`?) if the field is not defined.

**Comment by mesa57** [comment]
Strange, I cannot reproduce this error.

**Comment by dsadsdadsadsadsds** [comment]
Do you have ```error_reporting``` fully enabled (Spotweb does this by default) and ```display_errors``` set to 1 in your php.ini file, @mesa57 ?

**Comment by mesa57** [comment]
I will check that.
