### ISSUE TITLE
Retrieving spotsfull

### ISSUE THREAD

**Issue by sredXNY** [spotweb/spotweb#223]
Hey!! I just installed spotweb sucessfully, now I just run the retriever using `php retrieve.php -force` after a time it shows a message 

`Finished retrieving spots` that's ok, then it starts to retrieve the comments, it retrieves a lot of comments and then I get this:
```
Spotweb v0.67.28.31 on PHP v5.6.24 crashed 
Fatal error occured while connecting to the newsserver
<-999> Failed to write to socket! <connection lost!> [response: ""] 

#0 C:\mypathToProject\NNTP\Protocol\Client\.php<288>: Net_NNTP_Protocol_Client ->throwError<'Failed to write...', -999>
```
So, why it happens? and also, in which moment the fullspots table is filled? I see only the table spots with data.Thanks

**Comment by mesa57** [comment]
Spotsfull/commentsfull is normally used as a sort of cache when you open a spot.
The error (connection lost) could be a timeout of you're provider. Lower the number of headers retrieved at one time.

**Comment by sredXNY** [comment]
@mesa57 ok, thank you very much!!
