### ISSUE TITLE
Localization: Take 2

### ISSUE THREAD

**Issue by LeeThompson** [spotweb/spotweb#225]
This really isn't an issue per se but wanted to discuss this.

To @mesa57 @GeoffreyDijkstra 

I've managed to get spotweb working and I've decided to go ahead and commit to working on updating it with proper localization.

I am not a javascript programmer so this will be interesting but http://www.localeplanet.com/ seems pretty straightforward so I'll give it a go.   One thing, the current `we1rdo\js\scripts.js` already has a lot of stuff hardcoded from Dutch to English so to do this the proper way, does anyone have the original with the Dutch in it?   A quick search shows: English string lines #'s: 102, 350, 353, 355, 358, 384, 401, 403, 507, 509, 562, 565, 642, 645, 855, 859, 883, 893, 903, 1219, 1407, 1409, 1425, 1427, 1439, 1440; Dutch string lines #'s: 1419.

I'll go ahead and localize the mobile template as well since it's entirely in Dutch at this point.    I'll need to use google translate as I don't know any Dutch (just some German and Japanese).    

Currently the PHP localization seems a little "hackey" as well with locales just containing `nl_NL`.   I would think ideally there should be `nl_NL` containing only Dutch and an `en_US` containing English (and any other languages as well).     I'd like to fix this as well.

**Comment by GeoffreyDijkstra** [comment]
Funny thing to have someone translate to dutch while he can't speak it or for that matter understand :grin: 
I think it's better to change Spotweb in a way it supports multi language and leave the translating part to me or Mesa. If you want to go through all the trouble of translating with google is fine by me but I think it's easier less work for to add a placeholder (something like this: `--needs-translating--English text`) and we can do the translating for you :)

**Comment by mesa57** [comment]
See also my comments on his pull request.

**Comment by Sweepr** [comment]
Maybe i'm totally wrong, but doesn't this work anymore?

 Spotweb can use the Microsoft Translator API to translate comments and Spot description to the users native language. This requires a so-called Client ID and a SecretID which you need to request at Microsoft. Please enter the values in below fields.
Microsoft Translator API - Client ID
Microsoft Translator API - Secret ID

Found in settings.

**Comment by Sweepr** [comment]
Forget my last.
