### ISSUE TITLE
Spotweb Fails W3 Validator

### ISSUE THREAD

**Issue by LeeThompson** [spotweb/spotweb#226]
I'm not sure how important this is to the development team but thought I'd go ahead and report this.

Spotweb's generated HTML code does not pass the  [W3 Markup Validator](https://www.w3.org/).

My main spotweb page passed through the validator (internal, no reverse proxy) gets 162 Errors and 7 warnings.

**Comment by mesa57** [comment]
Btw., there is no development team.
