### ISSUE TITLE
Export nzbs?

### ISSUE THREAD

**Issue by slug1982** [spotweb/spotweb#227]
Is there a clean way to export nzbs? I run spotweb solely for importing nzb's into an indexer. 
I'd like to export old and future nzbs (or just have new nzb's save to disk).

**Comment by mesa57** [comment]
There is no 'mass' save of NZB's and there never will be (security reasons).

**Comment by GeoffreyDijkstra** [comment]
@mesa57 Not sure but how is it possible to make zip's with nzb's for SABnzbd. To me it looks possible somehow.

**Comment by mesa57** [comment]
Of course a single NZB could be zipped. But spotweb should not support mass export of NZB's. Reason is to protect spotters and to prevent dmca experts of using spotweb in an unwanted way.

**Comment by slug1982** [comment]
It only takes a spotweb install and a bit of bash magic and you have all the nzb's anyway. I was just after a more 'clean' way. So it's not really a security flaw to have an export.
Not to worry
