### ISSUE TITLE
API call times out when using tvmazeid

### ISSUE THREAD

**Issue by DavyHeutmekers** [spotweb/spotweb#229]
Whenever I call my spotweb API and I add a tvmazeid to the call, it doesn't give a response. Whenever I call http://ipaddress/spotweb/api?t=tvsearch&cat=5030,5040&extended=1&offset=0&limit=25 it works, but as soon as I add "&tvmazeid=17078" for example, the call slows down and doesn't give any response anymore.

**Comment by mesa57** [comment]
Sorry I cannot reproduce this problem. It works good here, I get all entries.
Maybe you can test if the tvmaze url is giving response for you : 
`http://api.tvmaze.com/shows/17078`

Via tvmaze search is obviously somewhat slower, but it should respond.

**Comment by DavyHeutmekers** [comment]
The link is working perfectly fine. I decided to do a clean install on my Synology using this GIT. But after doing a clean install from scratch, every API call towards spotify results in an error 404.

**Comment by mesa57** [comment]
htpp 404 is a 'not found' error.Either installation is not correct, or the .htaccess redirect is not correct.

**Comment by DavyHeutmekers** [comment]
Do I need ti configure my Web station as Apache or Nginx? I went for Nginx, but the rewrite from /api doesn't appear to be working. I don't know what I'm doing wrong.

**Comment by Sweepr** [comment]
Did you try thisd?

**Comment by DavyHeutmekers** [comment]
In which file would you like me to add this? Anything I change in the nginx.conf file is gone after a reboot of my Synology.

**Comment by mesa57** [comment]
Apache works out of the box.

**Comment by DavyHeutmekers** [comment]
Okay I just flipped my entire installation to Apache and the API works. BUT i'm back where I was in my first post to this issue. As soon as I add the tvmazeid it takes about 1-5 minutes to return something. Which is too long for Couchpotato and Sonarr, which will result in a timeout.

**Comment by mesa57** [comment]
Did you test the url I mentioned ? Are you on Synology or something else ?

**Comment by DavyHeutmekers** [comment]
Yes the url you supplied replies instantly. I'm running a Synology DS214play. All API requests to spotweb work fine http://ipaddress/spotweb/?page=newznabapi&t=tvsearch&cat=5030,5040&extended=1&offset=0&limit=25 for example , but as soon as I add &tvmazeid=[number] to the url it takes spotweb at least 2 minutes to return me the results.

**Comment by mesa57** [comment]
I ment the direct url for TVMaze, does it also take long ?

**Comment by DavyHeutmekers** [comment]
No that returns results instantly!

**Comment by mesa57** [comment]
Ok, can you test how long a search from the search box takes ?
Use the terms : +the +grand +tour

**Comment by DavyHeutmekers** [comment]
Less then 5 seconds and i get all results

**Comment by mesa57** [comment]
Then I am out of options. 
The TVMaze parameter does nothing but retrieving the title and use that as an search argument.
With my test spotweb results come after a few seconds.

**Comment by DavyHeutmekers** [comment]
Well I could sent you my ipaddress so you can see what i'm struggling with, if you don't mind helping me a little more haha.

**Comment by DavyHeutmekers** [comment]
Could it maybe have something to do with the MariaDB Key buffer size?

**Comment by DavyHeutmekers** [comment]
I update my my.cfg of MariaDB without any results:

key_buffer_size = 16M
max_allowed_packet = 1M
table_open_cache = 4
read_buffer_size = 8M
sort_buffer_size = 16M	
read_rnd_buffer_size = 512K
net_buffer_length = 2K
thread_stack = 240K
innodb_data_home_dir = /var/packages/MariaDB/target/mysql
innodb_data_file_path = ibdata1:10M:autoextend
innodb_log_group_home_dir = /var/packages/MariaDB/target/mysql
innodb_buffer_pool_size = 16M
innodb_additional_mem_pool_size = 2M
#innodb_log_file_size = 5M
#innodb_log_buffer_size = 8M
#innodb_flush_log_at_trx_commit = 1
#innodb_lock_wait_timeout = 50

Do you maybe have some higher values anywhere?

**Comment by mesa57** [comment]
I believe you. Btw the search argument is a little bit different. Could you test "The Grand Tour" (with quotes) in the search box ?
I don't use mariadb, but mysql. The search takes place on the spots table which is myisam.

**Comment by DavyHeutmekers** [comment]
"The Grand Tour" return data within a second or 2 / 3

**Comment by mesa57** [comment]
Ok, thank you. Found a problem with the query which is executed. I will look in to that.

**Comment by mesa57** [comment]
Last commit should solve this issue.
Let me know.

**Comment by DavyHeutmekers** [comment]
You're a god!  You deserve a medal! IT WORKS!

**Comment by mesa57** [comment]
Thx !
