### ISSUE TITLE
Funtion returnBytes does not properly convert to bytes

### ISSUE THREAD

**Issue by Caton371** [spotweb/spotweb#232]
Hello,

There are a few bugs in the function "returnBytes".

When converting from GB to bytes, the conversion factor must be **1024 * 1024 * 1024** instead of **1024**.

Similarly, when converting from MB to bytes, the conversion factor must be **1024 * 1024** instead of **1024**.

This is the reason why a memory_limit of 128M in file php.ini is not recognized as sufficient.

**Comment by GeoffreyDijkstra** [comment]
Related: https://github.com/spotweb/spotweb/issues/211

**Comment by mesa57** [comment]
I already prepared a change exactly like that, but did not have time to check it in.

**Comment by mesa57** [comment]
Merged
