### ISSUE TITLE
Mobile template; failed to open stream

### ISSUE THREAD

**Issue by pieterrrr** [spotweb/spotweb#237]
I just updated spotweb to the latest version. Using the mobile template I get the following error:

> Warning: require_once(/share/MD0_DATA/Web/spotweb/templates/mobileheader.inc.php): failed to open stream: No such file or directory in /share/MD0_DATA/Web/spotweb/templates/mobile/spots.inc.phpon line 3

> Fatal error: require_once(): Failed opening required '/share/MD0_DATA/Web/spotweb/templates/mobileheader.inc.php' (include_path='.:/etc/config/php') in /share/MD0_DATA/Web/spotweb/templates/mobile/spots.inc.phpon line 3

Platform is a Qnap NAS.

**Comment by mesa57** [comment]
Should be fixed now/
