### ISSUE TITLE
Spotweb settings is not saving nzbget username

### ISSUE THREAD

**Issue by piejanssens** [Spotweb/Spotweb#24]
Whenever I change the username 'nzbget' to something else and save, after reloading the settings/nzb handling page it's set back to 'nzbget'.

**Comment by piejanssens** [comment]
Now I'm starting to think that it does store the new username, but it just keeps displaying 'nzbget' and not showing the actual username stored in the db. @Muis Could you verify?

**Comment by buurman** [comment]
I fixed it a long while ago on my local copy of spotweb, it didn't break anything so I made a pull request: https://github.com/Spotweb/Spotweb/pull/32

**Comment by buurman** [comment]
Muis just pulled the change...update and let us know if it's fixed

**Comment by piejanssens** [comment]
Works great thanks!
