### ISSUE TITLE
Company Rights Spotweb

### ISSUE THREAD

**Issue by GeoffreyDijkstra** [spotweb/spotweb#242]
@Sweepr @mesa57 This is a personal "issue" :smile: 

@mbirth and I still have a few (composer) packages (repo's) which are only used in spotweb.
I still want to move this to the spotweb (github) company, so can 1 of you add me to the spotweb company so I can create those repo's?

You can of course also do this yourself :smiley:

**Comment by dsadsdadsadsadsds** [comment]
Which repos are that ? Do you mean ```php-gettext``` and the NNTP package? If so, I would suggest using the original repos to fork them and issue an pull request to those.

Especiall the PEAR_NNTP package is a really nice package (for its time inhistory :smile: ) and we should not add it to the Spotweb repo but instead update the package in Pear.

**Comment by GeoffreyDijkstra** [comment]
@dsadsdadsadsadsds Good luck with that one there is already an open PR for a few years there, normally I would fully agree with you on this matter. Also they are already forked, to our github because we don't have the rights to fork them to spotweb/* repo itself.

**Comment by dsadsdadsadsadsds** [comment]
That's strange because the Pear project has an project underway to make all their libraries compatible with PHP7?

**Comment by GeoffreyDijkstra** [comment]
@dsadsdadsadsadsds Maybe I looked at the wrong place, but the github version is 5 years old, but it seems the php.svn.net is 3 years old (never thought of looking there). But still there was a PR for more then a year old, but it seems it has been revoked.

**Comment by dsadsdadsadsadsds** [comment]
https://github.com/pear/Net_NNTP is the repository i mean, it was last updated a mere 5 months ago?

**Comment by GeoffreyDijkstra** [comment]
Hmm where did you find that info: `Latest commit 9bc48ba  on Feb 18, 2014` which is a little more then 5 years :smile:

**Comment by dsadsdadsadsadsds** [comment]
Ah yes, i counted the PR as an update -- we do not live in 2019 though :wink: 

Perhaps you could contat @cweiske of PEAR to ask for commit rights to that repository? Those guys really try hard to make PEAR PHP7 compatible and it would be a shame to fork such a nice package into our own repo

**Comment by GeoffreyDijkstra** [comment]
@mesa57 No they aren't because I compared them when introducing composer, that's why I made a own fork of this project and replaced it with spotwebs version.
