### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by Fietspomp86** [spotweb/spotweb#247]
Hi, 

I have the following error since commit 5303640e161eaa540a497eddef9e5e4acb81a7a3
This is the error: `PHP Fatal error:  Arrays are not allowed in class constants in /var/www/spotweb/lib/services/Format/Services_Format_Parsing.php on line 33`

Happens when I try to php retrieve.php

Running Spotweb on an OMV installation (debian wheezy 7.11)
PHP-v : PHP 5.4.45-0+deb7u6 (cli) (built: Dec 10 2016 16:03:16)

**Comment by GeoffreyDijkstra** [comment]
Well thats my bad I can fix that 😀

Op 19 dec. 2016 17:55 schreef "Fietspomp86" <notifications@github.com>:

**Comment by GeoffreyDijkstra** [comment]
@Fietspomp86 Why are you still running such an outdated php version + debian?

**Comment by mesa57** [comment]
Did the last commits made spotweb incompatible with php 5.4 ?

**Comment by Fietspomp86** [comment]
Running OpenMediaVault, which basically comes with these versions.
There is a major upgrade available tho, but it's stable for me now.
Don't want to break my installation.

Is it fixable or should I search for a way to upgrade PHP?

**Comment by GeoffreyDijkstra** [comment]
@Fietspomp86 Try a git pull, should be fixed.

**Comment by Fietspomp86** [comment]
You're the best, it works again!

**Comment by GeoffreyDijkstra** [comment]
I forgot it that it is not allowed in PHP 5.4, only running newer versions. As a sidenote: On debian 7 it's possible to upgrade to 5.6 afaik.

**Comment by GeoffreyDijkstra** [comment]
@mesa57 Yes it did because I moved the spot template array to a constant (I forgot that this wasn't supported in PHP 5.4, the rest is PHP5.4 compatible)

**Comment by GeoffreyDijkstra** [comment]
@mesa57 Do you know of a solution to check it on multiple PHP versions? I know there is such a tool, but don't know the name. Whould be great for constant integration stuff, auto decline PR if it doesn't work on 5.4 and higher. Mostly this requires unittests...

**Comment by GeoffreyDijkstra** [comment]
@mesa57 I ment more for github. I think @mbirth probably knows this because he already did a commit for CI stuff.

**Comment by mbirth** [comment]
Scrutinizer and Travis can both do that. You can specify multiple PHP versions in their configs and they will run the unit tests against those versions.

**Comment by dsadsdadsadsadsds** [comment]
@GeoffreyDijkstra if i see correctly you use PhpStorm, right? if so, just set the PHP interpreter to version 5.4 and it will automatically flag (mark as an error) all the PHP 5.5 and up expressions.

**Comment by GeoffreyDijkstra** [comment]
@dsadsdadsadsadsds I'm aware of that. But sometimes I just forget, because the default is set to PHP 7 for me :smile:
