### ISSUE TITLE
Issues after latest pull

### ISSUE THREAD

**Issue by Fossil01** [spotweb/spotweb#248]
Last retrieve at Tue 20 Dec 2016 03:17:30 PM CET
Retrieving new Spots from server europe.newsdemon.com...
Appr. Message count: 	2982663
First message number:	2
Last message number:	2982665
Current article number:	2982664

Retrieving 2982664 till 2982666
getBody(): Failed to retrieve article: <DCjmCWnAQEUODtZWAE7rH@spot.net>
 (parsed: 1, in DB: 1, signed: 1, invalid: 0, rtntn.skip: 0, mod: 0, full: 1, total: 2) in 1.02 seconds
Processed a total of 2 spots
Finished retrieving spots.

Calculating how many spots are new, done.
Last retrieve at Tue 20 Dec 2016 03:31:26 PM CET
Retrieving new reports from server europe.newsdemon.com...
Appr. Message count: 	231487
First message number:	2
Last message number:	231489
Current article number:	231489

Processed a total of 0 reports
Finished retrieving reports.

Non-fatal: Updating black/whitelist failed, most likely unreachable!Expiring debuglog entries, if any, done.
Starting to create statistics

SpotWeb v0.68.28.32 on PHP v7.0.14-2+deb.sury.org~xenial+1 crashed

Fatal error occured retrieving reports:
  Cache is corrupt, could not find on-disk resource for: 616813 ./cache//stats/9ff/fe3/77d/f85/981/0c8/e44/879/afb/78f/cca/278/e36d.stats -> ./cache//stats/616/616813.stats

#0 /data/spotweb/lib/dao/Base/Dao_Base_Cache.php(343): Dao_Base_Cache->getCacheContent('616813', 4, false)
#1 /data/spotweb/lib/dao/Base/Dao_Base_Cache.php(527): Dao_Base_Cache->getCache('spotspercategor...', 4)
#2 /data/spotweb/lib/services/Providers/Services_Providers_Statistics.php(188): Dao_Base_Cache->getCachedStats('spotspercategor...')
#3 /data/spotweb/lib/services/Providers/Services_Providers_Statistics.php(105): Services_Providers_Statistics->getStatisticsData('spotspercategor...', '')
#4 /data/spotweb/lib/services/Providers/Services_Providers_Statistics.php(60): Services_Providers_Statistics->createStatsPerCategory('')
#5 /data/spotweb/lib/services/Providers/Services_Providers_Statistics.php(36): Services_Providers_Statistics->renderStatImage('spotspercategor...', '')
#6 /data/spotweb/retrieve.php(251): Services_Providers_Statistics->createAllStatistics()
#7 {main}

Finished retrieving reports.

**Comment by Sweepr** [comment]
getBody(): Failed to retrieve article: DCjmCWnAQEUODtZWAE7rH@spot.net

This is probably your USP, i think they do not have that article. (You did not switch to a differenty USP on an existing instance?)

./cache// <- Double slash?  i fixed that a long time ago.

https://github.com/spotweb/spotweb/commit/d96dd03b1b9181403a9fd659c8c446cf026d2b35

Check table "settings" ID line 42 -> 'cache_path' should be './cache'

**Comment by Fossil01** [comment]
Cheers. Settings path is correct so might be another issue.

**Comment by GeoffreyDijkstra** [comment]
@Sweepr Why does it report it like ./cache I would expect a full path
instead?

**Comment by Sweepr** [comment]
@GeoffreyDijkstra,  Agree, that would be better, since i didn't write that code i can't answer your question, i only noticed a double slash where it shouldn't be.

**Comment by Sweepr** [comment]
@Fossil01 , closing this, if any further problems please re-open.

**Comment by GeoffreyDijkstra** [comment]
@Sweepr Side note: It's again a PHP 7+ installation, it seems spotweb doesn't really like that 😞

**Comment by GeoffreyDijkstra** [comment]
@Sweepr @mesa57 Is the cache like an optional thing in spotweb? Meaning can it savely be cleaned/removed -> will it automatically be rebuild?

**Comment by GeoffreyDijkstra** [comment]
@Fossil01 There is a bin/check-cache.php, maybe you can try running this?

**Comment by Sweepr** [comment]
@GeoffreyDijkstra Yes, you can safely remove (clean) the cache altough i wouldn't recommend this since this can negatively affect performance on the front and backend, the NZB's and image's etc are downloaded once and stored on disk for easy access when needed, this reduces download time, unneeded connection's to your USP and bandwidth.

If you really want to clean i would recommend setting up a cron that removes any file/folder in that dir older then 24 hours, and not accessed for 24 over hours.

/usr/bin/tmpwatch -uaf 24 /home/public_html/spotweb/cache/nzb
/usr/bin/tmpwatch -maf 24 /home/public_html/spotweb/cache/nzb
/usr/bin/tmpwatch -uaf 24 /home/public_html/spotweb/cache/image
/usr/bin/tmpwatch -maf 24 /home/public_html/spotweb/cache/image

Manual: https://linux.die.net/man/8/tmpwatch

I'm doing this myself as the cache can grow rather large consuming alot of inodes and disk space.

**Comment by GeoffreyDijkstra** [comment]
@Sweepr I meant it more like this might be a solution for @Fossil01 solving his issue, when the cache is rebuild performance is also fixed again I assume 😄

**Comment by Sweepr** [comment]
@GeoffreyDijkstra, If the path to the cache folder is correct then it would automatically heal itself, but since the files could not be stored in cache by spotweb, it needed to contact the outside to fetch the content and giving a warning "Cache is corrupt, could not find on-disk resource"

So cleaning out doesn't really fix the issue.

**Comment by GeoffreyDijkstra** [comment]
Well that sounds like somebody didn't fully think it over, because in my opinion a cache should contain variable / optional files but the system should not really depend on it and definitely not throwing errors...

But @Sweepr we need to help if possible so: Can @Fossil01 use the bin/check-cache.php for this, will this help?

**Comment by mesa57** [comment]
The cache (keys) are also maintained in the database (cache table).

**Comment by Sweepr** [comment]
@GeoffreyDijkstra Well, spotweb does not really depend on it (if it can't find the file locally it will fetch it from the USP, so basically it can run without a cache.

**Comment by Sweepr** [comment]
@GeoffreyDijkstra , in short, you can use bin/check-cache.php to repair the broken/missing cache.

**Comment by Fossil01** [comment]
Cheers, will look at those tmpwatch entries too as my cache is huge.

**Comment by aroundmyroom** [comment]
would it be an idea to create a function where you can do maintenance on the cache? due to using lots of inodes I expect that really old content do not need to be cached, only x months old for example.
Could be probably be put in the retrieve.php for maintenance purposes (or other script(s))

**Comment by mesa57** [comment]
I think for a single user the cache is pretty useless. And it should be possible to disable it.

**Comment by Fossil01** [comment]
Mine's a public install to a cache maintenance tool would me nice.

**Comment by Sweepr** [comment]
@aroundmyroom That's why i setup tmpwatch to remove everything older then 24 hours, been running so for years without problems.

@Fossil01 
Retrieve.php already has something like that builtin, comment from the file itself reads:

/*
	 * Retention cleanup. Basically when we ask for Spotweb to only
	 * keep spots for 'xx' days (eg: 30 days), we either have to delete
	 * everyting older than 'xx' days, or delete all 'full' resources
	 * older than the specified time period.
	 *
	 * The full resources are everything beyond the bare minimum to 
	 * display the spots, so we delete nzb's, images, comments, etc.
	 */

**Comment by mesa57** [comment]
Some script to clean up the cache wit a specified retention of X days ?

**Comment by mesa57** [comment]
There is a simple function in Dao_base_cache to do exactly that : 

```
	/*
	 * Removes items from the cache older than a specific amount of days
	 */
	function expireCache($expireDays) {
        /*
         * Calculate the filepath so we can remove the file from disk, we
         * ignore any error which might be thrown because we cannot do
         * anything about it anyway.
         */
```

**Comment by dsadsdadsadsadsds** [comment]
Just removing files from the cache, while functioanlity wise harmless, will hamper performance a bit as it will do several io's on disk and an delete+insert pair in the database.

**Comment by mesa57** [comment]
Agreed. But the expireCache functions clears both database and file entry's.
