### ISSUE TITLE
DIR changes

### ISSUE THREAD

**Issue by dsadsdadsadsadsds** [spotweb/spotweb#249]
Hi there,

Merry xmas to you all :bell: 

I was just reading the issues for a bit and I am kinda worried about this commit: 66d451e5a69f5d7ffad020bc8209919d32e06c53 -- it removes all the ```chdir()``` calls which is fine in itself, but it does not fix the settings table (not the defaults, and no setting migration) which is a huge warning sign.

In the settings table we store the directory of the cache: https://github.com/spotweb/spotweb/blob/0713d001cb4a11c80087ed515016d44e683ec1a2/lib/services/Upgrade/Services_Upgrade_Settings.php#L63 as a *relative* path -- eg, starting from the *CURRENT* directory.

This means, unless it has been fixed in a later commit, that users will have a *different* cache path when they retrieve from the cron job vs the cache path they use when they load the website.

This is based on a pure theoretical view, but please take look at this @GeoffreyDijkstra @mesa57

**Comment by mesa57** [comment]
Does retrieve.php use the cache at all ?

**Comment by GeoffreyDijkstra** [comment]
@mesa57 I don't know, but I would have expected errors in that case :smile:

**Comment by dsadsdadsadsadsds** [comment]
If "Retrieve full spots" is enabled, it will pre-cache all the assets of a particular spot (image, nzb, and the like) and hence load them into the cache.

The ```cache_path``` setting is retrieved in ```Bootstrap.php``` and then passed to the ```DAO_Factory```, afterwards it is used to instantiate the caching implementation. The cache implementation uses the cache path to create a full path to the cache, eg see https://github.com/spotweb/spotweb/blob/0713d001cb4a11c80087ed515016d44e683ec1a2/lib/dao/Base/Dao_Base_Cache.php#L265

This is of course problematic because of this. Say you run Spotweb from ```/var/www/html/spotweb/``` and the cache_dir setting is to its default of ```./cache``` (there is no UI to change it).

If you run the web ui, it will now use the default directory of the webserver (i have no idea what this is), and when you run the ```retrieve.php``` from cron, the current directory probably is something like ```/root``` or alike.

If my theory is correct, this means you'll end up creating cache directories at two places and you no longer use the existing cache directory so I really think this needs to be tested properly.

**Comment by mesa57** [comment]
If so, this would be a serious issue.

**Comment by tswestendorp** [comment]
Just got an error during retrieve probably related to this issue

```
Retrieving 2987540 till 2987603

SpotWeb v0.68.28.32 on PHP v7.0.14-2+deb.sury.org~xenial+1 crashed

Fatal error occured retrieving reports:
  Cache is corrupt, could not find on-disk resource for: 236935 ./cache//image/b67/127/d6d/fdb/6fb/1f1/ced/872/b81/c55/c72/6a6/5f19.jpg -> ./cache//image/236/236935.jpg

#0 /var/www/spotweb.sevenymedia.nl/htdocs/lib/dao/Base/Dao_Base_Cache.php(343): Dao_Base_Cache->getCacheContent('236935', 1, Array)
#1 /var/www/spotweb.sevenymedia.nl/htdocs/lib/dao/Base/Dao_Base_Cache.php(493): Dao_Base_Cache->getCache('1526u9C872EqxJs...', 1)
#2 /var/www/spotweb.sevenymedia.nl/htdocs/lib/services/Providers/Services_Providers_SpotImage.php(38): Dao_Base_Cache->getCachedSpotImage('1526u9C872EqxJs...')
#3 /var/www/spotweb.sevenymedia.nl/htdocs/lib/services/Retriever/Services_Retriever_Spots.php(505): Services_Providers_SpotImage->fetchSpotImage(Array)
#4 /var/www/spotweb.sevenymedia.nl/htdocs/lib/services/Retriever/Services_Retriever_Base.php(227): Services_Retriever_Spots->process(Array, '2987540', 2987603, 1483514881.4236)
#5 /var/www/spotweb.sevenymedia.nl/htdocs/lib/services/Retriever/Services_Retriever_Base.php(319): Services_Retriever_Base->loopTillEnd(2987603, '1000')
#6 /var/www/spotweb.sevenymedia.nl/htdocs/retrieve.php(145): Services_Retriever_Base->perform()
#7 {main}
```

**Comment by mesa57** [comment]
@tswestendorp Is retrieve full spots enabled ?

**Comment by tswestendorp** [comment]
Yes it is, here are my settings: 

<img width="155" alt="screen shot 2017-01-04 at 19 06 07" src="https://cloud.githubusercontent.com/assets/1061961/21653343/e781185e-d2b0-11e6-8be9-cef44237d7eb.png">

**Comment by mesa57** [comment]
Yesterday I discovered statistics we're not working due to this problem.
I did a temporary fix, but my proposal now is that : 
- if the cache settings contain a path with starts with ./ to replace it with __DIR__.'./'
That way a user could still specify an absolute path in settings, but current users will have a working cache path.

**Comment by mesa57** [comment]
Merge done
