### ISSUE TITLE
furthering discussion of pull request #214

### ISSUE THREAD

**Issue by dsadsdadsadsadsds** [spotweb/spotweb#250]
We had a small discussion there, but i think it's important to take it a bit more public so we can get some other opinions :)

If i look at the ```spotweb2``` you are making the exact same mistakes by pushing a huge commit doing nothing but formatting changes.

I am sorry, but if you push something like that you mess up all version history and make all history of the project useless because all diffs show 100% changed. The only reason you commit this is because of your personal preference. The code works just fine at the moment, so all you do is remove a lot (!!) of useful information because you do not like the pound sign :smile: :wink:

I think this is rather dangerous thing to do as I do not think you fully mastered the codebase and with you destroying the history, it will become a lot harder for other people to learn - let a lone for other people merging changes or for other branches (eg the mediainfo branch) to merge.

With regards to me creating PRs -- i have two open PRs which add a lot of cool functionality and both are rejected / not merged. As my fork is based on those PRs I cannot contribute anything else, but I do know the Spotweb codebase a little so I try to help with Spotweb by reviewing the code and issues a bit when I have some time available. 

Cc'ing @mesa57 and @Sweepr on this because i think it is important for other people to chime in regarding the massive formatting changes you have comitted in the seperate branch.

**Comment by GeoffreyDijkstra** [comment]
@dsadsdadsadsadsds Whoops, that branch shouldn't be here. It was my local experiment :blush:
It will perish today :wink:

**Comment by GeoffreyDijkstra** [comment]
@dsadsdadsadsadsds But on a different note: WE SHOULD do a reformat once, to meet the PSR standards, which means removing all the pointless "# endif" comments etc. To have a code base which is easily view-able is more attractive to other devs. Also following an official standard helps for such things.

**Comment by dsadsdadsadsadsds** [comment]
Ok, and again -- this is not to attack you but something like version history and existing coding style is not something to be taken too lightly if you work on a project which exists for several years and has several dozens of individual contributors.

It is just a totally different beast than a local small project which exists for a few months, and some things while annoying are "just the way it is". 

Reformatting all the code gives you very little advantage but will incur a major loss of history and information.

**Comment by GeoffreyDijkstra** [comment]
@dsadsdadsadsadsds Also yes the media branch should be merged before we can do such things. I was already looking into that but I don't have so much time atm.

**Comment by mesa57** [comment]
I agree with @dsadsdadsadsadsds about reformatting code. That is not much sense.
Anyway I would like to merge you're PR's @dsadsdadsadsadsds but do not have the time to fully review them. I am considering to give you merge authority if other team members agree.

**Comment by GeoffreyDijkstra** [comment]
@mesa57 It think he is an great addition. But I also think we should block the master branch and always force that the code is at least reviewed by someone else before merging.

@dsadsdadsadsadsds History is great and that is what GIT is for. I don't see how it will be lost by making such change. Also PSR is a big standard already included by many big projects,  which makes it easier for developers to contribute without worrying about different code style, but maybe this is just a matter of opinion. Anywas such changes will not affect our users and improve our efforts as open source team because of readable code.

**Comment by dsadsdadsadsadsds** [comment]
You lose history because reading a diff will become complete nonsense with only formatting changes. A version control system is for _much_ more than just a central directory with the sourcecode in it, it documents the history of the project and with useful commit messages it also helps to explain history.

If you, for example, take a file and read the diff, you can easily see changes and determine the cause for a bug. However, if you read a diff, and all you see is deletions and additions because someone ran phpcs on it has become useless as all useful information is lost.

Just try it out yourself - take a few files in the repository and ush the view history button and start clicking on the commit hashes, you can easily see what is changed.

Now try the same on your repository after all your formatting changes :)

This huge downside of losing that information does not compensate in any way the upside of having all the code in a more modern formatting style. Do not get me wrong, I am not saying that having PSR-1 and PSR-2 would be useful, i am just saying that the huge downside does not outweigh the relatively small upside.
