### ISSUE TITLE
Error when Retrieve from GUI

### ISSUE THREAD

**Issue by HeMaN-NL** [spotweb/spotweb#251]
After the automatic pull from GIT I do every Sunday, I have no updates to the posts when starting a "Retrieve" from the user interface in the browser. Before the GIT pull it was working fine.
GIT update was done on Sun Dec 25 03:00:00 CET 2016

In the error log:

```
`[Mon Dec 26 17:33:43 2016] [error] [client 192.168.150.123] PHP Notice:  Undefined variable: retriever in /raid0/data/module/Spotweb/bin/Spotweb/retrieve.php on line 305, referer: http://192.168.150.220:31000/?page=index&search[tree]=cat0_z2&search[value][]=&search[value][]=New:0
[Mon Dec 26 17:33:43 2016] [error] [client 192.168.150.123] PHP Fatal error:  Call to a member function quit() on a non-object in /raid0/data/module/Spotweb/bin/Spotweb/retrieve.php on line 305, referer: http://192.168.150.220:31000/?page=index&search[tree]=cat0_z2&search[value][]=&search[value][]=New:0
`

```
From the GIT pull log:

```
`Start update SpotWeb vanaf GIT om:
Sun Dec 25 03:00:01 CET 2016
 
Ophalen update SpotWeb vanaf GIT resultaat:
Updating 9cb237d..4d97648
Fast-forward
 lib/services/Format/Services_Format_Parsing.php | 1089 ++++++++++++-----------
 retrieve.php                                    |    1 +
 templates/installer/fatalerror.inc.php          |    2 +-
 vendor/.htaccess                                |    8 +
 4 files changed, 591 insertions(+), 509 deletions(-)
 mode change 100644 => 100755 retrieve.php
 create mode 100644 vendor/.htaccess
 
Bijwerken van de database indien nodig:
Updating schema..(pdo_mysql)`

```
No updates were made to the tables

When I do a retrieve from an ssh commandline all is working as expected.

PHP Version => 5.3.26

any more info needed? I will be happy to supply :)

**Comment by Sweepr** [comment]
Are you sure that apache is running the same PHP version as the commandline?

You can check this by uploading a file called "phpinfo.php" to your spotweb root folder with the following lines in it:

Filename: phpinfo.php

<?php

// Show all information, defaults to INFO_ALL
phpinfo();

?>

And then browse to it like this:

http://urltoyourspotweb/phpinfo.php

**Comment by Sweepr** [comment]
If both commandline and apache are using the same PHP version you could do one more thing:

To confirm weither or not the latest updates broke your install, do a rollback on the update and see if the GUI retrieve button starts working again?

**Comment by HeMaN-NL** [comment]
you are right, Apache is running PHP Version 5.5.9.

The error did not occur before the update, I can see that in the logging.

Is there an easy way to rollback to a previous verion? (never have done that before, think I need some guidance with that ;))

**Comment by Sweepr** [comment]
Looking at the point at which you want to undo to. 

`Updating 9cb237d..4d97648`

So:

`git reset --hard 9cb237d `

hould do the trick.

**Comment by Sweepr** [comment]
You can also find the previous version by using `git reflog`

**Comment by HeMaN-NL** [comment]
I found this in the GIT documentation
`git checkout 9cb237d`

After this the retrieve is working again from the web interface.
Is there any way I can help to debug this?

**Comment by Sweepr** [comment]
@GeoffreyDijkstra There seems to be an issue with this https://github.com/spotweb/spotweb/pull/245 as it seems to break the retriever function on the GUI page, any change you could confirm and fix this?

**Comment by GeoffreyDijkstra** [comment]
@Sweepr I got time in the weekend I think, maybe you can take a peek? Maybe it's just something simple.

**Comment by mesa57** [comment]
Don't look at the regional settings, but this is my error log when testing with php 5.5.36 : 

```
[28-Dec-2016 23:38:32 Asia/Kuwait] PHP Notice:  Undefined variable: retriever in D:\projects\spotweb\retrieve.php on line 305
[28-Dec-2016 23:38:32 Asia/Kuwait] PHP Stack trace:
[28-Dec-2016 23:38:32 Asia/Kuwait] PHP   1. {main}() D:\projects\spotweb\retrieve.php:0
[28-Dec-2016 23:38:32 Asia/Kuwait] PHP Fatal error:  Call to a member function quit() on a non-object in D:\projects\spotweb\retrieve.php on line 305
[28-Dec-2016 23:38:32 Asia/Kuwait] PHP Stack trace:
[28-Dec-2016 23:38:32 Asia/Kuwait] PHP   1. {main}() D:\projects\spotweb\retrieve.php:0

```

**Comment by mesa57** [comment]
The exception is triggered because the $retriever object is nothing.
Real exception is : 
```
#0 D:\projects\spotweb\lib\Bootstrap.php(142): CustomException->__construct()
#1 D:\projects\spotweb\lib\Bootstrap.php(49): Bootstrap->validate(Object(Services_Settings_Base))
#2 D:\projects\spotweb\retrieve.php(12): Bootstrap->boot()
#3 {main}
```

**Comment by mesa57** [comment]
Somehow this check fails (validate in bootstrap.php)
```
		/*
		 * Because users are asked to modify ownsettings.php themselves, it is 
		 * possible they create a mistake and accidentally create output from it.
		 *
		 * This output breaks a lot of stuff like download integration, image generation
		 * and more.
		 *
		 * We try to check if any output has been submitted, and if so, we refuse
		 * to continue to prevent all sorts of confusing bug reports
		 */
		if ((headers_sent()) || ((int) ob_get_length() > 0)) {
			throw new OwnsettingsCreatedOutputException();
		} # if

I see that ob_get_length returns 16, but I have no clue why
Is is also a problem with php 7. Looks like a serious problem as retrieve from the UI has been broken.
```

**Comment by mesa57** [comment]
A ob_get_contents() returns "#!/usr/bin/php"
Sound familiar to me .... @GeoffreyDijkstra for you too I suppose 😉

**Comment by GeoffreyDijkstra** [comment]
@mesa57 Sounds like we have to remove a line `#!/usr/bin/php` from `retrieve.php` 😉

**Comment by mesa57** [comment]
Hmmz, it indeed triggers an error when using retrieve from the UI in windows.
I still need to check if it is the same in Unix (debian/jessie).
However, the reported error by the issuer could be something different. Retrieve.php catches all exceptions and normaly echo's the error + stacktrace. Initiated from the UI this however remains invisible. 
Do you know a way to do proper error reporting ?

**Comment by HeMaN-NL** [comment]
Confirmed.

I updated to the master again, and retrieve from UI was throwing same error as before.
Removed line 1  "#!/usr/bin/php"  from  retrieve.php and retrieve from the UI is working again without error

**Comment by mesa57** [comment]
@GeoffreyDijkstra help : somehow github was resetted to the last merge on 1 dec. You're merges have been undone. I do not understand as I just did a pull to my local repo.

**Comment by mesa57** [comment]
Btw. that solved the retrieve error.

**Comment by buurman** [comment]
I had the same issue, removing #!/usr/bin/php resolved it.

**Comment by Sweepr** [comment]
This can be closed now since this issue has been resolved.

Please re-open if needed.
