### ISSUE TITLE
NZR spots ("Only for Spotnet Classic")

### ISSUE THREAD

**Issue by dsadsdadsadsadsds** [spotweb/spotweb#253]
hi there,

Did anyone already try to put some work into analyzing these of spots? Apparently they contain an additional field (<NZR>) in the Spotnet XML in the usenet header which seems to identify  another key.

It also references an message-id in the regular nzb-group but this NZB seems to be encrypted. 

The unfortunate thing is, the Spotclient.dll (which contains the VB with the decoding logic) seems to be obfuscated so a simple decompilation can take a while.

Did anyone got any further with this? Having to try to de-obfuscate SpotClient.dll would kinda suck tbh :)

**Comment by mesa57** [comment]
Please contact me on private mail mesa57 at hot mail.
