### ISSUE TITLE
CSS breaks when using a SSL certificate

### ISSUE THREAD

**Issue by buurman** [spotweb/spotweb#255]
My Spotweb server only shows a 'text' version when accessing it through https with a valid certificate.
I started digging and found that the base location in the header is set to http://website instead of https:// and I guess that is what wrecks it.

I'm no webdev but when I hacked the `templates/we1rdo/includes/header.inc.php` file and editted this line `<base href='<?php echo $tplHelper->makeBaseUrl("full"); ?>'>` to a line that contains https://website it looks okay again

update:
While doing this (accessing through https) the retrieve button doesn't work, switch back to http and all is well. I guess this makes sense because this part `$tplHelper->makeBaseUrl("full")` creates http url's that don't match on a https site.. or something like that.

**Comment by mesa57** [comment]
Known issue, but until now not found a working solution for all kinds of servers.

**Comment by buurman** [comment]
Ok, so was this useful information or did you guys already know the tplhelper (templatehelper I guess) was the badguy? (or related to the issue)

**Comment by phineus** [comment]
What is the reason that is cannot be fixed for all servers?

**Comment by mesa57** [comment]
I did not say it cannot be fixed, but all attemps until now broke somehow for somebody else. 
So if you know how to fix this and test it on all kind of server configurations we are happy to apply the change.

**Comment by mesa57** [comment]
Are you using a SSL proxy ?

**Comment by mesa57** [comment]
Still no answer can this issue be closed ?

**Comment by mesa57** [comment]
See wiki 'installation and troubleshooting' for the solution.
