### ISSUE TITLE
Configure SMTP server

### ISSUE THREAD

**Issue by Rouzax** [spotweb/spotweb#256]
Because of a crash I had to reconfigure my spotweb server however I can't seem to find how to configure my SMTP server for outgoing notification.
My previous install was able to sent mail notifications so it worked my previous build.

**Comment by Sweepr** [comment]
You can setup Email notifications under "Change preferences" ->"Notifications" -> "Send E-mail to (mail)"
-> select when to send mail.

**Comment by Sweepr** [comment]
Also please make sure that you have to rights to send mail via SMTP, some configuration's restrict outgoing SMTP other then root, exim, and mailman (FKA SMTP Tweak)

**Comment by Sweepr** [comment]
You cannot set the IP or port in Spotweb, normally mail would be send directly using the "mail" command 

Can you do this from the commandline as user and root.

mail -s "Test Email" user@example.com < /dev/null

Check if the test mail arrive's in your mailbox?  
If not please check your log's or post any error given by the command

**Comment by mesa57** [comment]
You normally configure you're SMTP server in php.ini : 

```
[mail function]
; For Win32 only.
; http://php.net/smtp
SMTP = localhost
; http://php.net/smtp-port
smtp_port = 25

```

**Comment by Wally73** [comment]
https://github.com/PHPMailer/PHPMailer

**Comment by Rouzax** [comment]
So apparently it worked, which I did not expect 😄

**Comment by Rouzax** [comment]
It works but spotweb does not seem to send always send emails out.
How can I debug that?

**Comment by mesa57** [comment]
The way I debugged that is to install a local mailserver and look at the smtp logs.
For windows I used hMailserver

**Comment by Rouzax** [comment]
I think that Spotweb it self does not consistently send out mails. The mail tracking on my webhost does not show anything coming in or being bounced.
Is there a way for Spotweb to run with a debug log?

**Comment by Rouzax** [comment]
If I send a mail through telnet on the same server from and to the same address as I want to use for Spotweb it works without authentication.
Are mails send at the end of retrieve.php?

**Comment by mesa57** [comment]
You can find the debug (lines) in the mysql debug table.

**Comment by Rouzax** [comment]
As far as I can tell there is nothing in the debug table that says anything about notifications. I only see NTTP related content.

**Comment by mesa57** [comment]
Did you look at the mysql notifications table if all expected notifications are in there ?
