### ISSUE TITLE
Error retrieving spots

### ISSUE THREAD

**Issue by stehof2** [spotweb/spotweb#258]
Hi,

I installed the latest version of Xampp and Spotweb yesterday. Everything went well and I could retrieve all spots.
The problem is that I'm not able to retrieve new spots after the first pull, when I'm run the command now, I get the error as show in the image.

I already read some issues about the error, the most people can fix the problem bij using the non-ssl port 119, I'm using the same port, but I still get the error.

I discovered that when I'm emty all records from table spots in the spotweb db, and I will run the retrieve command, then it will successfully receive all spots, when it's done and I'm running the command again, I got the same issue.

Does anybody had the same problem and know how to fix it?
Thanks in advance.

![img_1009](https://cloud.githubusercontent.com/assets/25264290/22174037/721694c8-dfd4-11e6-9e03-e32b9018ae51.PNG)

**Comment by mesa57** [comment]
I think this is a problem with you're USP. But I cannot test it as I don't have a 5eurousenet account.

**Comment by stehof2** [comment]
Thanks for the quick response, I will make a trial account with another usp and test it again, when I have the result I will post it.

**Comment by mesa57** [comment]
Ok, meantime I will execute a test with a 5eurousnet test account :)

**Comment by stehof2** [comment]
Yea the speed of 5eurousenet is the best, I could fill my entire spot db whithin 30min. I'm running the retrieve command now with USP pureusenet but it is a lot slower, this will take several hours, as soon as it's done I will test if I'm able to run the retrieve command again!

**Comment by mesa57** [comment]
5eurousenet is now working on the problem.

**Comment by stehof2** [comment]
Aaah that's a good thing. I made a trial account @ pure usenet, when I run the command on there server after I cleared the table spots it filled again with the spots.
After that I was able to run the command again, so the problem seems to be on the side of 5eurousenet.com.

Did they say if they fix the problem on short tail or not?

**Comment by mesa57** [comment]
They said they will try to fix it this weekend. I provided them with technical information what goes wrong in spotweb.

**Comment by stehof2** [comment]
nice, so did they gave you any feedback in the last days? Does it work now before I pay for another month? = P

**Comment by mesa57** [comment]
You're initial problem is solved now. But there is still an issue with headering comments. 
As there support is very keen on getting this solved, I would say : give them a change :)

**Comment by mesa57** [comment]
All problems with 5eurousenet are solved. Spots, comments and reports are retrieved correctly. Closing this issue.

**Comment by stehof2** [comment]
Aaah great! I'll start using them again :) thanks for figuring it out ;)
