### ISSUE TITLE
comments not verified

### ISSUE THREAD

**Issue by sredXNY** [spotweb/spotweb#259]
Hey, I've installed spotweb successfully, also I executed `php retrieve.php` and all good, then, in spotweb I see some comments count major to zero, some spots have 6,10,12...n comments, but when I click on it no comments are displayed, I followed the trace to see what happened and the comments seems to be not verified, so, how it should be done? the retriever doesnt do it? Thanks!

**Comment by mesa57** [comment]
Can you give some more information about you're installation, version nrs. etc ?
Also I would like to see the message-id of a spots which in you're opinion is missing comments ?

**Comment by sredXNY** [comment]
Surely, the spot is:
**Message-id of the spot:** 4Wsmox4UNfMGWWCWA8fNe@spot.net
**Title:** Mike Oldfield - Return To Ommadawn *2017* 24/96, flac ,mp3
**Comments counts** displayed in the spotweb index: 6 comments
**Spotweb version:** SpotWeb v0.68.28.32

I am convinced that is something that I'm missing, some configuration, etc...Is not possible to force to retrieve and validate the comments trough the console?

**Comment by mesa57** [comment]
Yes, you're missing comments. 
Do you have the openssl extension installed ? Comments are verified mainly by theire RSA hash.

**Comment by sredXNY** [comment]
Yes, I have. I checked also that

**Comment by sredXNY** [comment]
Hi, I checked the database and there are a lot of comments in the `commentsfull` table, but in the system none of them are displayed. So, I saw a column `messageid` in the `commentsfull` table and I made a simple query in PHPMyAdmin to check the correspondance between the spots and the comments:

`SELECT * FROM `spots` s join commentsfull c where c.messageid like s.`messageid`
`
But it gives 0 rows. So, I ask: that `commentsfull.messageid` should match with the `spots.messageid` column?

**Comment by Sweepr** [comment]
Could you paste the output of php retrieve.php ran from the console here using pastebin?

**Comment by sredXNY** [comment]
no, the retrieve is done right! but then in the system no comments are displayed, even the column "comments" show numbers major than zero

**Comment by Sweepr** [comment]
Ok, did you change usetnet provider inbetween on that installation?

**Comment by sredXNY** [comment]
I setted the usenet login settings, nothing else. What is the relation (id, messageid or something) between the spots and the commentsfull tables?

**Comment by Sweepr** [comment]
I think that your USP has either reset their article count or something else messed up this count, that's the reason why you see comments being retrieved, you see there are comments, but since the article count doesn't match they aren't linked in the DB and thus not visible in spotweb..

**Comment by sredXNY** [comment]
Yes, well, I will run the retriever with `--retro` and check what happen then! thanks

**Comment by mesa57** [comment]
As to you're database questions : 
- Commentsfull are linked to commentsxover via messageid. Commentsfull is not more then a cache and can be safely truncated (emptied)
- Commentsxover are linked to spots via commentsxover.nntpref to spots.messageid. Each commentsxover row with the same nntpref as the spot messageid is a comment belonging to the spot and will be retrieved (and saved in commentsfull) if the spot is openend.

As to the USP : they don't reset the article count, but sometime *renumber* all of there articles.
Spotweb saves the the last retrieved article in usenetstate. So if the USP renumbers or you switch to a different USP, spotweb will start retrieving at the wrong article number (however, there is a check so it should given an error message).

**Comment by Sweepr** [comment]
Closing since no reply,

Re-open if needed.
