### ISSUE TITLE
cache directory not availible on repository

### ISSUE THREAD

**Issue by bitking** [Spotweb/Spotweb#26]
Hi There,

In the root folder is no cache folder making NZB and images not load properly.

Please add a empty directory named "cache".

Thanks a lot.

**Comment by Wally73** [comment]
add the directory yourself (mkdir Cache ) simple as that

**Comment by bitking** [comment]
Hi, obviously i have done that but that is not gonna make this more easy for other people cloning from this git. Its mandatory for a full working spotweb so it should be here.

**Comment by dsadsdadsadsadsds** [comment]
Not can do this, Spotweb stores unique information in it and it causes version control issues.
