### ISSUE TITLE
Notify My Android notifier class not PHP7 compatible (deprecated class definition)

### ISSUE THREAD

**Issue by CptChaos** [spotweb/spotweb#260]
The class being used for Notify My Android gives an deprecated error about the class name or something like that. It isn't PHP7 compatible. 

I know I fixed it a while back, but thought the pull request was merged, but somehow it didn't I guess.
Unfortunatly, I've recently trashed my fork of Spotweb and don't have the code locally anymore. :(

Would be awesome if the class gets fixed again. :)

**Comment by mesa57** [comment]
Do you remember which class that was ?

**Comment by CptChaos** [comment]
I can't remember at the moment, had nma.php in the name. But I'll check it again when I get home to be sure.

**Comment by mesa57** [comment]
Updated uskr/nma-php via composer to 0.0.4 
Issue solved, see latest commit (master branch)

**Comment by CptChaos** [comment]
Oh, nice! :) Was busy all day to get the error / class for you. Nice seeing it solved already!
