### ISSUE TITLE
PHP Warning:  require(lib/RSA.php): failed to open stream running php-upgrade.php

### ISSUE THREAD

**Issue by mikeo999** [spotweb/spotweb#264]
Just did a Git Pull on a Synology DSM6 and then after running php-upgrade.php i get

`PHP Warning:  require(lib/RSA.php): failed to open stream: No such file or directory in /volume1/web/spotweb/lib/SpotClassAutoload.php on line 108
PHP Fatal error:  require(): Failed opening required 'lib/RSA.php' (include_path='.:/opt/share/pear') in /volume1/web/spotweb/lib/SpotClassAutoload.php on line 108`

In ownsettings.php the is a line that was once needed and created years ago.
`ini_set("include_path",`` ".:/opt/share/pear");`

Was running fine for a while back, even with DSM6.
But now i found that pear is not there anymore.

Not know if the problem is created because the missing pear of the something else is going wrong.

**Comment by mesa57** [comment]
The pear package should not be required for spotweb. It is running fine as is on dsm6 if all required parts of php are installed and authorisations are set correct. So comment out the ownsetings.

**Comment by mikeo999** [comment]
Comment out pear line in ownsetting and run php-upgrade again and the a get

`PHP Warning:  require(lib/RSA.php): failed to open stream: No such file or directory in /volume1/web/spotweb/lib/SpotClassAutoload.php on line 108
PHP Fatal error:  require(): Failed opening required 'lib/RSA.php' (include_path='.') in /volume1/web/spotweb/lib/SpotClassAutoload.php on line 108`

**Comment by mesa57** [comment]
Ok, I understand my problem now. You are using the media branche. 
As I have no knowlegde of the media branche we need @Sweepr to look at this issue.
Furtermore I think even then he does not know what is required for Synlogy/DSM6, but let's see.

**Comment by mikeo999** [comment]
Thanks, I will wait if @Sweepr now something about it.

**Comment by Sweepr** [comment]
Spotweb does not have a file called "php-upgrade.php" and is there any chance you could first verify which version it is you are actually running?

For the master branch the RSA.php file is located in this folder: 
spotweb/vendor/phpseclib/phpseclib/phpseclib/Crypt/

For the media branch the RSA.php file is located in this folder:
spotweb/vendor/phpseclib/Crypt/

**Comment by Sweepr** [comment]
https://github.com/spotweb/spotweb/blob/f2f08d5722efb5012fdc72af3ce33e371abf2a13/lib/SpotClassAutoload.php#L71-L78

**Comment by Sweepr** [comment]
I don't understand why SpotClassAutoload.php is looking for RSA.php in the 'lib' folder, there has never been such file in that place.

**Comment by mikeo999** [comment]
Sorry i mean upgrade-db.php. Was doing 2 things at the same time.

When i look in /volume1/web/spotweb/spotweb/.git/config is says Master branch.

The RSA.php file is in /volume1/web/spotweb/vendor/phpseclib/phpseclib/phpseclib
Why it is 3x phpseclib i don't know and I copyed the files extra to
/volume1/web/spotweb/vendor/phpseclib/phpseclib/

Why SpotClassAutoload.php is looking for the wrong folder i don't know. I just do a Git Pull sometimes and that it.

**Comment by mikeo999** [comment]
I just did a new Git clone of Spotweb master and now i can run upgrade-db.php wuthout errors.

But now when i run retrieve a get errors

`PHP Fatal error:  Undefined class constant 'MYSQL_ATTR_FOUND_ROWS' in /volume1/web/spotweb/lib/dbeng/dbeng_pdo_mysql.php on line 28

Fatal error: Undefined class constant 'MYSQL_ATTR_FOUND_ROWS' in /volume1/web/spotweb/lib/dbeng/dbeng_pdo_mysql.php on line 28
`

**Comment by mikeo999** [comment]
I just did a new Git Clone and all is working fine again.  Strange but glad it is fixed.

Thanks for the help.
