### ISSUE TITLE
Change bgcolor on number of spots

### ISSUE THREAD

**Issue by riemers** [spotweb/spotweb#268]
This is more an enhancement, the option to have a different color when spots have more then xx amount of comments on them. I added a css line and added some parts in my case where it checks if its higher then 30 posts to make it light green. This way i can easily see popular posts.

![image](https://cloud.githubusercontent.com/assets/682041/23359948/0cb952aa-fce9-11e6-8a5e-1280ff0d26ee.png)

I think it would be nicer if it was a setting with an option of the bgcolor. But i don't know that kind of detail, i am not a pro coder. Maybe others see the value of it too, i can help where i can ofcourse.

**Comment by mesa57** [comment]
You can create/use you're own css with spotweb I believe.

**Comment by riemers** [comment]
Yes, in the template or your own. I would see this as a addition to the
default template. you need to change a function too, in order to use the
postcount (still in template folder)

2017-02-27 12:47 GMT+01:00 mesa57 <notifications@github.com>:

**Comment by Mickroz** [comment]
ik have those edits in place, only my backgrounds are white/grey instead of the color of the cats.

**Comment by Sweepr** [comment]
@riemers @Mickroz
If one of you (or both) provide me an example of the CSS code that you use?

Then i can see if i can implement this?

**Comment by riemers** [comment]
I recently had to redo my install, and this was lost in the move :( also kinda forgot this ticket after 2 years :) perhaps @Mickroz still has it lying around.

**Comment by Mickroz** [comment]
yeah, i still use this on my setup, you have to change some core code too, let me check if i have got the edits somewhere.

**Comment by Sweepr** [comment]
Ok. no problem, i have made some edits on my test vm so it shouldn't be hard to implement.

**Comment by Mickroz** [comment]
open /templates/we1rdo/spots.inc.php

find:
`foreach($spots as $spot) {`
before add:
`	$count = 0;`

find:
`$tipTipClass = $show_mouseover_subcats ? 'showTipTip' : '';`
after add:
`		$count++;`

find:
`"<td class='title`
inline after add:
` " . ($count % 2 ? "bg1" : "bg2") . "`

find:
`"<td class='editspot`
inline after add:
` " . ($count % 2 ? "bg1" : "bg2") . " " . $newSpotClass . "`

find:
`"<td class='watch`
inline after add:
` " . ($count % 2 ? "bg1" : "bg2") . " " . $newSpotClass . "`

find:
`"<td class='comments`
inline after add:
` " . ($count % 2 ? "bg1" : "bg2") . " " . $newSpotClass . "`

find:
`"<td class='genre`
inline after add:
` " . ($count % 2 ? "bg1" : "bg2") . " " . $newSpotClass . "`

find:
`"<td class='poster`
inline after add:
` " . ($count % 2 ? "bg1" : "bg2") . " " . $newSpotClass . "`

find:
`"<td class='date`
inline after add:
` " . ($count % 2 ? "bg1" : "bg2") . " " . $newSpotClass . "`

find:
`"<td class='filesize`
inline after add:
` " . ($count % 2 ? "bg1" : "bg2") . " " . $newSpotClass . "`

find:
`"<td class='nzb`
inline after add:
` " . ($count % 2 ? "bg1" : "bg2") . " " . $newSpotClass . "`

find:
`"<td class='multinzb`
inline after add:
` " . ($count % 2 ? "bg1" : "bg2") . " " . $newSpotClass . "`

find:
`"<td class='sabnzbd`
inline after add:
` " . ($count % 2 ? "bg1" : "bg2") . " " . $newSpotClass . "`

find:
`"<td class='sabnzbd`
inline after add:
` " . ($count % 2 ? "bg1" : "bg2") . " " . $newSpotClass . "`

find:
`"<td class='nzb`
inline after add:
` " . ($count % 2 ? "bg1" : "bg2") . " " . $newSpotClass . "`

find:
`"<td class='multinzb`
inline after add:
` " . ($count % 2 ? "bg1" : "bg2") . " " . $newSpotClass . "`

find:
`"<td class='sabnzbd`
inline after add:
` " . ($count % 2 ? "bg1" : "bg2") . " " . $newSpotClass . "`

Save and close file.

And use this for custom css:
```
.bg1	{ background-color: #ececec !important; }
.bg2	{ background-color: #fefefe !important; }

.new { background-color: #edfeed !important; }
.new, .new a { color: #006600 !important; }
```

**Comment by Mickroz** [comment]
every inline after add has a space in front of it, github markdown discards this space :(

**Comment by Sweepr** [comment]
Nice work @Mickroz , altough i find too many colours doing to opposite thing, i clutters the overview too much, so here's what i've come up with:

If there are 10 or more comments, the spot turn light green:

![image](https://user-images.githubusercontent.com/2857865/63955009-5316ae80-ca84-11e9-9558-14089951c944.png)

I can work things out further for users to be able to change the colours and amounts of comments.

Or we can just leave it like this as a new feature, so just just have to deal with it?

@mesa57, What do you think?

**Comment by Mickroz** [comment]
ahh ok, mine looks like this:
![spotweb](https://user-images.githubusercontent.com/994362/63962578-68dfa000-ca93-11e9-9c6c-2813afef86f3.png)

**Comment by riemers** [comment]
Mine was like @Sweepr although i had the color set to dark green (sort off like the comment button on a github issue color) and only with really high numbers like 30+ but if that could be a setting somewhere then that would be nice.

**Comment by Sweepr** [comment]
Added this option into dev branch, settings are on/off if on, below there's a checkbox to fill in the amount of comments in order to highlight that spot.

![image](https://user-images.githubusercontent.com/2857865/64061413-bc103a80-cbda-11e9-919d-dc930e3a7969.png)

Default = On/10

In https://github.com/spotweb/spotweb/blob/develop/templates/we1rdo/css/style.css

/* Here you can change the color of the highlighted spots based on comments: eg #09ba09 */
.bg1	{ background-color: #edfeed !important; }

**Comment by Mickroz** [comment]
Hmm i would prefer that you change the .bg1 class to something else.

**Comment by Sweepr** [comment]
Ofcourse, any suggestions?

**Comment by Sweepr** [comment]
hg1?

**Comment by Mickroz** [comment]
Yeah, or something like hot, or populair?

**Comment by Sweepr** [comment]
Done, change to hg1

**Comment by Mickroz** [comment]
Thanks!

**Comment by Sweepr** [comment]
Didn't think about that, bg1 would break your local changes. ;-)

**Comment by Sweepr** [comment]
Closing this as it's implemented in the Dev branch, is any issue's please re-open.
