### ISSUE TITLE
Unable to retrieve. Failed to retrieve article

### ISSUE THREAD

**Issue by sredXNY** [spotweb/spotweb#269]
Hey, I'm trying to execute the _retrieve.php_ script. It was working somedays ago, but now I get an error while trying to retrieve new spots, I already tried with --force, --reallyforce and even -debug but it seems that something crashed in the database. I attach a screenshot so then you can see the strange symbols that appears in the error:

![untitled](https://cloud.githubusercontent.com/assets/4504205/23372732/a015a8b6-fcfb-11e6-9f3e-1f496356f7d1.png)

So, I would like to know how to fix it, and how to avoid in the future this problem, thank you!

**Comment by mesa57** [comment]
Do you have the option to download fullspots turned on ?

**Comment by mesa57** [comment]
Then of course turn it off and try again.

**Comment by sredXNY** [comment]
yes, you're right! why it happens? why I cannot download fullspots?

**Comment by mesa57** [comment]
Some spot with really strange data comes from you're USP

**Comment by sredXNY** [comment]
yes,well I understand. Thank you it helped me a lot!

**Comment by mesa57** [comment]
anyway, retrieving full spots has not much advantages. You're retrieve performance will be terrible and you're database will grow huge. Spotweb anyway retrieves the full spot when you open it the first time.
