### ISSUE TITLE
t=search works, t=movie doesn't...

### ISSUE THREAD

**Issue by ZeroZorro999** [spotweb/spotweb#272]
After a chat last night with @onedr0p, he mentioned it would be worth opening an issue inhere...

"so this works
http://<ip>/spotweb/api?t=search&cat=2000&extended=1&apikey=XXXXXXXXX&offset=0&limit=50

but this doesn't

http://<ip>/spotweb/api?t=movie&cat=2000&extended=1&apikey=XXXXXXXXX&offset=0&limit=50
I think this is an issue with Spotweb TBH
they aren't abiding by the newznab protocal 100%"

Currently trying to setup Spotweb as newnab indexer with Radarr on my Synology DS214play

**Comment by mesa57** [comment]
I would appreciate if you have a link to the newznab protocol specification.

**Comment by ZeroZorro999** [comment]
I hope you mean this, hope it helps...Spotweb is a webbased version of spotnet
https://github.com/spotweb/
https://en.wikipedia.org/wiki/Spotnet
For a full specification of the protocol see the Spotnet Wiki 
https://github.com/spotnet/spotnet/wiki

**Comment by Wally73** [comment]
https://github.com/nZEDb/nZEDb/blob/dev/docs/newznab_api_specification.txt 

newznab is the same (but the newer NN's are closed source)

**Comment by ZeroZorro999** [comment]
and this link:
http://newznab.readthedocs.io/en/latest/misc/api/#movie-search

**Comment by mesa57** [comment]
t=movie works BUT only with the imdbid parameter. 
According to newznab specification other parameters are optional and do not have to be implemented.

**Comment by onedr0p** [comment]
Yes, but with only t=movie and api key we get an error saying missing parameter

**Comment by onedr0p** [comment]
Ohh and the offset and limit parameters are set too

**Comment by onedr0p** [comment]
Expected result is t=search but with only movies

**Comment by onedr0p** [comment]
imdbid is optional too

**Comment by mesa57** [comment]
At this time it is the only possibilty to do a t-movie search.

**Comment by onedr0p** [comment]
We'll refer people here who have problems with radarr and spotweb. Hopefully you can implement it, thanks!

**Comment by mesa57** [comment]
@onedr0p You already made some minor code changes and created a pull request.
I invite you to complete you're change so that radarr is fully supported 😄

**Comment by onedr0p** [comment]
Unfortunately I'm too busy with other projects and work to set up dev tools and spotweb for testing :/ Plus you know the code base more than I do.

**Comment by Wally73** [comment]
spotweb api search: 

<search available="yes"/>
<tv-search available="yes" supportedParams="q,rid,tvmazeid,season,ep"/>
<movie-search available="yes"/>

newznab api search:

<search available="yes" supportedParams="q"/>
<tv-search available="yes" supportedParams="q,vid,tvdbid,traktid,rid,tvmazeid,imdbid,tmdbid,season,ep"/>
<movie-search available="yes" supportedParams="q,imdbid"/>

so its obvious that spotweb is behind

**Comment by the-darkvoid** [comment]
See pull request #274 for initial Radarr support

**Comment by mesa57** [comment]
Change request merged. Thank you for the coörperation 😄
