### ISSUE TITLE
Not sending email

### ISSUE THREAD

**Issue by Rouzax** [spotweb/spotweb#273]
After reinstalling Spotweb on a new server it is not sending out emails again.

Server: Windows Server 2016
PHP: 7.1.1
Spotweb: 7a38b46ede4d81648f49773fc1df21dddd255857

PHP mail is setup, I've created a test php file in my spotweb root and setup the same mail addresses and when I call that file I get an email.
```
<?php 
    ini_set( 'display_errors', 1 );
    error_reporting( E_ALL );
    $from = "mail@xxx.yyy";
    $to = "mail@xxx.yyy";
    $subject = "PHP Mail Test script";
    $message = "This is a test to check the PHP Mail functionality";
    $headers = "From:" . $from;
    mail($to,$subject,$message, $headers);
    echo "Test email sent";
?>
```
![image](https://cloud.githubusercontent.com/assets/4103090/23555567/b5e9b03e-0029-11e7-87a1-9a7a88fc43b7.png)

Within Spotweb the `notifications` table is empty
I see nothing in that is related to email in the `debuglog`
In my Cpanel of my mail server I also see nothing coming in with `Track Delivery`

**Comment by mesa57** [comment]
Tested under php 7.1 and it still works. So there should be some other problem with you're configurations or notifications setup.

**Comment by Rouzax** [comment]
Should the `notifications` table hold copies of the send mails?

**Comment by mesa57** [comment]
No, not a copy of the send mail, but a copy of the notification.
A notification can be send to multiple destinations, not only mail.

**Comment by Rouzax** [comment]
So it would be normal that mine would be completely empty because no notifications have been send yet.
How could I debug this further?

**Comment by mesa57** [comment]
If it is empty, then no notifications are triggered at all.
Please look at you're notifications setting.

**Comment by Rouzax** [comment]
![image](https://cloud.githubusercontent.com/assets/4103090/23558162/e416e9aa-0032-11e7-8801-b42d97a44328.png)
![image](https://cloud.githubusercontent.com/assets/4103090/23558198/f75ba69a-0032-11e7-93b7-8456ceb30a5d.png)

**Comment by mesa57** [comment]
Are there more the 0 spots retrieved ?
Is you're user member of the group 'Authenticated Users' ?

**Comment by Rouzax** [comment]
Since I changed the pchart it seems I'm getting mails.
![image](https://cloud.githubusercontent.com/assets/4103090/23561669/74ac1ce0-003f-11e7-8b15-69f70b208932.png)
Will keep an eye on it to check if all notifications are coming.

**Comment by mesa57** [comment]
Maybe the statistics update error prevented the notifications.

**Comment by Rouzax** [comment]
That is what I'm also thinking.
