### ISSUE TITLE
Add web.config to .gitignore

### ISSUE THREAD

**Issue by Rouzax** [spotweb/spotweb#277]
On a Windows IIS installation web.config is used to configure IIS, could that web added to https://github.com/spotweb/spotweb/blob/master/.gitignore to prevent it from being deleted if I do a git clean

**Comment by mesa57** [comment]
I know, but I do not think we should do installation specific changes in spotweb.

**Comment by Rouzax** [comment]
There are already entries in there that are installation specific, like .htpasswd for Apache.

**Comment by mesa57** [comment]
Which I don't like at all.
But would a line in .gitignore help ?

**Comment by Rouzax** [comment]
Yes, I just did a git clean of my Spotweb instance because I had manually added the PChart. I wanted to get back to the normal master. The clean also deleted my web.config file, it is not a big issue.
