### ISSUE TITLE
radarr still not working

### ISSUE THREAD

**Issue by p0nt** [spotweb/spotweb#278]
After installing the new version it seems that radarr is still not completely working.

Testing the index works, which is making the following query:
http://localhost/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=8dbc8974b98d1038e90f8938aca6c1a8&offset=0&limit=25

Actually searching for a movie makes the following query, which does not work and will provide no proper output:
http://localhost/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=8dbc8974b98d1038e90f8938aca6c1a8&offset=0&limit=25&imdbid=3640424

XML output:
https://justpaste.it/145s7

seems to lie with the imdbid (&imdbid=3640424)

**Comment by p0nt** [comment]
I have found the issue, it seems to be cat 2060 that does not work.

any url that has cat=2060 in it will fail, the rest of the cat's work

**Comment by p0nt** [comment]
as you can see here after removing 2060 from the SpotPage_newznabapi.php config file I can retrieve spots from my spotweb server:

http://imgur.com/a/0ic4T

**Comment by mesa57** [comment]
It is not necessary to specify cat at all in the url, so why do that ?

**Comment by the-darkvoid** [comment]
Confirmed that there is some issue regarding category 2060.
The same behaviour can be observed through the spotweb web interface, for some reason when combining a format query with a genre query no results are generated.

As work around I would suggest removing the category not in Spotweb code, but rather in the Radarr indexer configuration.

mesa57 is correct though that categories are not needed, you are searching for a unique IMDB ID anyways.

@p0nt,

Can you confirm that categories (blank) or "2000,2010,2020,2030,2035,2040,2045,2050" as indexer configuration works in Radarr?

**Comment by p0nt** [comment]
@the-darkvoid confirmed, leaving out 2060 solves the issue as well.

**Comment by Wally73** [comment]
2060 in spotweb is movies sport it seems
https://github.com/spotweb/spotweb/blob/master/lib/page/SpotPage_newznabapi.php#L871

but in newznab api spec that's bluray

**Comment by mesa57** [comment]
No, 2060 is newznab category Movies/3D
As spotweb/net does not know that category, it should be left out.
I've been busy whole day overhauling yhe newznab interface, I will merge it soon on the master branch.

**Comment by mesa57** [comment]
Fixed with commit  	535d8c9

**Comment by fahadshery** [comment]
Unfortunately, the real fix for me was to check what categories a particular indexer e.g. gktorrent, rarbg etc. supports Jackett (click the wrench symbol) and then set those in radarr. it was pain in the backside but it was worth doing it. now all issues have been resolved and it is working as it should be!
