### ISSUE TITLE
Undefined index after installation

### ISSUE THREAD

**Issue by leonvsc** [spotweb/spotweb#283]
I am new to Spotweb but after i installed it i get this error.

https://gyazo.com/000be2f48b435ddea3a6b51181101e3e

What can be the problem?

**Comment by mesa57** [comment]
Look related to this issue : 
https://github.com/spotweb/spotweb/issues/212

**Comment by leonvsc** [comment]
reinstalled it fourth times or somethings and in the fourth time its working so idk what that is
