### ISSUE TITLE
A lot of problems with the install.

### ISSUE THREAD

**Issue by includess** [spotweb/spotweb#286]
Hi everybody!

I'm trying to istall spotweb on a xamp server. 
When i try to run the  install.php page, i get this error:

Parse error: syntax error, unexpected '[' in C:\xampp\htdocs\Spotweb\install.php on line 53

I have used the install.php from this site, i tryed everything but nothing works.
Spotweb easy also doenst work, i got a php 500 error when i want to open my intall.php.
I'm searching for more then 50 hour, but i cant find a solution for al my problems.
Can someone help me out?

Greetings,

Alex

**Comment by mesa57** [comment]
First, give some clues about the OS, php version you use and the spotweb version ?

**Comment by includess** [comment]
The 500 error when opening install.php afther the install of the spotweb easy installer was on a windows 7 pc and a windows 2012 R2 Server.

That parse error i have on Xammp server is on a Windows 2012 r2 server PHP Version 5.3.8.
The spotweb version is from the Code tab of this site. 

Thanks for your time, much appreciated!!

**Comment by mesa57** [comment]
php 5.3 is pretty old and is not used for testing with spotweb anymore.
Could you upgrade to php version 5.6 or even better 7.1 ?

**Comment by includess** [comment]
Thanks, this fixed my problem! 
Now i got another problem, when i klik on the retrieve button it says new spots retrieved,  but i cant see anyspots in it.
When i openen the retreive wit php-win.exe nothing happens, i cant see a window or anything.

Maybe you know a solution?

**Comment by includess** [comment]
Nivermind i got it, it was upgrade db!
Thanks for your time, keep up the good work.

**Comment by mesa57** [comment]
No thanks, glad that's working 😄
