### ISSUE TITLE
Only last NZB downloaded

### ISSUE THREAD

**Issue by wiffleball666** [spotweb/spotweb#293]
If multiple NZBs are selected for download only the last one selected is actually downloaded, but the check box selection for the others are cleared.

**Comment by mesa57** [comment]
Please specify you're OS, php version, webserver (version) and browser used.

**Comment by HeMaN-NL** [comment]
Are you sure the other files are not downloaded? 
Spotnet  creates a single nzb file to download when you select multiple spots, but all selected will be downloaded (or should be)

**Comment by wiffleball666** [comment]
I believe I have to retract my comment. If the selections are valid (Newsgrabber opens the nzb) it's not an issue. 

My bad.
--------------------------------------------
On Fri, 3/17/17, HeMaN-NL <notifications@github.com> wrote:

 Subject: Re: [spotweb/spotweb] Only last NZB downloaded (#293)
 To: "spotweb/spotweb" <spotweb@noreply.github.com>
 Cc: "wiffleball666" <daveyb666@yahoo.ca>, "Author" <author@noreply.github.com>
 Received: Friday, March 17, 2017, 12:50 AM
 
 Are you sure the other files are
 not downloaded?
 
 Spotnet  creates a single nzb file to download when you
 select multiple spots, but all selected will be downloaded
 (or should be)
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by mesa57** [comment]
No problem 😄
