### ISSUE TITLE
commentsfull.stamp (and others) should be unsigned

### ISSUE THREAD

**Issue by GieltjE** [spotweb/spotweb#294]
Timestamps cannot be negative anyway and the database optimized might be able to return a bit faster. (We should consider making all int fields which cannot be negative unsigned as it is good practice).

Regarding reversestamp, do we still need this? (the world has come a long way in the past few years).
                                /*
                 * when asked to sort on the field 'stamp' descending, we secretly
                 * sort ascsending on a field called 'reversestamp'. Older MySQL versions
                 * suck at sorting in reverse, and older NAS systems run ancient MySQl
                 * versions
                 */

**Comment by mesa57** [comment]
If only for good practise I am at least not going to spent time on this.
Furtermore : what is 'old' ? I don't know.
Otherwise I agree with you.

**Comment by GieltjE** [comment]
Giving the optimizer information enhances it's potential for better optimization.

As for the old the only references I could find for MySQL being slow with sorting was for old 5 versions, as this would only be a problem for very old devices my best guess is that the memory is better spent on other things than a sorting column. (as for modern devices the optimizer combined with the index should be able to handle it just fine for us).

**Comment by mesa57** [comment]
5 versions are still widely in use (in fact I use that myself). 
You can of course create a commit but then do not forget to : 
- Update SQLite as well as the PostGre code besides MySQL.
- Update the schema version so that a db-upgrade is required.

**Comment by GieltjE** [comment]
I meant old 5.x versions, I shall run a test on the most recent 5.x version when I have some time in order to asses wether it is still required.

**Comment by mesa57** [comment]
Btw. if you do a commit, please create a develop branch.

**Comment by GieltjE** [comment]
Have got a basic implementation done, tests with postgresql and sqlite testing shall commence next.

Any other optimizations I could include?

**Comment by mesa57** [comment]
What do you mean by "other" ?
In my opinion retrieve.php is still running unbarely slow, but I have no idea what to optimize there.

**Comment by GieltjE** [comment]
For now I have removed it, hasn't resulted in a measurable difference on my old server but the MySQL 5.6 server still needs to be tested.

**Comment by mesa57** [comment]
If you remove it, also the scripts for initial db setup should be changed and the schema version should be incremented. Be aware the reversetimestamp is part of an index.

**Comment by GieltjE** [comment]
what is it with all the "} # if" code everywhere? Doesn't make any sense

**Comment by mesa57** [comment]
? example ?

**Comment by GieltjE** [comment]
index.php:25

**Comment by mesa57** [comment]
These are just comments to enhance readability for non curly bracked used programmers.
It is just cosmetic and used all over spotweb, so don't waste you're valuable time on that.

**Comment by HackAzz** [comment]
Is this project still alive?

**Comment by GieltjE** [comment]
Yeah, sorry for the slow updates have had a few hard weeks of work, the preliminary patches are done, need to test them in a few different configurations first

**Comment by HackAzz** [comment]
Hey GieltjE, Nice to hear from you, and good to know that the project is still be working on :-)
I am looking forward to it!
Keep up the good work.

**Comment by GieltjE** [comment]
Created pull request #314 could someone test it with pgsql?

**Comment by mesa57** [comment]
Could you please undo this pull request and file one to the development branch ?

**Comment by GieltjE** [comment]
done :)

**Comment by mesa57** [comment]
Nice, merged with develop branch now. See if I can find some time to test next week(end).

**Comment by GieltjE** [comment]
Might have to look at some of the indexes as that would be much more beneficial (http://use-the-index-luke.com/).

That would take me a bit more time as I would need to look at the possible queries.

**Comment by mesa57** [comment]
I did a test with this change, but the database upgrade took to long. I canceled it after hours of processing.

**Comment by mbirth** [comment]
@mesa57 I wouldn't call that "fairly large". Should be the default as many Usenet providers have unlimited retention nowadays. My SQLite database has 1.537.441 spots which should be all since the beginning and that amount is nothing for a database.

**Comment by mesa57** [comment]
The change was tested on a MySQL database (most used).

**Comment by GieltjE** [comment]
Removing the row from a large DB can take a long time (esentially rewriting the entire table).

Using 1900 day retention and full comment and spot data, took a few hours on an older system.

Just rewriting a few lines php should give a good indication of the performance.

A few index tweaks did some noticable changes on my server, but since it is fast enough to do it either way I kind of stopped caring over time.
