### ISSUE TITLE
Spotweb not working with HTTPS reverse proxy

### ISSUE THREAD

**Issue by Moonl1ghter** [spotweb/spotweb#298]
Hello,

I've got the problem that Spotweb does not work when using an NGINX reverse proxy server over https. CSS is not loaded. There was a quick fix for this by changing the settings.php, but this does not longer work because the settings.php has been changed. Is there anyway to get this to work?

Thanks in advance

**Comment by mesa57** [comment]
In the latest release that should work, but see the wiki how to configure you're nginx proxy.

**Comment by Archcry** [comment]
```
server {
    listen 443 ssl;

    server_name example.com www.example.com;
    root /path/to/spotweb;
    index index.html index.htm index.php;

    # SSL
    ssl_certificate /path/to/letsencrypt/fullchain.pem;
    ssl_certificate_key /path/to/letsencrypt/privkey.pem;

    # HTST
    add_header Strict-Transport-Security 'max-age=31536000; includeSubDomains; preload';

    location / {
        satisfy any;

        if ($uri !~ "api/"){
            rewrite /api/?$ /spotweb/index.php?page=newznabapi last;
        }

        location ~ \.php$ {
            try_files $uri =404;
            include fastcgi_params;
            fastcgi_pass unix:/path/to/php-fpm/spotweb.sock;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }

    # Disable Gzip
    gzip off;

    # SSL Stapling
    ssl_trusted_certificate /path/to/letsencrypt/chain.pem;
    ssl_stapling on;
    ssl_stapling_verify on;
}
```

This config works and has been working for my for over 6 months.

**Comment by mesa57** [comment]
Seems to me that this is not a nginx reverse proxy, but using nginx as only webserver (which always worked in spotweb https).

**Comment by Archcry** [comment]
Owait you're right. What does op need the reverse proxy for anyways?

**Comment by mesa57** [comment]
I have put some information here : 
https://github.com/spotweb/spotweb/wiki/Installation-tips-and-troubleshooting
(scroll down)
