### ISSUE TITLE
Database upgrade failed

### ISSUE THREAD

**Issue by neographikal** [spotweb/spotweb#302]
After getting the lastest master:

c:\webserver\websites\spotweb.neofoto.nl\bin>php upgrade-db.php
Updating schema..(pdo_pgsql)
        Validating spots(messageid)
        Validating spots(poster)
        Validating spots(title)
                Modifying column title (type) on spots

SpotWeb crashed

Database schema or settings upgrade failed:
   22001: 7: ERROR:  value too long for type character varying(128)

#0 C:\webserver\websites\spotweb.neofoto.nl\lib\dbstruct\SpotStruct_pgsql.php(240): dbeng_pdo->rawExec('ALTER TABLE spo...')
#1 C:\webserver\websites\spotweb.neofoto.nl\lib\dbstruct\SpotStruct_abs.php(161): SpotStruct_pgsql->modifyColumn('title', 'spots', 'VARCHAR(128)', NULL, false, 'utf8', 'type')
#2 C:\webserver\websites\spotweb.neofoto.nl\lib\dbstruct\SpotStruct_abs.php(346): SpotStruct_abs->validateColumn('title', 'spots', 'VARCHAR(128)', NULL, false, 'utf8')
#3 C:\webserver\websites\spotweb.neofoto.nl\lib\services\Upgrade\Services_Upgrade_Base.php(42): SpotStruct_abs->updateSchema()
#4 C:\webserver\websites\spotweb.neofoto.nl\bin\upgrade-db.php(34): Services_Upgrade_Base->database()
#5 {main}
c:\webserver\websites\spotweb.neofoto.nl\bin>

**Comment by mesa57** [comment]
In PGAdmin try to execute next sql before upgrade : 
`ALTER TABLE spots ALTER COLUMN title TYPE VARCHAR(128) USING SUBSTR(title, 1, 128)`
