### ISSUE TITLE
Erotica spots shown when hide erotica is checked.

### ISSUE THREAD

**Issue by Mickroz** [spotweb/spotweb#303]
for some reason erotica spots are not hidden in overview even though it is checked in preferences.

**Comment by mesa57** [comment]
Could you give some info about you're installation ?

**Comment by Mickroz** [comment]
running ARCH Linux 4.8.4
PHP version	7.1.3
mysql  Ver 15.1 Distrib 10.1.22-MariaDB
curl 7.53.1-1
php 7.1.3-1

**Comment by Mickroz** [comment]
i think the problem comes because the poster posted it movies as in erotica because the post says:
Type	Erotica
Type	Movie

**Comment by Mickroz** [comment]
Ok closing this for now, for some reason there hidden again, found some spots which were shown yesterday and they only have Type Erotica now, the Type Movie is gone.

**Comment by mesa57** [comment]
Sometimes problems solve themselfs :wink
