### ISSUE TITLE
After updating (git pull) the CSS styles are gone

### ISSUE THREAD

**Issue by CptChaos** [spotweb/spotweb#305]
Hello again!

I updated Spotweb yesterday since a while, and I saw there was a big update which I had missed.
I saw a framework is being used now, so I immediatly ran composer install after the pull was complete.
A lot of packages got installed. I was also looking for a database patch, perhaps there also was a patch.
I finally found upgrade-db.php in the bin folder (although I do not understand why, a php file is not binary at all!)

After those were completed, I tried Spotweb again. It worked. Partially. The CSS styling is not being loaded and I can't see why actually. The URL used to get the CSS (although I do not understand why a framework should parse static files) works properly, if I click the URL, I get to see the CSS being used. But somehow Firefox (latest stable) and Chrome (latest stable) do not parse the CSS at all. Any idee what I missed / can try?

I am running:
Debian 9 (testing)
PHP 7.0.16-3
MariaDB 10.1.22
Nginx 1.10.3

On a note: I have Spotweb behind a proxypass in Nginx, as SSL terminator. The database is on a centralised server, which also does the nginx proxy-ing. :) It worked before the upgrade, so my guess it has something to do with the upgrade.

**Comment by mesa57** [comment]
Could you try this (SSL proxy) : 
https://github.com/spotweb/spotweb/wiki/Installation-tips-and-troubleshooting

**Comment by CptChaos** [comment]
Cool! The override from ownsettings.php works!

**Comment by mesa57** [comment]
That was the fastest answer I ever saw 😉

**Comment by CptChaos** [comment]
The header in nginx (X-SSL 'on') works too. Although I already had this in my config:
```
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
```

So maybe (also?) check for X-Forwarded-Proto header, would be more obvious.

**Comment by piejanssens** [comment]
For haproxy I added this to my frontend: `http-request set-header X-SSL %[ssl_fc]`

**Comment by CptChaos** [comment]
Well, that is the header I added. But I think using a more common header (X-Forwarded-Proto for instance) would be more logical, because it's more widely used.

**Comment by piejanssens** [comment]
Yes you are right.
