### ISSUE TITLE
Hetero etc show though 'hide erotica' is checked

### ISSUE THREAD

**Issue by MrHappy** [spotweb/spotweb#306]
Spots marked only as Hetero for example are not hidden on my index page.
I suppose this is because it's only filtering on cat0_z3 and not the subtree of it (cat0_z3_xyz).
Is it possible to make that work (so it filters cat0_z3 and cat0_z3_a1 etc)?

**Comment by Mickroz** [comment]
I had the same but it for some reason got fixed without doing anything, does a spot show 2 Type's ?

**Comment by MrHappy** [comment]
It is still visible. This particular spot has 1 genre (Hetero) and 2 types (Movie and Erotic).
(url of the spot: http://<server>/?search[tree]=&search[unfiltered]=true#/?page=getspot&messageid=THZHVW9ocWNKr3O2SZ7n6jqxWUV%40spot.net).
I think it should filter out anything that contains cat0_z3 (even if it has other categories) if that's possible, so they never show up (unless you explicitly select the erotica-section ofcourse...

**Comment by Mickroz** [comment]
I think it does that, well as i said, it magically fixed it by itself on my spotweb.
fyi mine were with te same poster, and my spotweb hasn't updated since 28/4, only thing i did, but didn't work, was deactivating Hide erotic spots in index?, then save, and then activate it again.
the next day it was fixed.
I see some of his spots are still with 2 types, but are hidden in my overview.

**Comment by mesa57** [comment]
Please tell me if if this : 
`http://{youre spotweb url}/?search[tree]=cat0_z0&sortdir=DESC&sortby=stamp&search[value][]=Poster%3A%3D%3ADEF%3AKenji
`Delivers any results.

**Comment by Mickroz** [comment]
not on my spotweb.

**Comment by MrHappy** [comment]
not on mine either

**Comment by mesa57** [comment]
@MrHappy : the spot you mentioned is from poster Kenji, however the cat_z0 query does not deliver that in the list ?

**Comment by mesa57** [comment]
It is a direct consequence of the content of the header of those posts : 
`@17a09b03c00d75z03z00.`
I don't what post client the poster uses, but it is a pretty old one and it makes errors.
Closing the issue for now.

**Comment by MrHappy** [comment]
@mesa57: I have no idea what you mean with your last remark... Could you please clarify?
(I don't know if that is what you meant, but I updated my spotweb about a week ago)

**Comment by mesa57** [comment]
It has nothing to do with spotweb updates, but with spots being placed with the wrong information.
