### ISSUE TITLE
Fresh install doesn't produce CSS

### ISSUE THREAD

**Issue by Gibletron** [spotweb/spotweb#308]
I have a freshly installed Nginx + PHP + MariaDB, on this I'm trying to host Spotweb.
The issue I face has been discussed in a few tickets already, the CSS just doesn't get loaded, same issue as: https://github.com/spotweb/spotweb/issues/176
I have read the open en closed issues and found a lot of issues with the current spotweb release combined with an nginx reverse proxy.
My Nginx config uses SSL but since I host spotweb on the same nginx it's supposedly not a reverse proxy.
The suggestions on the wiki did not solve the issue: https://github.com/spotweb/spotweb/wiki/Installation-tips-and-troubleshooting
I also tried running it on HTTP instead of HTTPS with the same issue

I do notice something seems wrong with the urls on the page..
For instance the login url points to:
![image](https://cloud.githubusercontent.com/assets/17140683/25774208/6bc2457c-328b-11e7-8061-1891d222f8ec.png)

spotweb/index.php/spotweb ? no sure why that is or if it's normal

Is there anything I could be looking for? or does this just not work currently?

**Comment by mesa57** [comment]
That's not a correct url, no

**Comment by Gibletron** [comment]
The connect url is:
https://192.168.1.199/spotweb
And currently there is no ownsettings.php
I did have one which contained:
```
<?php
   $settings['ssloverride'] = true;
?>
```
But as that didn't work I removed it again
