### ISSUE TITLE
Timezone settings (ignored??)

### ISSUE THREAD

**Issue by ysm1mh** [spotweb/spotweb#309]
Hey guys.  i got a issue with the timezone settings.  i setup the timezone corrcetly.

but for some reason its either being ignored or something changed and i cant figure it out.

my timezone is set to  date.timezone = "Europe/Amsterdam"

error i keep getting is:

> Warning: strtotime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /home/angryroc/spotweb.angryrockkillers.com/lib/services/Nntp/Services_Nntp_SpotReading.php on line 28
PHP Warning:  strtotime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /home/angryroc/spotweb.angryrockkillers.com/lib/services/Format/Services_Format_Parsing.php on line 260

**Comment by Wally73** [comment]
there are 2 php.ini's change them both (esp the cli one )

**Comment by ysm1mh** [comment]
i hve no acces to the cli ini file.  the server has run for months without any issues.  now all of a suddon i get this problem.  weird.

ps. i run it on a webhosting.  prob a error on their behalve.

**Comment by mesa57** [comment]
Maybe you can try to use date_default_timezone_set() in ownsettings.php (to be created prob.)

**Comment by ysm1mh** [comment]
worth a try. anyone got a example file how to set that up.  i never used it.

**Comment by ysm1mh** [comment]
date_default_timezone_set() oh that did the trick..  awesome,

i wonder tho what changed.  but thx for the help.

**Comment by mesa57** [comment]
No thx, I will close this issue.
