### ISSUE TITLE
Commits

### ISSUE THREAD

**Issue by dsadsdadsadsadsds** [spotweb/spotweb#31]
a696fd4f4877d7ec94804c5393ffae6ad1905d6f

- I do not think this is correct. You basically supress an error caused by incorrect input, but it should never be incorrect. eg, you are fixing the wrong bug.

---

b57f5e6e8ad2ec12df701d770637d9bf7138db68

- Same story, i do not think this is correct as the calle should always be explicit about its intent, and we should not mangle the input in the database layer.

**Comment by Muis** [comment]
If you create a pull request which reverses them, I will merge it.

**Comment by dsadsdadsadsadsds** [comment]
I still think you need to fix those. I cannot do a commit for the moment, but they are wrong and will hide bugs in the future :)
