### ISSUE TITLE
Mysql port 3307

### ISSUE THREAD

**Issue by piejanssens** [spotweb/spotweb#313]
How can I setup Spotweb with mysql running on port 3307?

**Comment by mesa57** [comment]
At this time not possible, unless you change the code.

**Comment by piejanssens** [comment]
FYI On DSM 6 (Synology) you now have two MySQL packages; MariaDB 5 (port 3306) and MariaDB 10 (port 3307).
The standard phpMyAdmin package only works with MariaDB 10.

**Comment by mesa57** [comment]
Please note that spotweb is an open source project to which everybody can contribute.
Just change the code and create a pull request for merging.
