### ISSUE TITLE
Change from public -> non public setup

### ISSUE THREAD

**Issue by piejanssens** [spotweb/spotweb#317]
Can't find this info in the wiki.
My spotweb seems to be public, without logging in anyone can see the spots.
How can I change this so that the spotweb login screen appears first?

PS. When logged in I can see the user preferences, but not the settings page (or the page where you can see/manage all users?

**Comment by Sweepr** [comment]
Firstly you need to logon as admin.

When logged on as admin you need to select "User & Group management", from there you click on the user "Anonymous" and remove the check from "Anonymous user - open system" and check on "Anonymous user - closed system"

That should do the trick.

**Comment by piejanssens** [comment]
Thanks, I wasn't using my admin user!
