### ISSUE TITLE
Remove hardcoded mysql port 3306

### ISSUE THREAD

**Issue by belsander** [spotweb/spotweb#321]
Hi!

Can we remove the hardcoded 3306 port for the mysql in dbeng? I currently have a setup were I'm running mariadb-server on a non-default port, so I have modified the dbeng mysql driver locally.

If I have approval I'll create a pull-request for it.

Thx!

**Comment by Sweepr** [comment]
My question, why would you deviate from the standard port?

**Comment by belsander** [comment]
People, as for myself, run multiple database servers on one machine.

**Comment by buurman** [comment]
I'm wondering when this becomes a real issue, I have a docker-container with MariaDB which I've mapped to a non default port and it's working just fine with spotweb.

In my dbsettings.inc.php file the host setting looks like this on my setup:
$dbsettings['host'] = '192.168.x.xxx**:xxxx**';

I just added the port to the host as you kan see and it just works

**Comment by mesa57** [comment]
@buurman : Thanks. Closing this issue.
