### ISSUE TITLE
Error while connecting to server (server did not respond)

### ISSUE THREAD

**Issue by vpieper** [spotweb/spotweb#327]
I get this error, no encryption port 119 :

/usr/bin/php5 retrieve.php --force --debug

Last retrieve at Wed 08 Nov 2017 12:24:33 PM CET
Retrieving new Spots from server newszilla-ipv6.xs4all.nl...
SpotWeb v0.68.28.32 on PHP v5.6.30-0+deb8u1 crashed

Fatal error occured while connecting to the newsserver:
  (-1) Error while connecting to server (server did not respond) [response: ""] [response: ""]

#0 /home/vincent/www/spotweb/lib/services/Nntp/Services_Nntp_Engine.php(120): Services_Nntp_Engine->connect()
#1 /home/vincent/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(112): Services_Nntp_Engine->selectGroup('free.pt')
#2 /home/vincent/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(280): Services_Retriever_Base->connect(Array)
#3 /home/vincent/www/spotweb/retrieve.php(145): Services_Retriever_Base->perform()
#4 {main}

Finished retrieving spots.

I can however connect to the server:

telnet newszilla-ipv6.xs4all.nl 119
Trying 2001:888:0:18::119...
Connected to newszilla-ipv6.xs4all.nl.
Escape character is '^]'.
201 newszilla.xs4all.nl NNRP Service Ready (dreader37) (no posting)

What is going wrong?

New install, with old database and ran upgrade-db.php

**Comment by mesa57** [comment]
Try a wireshark trace to see what is happening.

**Comment by mesa57** [comment]
Btw. I see a 201 - posting not allowed. That could be the cause.

**Comment by vpieper** [comment]
Hi, you're right but it is a read only server. However, Sabnzbd can still connect and download from it. Same host.

I tried the ip address and /etc/hosts with same result. It started happeng after a git pull yesterday. Before that the spotweb install ran for months.

**Comment by mesa57** [comment]
Please revert to the previous version. The issue is in vendor package pear/NET_nntp
Before that we used a fork of a very old version, which creates problems when creating spots.
I will revert to the 'old' fork and try to solve the problem there. 
Until that time, please use the previous release (as you are not creating spots anyway).

**Comment by vpieper** [comment]
Can you help me getting the tag of that version and how to clone to my host?

**Comment by mesa57** [comment]
Just reverted master.

**Comment by vpieper** [comment]
Closed and thanks
