### ISSUE TITLE
External Blacklist (still around?)

### ISSUE THREAD

**Issue by kwamtum2** [Spotweb/Spotweb#33]
This was more of a request or question, i know in the very past there was an external blacklist. Are they still around? Or how can i add one if i find an external blacklist?

**Comment by Sweepr** [comment]
You can add them in your database:

<a href='http://postimg.org/image/jxn4lr2hf/' target='_blank'><img src='http://s13.postimg.org/jxn4lr2hf/Black.jpg' border='0' alt="Black" /></a>

**Comment by Wally73** [comment]
do you know in which format the txt has to be? with the long keys or the
short ones?

**Comment by Sweepr** [comment]
Not sure what you mean , could you be more specific?

**Comment by Wally73** [comment]
spotnet uses the long key format like

http://gyazo.com/643b2903243dce331a4fae8e90fcd856

while spotnetimprover uses the short format 

http://gyazo.com/fe7e5b6b8b98c3b2d974bd1bdd87852f

**Comment by Sweepr** [comment]
Aha, i understannd.. you mean the poster ID.. that has to be the short ID.

**Comment by Wally73** [comment]
ah yeah the poster ID ;)

do they need to be one id on one line or like it is on the 2nd image?

**Comment by Sweepr** [comment]
One line per ID
Like so:

xxxxx
aaaaa
bbbbb
ccccc

**Comment by Wally73** [comment]
ok thx then i have to edit some ;)

**Comment by nivong** [comment]
same issue with new links (hello google users)
https://github.com/spotweb/spotweb/issues/68

**Comment by Wally73** [comment]
the links which i have given work

**Comment by Wally73** [comment]
blacklist url        http://jijhaatmij.hopto.me/blacklist.txt 
whitelist url        http://jijhaatmij.hopto.me/whitelist.txt

for those who want to use mine ;)
