### ISSUE TITLE
No spots shown older then last update

### ISSUE THREAD

**Issue by ikkeenjij36** [spotweb/spotweb#331]
As title,i can't see anymore spots then the last update,before when i scrolled dowwn a get a new page with older posts but nog go aftger fresh instalation on syno dsm 6.1.4
It works nonetheless and retrieves spots by ssh.

**Comment by mesa57** [comment]
So, if you retrieve spots with retrieve.php in an putty (or else) session, it works ok ?

**Comment by ikkeenjij36** [comment]
Yes it did but now i get all sort of weird faults in my installation evrytime i reset it up
I retry and retry but no go evrytime something missing or worng.
I run it on a synology with dsm 6.1.4
Installation goes wel but after create system i get a page with login,after i try to login with user and pw it says incorrect ?
Ow help its all messed up now
``

**Comment by mesa57** [comment]
You're database is probably Mariadb 5 instead of 10 (dsm installs both seperate).
You can uninstall the package and reinstall it.
If you want to cleanup the database use phpmyadmin.
If you want to preserve the database, first save dbsettings.php and copy that after reinstalling the package to the original location. Remember : users / passwords are stored in the database.

**Comment by ikkeenjij36** [comment]
Ok tied to run it on db5 and 10 bith no luck with running smoothly,wierd issue though

**Comment by ikkeenjij36** [comment]
ok after making it public i get the setting back to adjus and did so,after that i went back to the user for single system wich i made during install and for now it's running and connecting to sabnzbd.
Will keep you posted but seems somthing is wrong during install?

**Comment by mesa57** [comment]
What kind of install you did that went wrong ?

**Comment by ikkeenjij36** [comment]
Did a normal install through webpackage
Its retrieving without probs now but back to the original problem that is that i can only see limited spots instead of all that is retrieved.

**Comment by mesa57** [comment]
It is normal that you see only 24 rows. But scrolling down would retrieve the next 24.

**Comment by ikkeenjij36** [comment]
Thats my issue now,scrolling down doesnt load the next rows

**Comment by mesa57** [comment]
That issue is never reported by no one. So I doubt we find a solution.

**Comment by Sweepr** [comment]
Do you have the sidebar (filters) pinned?

There is an pin icon next to the sidebar on the left.

**Comment by Sweepr** [comment]
You coul raise the amount of spots on the overview page to 50 and see if the scroll function will work?

**Comment by ikkeenjij36** [comment]
Tried bith solutions @Sweepr but no luck,i have a scrollbar on the right sidebut i can't scroll.
Also still busy with a retrieve i started last night

**Comment by mesa57** [comment]
Retrieve always starts with the oldest spots.

**Comment by ikkeenjij36** [comment]
Ok thats no prob then but still can't scroll to next page and when i want to edit settings i have to do it with public user
Don't know if you have the time to solve this with me in direct session?

**Comment by mesa57** [comment]
Could you execute this query (phpmyadmin spotweb database) : ```


SELECT s.id AS id,
												s.messageid AS messageid,
												s.category AS category,
												s.poster AS poster,
												l.download as downloadstamp, 
												l.watch as watchstamp,
												l.seen AS seenstamp,
												s.subcata AS subcata,
												s.subcatb AS subcatb,
												s.subcatc AS subcatc,
												s.subcatd AS subcatd,
												s.subcatz AS subcatz,
												s.title AS title,
												s.tag AS tag,
												s.stamp AS stamp,
												s.moderated AS moderated,
												s.filesize AS filesize,
												s.spotrating AS rating,
												s.commentcount AS commentcount,
												s.reportcount AS reportcount,
												s.spotterid AS spotterid,
 												s.editstamp AS editstamp,
 												s.editor AS editor,
												f.verified AS verified,
												COALESCE(bl.idtype, wl.idtype, gwl.idtype) AS idtype
												
									 FROM spots AS s  LEFT JOIN spotstatelist AS l FORCE INDEX FOR JOIN (idx_spotstatelist_1) ON ((s.messageid = l.messageid) AND (l.ouruserid = 3)) 
									 LEFT JOIN spotsfull AS f FORCE INDEX FOR JOIN (idx_spotsfull_1) ON (s.messageid = f.messageid)  
									 LEFT JOIN spotteridblacklist as bl FORCE INDEX FOR JOIN (idx_spotteridblacklist_1) ON ((bl.spotterid = s.spotterid) AND ((bl.ouruserid = 3) OR (bl.ouruserid = -1)) AND (bl.idtype = 1))
									 LEFT JOIN spotteridblacklist AS wl FORCE INDEX FOR JOIN (idx_spotteridblacklist_1) ON ((wl.spotterid = s.spotterid) AND ((wl.ouruserid = 3) AND (wl.idtype = 2)))
									 LEFT JOIN spotteridblacklist AS gwl FORCE INDEX FOR JOIN (idx_spotteridblacklist_1) ON ((gwl.spotterid = s.spotterid) AND ((gwl.ouruserid = -1) AND (gwl.idtype = 2))) 
  WHERE (bl.spotterid IS NULL)  AND (NOT ((s.Category = 0) AND (s.subcatz = 'z3|')))
									 ORDER BY s.reversestamp ASC LIMIT 26 OFFSET 25
```

**Comment by ikkeenjij36** [comment]
You lost me(sorry)where do i put this in?
I am in php and db spotweb

**Comment by mesa57** [comment]
Haha, what about phpmyadmin ? You can execute sql there ,,,

**Comment by ikkeenjij36** [comment]
Yes of course but which command do i have to put in there?
Paste and copy doesn't work

**Comment by mesa57** [comment]
Copy / paste should work

**Comment by ikkeenjij36** [comment]
And then all the text you put in ?

**Comment by mesa57** [comment]
Yes, I know it is a big query, but it is exactly what spotweb executes when you page down.

**Comment by ikkeenjij36** [comment]
Ok wil try it tonight when i'm home and will report back to you

**Comment by ikkeenjij36** [comment]
Tried to copy and paste but that/s a no go in phpadmin

**Comment by Sweepr** [comment]
![untitled](https://user-images.githubusercontent.com/2857865/32855538-4506a4ec-ca42-11e7-8653-ba713ff109b0.jpg)

Working just fine here.

**Comment by ikkeenjij36** [comment]
Well the db is just fine,over 4 gb big but just not scrolling in the web page

**Comment by Sweepr** [comment]
Could you perhaps post a screenshot of your browsers view when on spotweb's main page?

**Comment by ikkeenjij36** [comment]
[IMG]http://i67.tinypic.com/2ylp8i9.png[/IMG]
Here you go

**Comment by Sweepr** [comment]
What happens when you click on the left or right button? does it go to the left go to previous and the right to the next page?

![untitled](https://user-images.githubusercontent.com/2857865/32856588-843cdd72-ca45-11e7-969e-d23a42e3f03b.png)

And does the following work when you manually copy/paste this in your browser?

192.168.0.184/spotweb/?direction=next&pagenr=1&search[tree]=
192.168.0.184/spotweb/?direction=next&pagenr=2&search[tree]=
192.168.0.184/spotweb/?direction=next&pagenr=3&search[tree]=

**Comment by ikkeenjij36** [comment]
previous en next button works
The other ones i get a 505 page back

**Comment by Sweepr** [comment]
Can you press F12 in the browser and then F5, and show me that screenshot?

If that looks fine then there could be a problem with the Javascript on the Synology, wouldn't be the first and last time they decided to move around things which causes thing to go bump.

**Comment by Sweepr** [comment]
Any chance you could try a different browser?

**Comment by mesa57** [comment]
If there is a problem with Javascript it is not on the (synology) server, but on the client browser.

**Comment by ikkeenjij36** [comment]
![myscreenhunter](https://user-images.githubusercontent.com/3373819/32857617-a9c2868e-ca48-11e7-8c3e-7fb4d7716f17.png)
Here it is

**Comment by ikkeenjij36** [comment]
In ie it.s working so it's a problem with chrome

**Comment by mesa57** [comment]
Btw. the change for infinite scroll has been reverted, due to problems it gave with changing settings.
You did not answer my question. So what is you're screen resolution ?

**Comment by ikkeenjij36** [comment]
resolution is 1600x900 and javascript is enabled

**Comment by Sweepr** [comment]
Yes, that's right, since it's working in IE, there's something wrong with the Chrome for Windows 10, On my machine with Windows 7 here Chrome is working fine.

**Comment by ikkeenjij36** [comment]
Ok i have win10 and not working though,maybe there are more users with this prob on chrome.

**Comment by mesa57** [comment]
Chrome version : Versie 62.0.3202.94 (Officiële build) (64-bits) on Windows 10 creator (all updates done) : 
No problem when scrolling.

**Comment by ikkeenjij36** [comment]
Well strange its not working for me then

**Comment by ikkeenjij36** [comment]
Well strange its not working for me then

**Comment by mesa57** [comment]
Windows 10 pro (not creator) with latest chrome : no problem
So for me totally not reproducable.

**Comment by ikkeenjij36** [comment]
@ mesa57 and @sweepr thank you for your help but i resolved this by completely removing aal and reinstalling spotweb.
Got another small issue but nothing major and maybe opening another issue around this.
This can be closed.
