### ISSUE TITLE
NZBget download icon being added repeatedly on Chrome

### ISSUE THREAD

**Issue by klara31** [spotweb/spotweb#332]
Using Chrome on Windows 10, I am getting double (or sometimes even triple) download icons for NZBget. Please see the picture below. On the same PC using Edge, this problem does not occur.

![knipsel](https://user-images.githubusercontent.com/1309136/32687869-04532cce-c6c6-11e7-9f83-b7e1df7179ea.PNG)

**Comment by mesa57** [comment]
Although I mist admit the chrome look on a small window isn't the nicest, this problem is not reproducable with me (desktop chrome w10 creator, nzbget recent version of spotweb) : 

![2017-11-11_2121](https://user-images.githubusercontent.com/6350469/32693181-bade5e4a-c726-11e7-80df-4721ef69b04b.png)

**Comment by klara31** [comment]
I just checked: my MacBook with OSX 10.13.1 running Chrome has the same issue. Running Safari on the same machine, it is not a problem.So if it is not reproducible, what is causing this issue here?! These are my NZB settings, I already tried replacing the IP with localhost, same result: Please advice Op 11 nov. 2017, om 21:24 heeft mesa57 <notifications@github.com> het volgende geschreven:Although I mist admit the chrome look on a small window isn't the nicest, this problem is not reproducable with me (desktop chrome w10 creator, nzbget recent version of spotweb) :—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by mesa57** [comment]
Did you install the latest version of spotweb ? Which template are you using in you're settings ?

**Comment by klara31** [comment]
I have just reinstalled spotweb completely from scratch: dropped the database and dropped the folder in NGINX.
All settings are default, except for news server. Same result...

**Comment by mesa57** [comment]
Are you using https ?

**Comment by klara31** [comment]
No, just clean http

**Comment by mesa57** [comment]
Then I am out of options, @Sweepr : any idea ?

**Comment by Sweepr** [comment]
Did you try clearing the cache?

https://support.google.com/accounts/answer/32050?co=GENIE.Platform%3DDesktop&hl=en

    On your computer, open Chrome.
    On your browser toolbar, click More Moreand then More Tools and then Clear Browsing Data.
    In the "Clear browsing data" box, click the checkboxes for Cookies and other site data and Cached images and files.
    Use the menu at the top to select the amount of data that you want to delete. Choose beginning of time to delete everything. Note: This option does not appear on all devices. 
    Click Clear browsing data.

**Comment by mesa57** [comment]
Any errors / warnings in the NGINX log ?

**Comment by klara31** [comment]
I have cleared cache on Chrome, same result. It occurs on more than one Chrome station, so to me it looks like something with Spotweb (or nginx?)?

The NGINX error log is empty, access log has the following:
`192.168.10.107 - - [12/Nov/2017:20:08:20 +0100] "GET /spotweb/ HTTP/1.1" 200 12208 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
192.168.10.107 - - [12/Nov/2017:20:08:20 +0100] "GET /spotweb/?page=statics&type=ico&mod=1510482764 HTTP/1.1" 200 1407 "http://app-server/spotweb/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
192.168.10.107 - - [12/Nov/2017:20:08:22 +0100] "GET /spotweb/?page=getimage&messageid=UmrR5bwOkfEfIAIWgTess@spot.net&image[height]=260&image[width]=130 HTTP/1.1" 200 31262 "http://app-server/spotweb/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"`

**Comment by klara31** [comment]
That's weird... I just found out an interessting difference, which I hope may point the DEV guys in the right direction for this issue.

The problem still exists when opening spotweb on a (recent) Chrome browser on Windows 10. However, when I open the site on the same browser, but now only within an Incognito tab, the site works normally!
