### ISSUE TITLE
A few non-translated strings

### ISSUE THREAD

**Issue by LeeThompson** [spotweb/spotweb#336]
In the filter box there are a few strings that appear in Dutch.

## **Issues:**

`templates\we1rdo\js\scripts.js:`

Tussen .. en  (Between .. and) is hard-coded in Dutch at lines 1392 and 1421.

`templates\we1rdo\includes\filters.inc.php:`

The string "Sorteren op:" (Sort by:) is hard-coded in Dutch at line 188.

### filters.inc.php changes:

`templates\we1rdo\includes\filters.inc.php`

**188:**  `<h4>Sorteren op:</h4>`

_Should be:_
**188:**  `<h4><?php echo _('Sort by:'); ?></h4>`

### scripts.js changes:

`templates\we1rdo\js\scripts.js:`

Unfortunately the echo trick and have php localize it is not an option in .js, however, the rest of scripts.js has English strings so:

**1392:** `$( "#human-filesize" ).text( "Tussen " + format_size( parseInt($( "#min-filesize").val().substring("filesize:>:DEF:".length)) ) + " en " + format_size( parseInt($( "#max-filesize").val().substring("filesize:>:DEF:".length) )) );`

**1421:** `$( "#human-filesize" ).text( "Tussen " + format_size( parseInt($( "#min-filesize").val().substring("filesize:>:DEF:".length)) ) + " en " + format_size( parseInt($( "#max-filesize").val().substring("filesize:>:DEF:".length) )) );`

_Should be:_
(NOTE: Technically "en" translates more as "in" but that doesn't work properly in English.)

**1392:** `$( "#human-filesize" ).text( "Between" + format_size( parseInt($( "#min-filesize").val().substring("filesize:>:DEF:".length)) ) + " and " + format_size( parseInt($( "#max-filesize").val().substring("filesize:>:DEF:".length) )) );`

**1421:** `$( "#human-filesize" ).text( "Between" + format_size( parseInt($( "#min-filesize").val().substring("filesize:>:DEF:".length)) ) + " and " + format_size( parseInt($( "#max-filesize").val().substring("filesize:>:DEF:".length) )) );`

**Comment by mesa57** [comment]
See develop branche
