### ISSUE TITLE
GUI slow after the last update

### ISSUE THREAD

**Issue by Burner1977** [Spotweb/Spotweb#34]
Hello,

after the latest changes I have issues with a slow non responsive GUI. In my settings I have set to show 250 posts per page. When I scroll down and the GUI has to prepare the next 250 posts the GUI hangs. Results show after 30 seconds but before I can scroll again more then a minute is passed. 
I have tested this in IE 11, Chrome and Firefox and they all react the same. Normally I never had any issues with this. 
When I switch back to show 50 posts per page it is doable. Any thoughts what the issue can be? 
Thanks in advance for the support.
Cheers
Burner1977

**Comment by int3nz0r** [comment]
I'm having similar issues like this.

**Comment by kooimens** [comment]
same here

**Comment by Sweepr** [comment]
Running a query like OPTIMIZE TABLE `commentsxover` , `spotstatelist` , `nntp` , `spots` , `spotsfull`; also makes the database a bit faster.

**Comment by Sweepr** [comment]
https://github.com/Spotweb/Spotweb/wiki/Performance-tips

**Comment by dsadsdadsadsadsds** [comment]
Disable image preview on the spotlist as it apparently retrieves all images of all spots visible on the page. Especially if you do not have 'full' retrieval enabled, it will be severely slow.

**Comment by kooimens** [comment]
Disabling the image preview did the trick!

**Comment by Burner1977** [comment]
Can you give me a hint where the option is. I can't seem to find it.

Thx

**Comment by Sweepr** [comment]
/templates/we1rdo/spots.inc.php

Change line 115:

$catMap['image'] = '<center><br><img src="?page=getimage&messageid='.$spot['messageid'].'&image[height]=260&image[width]=130" height="175px" width="auto"></center>';

 into:

# $catMap['image'] = '<center><br><img src="?page=getimage&messageid='.$spot['messageid'].'&image[height]=260&image[width]=130" height="175px" width="auto"></center>';

**Comment by kooimens** [comment]
Or:
Preferences / General `Show subcats on mouseover in spots list`

**Comment by kooimens** [comment]
@Sweepr isn't it better to disable the image preview by default? I think many users are experiencing problems with it, because most of them will disable `retrieve full spots`.

**Comment by Sweepr** [comment]
@kooimens, effective, but no subcats ;-(

**Comment by kooimens** [comment]
You're right. Would be useful to have the ability to set them both. One option to enable/disable subcat and one to enable/disable the image preview.

**Comment by Sweepr** [comment]
@kooimens, Maybe you could ask for a feature request.

**Comment by Burner1977** [comment]
Jip found it. thanks for the tip.

Case closed
