### ISSUE TITLE
New install problems -SpotTemplateHelper

### ISSUE THREAD

**Issue by hippytyre** [spotweb/spotweb#340]
Hello,

I've just installed spotweb for the first time and I'm getting errors, could someone help me out? 

Apache/2.4.25 (Raspbian)
PHP Version 7.0.19-1
mysql  Ver 15.1 Distrib 10.1.23-MariaDB

I ran the installer and everything seemed to install ok but I get the following errors. retrieve.php seems to work fine.

`Fatal error: Uncaught Error: Class 'SpotTemplateHelper_' not found in /var/www/html/spotweb/lib/page/SpotPage_Abs.php:94 Stack trace: #0 /var/www/html/spotweb/lib/page/SpotPage_Abs.php(40): SpotPage_Abs->getTplHelper(Array) #1 /var/www/html/spotweb/lib/page/SpotPage_index.php(9): SpotPage_Abs->__construct(Object(Dao_Mysql_Factory), Object(Services_Settings_Container), Array) #2 /var/www/html/spotweb/index.php(377): SpotPage_index->__construct(Object(Dao_Mysql_Factory), Object(Services_Settings_Container), Array, Array) #3 {main} thrown in /var/www/html/spotweb/lib/page/SpotPage_Abs.php on line 94`

Thanks

Callum

**Comment by Sweepr** [comment]
Seems like a file is missing or corrupted.

I suggested a re-install.

**Comment by hippytyre** [comment]
Thanks, I reinstalled it again and left it as public by mistake, everything seemed to work so I deleted the dbsettings.inc.php file and tried to reinstall it as a single user and I get the errors again. Would it be ok to run it as a public one? It'll only ever be me using it.

**Comment by hippytyre** [comment]
I just tried another install and this time it installed correctly as a single user. I think I possibly had some directory permissions set incorrectly. Thanks for the help sweeper.
