### ISSUE TITLE
Scheduled Task on Synology NAS fails

### ISSUE THREAD

**Issue by thyeestes** [spotweb/spotweb#341]
I created a scheduled task to update Spotweb every hour, but this doesn't run successfully.

I get these errors:

SpotWeb v0.68.29.32 on PHP v5.6.31 crashed

Fatal error occured retrieving reports:
  Permission denied [21] for objectid []

#0 {main}

Notice: Undefined variable: retriever in /volume1/web/spotweb/retrieve.php on line 304

Fatal error: Call to a member function quit() on null in /volume1/web/spotweb/retrieve.php on line 304

**Comment by mesa57** [comment]
In taskplanner try : 

`sudo -i /usr/local/bin/php56 /volume1/web/spotweb/retrieve.php`

**Comment by thyeestes** [comment]
unfortunately that doesn't work. Sorry I'm quite new to Linux and a Synology NAS :-(

Task: Spotweb update
Start time: Fri, 24 Nov 2017 22:11:59 GMT Stop time: Fri, 24 Nov 2017 22:12:00 GMT Current status: 0 Standard output/error:
sudo: unable to change directory to /root: No such file or directory
sudo: unable to execute /bin/ash: No such file or directory

**Comment by mesa57** [comment]
As this is an Synology specific problem I advise you to post you're problem on the (dutch) synology forum : 
https://www.synology-forum.nl/spotweb/

**Comment by Sweepr** [comment]
It's just like it say's "Permission denied [21] for objectid []"  the taskscheduler is probably running as user which doesn't have to correct permission to run the php script.

![untitled](https://user-images.githubusercontent.com/2857865/33229900-cc9e0844-d1d8-11e7-8171-333f5cc3ccbc.jpg)

Check if the user is set correctly.

**Comment by thyeestes** [comment]
Thanks all. I'll post my question in the forum.

It seems like I screwed my NAS config so I'll start from scratch

**Comment by mesa57** [comment]
@Sweepr : did not know you where a synology expert 😉

**Comment by Sweepr** [comment]
@mesa57, I just happen to own a synology myself. ;-)

**Comment by mesa57** [comment]
Can this issue being closed ?

**Comment by thyeestes** [comment]
Yes no problem
