### ISSUE TITLE
Searching on spotterID does not work anymore

### ISSUE THREAD

**Issue by aroundmyroom** [spotweb/spotweb#342]
When adding a search for spotterID (create tag) or by pressing the link in a spot 

this URL does not work anymore:

http://mydomain.lan/?search[tree]=&search[value][]=SpotterID:=:YrBUBg&sortby=stamp&sortdir=DESC

When searching on spottername it is ok, but the name is not used when you save a search on the tag for spotterID

**Comment by mesa57** [comment]
Which version of spotweb are you using ?

**Comment by mesa57** [comment]
Can you please check out the develop branch and test the bugfix ?

**Comment by aroundmyroom** [comment]
did a checkout on the develop branch 
git checkout develop
and .. 
for me its fixed
thanks !

**Comment by mesa57** [comment]
Ok, going to deploy to master.
