### ISSUE TITLE
Possibility to only receive categories that matter

### ISSUE THREAD

**Issue by Archcry** [spotweb/spotweb#345]
Is it possible to exclude categories during the retrieving of spots? I have certain categories I am not interested in.

**Comment by mesa57** [comment]
As you can filter on category's as a work around, this would be an enhancement.

**Comment by Archcry** [comment]
Yes indeed, but it would be nice to not receive the spots at all, this saves time, bandwidth and database space.

**Comment by mesa57** [comment]
Only database space. The spots have to be read anyway.

**Comment by Archcry** [comment]
Ah, I would still like that though, do you think this is easy or difficult to implement? I could take a look at it myself but you'd have to point me in the right direction file wise.

**Comment by mesa57** [comment]
I indeed have no spare time to spent on enhancements.
The most difficult part would be : how to specify the filters for the category's and make that persistent in the database.
Second is using that data when retrieving spots, but that would be more simple.
Keep in mind thow that spotweb retrieves ALL comments regardless of spots being present in the database or not. Comments make up 90% of the database. So without additional comments filtering, you would not gain very much.

**Comment by Sweepr** [comment]
The only way to achieve this, would be by creating your own filterset, and depending on the categories you want you could also choose to set the retention low, also you could choose for unchecking the retrieval of comments/full comments/full spots and reports etc, except for that there isn't much more to gain.

Also i don't see the point, for example my install currently has 2 years of spots backlog on all categories:

Rows:  | ~2,986,692 | Size: | 1.1 GiB

**Comment by muis** [comment]
In the past, many NNTP servers supported commands (like XPAT) for wildcard searching in headers server-side. This can be (mis)used to filter on categories in the From: field, without retrieving them first.

But because this puts a strain on the server CPU, and bandwidth was much cheaper than CPU time, most usenet providers disabled it to save costs..

**Comment by Archcry** [comment]
Well that sure seems like a lot of hassle, maybe it's better to just leave it as is.

**Comment by mesa57** [comment]
One way to do this would be : 
- Ability to specify a filtername to be used when retrieving spots
- During retrieve spotweb inserts ALL spots from a chunk in the database
- Then the filter the the inserted spots and delete all which are found

Anyway the database would not shrink much as comments are still all retrieved.

**Comment by Sweepr** [comment]
This van be closed , no longer relevant.
