### ISSUE TITLE
Newznab API not returning results if season or ep are used

### ISSUE THREAD

**Issue by wijmaar** [spotweb/spotweb#349]
The newznab API of my spotweb installation doesn't return any results if I use the season or ep parameter. For example:

http://localhost/spotweb/api?t=tvsearch&apikey=...&maxage=3350&cat=5000%2C5030%2C5040%2C5050&q=ShowTitle&limit=100&offset=0 -> works perfectly fine and loads in seconds

http://localhost/spotweb/api?t=tvsearch&apikey=...&season=6&maxage=3350&cat=5000%2C5030%2C5040%2C5050&q=ShowTitle&limit=100&offset=0&ep=5 -> processing time is 5min+

This causes SickRage to timeout on any Spotweb search.

**Comment by mesa57** [comment]
Yes, that's correct. Unless you use the notag=1 option added to the API call the query will be pretty inefficient.

**Comment by mesa57** [comment]
Please try the develop branch.

**Comment by wijmaar** [comment]
Thanks! Using development branch solved the issue!
