### ISSUE TITLE
Spotweb error on opening all of a sudden

### ISSUE THREAD

**Issue by heula** [spotweb/spotweb#352]
Using Sickrage with spotweb and since yesterday I get this error when I open my Spotweb page. Nothing is changed on my hand so I wonder why I get error all of a sudden?

Tried to setup to the spotweb installation again with "http://127.0.0.1/spotweb/install.php" but no luck so far.

Notice: Undefined index: userid in C:\xampp\htdocs\spotweb\lib\SpotSecurity.php on line 140

Notice: Undefined index: prefs in C:\xampp\htdocs\spotweb\lib\services\User\Services_User_Authentication.php on line 138

Notice: Undefined index: userid in C:\xampp\htdocs\spotweb\lib\services\User\Services_User_Authentication.php on line 70

Notice: Undefined index: prefs in C:\xampp\htdocs\spotweb\index.php on line 62

Notice: Undefined index: prefs in C:\xampp\htdocs\spotweb\index.php on line 63

Notice: Undefined index: userid in C:\xampp\htdocs\spotweb\index.php on line 72

Notice: Undefined index: userid in C:\xampp\htdocs\spotweb\index.php on line 371

Fatal error: Uncaught Error: Class 'SpotTemplateHelper_' not found in C:\xampp\htdocs\spotweb\lib\page\SpotPage_Abs.php:94 Stack trace: #0 C:\xampp\htdocs\spotweb\lib\page\SpotPage_Abs.php(40): SpotPage_Abs->getTplHelper(Array) #1 C:\xampp\htdocs\spotweb\lib\page\SpotPage_index.php(9): SpotPage_Abs->__construct(Object(Dao_Mysql_Factory), Object(Services_Settings_Container), Array) #2 C:\xampp\htdocs\spotweb\index.php(377): SpotPage_index->__construct(Object(Dao_Mysql_Factory), Object(Services_Settings_Container), Array, Array) #3 {main} thrown in C:\xampp\htdocs\spotweb\lib\page\SpotPage_Abs.php on line 94

Thanks.

**Comment by mesa57** [comment]
Looks like you're installation and/or database is corrupted.
Best is to reinstall spotweb again (delete database from mysql, download spotweb again) and reload you're database.

**Comment by heula** [comment]
Thanks, did that and all working fine again.
Thanks.
