### ISSUE TITLE
ERROR:  duplicate key value violates unique constraint "idx_cache_1"

### ISSUE THREAD

**Issue by digrouz** [spotweb/spotweb#357]
Hello,

I upgraded my SpotWeb installation after a while and I'm now getting this when I run the retrieve.php script. I running on Postgresql 9.6

Any Idea how to fix this ?

```
SpotWeb v0.68.29.32 on PHP v7.1.15 crashed

Fatal error occured retrieving reports:
  23505: 7: ERROR:  duplicate key value violates unique constraint "idx_cache_1"
DETAIL:  Key (resourceid, cachetype)=(spotspercategory., 4) already exists.



#0 /www/spotweb/lib/dao/Base/Dao_Base_Cache.php(364): dbeng_pdo->exec('UPDATE cache SE...', Array)
#1 /www/spotweb/lib/dao/Base/Dao_Base_Cache.php(554): Dao_Base_Cache->saveCache('spotspercategor...', 4, false, 0, 'a:4:{i:2;d:7406...')
#2 /www/spotweb/lib/services/Providers/Services_Providers_Statistics.php(214): Dao_Base_Cache->saveStatsCache('spotspercategor...', Array)
#3 /www/spotweb/lib/services/Providers/Services_Providers_Statistics.php(105): Services_Providers_Statistics->getStatisticsData('spotspercategor...', '')
#4 /www/spotweb/lib/services/Providers/Services_Providers_Statistics.php(60): Services_Providers_Statistics->createStatsPerCategory('')
#5 /www/spotweb/lib/services/Providers/Services_Providers_Statistics.php(36): Services_Providers_Statistics->renderStatImage('spotspercategor...', '')
#6 /www/spotweb/retrieve.php(250): Services_Providers_Statistics->createAllStatistics()
#7 {main}

Finished retrieving reports.
```

Kind Regards

**Comment by Sweepr** [comment]
You could try running this script:

**Comment by Sweepr** [comment]
Otherwise truncate the cache table's and empty the ondisk cache folder, then retrieve again.

**Comment by digrouz** [comment]
here is the output
`Validating cache content, items 0 to 1000
  Trying to fetch #2228 for spotspercategory.month again, 
  Trying to fetch #2278 for XpwDBTQKaSEyebwWQsS6k@spot.net again, retrieved image as 2375

  Trying to fetch #2356 for 1wC2burit1cd16gWgTac8@spot.net again, retrieved image as 2376

  Trying to fetch #2337 for oHmzlXf07loT4OhWgpEDA@spot.net again, retrieved image as 2377
, done. 
Validating cache content, items 1000 to 2000, done. 
Validating cache content, items 2000 to 3000, done. `

Still the same issue ...

**Comment by digrouz** [comment]
empty the table cache and the filesystem cache did the trick, thanks!
