### ISSUE TITLE
Blank screen on install.php: PHP error

### ISSUE THREAD

**Issue by demirdag** [Spotweb/Spotweb#36]
Hello!

I'm experiencing a problem with my new setup of Spotweb on a OpenSuse 13.2 system.

I clone the project from Git and then browse to [server]/spotweb/install.php but nothing happens. I get a blank screen. In the apache error_log file I get the following:

 [php5:error] [pid 9487] [client ::1:49948] PHP Notice:  Undefined offset: 20 in /srv/www/htdocs/spotweb/vendor/phpseclib/Math/BigInteger.php on line 3491

I can't seem to get it working. I've done this setup a couple of times already on other systems but now it doesn't seem to work anymore. 

Can you help me?

**Comment by demirdag** [comment]
nobody cares?

**Comment by Sweepr** [comment]
Enter the full path to PHP for the script to parse properly. PHP not being in your PATH may end up getting blank screens during the install process.

E.g.

Code: Select all
    /mnt/ext/opt/apache/bin/php -C /php.ini /share/Qweb/spotweb/upgrade-db.php

Code: Select all
    /mnt/ext/opt/apache/bin/php -C /php.ini /share/Qweb/spotweb/retrieve.php --force

**Comment by workmonitored** [comment]
Download latest release 0.3.1 from phpseclib and replace directory with it. That fixed the problem for me.

**Comment by Thermionix** [comment]
This is also still an issue - fixed also by re-extracting phpseclib from sourceforge
