### ISSUE TITLE
Back to mainview font

### ISSUE THREAD

**Issue by vpieper** [spotweb/spotweb#360]
The back to mainview button used to look like this in Firefox:

![afbeelding](https://user-images.githubusercontent.com/17639498/38410537-20e25676-3985-11e8-9823-79fb6202d468.png)

It now has this font:

![afbeelding](https://user-images.githubusercontent.com/17639498/38410587-42558ef4-3985-11e8-9295-98b39a2c79e6.png)

Ugly in my opinion. Must be a font setting somewhere?

**Comment by sinistra** [comment]
Looks like a browser issue. Which one are
you using?

**Comment by vpieper** [comment]
Firefox 59.0.2. Issue also occurs in latest Chrome. However not in latest Edge.

Check Google image search to see that others having the same issue.

**Comment by Sweepr** [comment]
https://superuser.com/questions/1118573/weird-fonts-rendering-on-chrome-and-firefox-windows-10

**Comment by vpieper** [comment]
Font is total different thing than cleartype

**Comment by Sweepr** [comment]
Is that so?

https://en.m.wikipedia.org/wiki/ClearType

**Comment by Sweepr** [comment]
Qoute: "Is ClearType enabled system-wide? Last I knew Windows had options for ClearType in browser that were separate (or could be enabled separately) from the system overall. No font smoothing in non-Microsoft browsers seems like this could be part of your issue. – "

**Comment by vpieper** [comment]
First, stop posting mobile sites.

Second, it is. Font is a lettertype like Arial, Times, etc. Cleartype means how fonts are rendered. Is says so in your own link.

Third I tried out switching off cleartype with same result, see second image in first post.

**Comment by Sweepr** [comment]
Tried locally one 5 different browsers , closed because not spotweb related issue.
