### ISSUE TITLE
not an issue more of a question to the devs

### ISSUE THREAD

**Issue by Hydranet** [spotweb/spotweb#361]
Hello spotweb devs,
I'm using the master git repository of spotweb, and over the past year I haven't seen many updates coming out in the past year. Is spotweb still being actively developed or should I use I start using a different branch?

**Comment by mesa57** [comment]
Spotweb is still maintained and you can best use the master branch.
Unless you want also bèta versions, then you could use the develop branch.

**Comment by Hydranet** [comment]
@mesa57 Thanks for the response. I'll stick to the master branch then, and thanks for all the time the devs  put in spotweb!
