### ISSUE TITLE
Apache/PHP 7.2 generates error / problem with search function

### ISSUE THREAD

**Issue by bastian433** [spotweb/spotweb#362]
When clicking a category, and then searching, the categories section generates a Load error! (parsererror).
When hovering the mouse over it generates the following error: SyntaxError: Unexpected Token < in JSON at position 0
The problem it causes is that it is no longer possible to select a category and then search in just that category.

The following error is generated in the apache2 log:

[Wed Apr 25 17:28:52.927046 2018] [php7:warn] [pid 15703] [client X.X.X.X:60901] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/spotweb/lib/services/Search/Services_Search_QueryParser.php on line 868, referer: https://X.X.X.X/spotweb/?page=index&search[tree]=cat0_z0_a4,cat0_z0_a6,cat0_z0_a7,cat0_z0_a8,cat0_z0_a9&search[value][]=

**Comment by mesa57** [comment]
Spotweb is not tested with php 7.2
The dev tools do not support it yet.
So I keep the bug open until the tools support it.
Meanwhile I advise you to downgrade to php 7.0

**Comment by Wally73** [comment]
spotweb works fine with php 7.1.x so use that instead of php 7.2

**Comment by mesa57** [comment]
Please checkout the develop branche, should be solved. Closing this issue. You can reopen if any problems.
