### ISSUE TITLE
Layout problem with layout when long character spotter name

### ISSUE THREAD

**Issue by joaonl** [spotweb/spotweb#364]
Hi there,

See screenshot; when the poster name has a lot of characters and the spotter is whitelisted, it breaks a part of the layout.

Can this be fixed?
![layout](https://user-images.githubusercontent.com/7014736/39396704-90cbe072-4af3-11e8-8301-fa0f5d558150.PNG)

Thanks.

**Comment by joaonl** [comment]
Fixed it by changing the style.css from 110px to

```
/* CHANGED */
table.spots td.poster a {width:115px;}
```

**Comment by mesa57** [comment]
Please change this on the develop branche so it can be tested.

**Comment by mesa57** [comment]
Tested in IE, Firefox and Chrome. Merged develop with master.
Thanks for the contribution 😄
