### ISSUE TITLE
[Sonarr search error] no q, tvmaze or rid parameter present

### ISSUE THREAD

**Issue by simkin** [spotweb/spotweb#367]
I have the following Nginx rewrite to enable newznab searching:
`rewrite /spotweb/api/?$ /spotweb/index.php?page=newznabapi;`

But get an error in the log:

http://localhost/spotweb/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=50&tvmazeid=1371&season=2: **On TVSearch no q, tvmaze or rid parameter present**

Is this fixable? Perhaps via e.g. another rewrite?

**Comment by mesa57** [comment]
Is that on a synology installation ?

**Comment by simkin** [comment]
No, Debian stretch, DEVELOP branch

**Comment by mesa57** [comment]
The rewrite in the wiki is specific for synology / dsm. May you can try the old way ?

**Comment by mesa57** [comment]
No feedback, closing issue.
