### ISSUE TITLE
[Feature request] Add Spotweb attribute

### ISSUE THREAD

**Issue by JackDandy** [spotweb/spotweb#374]
Hello again @mesa57 

As discussed in IRC, [SickGear](https://github.com/SickGear/SickGear) has enhanced Spotweb support, but it can be even better.
  
Could you add a new attribute to the **_server_** node in the response for caps ....
like a new attr named: "software_type" that is a fixed string = "Spotweb"

Sites already have custom attrs so this extra attr will be ignored by existing clients and the _server_ node is a good place for this.

There is already version number, just not the _type_ of software that is used.

Also, attr "Title" is already set fixed to 'spotweb' but a site owner can simply change that to their site name, as is normal with nn installations.

Thanks,

JD

**Comment by mesa57** [comment]
Hi JD,

The <server> tag already contains title : 
`<server title="Spotweb" image="http://192.168.2.87:82/images/spotnet.gif" url="http://192.168.2.87:82/" email="info@xxxx.nl (mesa57 mesa57)" strapline="Spotweb API Index" version="0.1"/>
`
You said (irc) that title can be changed. But in Spotweb it is hard coded, so it cannot change.
Is that usable for you ? (btw, version is also hardcoded).

**Comment by JackDandy** [comment]
Hi @mesa57 

Yeah, like I said, we appreciate that attr "title" does exist, and that it is fixed (hard-coded), and we will use that as a first check. However, if there is a dedicated attr, then the site owner is less likely to change that compared to them being more likely to change the title attr to for example "my wonderful-site.com".

So something like...  
`<server title="Spotweb" software_id="spotweb" image="http://192.168.2.87:82/images/spotnet.gif" url="http://192.168.2.87:82/" email="info@xxxx.nl (mesa57 mesa57)" strapline="Spotweb API Index" version="0.1"/>`

We will add code to test for attr `software_id` and if not exists, then test for... `if "Spotweb" in title.lower()` as a graceful fallback and to also mop up on installation that have not upgraded to the code with the suggested new attr.

**Comment by mesa57** [comment]
I will add type="Spotweb" attribute to the <server> tag.
Basicly it indicates the type of the <server>, hence the name.

**Comment by JackDandy** [comment]
The only thing i was thinking about **not** using "type" is that it may already be used

**Comment by mesa57** [comment]
Not that I know of.

**Comment by JackDandy** [comment]
my bad sorry, delete last msg

**Comment by mesa57** [comment]
The change is on the develop branch, so you can test.

**Comment by JackDandy** [comment]
Thanks @mesa57
