### ISSUE TITLE
[bug] upgrade-db.php arguments not working anymore

### ISSUE THREAD

**Issue by edv** [spotweb/spotweb#376]
When using the commandline to e.g. reset a password I always use;

`
php /app/bin/upgrade-db.php --reset-password admin
`

This is however not working anymore since this commit https://github.com/spotweb/spotweb/commit/f1087037fb8563b4958ca9718f8a18fc18e343b0#diff-25388f109a1239ccd6b4c683359ab2cc

Before this commit the parseParameters function would return the following array (when using the command above)

```
array(2) {
  [0]=>
  string(23) "/app/bin/upgrade-db.php"
  ["reset-password"]=>
  string(5) "admin"
}
```

Currently the following is returned:

```
array(3) {
  [0]=>
  string(23) "/app/bin/upgrade-db.php"
  ["reset-password"]=>
  string(23) "/app/bin/upgrade-db.php"
  [1]=>
  string(5) "admin"
}
```

Reverting only the following seems to fix the problem, but I do not run on PHP 7.2 so I have not tested that.

`
while (list($tmp, $p) = each($params)) {	
`

with

`
foreach ($params as $p) {
`

**Comment by mesa57** [comment]
the each() function is deprecated in php 7.2
But I will look into the issue.

**Comment by mesa57** [comment]
Please checkout the develop branch and test if it's now working for you.

**Comment by edv** [comment]
@mesa57 Just tested the develop branch, and it works like a charm!

**Comment by mesa57** [comment]
Ok, thank you for reporting the issue and testing the solution. 😄

**Comment by mesa57** [comment]
I think next weekend, but could be sooner.

**Comment by mesa57** [comment]
Master has been updated. Sorry for the delay.
