### ISSUE TITLE
missing settings and "update" button

### ISSUE THREAD

**Issue by shadi1989** [spotweb/spotweb#383]
Hi,

I've downloaded the spotweb-develop.zip and extracted it in my /web/ folder of my synology.
Did the installation and connected to MariaDB10 database correctly.

I mis the "Retrieve" button in the left lower corner
i mis the "Settings" and "User & group managment" buttons under Config.

Any idea how i can get them back?

**Comment by Sweepr** [comment]
Please verify you are logged in as a user with admin permission.

**Comment by shadi1989** [comment]
Solved it by:

1. Login PHPMyadmin, open database "spotweb" and table "usergroups"
2. Insert line:
ID: next available id
userid: 3
groupid: 5
prio: 4
