### ISSUE TITLE
Changed user to closed system now cant log in 

### ISSUE THREAD

**Issue by sojab0on** [spotweb/spotweb#385]
Hi i stupidly changed admin and my normal user to closed system group an unticked anonimesly group
now i cant log in any more.

How can i change this back

**Comment by Sweepr** [comment]
From the cli you can use 

php upgrade-db.php --reset-securitygroups

And 

php upgrade-db.php --reset-securitygroups

**Comment by sojab0on** [comment]
tried that but it fails with
Database schema or settings upgrade failed:
   42S22: 1054: Unknown column 'content' in 'where clause'

how to fix that error 
that error also prefents retiving spots.
H:\Web\spotweb.sojab0on.nl>C:\"Program Files\PHP\v7.0\php.exe" retrieve.php --force


SpotWeb v0.68.29.32 on PHP v7.0.21 crashed

Fatal error occured retrieving reports:
  Unknown SchemaNotUpgradedException



#0 H:\Web\spotweb.sojab0on.nl\lib\Bootstrap.php(136): CustomException->__construct()
#1 H:\Web\spotweb.sojab0on.nl\lib\Bootstrap.php(62): Bootstrap->validate(Object(Services_Settings_Base))
#2 H:\Web\spotweb.sojab0on.nl\retrieve.php(11): Bootstrap->boot()
#3 {main}

PHP Notice:  Undefined variable: retriever in H:\Web\spotweb.sojab0on.nl\retrieve.php on line 304
PHP Fatal error:  Uncaught Error: Call to a member function quit() on null in H:\Web\spotweb.sojab0on.nl\retrieve.php:304
Stack trace:
#0 {main}
  thrown in H:\Web\spotweb.sojab0on.nl\retrieve.php on line 304

**Comment by Sweepr** [comment]
Whats the output when running only. php upgrade-db.php

**Comment by sojab0on** [comment]
h:\Web\spotweb.sojab0on.nl\bin>C:\"Program Files\PHP\v7.0\php.exe" upgrade-db.php
Updating schema..(pdo_mysql)
        Validating spots(messageid)
        Validating spots(poster)
        Validating spots(title)
        Validating spots(tag)
        Validating spots(category)
        Validating spots(subcata)
        Validating spots(subcatb)
        Validating spots(subcatc)
        Validating spots(subcatd)
        Validating spots(subcatz)
        Validating spots(stamp)
        Validating spots(reversestamp)
        Validating spots(filesize)
        Validating spots(moderated)
        Validating spots(commentcount)
        Validating spots(spotrating)
        Validating spots(reportcount)
        Validating spots(spotterid)
        Validating spots(editstamp)
        Validating spots(editor)
        Validating spotsfull(messageid)
        Validating spotsfull(verified)
        Validating spotsfull(usersignature)
        Validating spotsfull(userkey)
        Validating spotsfull(xmlsignature)
        Validating spotsfull(fullxml)
        Validating usenetstate(infotype)
        Validating usenetstate(curarticlenr)
        Validating usenetstate(curmessageid)
        Validating usenetstate(lastretrieved)
        Validating usenetstate(nowrunning)
        Validating commentsxover(messageid)
        Validating commentsxover(nntpref)
        Validating commentsxover(spotrating)
        Validating commentsxover(moderated)
        Validating commentsxover(stamp)
        Validating reportsxover(messageid)
        Validating reportsxover(fromhdr)
        Validating reportsxover(keyword)
        Validating reportsxover(nntpref)
        Validating spotstatelist(messageid)
        Validating spotstatelist(ouruserid)
        Validating spotstatelist(download)
        Validating spotstatelist(watch)
        Validating spotstatelist(seen)
        Validating commentsfull(messageid)
        Validating commentsfull(fromhdr)
        Validating commentsfull(stamp)
        Validating commentsfull(usersignature)
        Validating commentsfull(userkey)
        Validating commentsfull(spotterid)
        Validating commentsfull(hashcash)
        Validating commentsfull(body)
        Validating commentsfull(verified)
        Validating commentsfull(avatar)
        Validating settings(name)
        Validating settings(value)
        Validating settings(serialized)
        Validating commentsposted(ouruserid)
        Validating commentsposted(messageid)
        Validating commentsposted(inreplyto)
        Validating commentsposted(randompart)
        Validating commentsposted(rating)
        Validating commentsposted(body)
        Validating commentsposted(stamp)
        Validating spotsposted(messageid)
        Validating spotsposted(ouruserid)
        Validating spotsposted(stamp)
        Validating spotsposted(title)
        Validating spotsposted(tag)
        Validating spotsposted(category)
        Validating spotsposted(subcats)
        Validating spotsposted(filesize)
        Validating spotsposted(fullxml)
        Validating reportsposted(ouruserid)
        Validating reportsposted(messageid)
        Validating reportsposted(inreplyto)
        Validating reportsposted(randompart)
        Validating reportsposted(body)
        Validating reportsposted(stamp)
        Validating usersettings(userid)
        Validating usersettings(privatekey)
        Validating usersettings(publickey)
        Validating usersettings(avatar)
        Validating usersettings(otherprefs)
        Validating users(username)
        Validating users(firstname)
        Validating users(passhash)
        Validating users(lastname)
        Validating users(mail)
        Validating users(apikey)
        Validating users(lastlogin)
        Validating users(lastvisit)
        Validating users(lastread)
        Validating users(lastapiusage)
        Validating users(deleted)
        Validating sessions(sessionid)
        Validating sessions(userid)
        Validating sessions(hitcount)
        Validating sessions(lasthit)
        Validating sessions(ipaddr)
        Validating sessions(devicetype)
        Validating securitygroups(name)
        Validating grouppermissions(groupid)
        Validating grouppermissions(permissionid)
        Validating grouppermissions(objectid)
        Validating grouppermissions(deny)
        Validating usergroups(userid)
        Validating usergroups(groupid)
        Validating usergroups(prio)
        Validating notifications(userid)
        Validating notifications(stamp)
        Validating notifications(objectid)
        Validating notifications(type)
        Validating notifications(title)
        Validating notifications(body)
        Validating notifications(sent)
        Validating filters(userid)
        Validating filters(filtertype)
        Validating filters(title)
        Validating filters(icon)
        Validating filters(torder)
        Validating filters(tparent)
        Validating filters(tree)
        Validating filters(valuelist)
        Validating filters(sorton)
        Validating filters(sortorder)
        Validating filters(enablenotify)
        Validating filtercounts(userid)
        Validating filtercounts(filterhash)
        Validating filtercounts(currentspotcount)
        Validating filtercounts(lastvisitspotcount)
        Validating filtercounts(lastupdate)
        Validating spotteridblacklist(spotterid)
        Validating spotteridblacklist(ouruserid)
        Validating spotteridblacklist(idtype)
        Validating spotteridblacklist(origin)
        Validating spotteridblacklist(doubled)


SpotWeb crashed

Database schema or settings upgrade failed:
   42S22: 1054: Unknown column 'content' in 'where clause'

**Comment by sojab0on** [comment]
have tried the x86 php v7.0 and 64bit version booth end with the same error

**Comment by Sweepr** [comment]
This was a working installation before?  Seems like there is an entire column missing from the database.

**Comment by sojab0on** [comment]
yes it was, until i supidly changed the securitygroups

**Comment by sojab0on** [comment]
if i delete the database and take out the db-config file and just restart the install i can recreate it right

**Comment by sojab0on** [comment]
i just did what i tought would work and that fixed it 
deleted spotweb db and db setings php file 
Tough phpmyadmin created a new sptoweb db and gave spotweg user full rights on it.

rerun install 

And run retrive script again and boom retriveing spots runs like a chrom again.
