### ISSUE TITLE
Spotweb on ubuntu 

### ISSUE THREAD

**Issue by sojab0on** [spotweb/spotweb#389]
Hi i have a new ubunt uvm on an esxi host, dowload of the package went great mv to /var/www/spotweb went fine but now if i do htp://localhost/spotweb/install.php i get 404 not found.

also tried to 127.0.0.1/spotweb/install.php

I have webmin installed, tried to create a new virtual host that uses /var/www/spotweb as document root, but even with that running i cant get to the install.php keep getting not found error.

What am i dooing worng.

By the way i am dutch so a dutch answer is also welcome.

Server specs 
4 virtual cores 
8GB ram 
150gb hard drive split in 
20gb for /
200mb /boot 
little over 40GB for /home
100gb /var 
1 gb nic witch has complete internet acess

what i tried to get to the install.php
localhost/spotweb/install.php
127.0.0.1/spotweb/install.php 
192.168.2.5/spotweb/install.php

but they al get to not found.

file is there webmin and normal nautilus sees the folder and sees the install.php
can someone help me out here want to get this working on my new webserver.

**Comment by mesa57** [comment]
Some misconfiguration of you webserver I suppose.
- Which webserver do you use ?
- Has it been enabled for PHP ?
- What is the webroot folder ?
- Do you see folders when you goto http://localhost ? (otherwise enable folder browsing on you're webserver temporary).

**Comment by sojab0on** [comment]
Apache 2 
Php modules are active version 7.2 
webroot folder /var/www/html for normal site but the guide has a flaw then because the guide say mv spotweb-spotweb-* /var/www/spotweb 

if i go to http://localhost i get the apache2 ubuntu default page fully themed 

so i only can do sudo mv spotweb to /var/www/html and test if it works from there ?

**Comment by sojab0on** [comment]
but now i have the problem that i have setup single user system and the account i created doesnt have alle te setup options. 

how do i fix that?

**Comment by mesa57** [comment]
For nzb handling see : https://github.com/spotweb/spotweb/wiki/Configuring-NZB-handling

**Comment by mesa57** [comment]
In a single user system anonymous user should be set to the custom admin use
So do not use login credentials

**Comment by sojab0on** [comment]
I have an account or do i need to soomehw change to multiuser system the nzb handeling doenst work i only can use sabnzb trough client browser other options i dont have

**Comment by mesa57** [comment]
If you logon as anonymous  (no user) you should be able to change the security group of you're account to administrator.
Please read the wiki for nzbget or sabnzbd setup.
