### ISSUE TITLE
User avatars are not displayed (spotinfoimages are displayed OK)

### ISSUE THREAD

**Issue by simkin** [spotweb/spotweb#394]
In the comment section below spots, user avatars are not rendered. When trying to resolve the image URL/download the user avatar in the browser, the browser downloads an empty file "download". I am hosting Spotweb behind an Nginx proxy. The nginx error log does not contain any errors. "spotinfoimage" posters/cover-art is displayed correctly

Anybody any idea how to fix this?

Debugger:
![image](https://user-images.githubusercontent.com/958263/45412924-35d0b080-b678-11e8-8d10-a777d9ce574a.png)

**Comment by mesa57** [comment]
If you refresh, is the avatar still not displaying ?
