### ISSUE TITLE
php upgrade-db error table commentsxover

### ISSUE THREAD

**Issue by WorkaholicGoT** [spotweb/spotweb#40]
Ik dacht even slim te zijn door mijn commentsxover table te verwijderen met als doel om deze op te ruimen (3gb groot!) en opnieuw aan te laten maken met php upgrade-db. Helaas lukt dit niet en krijg ik onderstaande error. iemand een idee wat er mis gaat?

user@webserver:~/domains/mijndomein.nl/private_html/spotweb$ php upgrade-db.php
Updating schema..(mysql)
Validating spots(messageid)
Validating spots(poster)
Validating spots(title)
Validating spots(tag)
Validating spots(category)
Validating spots(subcata)
Validating spots(subcatb)
Validating spots(subcatc)
Validating spots(subcatd)
Validating spots(subcatz)
Validating spots(stamp)
Validating spots(reversestamp)
Validating spots(filesize)
Validating spots(moderated)
Validating spots(commentcount)
Validating spots(spotrating)
Validating spots(reportcount)
Validating spots(spotterid)
Validating spots(editstamp)
Validating spots(editor)
Validating spots(collectionid)
Validating spotsfull(messageid)
Validating spotsfull(verified)
Validating spotsfull(usersignature)
Validating spotsfull(userkey)
Validating spotsfull(xmlsignature)
Validating spotsfull(fullxml)
Validating usenetstate(infotype)
Validating usenetstate(curarticlenr)
Validating usenetstate(curmessageid)
Validating usenetstate(lastretrieved)
Validating usenetstate(nowrunning)

Database schema or settings upgrade failed:
HY000: 1005: Can't create table 'spotweb.commentsxover' (errno: 150)50)

#0 /home/user/domains/mijndomein.nl/private_html/spotweb/lib/dbstruct/SpotStruct_mysql.php(254): dbeng_pdo->rawExec('CREATE TABLE co...')
#1 /home/user/domains/mijndomein.nl/private_html/spotweb/lib/dbstruct/SpotStruct_abs.php(387): SpotStruct_mysql->createTable('commentsxover', 'ascii')
#2 /home/user/domains/mijndomein.nl/private_html/spotweb/lib/services/Upgrade/Services_Upgrade_Base.php(42): SpotStruct_abs->updateSchema()
#3 /home/user/domains/mijndomein.nl/private_html/spotweb/upgrade-db.php(44): Services_Upgrade_Base->database()
#4 {main}user@webserver:~/domains/mijndomein.nl/private_html/spotweb$

**Comment by dsadsdadsadsadsds** [comment]
MySQL zuigt, het staat jou namelijk toe een tabel te droppen waar vervolgens nog foreign keys op liggen. Als je die tabel daarna aanmaakt, moet die exact overeenkomen met de structuur, maar zo werkt Spotweb niet (Spotweb bouwt tabellen incrementeel op).

Wijze lessen zijn dus:

1. Drop je tabel niet. Echt niet. Stop met je database te droppen.
2. Als je het toch doet, TRUNCATE dan je tabel ipv hem te droppen.
3. Als je hem toch gedropped hebt, wis dan de forein keys die op de andere tabellen staan (spots, commentsfull) en draai daarna upgrade-db

Maar alsjeblieft stop gewon met je tabellen te droppen :smile:

**Comment by piejanssens** [comment]
> 2\. TRUNCATE

#1701 - Cannot truncate a table referenced in a foreign key constraint (`spotweb`.`commentsfull`, CONSTRAINT `commentsfull_ibfk_1` FOREIGN KEY (`messageid`) REFERENCES `spotweb`.`commentsxover` (`messageid`))

**Comment by mesa57** [comment]
Please open a new issue if needed.
