### ISSUE TITLE
commentsxover > 5GB --> How can I reduce this?

### ISSUE THREAD

**Issue by piejanssens** [spotweb/spotweb#400]
I can live without comments. How can I reduce the size of this table safely?

**Comment by Sweepr** [comment]
Since you can live without comments, i'd suggest disabling "Retrieve comments" / "Retrieve full comments" under "Settings" -> "Retrieve"

Then truncate those table's.

**Comment by piejanssens** [comment]
Thanks

**Comment by sojab0on** [comment]
Have same isue but when i try to turncate the bale it errors with the following error 
Cannot turncate a table referenced in forgeign key CONSTRAINT
TURNCATE 'spotweb''comentsxover'

What can i do to fix that

**Comment by mesa57** [comment]
Just truncate commentsxover first.

**Comment by sojab0on** [comment]
i tried than it errors back with that error
