### ISSUE TITLE
[announcement] black/white list end of life

### ISSUE THREAD

**Issue by Wally73** [spotweb/spotweb#401]
I'm gonna stop in 14 days with the blacklist and whitelist for spotweb/spotlight (not renewing domain) 

so turn of external bl/wl lookup

**Comment by Sweepr** [comment]
We can do that, but who will update the list?

**Comment by mesa57** [comment]
Nobody, so I think the list should be removed.

**Comment by mesa57** [comment]
Black/whitelist will be replaced by spotnet 2 lists

**Comment by ArieKindicator** [comment]
Which "spotweb 2 list"?
Running retrieve.php, results in `Non-fatal: Updating black/whitelist failed, most likely unreachable!Starting to create statistics`
because the urls aren't active any more.

**Comment by mesa57** [comment]
Solved on latest devellop branch.
Closing this issue, please reopen if needed.
