### ISSUE TITLE
php timezone error on every page

### ISSUE THREAD

**Issue by hijglander** [spotweb/spotweb#402]
The following error shows after installing the latest update of DSM on a Synology NAS:

Warning: strftime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /volume1/web/spotweb/lib/SpotTemplateHelper.php on line 862

To fix I altered this function:
  function formatDate($stamp, $type) {
        date_default_timezone_set('Europe/Amsterdam');  ## The added line to fix the error.
        if (empty($stamp)) {
            return _("unknown");
        } elseif (substr($type, 0, 6) == 'force_') {
            return strftime("%a, %d-%b-%Y (%H:%M)", $stamp);
        } elseif ($this->_currentSession['user']['prefs']['date_formatting'] == 'human') {
            return $this->time_ago($stamp);
        } else {
            switch($type) {
                case 'comment'      :
                case 'spotlist'     :
                case 'lastupdate'   :
                case 'lastvisit'    :
                case 'userlist'     :
                default             : return strftime($this->_currentSession['user']['prefs']['date_formatting'], $stamp);
            } # switch
        } # else
    } # formatDate

Greetz,

Hijglander

**Comment by mesa57** [comment]
You should set you're timezone in php.ini : Europe/Amsterdam
