### ISSUE TITLE
Spotweb broken for Radarr

### ISSUE THREAD

**Issue by Groofster** [spotweb/spotweb#403]
Spotweb is no longer working for Radarr (and probably all other movie downloaders) and gives the following error in the logs:

Undefined offset: 1 in /var/www/spotweb/lib/services/MediaInformation/Services_MediaInformation_Imdb.php on line 41

Seems like IMDB has made some changes to their site breaking the code. I've been trying to come up with a fix myself but running it in docker and my limited knowledge of PHP make it hard to find one.

**Comment by mesa57** [comment]
For the time being you can set search on title instead of IMDB in you're Radarr configuration.

**Comment by mesa57** [comment]
And please look in you're radarr log which title is failing. I could not see any changes on the imdb page.

**Comment by Groofster** [comment]
I have tried it with 15 different IMDB Id's and they all fail with the same error. I tested it by directly browsing the spotweb url which is present in the Radarr error log.

The error I get is:  <error code="301" description="IMDB information returned is invalid"/>

I'm using the following docker container: jgeusebroek/spotweb  and have made sure it's on the latest spotweb commit.

Searching by title works like a charm, thanks for the tip.

**Comment by Groofster** [comment]
Hotfix checked and working. I tip my hat to you !

**Comment by mesa57** [comment]
Just wanted to ask you to test :wink

**Comment by Sweepr** [comment]
Closing, resolved.

**Comment by stefan0028** [comment]
@mesa57 maby a stupid qustion but how do i set  search on title instead of IMDB in my Radarr configuration.

**Comment by Groofster** [comment]
@stefan0028: enable advanced settings before opening the spotweb settings in Radarr

**Comment by stefan0028** [comment]
@Groofster o woow thank you i have learn something new today :)
