### ISSUE TITLE
Spotweb stopped working after latest git pull

### ISSUE THREAD

**Issue by ac3nl** [spotweb/spotweb#408]
PHP Parse error:  syntax error, unexpected '.', expecting ',' or ';' in /volume1/web/spotweb/lib/SpotDebug.php on line 17

Can’t retrieve, can’t open spot. Search works

**Comment by Sweepr** [comment]
Must be a local pronken, nothing changed in the code.

Can you revert your last pull using 'git reflog'

https://stackoverflow.com/questions/1223354/undo-git-pull-how-to-bring-repos-to-old-state

**Comment by ac3nl** [comment]
Thanks for a quick reply

Tried that, same problem so it must be a unrelated problem.
Any suggestions to fix this anyways?

Regards

**Comment by Sweepr** [comment]
It was working before?

Can you provide us some more information. OS, php version, things you recently changed prior to the issue started?

**Comment by ac3nl** [comment]
Is running on synology Ds1010+ running dsm 5.2
Php Version 5.5.33

On 2/3 i had a restore of a raid 5 crash. Volume was rebuild on 2/3
Spotweb did update on 3/3 3 times on cron.
After the git pull of 4/3 the retrieve did not work any more

**Comment by Sweepr** [comment]
Yikes, never updated since 2013? i think you will have to update your PHP version, since alot has changed since 2013, PHP 5.5.33 is really old.

I suggest updating to PHP 7.0 if possible for both CLI and Web, that should fix your issue.

**Comment by ac3nl** [comment]
There are no update packages for php7. For synology
Is the php 5.5.33 realy an issue since yesterday?

**Comment by mesa57** [comment]
Still works with php 5.6 (however that version is also deprecated)

**Comment by Sweepr** [comment]
If your previous Spotweb has been running since 2013 without any update's, and now you've pulled the latest then the code you pulled has changed too much to be able to run on your current install.

I was about to mention 5.6 altough that one is also not recommended.

**Comment by ac3nl** [comment]
What could it be the error? Database is running, i can search, but not open spots.
Retrieve gives the mentioned error. Git Is up to date it says.

What am i missing ?

**Comment by Sweepr** [comment]
You need to upgrade PHP to at least 5.6 or higher, the current release differs too to much since 2013.

Without a proper backup youare basically forced to upgrade.

**Comment by ac3nl** [comment]
Overnight? That is weird

**Comment by mesa57** [comment]
On 3 march the develop branch was merged into master with changen made already in sept. 2018

**Comment by Sweepr** [comment]
Sorry, maybe i misunderstood but you said earlier: Php Version 5.5.33
Spotweb was installed in 2013 and has worked ever since.

For my understanding,

You had a system crash, restored, spotweb was working, then you did a git pull and stopped working.

Right?

**Comment by ac3nl** [comment]
Exactly right. 
Volume crash - fixed.
Spotweb updated 3 times after that, untill the 3/3 git pull

Php version is from 2016. Os was updated while supported.
Now there is no way i get php 5.6 on this old baby.

**Comment by ckruijntjens** [comment]
Hi 

I have the same issue. After latest git pull. Machine is Centos7

PHP 5.4.16 (cli) (built: Oct 30 2018 19:30:51)

Error when retrieving

PHP Fatal error:  Class 'SpotDebug' not found in /var/www/spotweb/retrieve.php on line 91

Always worked before the last git pull.

**Comment by ckruijntjens** [comment]
New PHP version 7.4 resolves the problem

**Comment by ac3nl** [comment]
How did you update?

**Comment by ckruijntjens** [comment]
Sorry yust tested some further and it is not working. (php 7.2) When openening a post i still get the error:

Parse error: syntax error, unexpected '.', expecting ',' or ';' in /var/www/spotweb/lib/SpotDebug.php on line 17

**Comment by Sweepr** [comment]
Did you perform a 'composer install' inside the document root?

**Comment by Sweepr** [comment]
Do you have timing enabled in the settings?  this enables debugging aswell which could output this error

**Comment by Sweepr** [comment]
I just installed a fresh Spotweb and i'm not seeing the issue's described at all.

retriever is working, opening spots is working.

Using PHP 7.2.15

It seems there's not a real issue here, if you need help i suggest you join a forum that can help with spotweb but this is not the correct place, so closing.

**Comment by ckruijntjens** [comment]
damn i forgot to restart apache.

with the new php 7.2 it is working as it should!

**Comment by Marski69** [comment]
Same problems here on old x86 Qnap.
On https://www.qnapclub.eu/nl/qpkg/268 get Qapache_2.4.23.0_x86.qpkg (X86)
and follow instructions. Qnap with spotweb is working great again.

**Comment by ghorsie** [comment]
I do not know if I should open a new issue because this one is closed...
But I have the same problem coming from commit 3d822c2 to f236a93

I got the same error : Parse error: syntax error, unexpected '.', expecting ',' or ';' in /var/www/spotweb/lib/SpotDebug.php on line 17

I looked into this problem, and if I am correct, the code is wrong. It breaks on php5 because you are not allowed to initialize a static class property with an expression which is not known until runtime. Instead, initialize it in the constructor

File SpotDebug.php from line 17
Old code:
    static private $_logDir = __DIR__ . '/../logs';
    static private $_debugLogDao = null;

New code : 
    static private $_logDir;
    static private $_debugLogDao = null;

function __construct()
 {
   $_logDir = __DIR__ . '/../logs';
}

Forgive the lay-out... 
After making this change I can retrieve again using php5
