### ISSUE TITLE
Couchpotato cannot find posts in spotweb using imdbid=xxxx in API

### ISSUE THREAD

**Issue by D4nnyF3nt0m** [spotweb/spotweb#412]
I have a working spotweb running on Synology (DSM 6.2.1-23824 Update 6) with WebStation running on Apache HTTP Server 2.4, PHP7.2, and MariaDB10 database. Couchpotato cannot find movies on spotweb with log error:

ERROR [edia._base.providers.base] Invalid XML returned, check "http://192.168.1.200/spotweb/api?imdbid=1392170&apikey=xxx&t=movie&extended=1" manually for issues

Trying this manually in the browser keeps giving the following error for any movie:

Notice: Undefined offset: 1 in /volume1/web/spotweb/lib/services/MediaInformation/Services_MediaInformation_Imdb.php on line 41

Warning: Cannot modify header information - headers already sent by (output started at /volume1/web/spotweb/lib/services/MediaInformation/Services_MediaInformation_Imdb.php:41) in /volume1/web/spotweb/lib/page/SpotPage_Abs.php on line 72

Running the api manually without the imdbid works fine and shows many movies.
Can you please help in finding/solving the problem?

**Comment by D4nnyF3nt0m** [comment]
Services_MediaInformation_Imdb.php lines:
39) // imdb sometimes returns the title translated, if so, pass the original title as well
40)   preg_match('/<meta name="title" content="([^<]*?)\([0-9]*?\)/ms', $imdb, $originalTitle);
**41)    if ((!empty($originalTitle)) && (trim($originalTitle[1]) != $movieTitle[1])) {**
42)    $mediaInfo->setAlternateTitle(trim($originalTitle[1]));
43)    } # if

SpotPage_Abs.php lines:

 * Send the correct content header and character set to the browser
 */
function sendContentTypeHeader($type) {
		switch($type) {
	**line 72)	case 'xml'		: Header("Content-Type: text/xml; charset=utf-8"); break;**
			case 'rss'		: Header("Content-Type: application/rss+xml; charset=utf-8"); break;
			case 'json'		: Header("Content-Type: application/json; charset=utf-8"); break;
			case 'css'		: Header("Content-Type: text/css; charset=utf-8"); break;
			case 'js'		: Header("Content-Type: application/javascript; charset=utf-8"); break;
			case 'ico'		: Header("Content-Type: image/x-icon"); break;
            case 'nzb'		: Header("Content-Type: application/x-nzb"); break;

			default 		: Header("Content-Type: text/html; charset=utf-8"); break;
		} # switch

**Comment by Sweepr** [comment]
This should be fixed in :

https://github.com/spotweb/spotweb/issues/403

**Comment by D4nnyF3nt0m** [comment]
Thank you very much Sweepr! I spent several hours to look for problems and #403 let me fix it in a minute!

**Comment by Sweepr** [comment]
Cool!, closing..
