### ISSUE TITLE
Some php erros when running retrieve

### ISSUE THREAD

**Issue by Fixion-** [spotweb/spotweb#414]
Hello,

I have installed a new server and when i run retrieve.php i have this:

....
PHP Warning:  gzinflate(): data error in /var/www/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 150
PHP Warning:  gzinflate(): data error in /var/www/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 150
getHeader(): Failed to retrieve article: <e98b11c273354a9aacaa447e3f69f1a42@free.pt>
PHP Warning:  gzinflate(): data error in /var/www/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 150
_**....+50 lines of this error...**_
PHP Warning:  gzinflate(): data error in /var/www/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 150
 (parsed: 5001, in DB: 0, signed: 4906, invalid: 95, rtntn.skip: 0, mod: 0, full: 4906, total: 5001) in 818.96 seconds
Retrieving 640129 till 645130PHP Warning:  gzinflate(): data error in /var/www/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 150
....

The PHP version:
stef@asusvivopc-02:/var/www/spotweb/# php -v
PHP 7.3.5-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: May  3 2019 10:00:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.5-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

OS: Ubuntu 18.04.2 LTS (Debian 9 had the same errors)

What am i missing, or doing wrong?

**Comment by Sweepr** [comment]
Got Gzip enabled for your install?

**Comment by Fixion-** [comment]
Yes i have installed Gzip, and it looks that it is active if i read the  "/etc/nginx/nginx.conf" correctly

```
        gzip on;

        # gzip_vary on;
        # gzip_proxied any;
        # gzip_comp_level 6;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
        # gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

```

**Comment by Sweepr** [comment]
Im not familiar with nginx, so can't tell if this conf is correct.

Did you try another provider or disable ssl?

**Comment by Fixion-** [comment]
I have tried different providers (Eweka and Tweaknews) and turned SSL off and changed to port 119.

**Comment by mesa57** [comment]
Cannot find mentioned article. Probably very old ?

**Comment by mesa57** [comment]
Closing because no reaction.
