### ISSUE TITLE
SQL migration from: spotweb v0.67.28.31  to: spotweb v0.68.29.32

### ISSUE THREAD

**Issue by Sweepr** [Spotweb/Spotweb#42]
Hello,

I want to move user's and their settings from the mysql database to a new server 

From: spotweb v0.67.28.31 
To: spotweb v0.68.29.32

Is this possible? and if so, what the best way to do so?

I have already tried to export the table's users and usersetting and importing them in the new server but i cannot login using a test user, nor are their details shown:

Username
Firstname
Lastname
E-mail Address
Member of group seems also to be empty for the copied users.

**Comment by dsadsdadsadsadsds** [comment]
You also need to export the 'settings' table as it contains the users' password salt. My suggestion would be to not migrate part of Spotweb, but:

Migrate everything, *except*
* commentsxover
* commentsfull
* cache
* spots
* spotsfull
* reportsxover

After you done this, run upgrade-db.php to ensure we have a consistent database, and then start retrieving spots again.

My real suggestion, however, would be to just do a full backup/restore. Databass don't have an expiration date and they don't go "bad", there usually is no need to start from fresh.

**Comment by Sweepr** [comment]
Yes, did exactly like you said and it works now.
