### ISSUE TITLE
Table underneeth all pages of spotweb 

### ISSUE THREAD

**Issue by sojab0on** [spotweb/spotweb#420]
I have an issue with my spotweb single user instance 
Underneeth every page is see a table 

with the following colmn names above the colmns

Name | Time | Extra

![Screenshot 2019-07-11 at 19 12 53](https://user-images.githubusercontent.com/5721263/61070927-0f9ead00-a410-11e9-8998-4fd0c6a7b7c2.png)
![Screenshot 2019-07-11 at 19 13 07](https://user-images.githubusercontent.com/5721263/61070934-12999d80-a410-11e9-8d09-63f207567925.png)

**Comment by Sweepr** [comment]
Under settings->performance untick the "enable timing" and "enable stacktrace".

**Comment by Sweepr** [comment]
Closing, not a real issue but settings configuration error.
