### ISSUE TITLE
Guest spots full page intead of 25 posts

### ISSUE THREAD

**Issue by Solidjeuh** [spotweb/spotweb#421]
Hello,

Guests only see 25 spots, how can I change that? Yes, the can see more when scrolling, but I would like to show the full page.

Kind regards
![2019-07-15 13 31 33](https://user-images.githubusercontent.com/7800936/61213280-e1b5b300-a704-11e9-963c-c81609318c4d.jpg)

**Comment by Sweepr** [comment]
Under config->preferences change the items per page as you like, 25-50-100 or 250, but be aware this can cause bigger sql queries depending on the amounr of users.

**Comment by Solidjeuh** [comment]
That's for logged in users, guests still see only 25

**Comment by Sweepr** [comment]
Even easier to change this install-wide.

php /bin/upgrade-db.php --mass-userprefchange perpage=50

**Comment by Sweepr** [comment]
I'll close this for now, re-open if needed.
