### ISSUE TITLE
MariaDB 10.4 compatibility

### ISSUE THREAD

**Issue by GieltjE** [spotweb/spotweb#426]
When clean installing the the foreign key constraints need to be formatted differently (also see pull request #425 ).

```Database schema or settings upgrade failed:
   HY000: 1005: Can't create table `spotweb2`.`usergroups` (errno: 150 "Foreign key constraint is incorrectly formed")


#0 /var/www/spotweg2/lib/dbstruct/SpotStruct_mysql.php(308): dbeng_pdo->rawExec('ALTER TABLE use...')
#1 /var/www/spotweg2/lib/dbstruct/SpotStruct_abs.php(799): SpotStruct_mysql->addForeignKey('usergroups', 'groupid', 'securitygroups', 'id', 'ON DELETE CASCA...')
#2 /var/www/spotweg2/lib/services/Upgrade/Services_Upgrade_Base.php(42): SpotStruct_abs->updateSchema()
#3 /var/www/spotweg2/bin/upgrade-db.php(34): Services_Upgrade_Base->database()
```

They should look something like:

ALTER TABLE `usergroups`
  ADD CONSTRAINT `usergroups_ibfk_1` FOREIGN KEY (`userid`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `usergroups_ibfk_2` FOREIGN KEY (`groupid`) REFERENCES `securitygroups` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

**Comment by mesa57** [comment]
Does this also work for lower versions of MariaDB or MySQL ?
What abiut other engines ?

**Comment by GieltjE** [comment]
https://dev.mysql.com/doc/refman/8.0/en/alter-table.html

**Comment by mesa57** [comment]
Closing for now. Please reopen if needed.
