### ISSUE TITLE
MS SQL db 

### ISSUE THREAD

**Issue by sojab0on** [spotweb/spotweb#427]
Hi i am an Azure user and the nas in run spotweb on has limited resources so i tough about using MS SQL trough Azure because i already have a running ms sql server there, also an MY sql on ubuntu instance but do know witch works better.

Please advice witch to use and if i need to stick with my sql, if i can use the azure instance and witch system is best for spotwebs db use

**Comment by sojab0on** [comment]
hope it can work on MS SQL have a server on azure with MS SQL running and MY SQL on Azure is a pain in the butt to setup, and lock out access for everyone except the 2 or 3 ips i want to have access from

**Comment by mesa57** [comment]
Spotweb has no DAO setup for MS-SQL (unless you build it youreself).

**Comment by sojab0on** [comment]
than leave it be
