### ISSUE TITLE
13:59:56	TRUNCATE `spotweb`.`commentsxover`	Error Code: 1701 Cannot truncate a table referenced in a foreign key constraint (`spotweb`.`commentsfull`, CONSTRAINT `commentsfull_ibfk_1`)	

### ISSUE THREAD

**Issue by sojab0on** [spotweb/spotweb#428]
I cant seenm to get mysql to turncate the commentxovertable witch is getting huge.

It gives the following error 
13:59:56	TRUNCATE `spotweb`.`commentsxover`	Error Code: 1701 Cannot truncate a table referenced in a foreign key constraint (`spotweb`.`commentsfull`, CONSTRAINT `commentsfull_ibfk_1`)	

what can i do to turncate it .

**Comment by sojab0on** [comment]
have turncated all the other comment tables
but still cant turncate

**Comment by mesa57** [comment]
What message do you get when you truncate commentsfull ?

**Comment by sojab0on** [comment]
that goes normal but when i try to turncate xover it give that

**Comment by mesa57** [comment]
Try this :

SET FOREIGN_KEY_CHECKS = 0; 
TRUNCATE table $table_name; 
SET FOREIGN_KEY_CHECKS = 1;

**Comment by Sweepr** [comment]
Close, re-open if needed.
