### ISSUE TITLE
Spotnet link is unavailable

### ISSUE THREAD

**Issue by peter279k** [spotweb/spotweb#429]
As title, it seems that the [Spotnet](https://github.com/spotweb/spotweb/blob/master/spotnet/spotnet/wiki) link is broken in `README`.

It seems that this link is about a GitHub wiki for introducing the Spotnet protocol.

I think this should be added and let developers know details about Spotnet protocol.

**Comment by Sweepr** [comment]
Fixed now.

**Comment by peter279k** [comment]
@Sweepr, thanks for your quick reply and fix :).
