### ISSUE TITLE
External MySQL database to slow for spotweb 

### ISSUE THREAD

**Issue by sojab0on** [spotweb/spotweb#430]
I tried getting my local mysql db to migrate to a ne azure external server, but it reacts to slow.

Is there a way to improve reaction time or increase the time spotweb wiats for the server to respond and return de requests?

**Comment by mesa57** [comment]
Sorry, no idea what to do about that, Mysql is normally pretty performant.

**Comment by Sweepr** [comment]
It might be a DNS issues, did you try to by-pass the DNS, and use fixed IP addresses as DNS look-ups tend to slow things down dramatically, you may use `--skip-name-resolve` option in your "my.cnf"

Reference: https://www.vionblog.com/skip-name-resolve-to-speed-up-mysql-and-avoid-problems/

"Suit yourself":

My suggestion: Keep your database local and behind your firewall, course you can have a firewall and security between computers but firewalls, internet, routing, DNS lookup's etc, etc, slow down your connection, so i would recommend you to not expose your MySQL database connection to the Internet.
