### ISSUE TITLE
setting up closed system, opening spotweb fails

### ISSUE THREAD

**Issue by HeMaN-NL** [spotweb/spotweb#431]
I was setting up a new VM with spotweb as a closed system (Ubuntu 18.04 server, spotweb latest version) and had issues after finishing the setup to enter spotweb.
Finally managed to get a working system by chosing a public installation of spotweb.

When trying to change this working public system to a closed system (https://github.com/spotweb/spotweb/issues/317) I could not enter the spotweb pages again (just shows a blanc page).

php 7.2.19
ubuntu 18.04 with all updates to date

Is there a known issue or is there something I can try to make the closed system work?

**Comment by Sweepr** [comment]
Do you get any error?

Blank pages usually point to PHP error's, check your log files.

**Comment by HeMaN-NL** [comment]
no error, just a blank page.
from the apache2 error.log I also see no difference in errors between the working public instance and the closed instance


error log of apache2 with the working public system (I probably enabled a few to much modules in trying to figure out how to get this working :) )

`PHP Warning:  PHP Startup: Unable to load dynamic library 'mysqli' (tried: /usr/lib/php/20170718/mysqli (/usr/lib/php/20170718/mysqli: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/mysqli.so (/usr/lib/php/20170718/mysqli.so: undefined symbol: mysqlnd_global_stats)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'openssl' (tried: /usr/lib/php/20170718/openssl (/usr/lib/php/20170718/openssl: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/openssl.so (/usr/lib/php/20170718/openssl.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_mysql' (tried: /usr/lib/php/20170718/pdo_mysql (/usr/lib/php/20170718/pdo_mysql: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/pdo_mysql.so (/usr/lib/php/20170718/pdo_mysql.so: undefined symbol: mysqlnd_allocator)) in Unknown on line 0
PHP Warning:  Module 'bcmath' already loaded in Unknown on line 0
PHP Warning:  Module 'gd' already loaded in Unknown on line 0
PHP Warning:  Module 'gmp' already loaded in Unknown on line 0
[Thu Aug 15 20:45:11.986683 2019] [mpm_prefork:notice] [pid 25395] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Thu Aug 15 20:45:11.986753 2019] [core:notice] [pid 25395] AH00094: Command line: '/usr/sbin/apache2'`

changed in spotweb to closed system and restarted apache2

`[Thu Aug 15 20:49:03.302195 2019] [mpm_prefork:notice] [pid 25395] AH00169: caught SIGTERM, shutting down
PHP Warning:  PHP Startup: Unable to load dynamic library 'mysqli' (tried: /usr/lib/php/20170718/mysqli (/usr/lib/php/20170718/mysqli: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/mysqli.so (/usr/lib/php/20170718/mysqli.so: undefined symbol: mysqlnd_global_stats)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'openssl' (tried: /usr/lib/php/20170718/openssl (/usr/lib/php/20170718/openssl: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/openssl.so (/usr/lib/php/20170718/openssl.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_mysql' (tried: /usr/lib/php/20170718/pdo_mysql (/usr/lib/php/20170718/pdo_mysql: cannot open shared object file: No such file or directory), /usr/lib/php/20170718/pdo_mysql.so (/usr/lib/php/20170718/pdo_mysql.so: undefined symbol: mysqlnd_allocator)) in Unknown on line 0
PHP Warning:  Module 'bcmath' already loaded in Unknown on line 0
PHP Warning:  Module 'gd' already loaded in Unknown on line 0
PHP Warning:  Module 'gmp' already loaded in Unknown on line 0
[Thu Aug 15 20:49:09.007580 2019] [mpm_prefork:notice] [pid 25641] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Thu Aug 15 20:49:09.007644 2019] [core:notice] [pid 25641] AH00094: Command line: '/usr/sbin/apache2'`


last few lines from my access.log (working page - staring the user manager and change to closed system - trying to access spotweb)

`192.168.150.21 - - [15/Aug/2019:20:46:52 +0200] "GET /spotweb/templates/we1rdo/css/images/ui-icons_222222_256x240.png HTTP/1.1" 200 4655 "http://192.168.150.221/spotweb/?page=statics&type=css&mod=1565464942" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.150.21 - - [15/Aug/2019:20:46:55 +0200] "GET /spotweb/?page=edituser&userid=3 HTTP/1.1" 200 1466 "http://192.168.150.221/spotweb/?page=render&tplname=usermanagement" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.150.21 - - [15/Aug/2019:20:46:56 +0200] "GET /spotweb/images/refresh.png HTTP/1.1" 200 3903 "http://192.168.150.221/spotweb/?page=render&tplname=usermanagement" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.150.21 - - [15/Aug/2019:20:47:07 +0200] "POST /spotweb/?page=edituser HTTP/1.1" 200 545 "http://192.168.150.221/spotweb/?page=render&tplname=usermanagement" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.150.21 - - [15/Aug/2019:20:47:07 +0200] "GET /spotweb/?page=render&tplname=listusers HTTP/1.1" 200 1260 "http://192.168.150.221/spotweb/?page=render&tplname=usermanagement" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.150.21 - - [15/Aug/2019:20:47:14 +0200] "GET /spotweb/ HTTP/1.1" 200 909 "http://192.168.150.221/spotweb/?page=render&tplname=usermanagement" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.150.21 - - [15/Aug/2019:20:47:14 +0200] "GET /favicon.ico HTTP/1.1" 404 506 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.150.21 - - [15/Aug/2019:20:48:43 +0200] "GET / HTTP/1.1" 200 3477 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.150.21 - - [15/Aug/2019:20:48:43 +0200] "GET /icons/ubuntu-logo.png HTTP/1.1" 200 3623 "http://192.168.150.221/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"
192.168.150.21 - - [15/Aug/2019:20:48:43 +0200] "GET /favicon.ico HTTP/1.1" 404 506 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"`

Anywhere else I can look?

**Comment by Sweepr** [comment]
Can create a phpinfo.php file and add the text below and copy that to the root folder of your spotweb instance,

The browse to http://yourspotwebadrress/phpinfo.php and post the results here.

<?php

// Show all information, defaults to INFO_ALL
phpinfo();

?>

**Comment by HeMaN-NL** [comment]
output is 17 pages :)
made a pdf from it

**Comment by Sweepr** [comment]
So i have looked at your PDF it's looks fine, but the extension_dir is defined as `/usr/lib/php/20170718/`, looking at the error's you've posted earlier e.g. `PHP Warning: PHP Startup: Unable to load dynamic library 'mysqli' (tried: /usr/lib/php/20170718/mysqli (/usr/lib/php/20170718/mysqli: cannot open shared object file: No such file or directory)` seems like PHP can't find certain module's that it requires.

You need to verify where those module's are, since they can't be found in `/usr/lib/php/20170718`, they are needed.

**Comment by HeMaN-NL** [comment]
I tried again from the start; 
new VM, installed packages, created database, got latest version from wget https://github.com/spotweb/spotweb/tarball/master , did the install php (set timezone in php.ini, installed php-curl (must have missed that package) added the cache directory and chmod 777.
Set up the database, set up the newsprovider, both tested ok.
created the dbsettings.inc.php, set up useraccount …. and nothing again
Blank page when trying to open the spotweb page. No errors in the apache log, nothing …..

only entry in the access log:
'192.168.150.21 - - [18/Aug/2019:15:45:08 +0200] "GET /spotweb/ HTTP/1.1" 200 907 "http://192.168.150.100/spotweb/install.php?page=99" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0"'

**Comment by HeMaN-NL** [comment]
After editing my post above I think I know where I went wrong when switching:
I changed the current test-user account I created to "anonymous user - closed system" and not the "anonymous user" account.
After changing the anonymous user I think it is working again like I expected (oops, my bad)

What I think is still not right is when choosing "single user system" during the setup, it creates a multi user system.

**Comment by Sweepr** [comment]
I was just about that write the same thing, it can be confusing at first, but once you get the hang of it you'll understand how things work and why they are made like this.

Is you issue resolved?

**Comment by HeMaN-NL** [comment]
Did some more testing.
Accessing spotweb from a brwoser in another vm I did not access spotweb before, I was presented with a login screen again.
So no automatic login like I exopected from the single user system.

I then tried changing the admin and created user as well to "anonymous user - closed system" and removed all cookies.
Then I could not access spotweb again from any machine, always a blank page.

Still confusing to me. will be reverting to my latest snapshot from before fiddeling with the account permissions and leave it that way I suppose. I have to live with logging in into the system when accessing it from a new pc or after have cleared my cookies.

The thing I noticed (maybe a bug, maybe me not knowing how things are working)
- when installing spotweb and choosing the option single user, I am expecting not to have to log in when accessing spotweb. This is not the case, I do have to log in.

**Comment by Sweepr** [comment]
If you want a closed system, please remove the "Anonymous" user from the "Anonymous user - open system" group, and add it to the "Anonymous user - closed system" securitygroup.

Which of the following options did you choose?

Single user:
Single user systems are one-user systems, not shared with friends or family members. Spotweb wil always be logged on using the below defined user and Spotweb will never ask for authentication.

Shared:
Shared systems are Spotweb installations shared among friends or family members. You do have to logoN using an useraccount, but the users who do log on are trusted to have no malicious intentions.

Public:
Public systems are Spotweb installations fully open to the public. Because the installation is fully open, regular users do not have all the features available in Spotweb to help defend against certain malicious users.

**Comment by HeMaN-NL** [comment]
I used single user, but was asked to log in when I opened the spotweb page

> Single user:
Single user systems are one-user systems, not shared with friends or family members. Spotweb wil always be logged on using the below defined user and Spotweb **will never ask for authentication**.

**Comment by Sweepr** [comment]
I understand this system isn't the most easiest thing to understand, i also had a difficult time to understand and took me multiple installations before i got the hang of it.

Just to confirm, i did a fresh install just like you and used the option "Single" create a user and after that i was presented with the main view.

Now i don't have to login or authenticate myself, even when using different browsers, tried I.E., Firefox, Chrome i just stay logged on.

So i have no clue to find the root-cause of your issue, maybe it's a permission/cookie thing.

I downloaded the ZIP from https://github.com/spotweb/spotweb/archive/1.3.9.zip

Using Xammp v3.2.3
 and
PHP 7.3.3 (cli) (built: Mar  6 2019 21:53:23) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.3, Copyright (c) 1998-2018 Zend Technologies

**Comment by HeMaN-NL** [comment]
Thnx for the explanation. I made a snapshot of the vm just before i started the configuration of spotweb. I think this weekend I will go through the config procedure once again and see if I can get it to work and trace what is happening.

something I did not understand before, but think I do now; a single user system is not the same as a closed system?
closed system = you need to log in before you see anything of the spots?

Is there maybe a post or wiki describing how to change from a public to a single user installation?

**Comment by Sweepr** [comment]
There is an Wiki, but it's in Dutch, if that an issue then maybe you can translate it online?
https://github.com/spotweb/spotweb/wiki/Hoe-het-rechten-systeem-werkt

Closing as it's not an actuall issue, re-open if needed.
