### ISSUE TITLE
Send directly to NZB client button gone 

### ISSUE THREAD

**Issue by klara31** [spotweb/spotweb#440]
Somewhere in the latest updates in september, the green arrow at the end of each line, which sends the NZB directly to the download client, is gone. I am using NZBget over http.
I checked my config, nothing changed. Checked nginx logs, which shows:
````
2019/09/15 10:48:53 [error] 1102#1102: *185967 FastCGI sent in stderr: "PHP message: ERROR: Could not decode json-data for NZBGet method 'status', http returncode: 700 / OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 192.168.10.10:6789" while reading response header from upstream, client: 192.168.10.175, server: app-server, request: "GET /spotweb/?search[tree]=&search[unfiltered]=true HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "app-server", referrer: "http://app-server/spotweb/"
````
I do not have SSL configured for NZBget, neither in spotweb, neither in NZBget. If I read the log correctly (?), it looks like spotweb is trying to get to NZBget over SSL.

When reverting back to 216aaacf, it is working again

**Comment by mesa57** [comment]
Hotfix available on develop branch. Please confirm solution.

**Comment by klara31** [comment]
confirmed!
Thanks :)

**Comment by mesa57** [comment]
No thanks !
