### ISSUE TITLE
Some lines have hg1 in several classes

### ISSUE THREAD

**Issue by MrHappy** [spotweb/spotweb#446]
This gives the line (except for the media and # comments) a light green background colour.
This appeared after I updated yesterday (my previous check on a new version was about a month ago).
Is it intentional to not change the media and # comments?

**Comment by mesa57** [comment]
Please post a screenprint to eleborate exactly what you mean.

**Comment by MrHappy** [comment]
![image](https://user-images.githubusercontent.com/686360/65320786-f13cf680-dba2-11e9-9c52-31c2efd4236f.png)
As you can see the title has become light green, but the media is still blue. Is this intentionally?

**Comment by Sweepr** [comment]
This is done intentionally, see: https://github.com/spotweb/spotweb/issues/268

Can be changed, if there's a need for it, i decided it looked better this way.

**Comment by MrHappy** [comment]
Ahh.. MIssed that one.. 
Thanks.
No need to change it (at least not for me)
