### ISSUE TITLE
Postgresql dreadfully slow on latest release (1.4.3)

### ISSUE THREAD

**Issue by jb044** [spotweb/spotweb#447]
First of all is postgresql (11) still supported?

After I upgraded to the latest version, my spotweb install became unusable. Postgresql queries take forever, however it seems the overview category I request makes a difference, some load within 30 seconds, some take significantly longer. During this postgresql threads take 100% cpu usage. Already tried to disable postgresql concurrency without a difference and restore form backups. After the last the problem disappeared for some while but at some point returned like before.

OS: CentOS 7.7
php: 7.2
postgresql: 11

Can provide more details if needed.

**Comment by jb044** [comment]
Oh, strace on postgresql gave endless loops of this:

lseek(57, 0, SEEK_END)                  = 1114112
lseek(57, 0, SEEK_END)                  = 1114112
lseek(57, 0, SEEK_END)                  = 1114112
lseek(57, 0, SEEK_END)                  = 1114112
lseek(57, 0, SEEK_END)                  = 1114112
lseek(57, 0, SEEK_END)                  = 1114112
lseek(57, 0, SEEK_END)                  = 1114112
lseek(57, 0, SEEK_END)                  = 1114112
lseek(57, 0, SEEK_END)                  = 1114112
lseek(57, 0, SEEK_END)                  = 1114112
lseek(57, 0, SEEK_END)                  = 1114112
lseek(57, 0, SEEK_END)                  = 1114112
lseek(57, 0, SEEK_END)                  = 1114112
lseek(57, 0, SEEK_END)                  = 1114112
lseek(57, 0, SEEK_END)                  = 1114112
lseek(57, 0, SEEK_END)                  = 1114112
lseek(57, 0, SEEK_END)                  = 1114112
lseek(57, 0, SEEK_END)                  = 1114112
lseek(57, 0, SEEK_END)                  = 1114112
lseek(57, 0, SEEK_END)                  = 1114112
lseek(57, 0, SEEK_END)                  = 1114112
lseek(57, 0, SEEK_END)                  = 1114112

**Comment by Sweepr** [comment]
Could you do a slow query log and post the result, maybe that points us in a direction to start.

**Comment by jb044** [comment]
this one takes 3 minutes to run:

`select         x.*,
                                        f.verified ,
                                                            COALESCE(x.idtype, wl.idtype, gwl.idtype) AS idtype
                                    from
                                    (SELECT s.id AS id,
                                                                            s.messageid AS messageid,
                                                                            s.category AS category,
                                                                            s.poster AS poster,
                                                                            s.subcata AS subcata,
                                                                            s.subcatb AS subcatb,
                                                                            s.subcatc AS subcatc,
                                                                            s.subcatd AS subcatd,
                                                                            s.subcatz AS subcatz,
                                                                            s.title AS title,
                                                                            s.tag AS tag,
                                                                            s.stamp AS stamp,
                                                                            s.moderated AS moderated,
                                                                            s.filesize AS filesize,
                                                                            s.spotrating AS rating,
                                                                            s.commentcount AS commentcount,
                                                                            s.reportcount AS reportcount,
                                                                            s.spotterid AS spotterid,
                                                                            s.editstamp AS editstamp,
                                                                            s.editor AS editor,
                                                l.download as downloadstamp,
                                                l.watch as watchstamp,
                                                l.seen AS seenstamp,
                                            bl.idtype as idtype,
                                            s.reversestamp as reversestamp


                                                                            FROM spots AS s

        LEFT JOIN spotteridblacklist as bl ON ((bl.spotterid = s.spotterid) AND ((bl.ouruserid = 3) OR (bl.ouruserid = -1)) AND (bl.idtype = 1))
                                                                        LEFT JOIN spotstatelist AS l on ((s.messageid = l.messageid) AND (l.ouruserid = 3))
                                             WHERE (bl.spotterid IS NULL)  AND (((s.category = 0) AND (s.subcatz = 'z0|') AND ( ((s.subcata = 'a4|')  OR (s.subcata = 'a6|')  OR (s.subcata = 'a7|')  OR (s.subcata = 'a8|')  OR (s.subcata = 'a9|') ) ) ))

                                                                            ORDER BY s.reversestamp ASC LIMIT 26 OFFSET 0
                                    ) as x
                                    LEFT JOIN spotsfull AS f ON (f.messageid = x.messageid)
                                                        LEFT JOIN spotteridblacklist as wl on ((wl.spotterid = x.spotterid) AND ((wl.ouruserid = 3) AND (wl.idtype = 2)))
                                                                LEFT JOIN spotteridblacklist as gwl on ((gwl.spotterid = x.spotterid) AND ((gwl.ouruserid = -1) AND (gwl.idtype = 2)))
                                    ORDER BY x.reversestamp ASC`

**Comment by Sweepr** [comment]
You are on Master branch?

When you revert to a previous version all goes back to normal?

**Comment by jb044** [comment]
On latest release 1.4.3, revert to 1.3.9 did not help :(

```
duration: 227366.909 ms  execute pdo_stmt_00000008: select 	x.*,
		                        f.verified ,
							    COALESCE(x.idtype, wl.idtype, gwl.idtype) AS idtype
	                            from
	                            (SELECT s.id AS id,
									    s.messageid AS messageid,
									    s.category AS category,
									    s.poster AS poster,
									    s.subcata AS subcata,
									    s.subcatb AS subcatb,
									    s.subcatc AS subcatc,
									    s.subcatd AS subcatd,
									    s.subcatz AS subcatz,
									    s.title AS title,
									    s.tag AS tag,
									    s.stamp AS stamp,
									    s.moderated AS moderated,
									    s.filesize AS filesize,
									    s.spotrating AS rating,
									    s.commentcount AS commentcount,
									    s.reportcount AS reportcount,
									    s.spotterid AS spotterid,
	 								    s.editstamp AS editstamp,
	 								    s.editor AS editor,
		                                l.download as downloadstamp,
		                                l.watch as watchstamp,
		                                l.seen AS seenstamp,
	                                    bl.idtype as idtype,
	                                    s.reversestamp as reversestamp


									    FROM spots AS s

	LEFT JOIN spotteridblacklist as bl ON ((bl.spotterid = s.spotterid) AND ((bl.ouruserid = 3) OR (bl.ouruserid = -1)) AND (bl.idtype = 1))
								        LEFT JOIN spotstatelist AS l on ((s.messageid = l.messageid) AND (l.ouruserid = 3))
	                                     WHERE (bl.spotterid IS NULL)  AND (((s.category = 0) AND (s.subcatz = 'z0|') AND ( ((s.subcata = 'a4|')  OR (s.subcata = 'a6|')  OR (s.subcata = 'a7|')  OR (s.subcata = 'a8|')  OR (s.subcata = 'a9|') ) ) ))

									    ORDER BY s.reversestamp ASC LIMIT 26 OFFSET 0
	                            ) as x
	                            LEFT JOIN spotsfull AS f ON (f.messageid = x.messageid)
	 					        LEFT JOIN spotteridblacklist as wl on ((wl.spotterid = x.spotterid) AND ((wl.ouruserid = 3) AND (wl.idtype = 2)))
								LEFT JOIN spotteridblacklist as gwl on ((gwl.spotterid = x.spotterid) AND ((gwl.ouruserid = -1) AND (gwl.idtype = 2)))
	                            ORDER BY x.reversestamp ASC
2019-09-23 20:36:10.546 CEST [28319] LOG:  duration: 227366.898 ms  plan:
	Query Text: select 	x.*,
		                        f.verified ,
							    COALESCE(x.idtype, wl.idtype, gwl.idtype) AS idtype
	                            from
	                            (SELECT s.id AS id,
									    s.messageid AS messageid,
									    s.category AS category,
									    s.poster AS poster,
									    s.subcata AS subcata,
									    s.subcatb AS subcatb,
									    s.subcatc AS subcatc,
									    s.subcatd AS subcatd,
									    s.subcatz AS subcatz,
									    s.title AS title,
									    s.tag AS tag,
									    s.stamp AS stamp,
									    s.moderated AS moderated,
									    s.filesize AS filesize,
									    s.spotrating AS rating,
									    s.commentcount AS commentcount,
									    s.reportcount AS reportcount,
									    s.spotterid AS spotterid,
	 								    s.editstamp AS editstamp,
	 								    s.editor AS editor,
		                                l.download as downloadstamp,
		                                l.watch as watchstamp,
		                                l.seen AS seenstamp,
	                                    bl.idtype as idtype,
	                                    s.reversestamp as reversestamp


									    FROM spots AS s

	LEFT JOIN spotteridblacklist as bl ON ((bl.spotterid = s.spotterid) AND ((bl.ouruserid = 3) OR (bl.ouruserid = -1)) AND (bl.idtype = 1))
								        LEFT JOIN spotstatelist AS l on ((s.messageid = l.messageid) AND (l.ouruserid = 3))
	                                     WHERE (bl.spotterid IS NULL)  AND (((s.category = 0) AND (s.subcatz = 'z0|') AND ( ((s.subcata = 'a4|')  OR (s.subcata = 'a6|')  OR (s.subcata = 'a7|')  OR (s.subcata = 'a8|')  OR (s.subcata = 'a9|') ) ) ))

									    ORDER BY s.reversestamp ASC LIMIT 26 OFFSET 0
	                            ) as x
	                            LEFT JOIN spotsfull AS f ON (f.messageid = x.messageid)
	 					        LEFT JOIN spotteridblacklist as wl on ((wl.spotterid = x.spotterid) AND ((wl.ouruserid = 3) AND (wl.idtype = 2)))
								LEFT JOIN spotteridblacklist as gwl on ((gwl.spotterid = x.spotterid) AND ((gwl.ouruserid = -1) AND (gwl.idtype = 2)))
	                            ORDER BY x.reversestamp ASC
	Nested Loop Left Join  (cost=52654.92..52675.49 rows=1 width=459) (actual time=227362.153..227366.810 rows=26 loops=1)
	  ->  Nested Loop Left Join  (cost=52654.63..52670.71 rows=1 width=459) (actual time=227362.134..227366.679 rows=26 loops=1)
	        ->  Nested Loop Left Join  (cost=52654.35..52662.38 rows=1 width=455) (actual time=227362.082..227366.492 rows=26 loops=1)
	              ->  Limit  (cost=52653.92..52653.92 rows=1 width=454) (actual time=227361.973..227365.719 rows=26 loops=1)
	                    ->  Sort  (cost=52653.92..52653.92 rows=1 width=454) (actual time=227361.970..227361.978 rows=26 loops=1)
	                          Sort Key: s.reversestamp
	                          Sort Method: top-N heapsort  Memory: 39kB
	                          ->  Nested Loop Left Join  (cost=14221.20..52653.91 rows=1 width=454) (actual time=90.436..226758.105 rows=74615 loops=1)
	                                Join Filter: ((s.messageid)::text = (l.messageid)::text)
	                                Rows Removed by Join Filter: 1059538629
	                                ->  Gather  (cost=14221.20..52160.46 rows=1 width=442) (actual time=85.920..395.314 rows=74615 loops=1)
	                                      Workers Planned: 2
	                                      Workers Launched: 2
	                                      ->  Hash Anti Join  (cost=13221.20..51160.36 rows=1 width=442) (actual time=78.707..164.240 rows=24872 loops=3)
	                                            Hash Cond: ((s.spotterid)::text = (bl.spotterid)::text)
	                                            ->  Parallel Bitmap Heap Scan on spots s  (cost=12815.52..50562.78 rows=51174 width=438) (actual time=72.019..133.359 rows=24872 loops=3)
	                                                  Recheck Cond: (((category = 0) AND ((subcata)::text = 'a4|'::text) AND ((subcatz)::text = 'z0|'::text)) OR ((category = 0) AND ((subcata)::text = 'a6|'::text) AND ((subcatz)::text = 'z0|'::text)) OR ((category = 0) AND ((subcata)::text = 'a7|'::text) AND ((subcatz)::text = 'z0|'::text)) OR ((category = 0) AND ((subcata)::text = 'a8|'::text) AND ((subcatz)::text = 'z0|'::text)) OR ((category = 0) AND ((subcata)::text = 'a9|'::text) AND ((subcatz)::text = 'z0|'::text)))
	                                                  Heap Blocks: exact=1
	                                                  ->  BitmapOr  (cost=12815.52..12815.52 rows=130495 width=0) (actual time=69.303..69.304 rows=0 loops=1)
	                                                        ->  Bitmap Index Scan on idx_spots_4  (cost=0.00..449.10 rows=4612 width=0) (actual time=2.568..2.568 rows=2754 loops=1)
	                                                              Index Cond: ((category = 0) AND ((subcata)::text = 'a4|'::text) AND ((subcatz)::text = 'z0|'::text))
	                                                        ->  Bitmap Index Scan on idx_spots_4  (cost=0.00..370.81 rows=3818 width=0) (actual time=4.896..4.896 rows=11430 loops=1)
	                                                              Index Cond: ((category = 0) AND ((subcata)::text = 'a6|'::text) AND ((subcatz)::text = 'z0|'::text))
	                                                        ->  Bitmap Index Scan on idx_spots_4  (cost=0.00..381.33 rows=3894 width=0) (actual time=0.235..0.235 rows=190 loops=1)
	                                                              Index Cond: ((category = 0) AND ((subcata)::text = 'a7|'::text) AND ((subcatz)::text = 'z0|'::text))
	                                                        ->  Bitmap Index Scan on idx_spots_4  (cost=0.00..1359.87 rows=14000 width=0) (actual time=0.756..0.756 rows=231 loops=1)
	                                                              Index Cond: ((category = 0) AND ((subcata)::text = 'a8|'::text) AND ((subcatz)::text = 'z0|'::text))
	                                                        ->  Bitmap Index Scan on idx_spots_4  (cost=0.00..10100.89 rows=104171 width=0) (actual time=60.840..60.840 rows=60012 loops=1)
	                                                              Index Cond: ((category = 0) AND ((subcata)::text = 'a9|'::text) AND ((subcatz)::text = 'z0|'::text))
	                                            ->  Hash  (cost=274.52..274.52 rows=10493 width=10) (actual time=6.400..6.400 rows=10585 loops=3)
	                                                  Buckets: 16384  Batches: 1  Memory Usage: 571kB
	                                                  ->  Seq Scan on spotteridblacklist bl  (cost=0.00..274.52 rows=10493 width=10) (actual time=0.033..3.581 rows=10585 loops=3)
	                                                        Filter: ((idtype = 1) AND ((ouruserid = 3) OR (ouruserid = '-1'::integer)))
	                                                        Rows Removed by Filter: 16
	                                ->  Seq Scan on spotstatelist l  (cost=0.00..314.73 rows=14298 width=43) (actual time=0.004..2.031 rows=14200 loops=74615)
	                                      Filter: (ouruserid = 3)
	              ->  Index Scan using idx_spotsfull_1 on spotsfull f  (cost=0.43..8.45 rows=1 width=34) (actual time=0.028..0.028 rows=1 loops=26)
	                    Index Cond: ((messageid)::text = (s.messageid)::text)
	        ->  Index Only Scan using idx_spotteridblacklist_1 on spotteridblacklist wl  (cost=0.29..4.31 rows=1 width=10) (actual time=0.006..0.006 rows=1 loops=26)
	              Index Cond: ((spotterid = (s.spotterid)::text) AND (ouruserid = 3) AND (idtype = 2))
	              Heap Fetches: 0
	  ->  Index Only Scan using idx_spotteridblacklist_1 on spotteridblacklist gwl  (cost=0.29..4.31 rows=1 width=10) (actual time=0.004..0.004 rows=0 loops=26)
	        Index Cond: ((spotterid = (s.spotterid)::text) AND (ouruserid = '-1'::integer) AND (idtype = 2))
	        Heap Fetches: 0
```

Problem seems to be in the joins

**Comment by jb044** [comment]
hmm, after an analyse on the spotweb db, performance is back again at reasonable levels. Could this be nescesaary after a run of bin/upgrade-db.php?

**Comment by Sweepr** [comment]
Not sure, not that experienced with postgresql.

For now since it's solved i'm closing the issue, if it happens again feel free to re-open.

**Comment by scanno** [comment]
Running postgreSQL 12 and indeed it is very slow.
