### ISSUE TITLE
Unable to retrieve new spots

### ISSUE THREAD

**Issue by bizziebis** [spotweb/spotweb#448]
I have just installed a fresh Spotweb install but I am unable te get new spots. 

> dietpi@SpotWebVM:~ $ php7.3 /var/www/spotweb/retrieve.php
> Removing Spot information which is beyond retention period,, done
> Last retrieve at Fri Oct  4 02:55:37 2019
> Retrieving new Spots from server news.newsgroupdirect.com...
> SpotWeb v0.68.30.33 on PHP v7.3.9-1+0~20190902.44+debian9 1.gbpf8534c crashed
> 
> Fatal error occured while connecting to the newsserver:
>   (400) Unexpected response [response: "Operation failed"]
> 
> 
> #0 /var/www/spotweb/vendor/spotweb/nntp/src/Protocol/Client.php(662): Net_NNTP_Protocol_Client->throwError('Unexpected resp...', 400, 'Operation faile...')
> #1 /var/www/spotweb/vendor/spotweb/nntp/src/Protocol/Client.php(2022): Net_NNTP_Protocol_Client->_handleUnexpectedResponse(400)
> #2 /var/www/spotweb/vendor/spotweb/nntp/src/Client.php(1144): Net_NNTP_Protocol_Client->cmdXHdr('Message-ID', '3330876')
> #3 /var/www/spotweb/lib/services/Nntp/Services_Nntp_Engine.php(179): Net_NNTP_Client->getHeaderField('Message-ID', '3330876')
> #4 /var/www/spotweb/lib/services/Nntp/Services_Nntp_Engine.php(190): Services_Nntp_Engine->getMessageIdByArticleNumber('3330876')
> #5 /var/www/spotweb/lib/services/Nntp/Services_Nntp_Engine.php(190): Services_Nntp_Engine->getMessageIdByArticleNumber('3330876')
> #6 /var/www/spotweb/lib/services/Nntp/Services_Nntp_Engine.php(190): Services_Nntp_Engine->getMessageIdByArticleNumber('3330876')
> #7 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(141): Services_Nntp_Engine->getMessageIdByArticleNumber('3330876')
> #8 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(308): Services_Retriever_Base->searchMessageId('3330876', '1xioogF58swpVuW...', Array)
> #9 /var/www/spotweb/retrieve.php(145): Services_Retriever_Base->perform()
> #10 {main}
> 
> Finished retrieving spots.

The initial retrieve was successful. When I run retrieve --retro the process will run without any problems.
This looks to me the install was fine and connection with Newsserver is OK.

I have tried with all different settings.. Decrease the amount of spots per retrieve, set newsserver as buggy, tried different ports, tried ssl on and off, retention 30 days.

Is there something else I can try ?

**Comment by Sweepr** [comment]
Error 400 means:

If the server has to terminate the connection for some reason, it MUST give a 400 response code to the next command and then immediately close the connection. Following a 400 response, clients SHOULD NOT simply reconnect immediately and retry the same actions. Rather, a client SHOULD either use an exponentially increasing delay between retries (e.g., double the waiting time after each 400 response) or present any associated text to the user for them to decide whether and when to retry. The client MUST be prepared to receive any of these responses for any command (except, of course, that the server MUST NOT generate a 500 response code for mandatory commands).

**Comment by Sweepr** [comment]
In short, probably they rate limit the amount of executive connection.

**Comment by bizziebis** [comment]
I see. So I either have to switch to a different Usenet service, or alter the code In some way to add delays?

**Comment by Sweepr** [comment]
How often do you run retrieve?

**Comment by bizziebis** [comment]
I don't have a cronjob set yet. I run the command manually. It will immidiately show the 400 error.

**Comment by Sweepr** [comment]
Ok, Either way you connect too fast, or the USP is rate limiting.

**Comment by bizziebis** [comment]
I don't think the speed of connecting is in my control. I think my USP is rate limiting indeed . I see some behaviour in my NZBGet logs which could indicate this.

Can this be fixed in the Spotweb code? I can surely switch USP, but that won't solve the problem if they also decide to rate limit the connection.

If you have an idea, I can surely test it over here.

**Comment by Sweepr** [comment]
Spotweb uses 1 connection, if nzbget is downloading using all connection available at that time, then probably that can cause problems, can you disable nzbget temporarly and see if your issue goes away?

**Comment by bizziebis** [comment]
My VM with nzbget is not started at the moment. I have no outgoing connections to the usp. So that is not causing it. But like I mentioned in the first post, retrieve --retro will run just fine. But that's not something you want to run each hour.

**Comment by Sweepr** [comment]
You could send a e-mail to newsgroupdirect.com support and ask the question why you get 400 response.

**Comment by Sweepr** [comment]
Since not a real issue or bug i'm closing this, there are plenty help forums regarding spotweb for say tweakers which may help you but this is not the place.

**Comment by mesa57** [comment]
Reported to me via an other channel this problem appeared to be specific for newsgroupdirect and will e solved by them.
