### ISSUE TITLE
Sickchill: spotweb no longer working as search provider

### ISSUE THREAD

**Issue by bouwew** [spotweb/spotweb#449]
I updated recently to the latest code on the master-branch.

After the update Sickchill does not seem to find any things to download anymore. While, for instance, the wanted tv-episodes are present on the spotweb-page.

If I remember correctly, I was running the code from the master-branch of March 5. At that time the search-provider function was still working.

**Comment by Sweepr** [comment]
Do you have any error's in you log files?

**Comment by bouwew** [comment]
Thanks for the quick response!
I decided to take a good look at the sickchill log.
Looks like it's picking up some episodes but not all.
It might be that this is because of my Sickchill-settings. I'll experiment a bit,
And close this issue, as apparently there is no issue, sorry about that :)
