### ISSUE TITLE
Support for (NGINX) SSL offloading reverse proxy

### ISSUE THREAD

**Issue by WzL** [spotweb/spotweb#45]
According to GitHub issue [1569] (https://github.com/Spotweb/Spotweb/commit/33920a282764f7fb91a1b18eb8169c4d45e26177) (Add support for NGINX proxy forward) enabling php env var $_SERVER['HTTP_X_FORWARDED_SSL'] would enable https opportunities using SpotWeb.

In case of the Master branch, HTTPS does not work using NGINX as a reverse proxy. Issue [1569] (https://github.com/Spotweb/Spotweb/commit/33920a282764f7fb91a1b18eb8169c4d45e26177) involves also a change in the file ` lib/page/SpotPage_statics.php ´. This change is currently not included in the Master branch, which maybe the cause of the above issue.

**Comment by WzL** [comment]
I made 2 changes to made HTTPS work and thus solve my above issue. I am not a programmer so if some one could take a look at this `solution´.
1. Added Array(SpotReq::getRequestProtocol(), to line 29 of file ` lib/page/SpotPage_statics.php ´ as described by GH issue #1569 change
2. Changed (own)settings.php line 32 from 
$settings['spotweburl'] = (@$_SERVER['HTTPS'] ...
to
$settings['spotweburl'] = (@$_SERVER['HTTP_X_FORWARDED_SSL'] ...

Probably not the prettiest fix but it makes the HTTP URL´s in the Spotweb source go to HTTPS and CSS is loaded normally again.

**Comment by kooimens** [comment]
I've got the same issue, but with Apache2. However, the fix provided by @WzL didn't work out for me...

**Comment by WzL** [comment]
To get SSL working in combination with a reverse proxy which handels SSL offloading the reverse proxy needs to set the X-Forwarded-Ssl header. As far as i could find out you can set is using the following option using apache: RequestHeader set X-Forwarded-Ssl on (mod_headers enabled). is that active?

**Comment by kooimens** [comment]
Thanks for your help. I'm having a setup with trafficserver (apache) as front-end and a local backend with apache2. The other suggestion you provided didn't make a change either. I found out that the spotweb was using the local domain name of the backend host instead of the address used by the trafficserver. I solved the issue by setting the spotweburl (hardcoded) to my front-end web address within the ownsettings.php file.

**Comment by WzL** [comment]
Ok, my first lines of code, proposal for replacement of the following code in settings.php:

if (isset($_SERVER['SERVER_PROTOCOL'])) {
$settings['spotweburl'] = (@$_SERVER['HTTPS'] == 'on' ? 'https' : 'http') . '://' . @$_SERVER['HTTP_HOST'] . (dirname($_SERVER['PHP_SELF']) != '/' && dirname($_SERVER['PHP_SELF']) != '\\' ? dirname($_SERVER['PHP_SELF']). '/' : '/');
} else {
$settings['spotweburl'] = 'http://mijnuniekeservernaam/spotweb/';
}

replaced by

if (isset($_SERVER['SERVER_PROTOCOL'])) {
$settings['spotweburl'] = (@$_SERVER['HTTPS'] == 'on' ? 'https' : 'http') . '://' . @$_SERVER['HTTP_HOST'] . (dirname($_SERVER['PHP_SELF']) != '/' && dirname($_SERVER['PHP_SELF']) != '\\' ? dirname($_SERVER['PHP_SELF']). '/' : '/');
} elseif {
$settings['spotweburl'] = (@$_SERVER['HTTP_X_FORWARDED_SSL'] == 'on' ? 'https' : 'http') . '://' . @$_SERVER['HTTP_HOST'] . (dirname($_SERVER['PHP_SELF']) != '/' && dirname($_SERVER['PHP_SELF']) != '\\' ? dirname($_SERVER['PHP_SELF']). '/' : '/');
} else {
$settings['spotweburl'] = 'http://mijnuniekeservernaam/spotweb/';
}

**Comment by WzL** [comment]
The above solution is a workaround, the root cause of this issue lies in the getRequestProtocol funtion which is not called by lib/page/SpotPage_statics.php as is proposed in this change. Seems that the change for [issue 1569] (https://github.com/Spotweb/Spotweb/commit/33920a282764f7fb91a1b18eb8169c4d45e26177)  is applied only to  lib/SpotReq.php.

**Comment by Muis** [comment]
@WzL Can you make a commit for that?

**Comment by WzL** [comment]
Yeah sure, but i would like to call the function getRequestProtocol($protocol) in 'lib/SpotReq.php' by settings.php instead of using 
```php
(@$_SERVER['HTTPS'] == 'on' ? 'https' : 'http')
```
Why not make use of existing code instead of defining the same functionality on multiple locations?
So far my own tests return: Fatal error: 
```php
Call to undefined function getRequestProtocol() in /var/www/spotweb/settings.php on line 32:
```
My testcode:

```php
if (isset($_SERVER['SERVER_PROTOCOL'])) {
$settings['spotweburl'] = getRequestProtocol($protocol) . '://' . @$_SERVER['HTTP_HOST'] . (dirname($_SERVER['PHP_SELF']) != '/' && dirname($_SERVER['PHP_SELF']) != '\\' ? dirname($_SERVER['PHP_SELF']). '/' : '/');
} else {
$settings['spotweburl'] = 'http://mijnuniekeservernaam/spotweb/';
} # if
```
So I am still figuring out how to call getRequestProtocol($protocol) in settings.php. When i find out I will make that commit.

**Comment by WzL** [comment]
Git push origin master using a Github registred public key gives me: 

ERROR: Permission to spotweb/spotweb.git denied to WzL.

**Comment by WzL** [comment]
For the moment I am testing and it seams that i do not get images of the posts presented in my popup when i move the mouse over a post. Not sure if this is related to the above change, need to test more to identify the cause of this behavior.

**Comment by WzL** [comment]
Still testing, bug as stated above, in regards to hovering with the mouse over posts and the lack of images was due to differences between branches, so functionality as designed. Now experiencing retrieving issues using SSL connecting to USP. Could be caused by making use of a nightly version of PHP. So more testing from my side is required.

**Comment by anonymouz** [comment]
This is a Nginx config problem, not a spotweb problem. I have this up-and-running. This issue can be closed.

**Comment by WzL** [comment]
Can you please elaborate on details,  what is your situation and which software do you use?

**Comment by anonymouz** [comment]
I use Ubuntu 14.04, Nginx, PHP-FPM and MySQL. If you have Nginx for spotweb working on HTTP on port 80, then HTTPS on port 443 is just the same but with some SSL statements.

**Comment by WzL** [comment]
I understand that this particular usecase can be unclear/vague because of the separation of this issue over two separate github issues. This issue is not in regards to default SSL functionality on any web server, HTTPS/SSL on 443TCP just works in combination with the required webserver configuration.

This issue is in regards to a solution where two separate servers are involved:
1. Webserver (lighttpd) serving HTTP tcp80 (spotweb) content;
2. Proxyserver (nginx) offloading HTTPS tcp443 and forwarding HTTP tcp80 requests to Webserver (1), Webserver responds to Proxyserver HTTP tcp80, Proxyserver responding HTTPS tcp443 to client browser.

IT looks like your usecase described does not match the usecase I initially issued and am still testing. The HTTP header required and described, HTTP_X_FORWARDED_SSL, is for example responsible for presenting all URL's to be printed as HTTPS while the dataflow between webserver and proxyserver is still HTTP.

**Comment by avluis** [comment]
Sorry to revive this older issue, but after Synology pushed DSM 6.0 beta (which is separating the built-in Apache service with NGINX for hosting) I have been getting the same issues described here.
(Example here)[https://avnet.ws/spotweb/].

This install worked wonders with Apache with an SSL proxy, but moving to NGINX has made it all but difficult to work with. I hope some sort of workaround is put together for those not well versed with this issue.

**Comment by mesa57** [comment]
Can I close this issue ?

**Comment by WzL** [comment]
Yes, can be closed.

2016-03-16 11:46 GMT+01:00 mesa57 <notifications@github.com>:

> Can I close this issue ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/spotweb/spotweb/issues/45#issuecomment-197257009>
>



-- 
Met vriendelijke groet,

With kind regards,

Mit freundlichen Grüßen,

Distinti saluti,

Atentos saludos,


Jacco Onderdijk

**Comment by mesa57** [comment]
thx.
