### ISSUE TITLE
Cannot add new spots (please enter a description)

### ISSUE THREAD

**Issue by BigWebstas** [spotweb/spotweb#450]
Cannot add new spots the ui returns "please enter a description" i have tried entering data in every field to no avail.
![image](https://user-images.githubusercontent.com/2896329/66357155-0c419180-e92b-11e9-8744-0d10721fcde6.png)

I checked the logs folder it doesn't seem to log this as an error so nothing is returned. any assistance would be appreciated

**Comment by Sweepr** [comment]
I think the description and title are too short, did you try entering more information?

**Comment by mesa57** [comment]
No response lastr 8 days. Closing
