### ISSUE TITLE
[Feature Request] Spotweb behind reverse proxy (docker)

### ISSUE THREAD

**Issue by klara31** [spotweb/spotweb#451]
I would like to run Spotweb in a docker container. 
As I do not want to use a portnumber in my URL, I'd need to be able to get access via reverse proxy. Currently this is not working (or at least: I cannot get it working). 

The configuration of Spotweb would probably need a base-URL for this.

**Comment by mesa57** [comment]
I am not a docker expert, but normally docker should be able to map ports of the container to a port on the host. You can either map it then to port 80 or any other port. A reverse proxy which maps port 80 to the mentioned docker port should use the docker IP adres of you're docker container which contains spotweb.

**Comment by klara31** [comment]
The problem is that Spotweb only works if I map it to port 80 on the host. But that port is already in use...

**Comment by mesa57** [comment]
What error do you get if you map the container port 80 to another port ?

**Comment by klara31** [comment]
I do not get an error when linking a host port (9002) to container port 80. When surfing to http://app-server:9002/, spotweb is working correctly.

What I would like, is to be able to use a reverse proxy, so that I do not have to remember which port spotweb is running on. To do that, I want to use nginx reverse proxy. The config has the following:
```
location /spot {
    proxy_pass http://127.0.0.1:9002/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
```
When surfing to the server with URI http://app-server/spot/, spotweb renders as follows:
<img width="928" alt="Schermafbeelding 2019-10-15 om 14 30 56" src="https://user-images.githubusercontent.com/1309136/66831633-6e684b00-ef58-11e9-9c0f-dec5c288fee3.png">

**Comment by mesa57** [comment]
Try adding proxy_set_header X-Original-Request $request_uri;
to you're nginx

**Comment by mesa57** [comment]
If I run a local IIS server on port 81 and setup a nginx proxy to port 881 with this config :+1: 
```
   server {
	listen 881;
        server_name  vmphp;


        location / {
		proxy_pass http://localhost:81;
		proxy_set_header Host $host:$server_port;
		proxy_set_header X-Forwarded-For $remote_addr;
```

It works just fine without any change in code.

**Comment by klara31** [comment]
In this config, you are running spotweb on location / 
I am trying to run spotweb on location /spotweb

**Comment by klara31** [comment]
I can't get it working... can you share your nginx settings?

**Comment by mesa57** [comment]
Uh ? See previous message ....

**Comment by klara31** [comment]
previous message does not have paths, it uses only the root (/) not /spotweb
So if it does work with you, it must be something specific in my nginx settings, but which?

I have tried all possibilities (I think), but it just won't work :(

**Comment by mesa57** [comment]
Of course that location should exists on you're localhost server.

**Comment by klara31** [comment]
I am running Spotweb in a docker container (jgeusebroek/spotweb:latest). In this container, spotweb is running on port 80 on /.

The host (linux) is running nginx on port 80. On my host I forward port 9002 to port 80 (docker run -p 9002:80 ....).

When accessing http://host:9002/ spotweb works OK
When accessing http://host/spotweb (so via nginx reverse proxy) I get the result as depicted above

**Comment by mesa57** [comment]
As location /spotweb is not present on the localhost you cannot access it.
I am not and nginx specialist, but I think you need rewrite rules to accomplish that.,
With that I cannot help you.

**Comment by klara31** [comment]
The location /spotweb on the host is defined in the reverse proxy settings from nginx:
```
location /spotweb {
    proxy_pass http://127.0.0.1:9002/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
```

**Comment by mesa57** [comment]
These are important btw : 
		proxy_set_header Host $host:$server_port;
		proxy_set_header X-Forwarded-For $remote_addr;

**Comment by mesa57** [comment]
Btw it only works if you're webserver (docker) know the location /spotweb which is doen't,
So you need rewrite rules.

**Comment by klara31** [comment]
> These are important btw :
> proxy_set_header Host $host:$server_port;
> proxy_set_header X-Forwarded-For $remote_addr;

With those, it still does not work, same result...

**Comment by mesa57** [comment]
Try to change the docker location to localhost/spotweb and it will work.
(tip : see apache config file).

**Comment by mesa57** [comment]
If have changed code to support different locations (source vs target) in nginx reverse proxy configuration.
You have to checkout the develop branch and add to nginx conf : 

proxy_set_header X-Forwarded-Uri $request-uri

**Comment by Longshot** [comment]
I'm having the same problem. 
CSS is messed up behind NginX reverse proxy.

This is my config

server {
        listen 443 ssl;
        server_name spotweb.domain.com;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        location / {
                proxy_pass http://192.168.2.151:80;
                proxy_set_header X-SSL 'on';
                proxy_set_header X-Forwarded-Uri /spotweb;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Uri $request-uri;
                proxy_connect_timeout 150;
                proxy_send_timeout 100;
                proxy_read_timeout 100;
                proxy_buffers 4 32k;
                client_max_body_size 8m;
                client_body_buffer_size 128k;
        }

I'm on Master and can't seem to switch to another branch (git only shows master).

**Comment by mesa57** [comment]
I see X-Forwarded-Uri twice in you're config. Only the secon is valid.

**Comment by Longshot** [comment]
It still doesn't work after taking out the first one.

https://spotweb.domain.com/install.php
and
https://spotweb.domain.com/api?t=c
do work but the latter has something weird in it:
<server version="0.1" title="Spotweb" strapline="Spotweb API Index" email="jlp@starfleet.cum (Jean-Luc Picard)" url="https://spotweb.domain.comGET /api?t=c HTTP/1.1-uri/" image="https://spotweb.webjunkie.nlGET /api?t=c HTTP/1.1-uri/images/spotnet.gif" type="Spotweb"/>

Also, if I click on "Add user" it tries to load
https://spotweb.domain.comget%20/?api%20HTTP/1.1-uri/

Weirdness is going on :)

**Comment by pug306d** [comment]
this config is working ok for me where spotweb is my container name and resolves by dns

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name spotweb.*;

	add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
	
	location / {
		proxy_pass http://spotweb:80;
		proxy_set_header X-SSL 'on';
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_connect_timeout 150;
		proxy_send_timeout 100;
		proxy_read_timeout 100;
		proxy_buffers 4 32k;
		client_max_body_size 8m;
		client_body_buffer_size 128k;
		}
}

**Comment by correctomundo79** [comment]
If someone still has issues with Spotweb behind NPM, I too had the CSS issue, but solved it by adding a custom location '/' and adding the following:

proxy_set_header Early-Data $ssl_early_data;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Host $host;
proxy_set_header X-Forwarded-Proto https;
proxy_set_header X-Forwarded-Ssl on;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-SSL 'on';

**Comment by TrueOsiris** [comment]
Just fixed a working spotweb behind my traefik reverse proxy.

ownsettings.php:
```
<?php
   $settings['ssloverride'] = true;
?>
```

traefik:
routers.yml:
```
tcp:
  routers:
    router_spotweb:
      rule: "Host(`spotweb.example.com`)"
      entrypoints:
        - websecure
      tls:
        certResolver: godaddy1
        domains:
          - main: "example.com"
            sans:
              - "*.example.com"
      service: "service_spotweb"
      priority: 1097
      middlewares:
        - "middleware_header_XForwarded"
```
middlewares.yml:
```
http:
  middlewares:
    middleware_header_XForwarded:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          X-Forwarded-Uri: "/"
```
services.yml:
```
http:
  services:
    service_spotweb:
      loadBalancer:
        servers:
          - url: http://10.10.0.6:8100
```
