### ISSUE TITLE
Missing 'highlight' index in an array causing a lot of notice warnings before content

### ISSUE THREAD

**Issue by CptChaos** [spotweb/spotweb#454]
Today I updated Spotweb since some time again (I'm now at `8ccae2d3`).
For some reason I now get the following error:

```Notice: Undefined index: highlight in /var/www/spotweb/lib/services/Settings/Services_Settings_Container.php on line 62```

I tried to check-out a few older versions, but the problem persists.
The machine which runs Spotweb is running on Debian (testing), with PHP version `PHP 7.3.10-1+b1` through Nginx (and thus using PHP FPM).

If there's anything I have to do to fix this (as my Googlefu didn't result in anything), I would be glad to try! :)

New posts do show up, after a long list of notices, I made a screenshot of a selection:
![image](https://user-images.githubusercontent.com/650746/68164731-ecb77c00-ff5d-11e9-835e-d555c1c78130.png)

**Comment by Sweepr** [comment]
Yes, did you run upgrade-db.php after updating?

**Comment by CptChaos** [comment]
Hi @Sweepr! Thanks for your reply! No, I did not run the update script, as normally there would be a warning about it and I didn't receive that. Will try that now and let you know if it worked!

**Comment by Sweepr** [comment]
True, i need to consider the option to show a message in case you need to run upgrade-db.

Normally it's best to run upgrade-db.php once after upgrading at any time.

**Comment by Sweepr** [comment]
I forgot to update bootstrap.php in this case, closing as it's fixed in: https://github.com/spotweb/spotweb/commit/5ef9da573bf87f7d289217ec148cb4f10e604f71
