### ISSUE TITLE
notifications removed, spotwebversioncheck should be updated

### ISSUE THREAD

**Issue by mesa57** [spotweb/spotweb#455]
Currently give notifications :
https://p39.f2.n0.cdn.getcloudapp.com/items/geuYme70/Foutmeldingen+spotweb.png?v=1f41ea8de134586276730f1843fee14f

**Comment by Sweepr** [comment]
I commited that in dev branch: https://github.com/spotweb/spotweb/commit/45dc75020be5c9b4fac9899c9460aede87a8d0ad#diff-04966ad8bece91d86289d50783ca13fb

**Comment by Sweepr** [comment]
Just removed the enite tab from showing, be left the rest intact just incase we decide to revert.

**Comment by mesa57** [comment]
Ehhh, what about those messages from spotwebversioncheck.php (in /lib) ?

**Comment by Sweepr** [comment]
When the entire tab is removed then spotwebversioncheck.php isn't being called, so tge messages are not showing or generating error's, but that a problem if you are still on master branch now..  b.t.w. i don't know why "notifications.xml" is missing from master branch, i only removed it from dev i believe.

**Comment by mesa57** [comment]
If it's true what you say the whole spotwebversioncheck.php can be removed.
However, is that not also used to give a signal when upgrade-db.php should be runned ?

**Comment by Sweepr** [comment]
There are catch exceptions in index.php on : https://github.com/spotweb/spotweb/blob/90526122d8069d0937f3835e12379c9c835b370c/index.php#L423 https://github.com/spotweb/spotweb/blob/90526122d8069d0937f3835e12379c9c835b370c/index.php#L427 and https://github.com/spotweb/spotweb/blob/90526122d8069d0937f3835e12379c9c835b370c/index.php#L431

As case of test i just renamed `/lib/SpotWebVersionCheck.php` into `/lib/_SpotWebVersionCheck.php `

Upped https://github.com/spotweb/spotweb/blob/90526122d8069d0937f3835e12379c9c835b370c/lib/Bootstrap.php#L7 into define('SPOTWEB_SETTINGS_VERSION', '0.50'); just a higher number then currently in DB. refreshed spotweb anmd it showed me: 

![afbeelding](https://user-images.githubusercontent.com/2857865/68335169-42b22e00-00dc-11ea-8665-26e036932321.png)

So /lib/SpotWebVersionCheck.php isn't needed.

**Comment by mesa57** [comment]
Nice :thumbsup:

**Comment by mesa57** [comment]
Btw. we should consider merging develop with master soon.

**Comment by Sweepr** [comment]
True, b.t.w. the actual check is performed in bootstrap.php on line https://github.com/spotweb/spotweb/blob/5ef9da573bf87f7d289217ec148cb4f10e604f71/lib/Bootstrap.php#L146

**Comment by Sweepr** [comment]
Merging dev into master soon, closing as this will be fixed in next release.
