### ISSUE TITLE
settings problem

### ISSUE THREAD

**Issue by ikkeenjij36** [spotweb/spotweb#456]
Hi ,when i go to settings/spotweb updates in my spotweb i get this error message so now i can't set date for spots date.

`Warning: file_get_contents(https://raw.github.com/spotweb/spotweb/master/notifications.xml): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in /volume1/web/spotweb/lib/SpotWebVersionCheck.php on line 58 Notice: Trying to get property of non-object in /volume1/web/spotweb/lib/SpotWebVersionCheck.php on line 78 Notice: Trying to get property of non-object in /volume1/web/spotweb/lib/SpotWebVersionCheck.php on line 78 Warning: Invalid argument supplied for foreach() in /volume1/web/spotweb/lib/SpotWebVersionCheck.php on line 78 Notice: Undefined offset: 0 in /volume1/web/spotweb/lib/page/SpotPage_versioncheck.php on line 15`
How can i resolve this?

**Comment by Sweepr** [comment]
Check: https://github.com/spotweb/spotweb/issues/455

Or wait untill we merge dev into master.

**Comment by ikkeenjij36** [comment]
> Check: #455
> 
> Or wait untill we merge dev into master.

ok will wait for new master and then i should do a upgradedb.php?

**Comment by Sweepr** [comment]
If spotweb say's then yes, we will merge dev into master probably this week.

**Comment by ikkeenjij36** [comment]
> If spotweb say's then yes, we will merge dev into master probably this week.

ok thanks will be waiting for the update

**Comment by Sweepr** [comment]
Merging dev into master soon, closing as this will be fixed in next release.
