### ISSUE TITLE
Unable to run upgrade-db.php without (installed) database (useful for Docker)

### ISSUE THREAD

**Issue by edv** [spotweb/spotweb#459]
I have a Docker container that uses the upgrade-db.php script to initialize the database (so the Spotweb installer is not required). This was working until recently, when the following change was made:

https://github.com/spotweb/spotweb/blob/develop/bin/upgrade-db.php#L46

Without this specific line the database structure will be added to the database and the Spotweb installation (again, for this Docker container) is working. However, the script now crashes, as it expects the `usenetstate` table.

Is there any chance this change can be reverted or modified? (ps: see https://github.com/edv/docker-spotweb/ for this docker setup). Or is there anything I can help with to make this work again?

**Comment by Sweepr** [comment]
You are using that script to do something it was not designed for to do.

It's possible to keep an older version of the upgrade-db.php in your docker spotweb repo.

If users are going to utilize scripts in other ways then for the purpose they ate designed we cannot prevent breaking change's from happening.

**Comment by edv** [comment]
I totally agree, I'm just looking into options on how to resolve this (as the Docker container is a really easy way to get started with Spotweb). I will have a look at a more permanent solution 👍

**Comment by Sweepr** [comment]
Can you try to remove line 46 and placing it in line 127 and 179, and see if that fixes your problem?

**Comment by edv** [comment]
For now I will use the current upgrade-db.php and change the line with $isRetrieverRunning (when the container is build). For now this will resolve this problem, but maybe I should just stop trying to automate the installation using this script (as I have no idea when new changes will be made, which might break the workaround again).

Thanks for the quick feedback by the way!

**Comment by Sweepr** [comment]
No problem,. maybe if you could try this commit and see if that fixes it for you?

https://github.com/spotweb/spotweb/commit/af271e9c7de58e7b1c5dc0aee7fcb5efc3d598e6

**Comment by Sweepr** [comment]
Did this work for you?

Please let me know, then i will either revert or leave the change and close this issue?

**Comment by edv** [comment]
It's working perfectly! Thanks for the fast reply and fix, I appreciate it!

**Comment by Sweepr** [comment]
Perfect, closing.. be aware this won't be in master untill next merge.
