### ISSUE TITLE
Posting spot issue

### ISSUE THREAD

**Issue by Sweepr** [spotweb/spotweb#46]
In the past under the original Spotweb i fixed an issue where after pressing the Add button the text would be cleared from the "Add spot", Currently after pressing "Add spot " it looks like nothing happens, but the spot get's posted like normal.

Apparently this was never commited into the newer branches and since the original tree has been deleted the issue remains, sadly i forgot half about what the fix was.. all i know that there is a $ missing infront of a "article" variable somewhere,  "article" ,must be "$article", but i don't remember where.

I have been searching for a few hours compairing files one by one using my old install (v0.67.28.31) over the new install (v0.68.29.32) but for now and untill now i am unable to locate the bugged file, some help would be appreciated.

Does anyone have a clue or maybe you could digg through your archive and see if you can find this fix?

**Comment by Sweepr** [comment]
After searching i could not find any file that was different, investigating the error_log showed me this;

PHP Warning:  Illegal string offset 'modulo', 
Which turns out i had the native PHP set to 5.5, after setting native to 5.3 the "Add spot" is working like intended and text got cleared.

**Comment by dsadsdadsadsadsds** [comment]
If Spotweb actually breaks using PHP 5.6 that is a bug and it should be fixed. Do you happen to have more information about that notice?

**Comment by Sweepr** [comment]
Only thing i could find was that error in the error_log: PHP Warning: Illegal string offset 'modulo', 

The error Illegal string offset 'whatever' in... generally means: you're trying to use a string as a full array.

That is actually possible since strings are able to be treated as arrays of single characters in php. So you're thinking the $var is an array with a key, but it's just a string with standard numeric keys, for example:

$fruit_counts = array('apples'=>2, 'oranges'=>5, 'pears'=>0);
echo $fruit_counts['oranges']; // echoes 5
$fruit_counts = "an unexpected string assignment";
echo $fruit_counts['oranges']; // causes illegal string offset error

So somewhere the 'module' variable is illegal, question is where?

**Comment by Sweepr** [comment]
I just set the native PHP for the spotweb root to PHP 5.5, tried to post a spot, but i just did not get posted, no error, no error_log, nothing happend.

Set back to PHP 5.3 and the spot got posted.

**Comment by Sweepr** [comment]
Small update on this, before i said they did not get posted with PHP5.5 but the spots were posted with PHP 5.5 but the  text from the 'Add spot' form did not get cleared 

Set back to PHP 5.3 and the spot got posted and box got cleared

**Comment by dsadsdadsadsadsds** [comment]
The modulo error, did you get an notice or something?

From what you describe, the PHP throws an notice/reror/warning, and hence does not return the proper JSON/JS response when trying to update the spot. This does not trigger the correct code for clearing the UI and stuff, so first thing you should  do is trace down where / what error you are actually getting.

**Comment by Sweepr** [comment]
I'll have to try this and debug what actually happens on my test environment.

I'll update the results.

**Comment by dsadsdadsadsadsds** [comment]
In case you do not know this, or if anyone else bothers to read these sort of requests. An easy way to troubleshoot is to:

1. Open the 'Edit spot window'
2. Press F12 in your browser.
3. Go to the network tab.
4. Submit you edit.
5. Watch the request going to Spotweb.
6. Look at the response.

Spotweb is coded to always display errors, per default, so if an error occurs it should be visible in the network tab.

**Comment by Sweepr** [comment]
Ah yes, you mean in Firefox using Firebug?, using that, best tool ever!

**Comment by Sweepr** [comment]
I have an update:

Previously i did not have mysqli added to the PHP config so the error vanished.
Yesterday i added mysqli plugin to the PHP compile and it's back.

The textbox is not being cleared, so no confirmation spot has been posted, altough the spots do appear on spotweb.

These are the error's i get:

Europe/Amsterdam] PHP Warning:  Illegal string offset 'modulo' in /home/sinistra/public_html/nzbstars/lib/page/SpotPage_postspot.php on line 94
Europe/Amsterdam] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/sinistra/public_html/nzbstars/lib/page/SpotPage_postspot.php:94) in /home/sinistra/public_html/nzbstars/lib/page/SpotPage_Abs.php on line 57
Europe/Amsterdam] PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/sinistra/public_html/nzbstars/lib/page/SpotPage_postspot.php:94) in /home/sinistra/public_html/nzbstars/lib/page/SpotPage_Abs.php on line 58
PHP Warning:  Cannot modify header information - headers already sent by (output started at /home/sinistra/public_html/nzbstars/lib/page/SpotPage_postspot.php:94) in /home/sinistra/public_html/nzbstars/lib/page/SpotPage_Abs.php on line 80

Does anone have a clue what this is?
Later on i'll try to figure out what's wrong here.

adding mysqli to PHP breaks the posting form.

**Comment by Sweepr** [comment]
After some trial and error i figured out that it was not the mysqli addon that breaks the spot posting form, but actually it is due to PHP Version 5.5.24.

Using:

<?php
// Show all information, defaults to INFO_ALL
phpinfo();
?>

I found out that spotweb was actually running on PHP Version 5.5.24. 
Adding this to htaccess:

AddHandler application/x-httpd-php53  .php53 .php

Make's sure spotweb runs on PHP Version 5.3.28 and now the form is being properly cleared.
I have absolutly no idea why PHP5.5 breaks to form, maybe someone else does?

**Comment by dsadsdadsadsadsds** [comment]
Interesting. Is this the media branch? If so, please add (just before the current line of 94) a 

````php
var_dump($this->_currentSession['user']['publickey']));
````

Do not post the output unsanitized here because it contains your key, but mangle some bits in the output and then post it here. Of course, do this with PHP 5.5

**Comment by Sweepr** [comment]
Yes this is the media branch, but which file do you want me to put this code?

**Comment by jb044** [comment]
Switched explicitly to the mediainfo branch, now the spot gets posted. That is the entry page reloads and all fields are empty as expected after a succesfull post.

Php 5.4.16 as bundled with CentOS 7.1 chokes on the nzb when posted, hhvm 3.6.2 returns a blank nzb. Seems kind of silly to revert to 5.3 just for spotweb.... ;)

**Comment by Sweepr** [comment]
@jb044 

Which version of PHP do you have for spotweb?
I set the native PHP handler to PHP5.3 especially for spotweb.

**Comment by jb044** [comment]
Currently I Use hhvm 3.6.2 (identifies itself as php 5.6.99) and spots seem to post but the nzb posted is rubbish :( Normally I use a slightly patched [1] php-5.4.16, same results. With the latest mediainfo revision the 'modulo' index does seem to exist but as mentioned it doesn't work anyway.

1 Just CentOS SRPM augmented with 1 upstream patch that enables urls like index.php/arg1/arg2 and applies cleany.

**Comment by jb044** [comment]
The real problem is I need to really spot and provide the community with rubbish, as you probably know the community isn't what it once was so this isn't appreciated at all!

Any way arround that?

**Comment by Sweepr** [comment]
I don't understand your story at all, you say you really need to spot and provide the community with rubbish?

We don't want rubbisch..

**Comment by jb044** [comment]
Ah, I mean I've got a working nzb (tested it before spotting it), after the spot I get xml parse errors. So somehow it gets scrambled. Simply editting an existing spot doesn't do much, or am I mistaken?

For now I work arround this by also providing a nzbindex.nl nzb link.

**Comment by Sweepr** [comment]
Aha, now i understand, best work around to get everything working normally is to reverted to PHP5.3, this works, and the NZB's are posted correctly.

Therefor i added: "AddHandler application/x-httpd-php53 .php53 .php" into my .htaccess so i'm running on PHP Version 5.3.28

Untill now there has not yet been a fix or found out what's causing this problem.

Editing spots only applies local, so inside YOUR database, no change's made to the usenet groups

**Comment by jb044** [comment]
Hmm, could you elaboate a bit. I guess just that one-liner doesn't do all the magic ;)
And did you manage to do that cleanly on a CentOS 7 machine?

**Comment by Sweepr** [comment]
@jb044 
Well first of all you need to have PHP5.3 installed next to PHP5.5 duh, my guess is you have?

You added this without the qoutes to you .htaccess file? 

AddHandler application/x-httpd-php53  .php53 .php

**Comment by Sweepr** [comment]
You could use this as a reference:

PHP 5.5.x and 5.6.x will be used there, but you can replace them with other versions.

http://www.sitepoint.com/run-multiple-versions-php-one-server/
http://nathangiesbrecht.com/install-multiple-versions-php-centos-7

Or search on google how to Add multiple php support on Centos 7

**Comment by jb044** [comment]
Hmm sounds like a lot of trouble for something that imho should be fixed, 5.3 is getting really old now! And stepping away from proper package management and security support, which I rather avoid.

Will try to debug this a bit further without actually posting scrambled nzb's to usenet

**Comment by Sweepr** [comment]
I agree, this should be fixed, but i'm not able to figure this out, have not got the knowledge to do so, maybe someone else can..

**Comment by jb044** [comment]
Seems the nzb JBinUP provided isn't valid after all, at least not always (it just worked in my usenet grabber though). It seems spotweb expects iso-8891-1 not utf-8 for one, and also the nzb JBinUp provides has no DTD set.

For now I will just work around this by waiting for a proper nzb to show up on nzbindex.nl

To sum it up: 
- at first I got the modula error, which led me to this issue
- since then I did explicitly checkout the mediainfo branch
- error gone

Are you sure you use this branch?

**Comment by Sweepr** [comment]
Ah yes, i'm sure i use this media branch.

Posting goes fine using PHP5.3 as AddHandler in .htaccess, but whenever i switch to PHP 5.4 or PHP5.5 this error occurs.

**Comment by mesa57** [comment]
Is this bug still present in the master branch ?

**Comment by Sweepr** [comment]
https://github.com/spotweb/spotweb/commit/ad0471ee924c9d2b5e38a0a86a319bbb9d31420d
