### ISSUE TITLE
Retrive keeps crashing spotweb 

### ISSUE THREAD

**Issue by sojab0on** [spotweb/spotweb#462]
Hi my spotweb keeps crashing on retriving spots with 
SpotWeb v0.68.31.33 on PHP v7.4.2 crashed

Fatal error occured retrieving reports:
  HY000: 1364: Field 'id' doesn't have a default value

What can i do to fix this ?

**Comment by Sweepr** [comment]
https://lmgtfy.com/?q=HY000%3A+1364%3A+Field+%27id%27+doesn%27t+have+a+default+value

**Comment by sojab0on** [comment]
already tried that but i dont know in witch table so dont try and mok me botther me with that kind of things and just close the tread

**Comment by Sweepr** [comment]
We are willing to help everyone with problems but you give us little to nothing to work with and think we have somekind of magic mirror which magically gives you the solution to your problem.

Only leads we have are: SpotWeb v0.68.31.33 on PHP v7.4.2 that's it.

What have you tried yourself?
What is your operating system?
Which SQL do you use?
Did it work before?
What did you do before it stopped working?
When did it work?
What did you do prior to the malfuntion?

And so on..

So yeah, don't blame us.

**Comment by Sweepr** [comment]
Solution 1

MySQL is most likely in STRICT SQL mode. Try to execute SQL query SET GLOBAL sql_mode='' or edit your my.cnf / my.ini to make sure you aren't setting STRICT_ALL_TABLES and/or STRICT_TRANS_TABLES.
Solution 2

If Solution-1 is not working then try Solution-2 as given in below steps:

    Run MySQL Administrator tool as Administrator.
    Then go to Startup Variable.
    Then go to the Advance tab.
    find SQL Mode and remove the STRICT_ALL_TABLES and/or STRICT_TRANS_TABLES and then Click on Apply Changes.
    Restart MySQL Server.
    Done.

**Comment by sojab0on** [comment]
Strange thing is that if i look for sql_mode it has no value set 

I run on Windows 10 pro X64 
I run My SQL comunity edition 8.0.18

I have searched this error but all i coudl find was same as you gave but most go from that it is an id in a spesific table, but retrive doesnt give back that.

Migrated to a new system spotweb never had this on my previous system witch was windowsserver 2012 

i just installed My SQL server and php 7.4.2 and setup spotweb after that every time i tried retriving spots it craches.

**Comment by Sweepr** [comment]
Does this line show in you my.cnf?

Alternatively you can comment out the above line and add the sql_mode line to your system MySQL config at /etc/my.cnf:

[mysqld] sql_mode = ""

**Comment by Sweepr** [comment]
And restart the sql service.

**Comment by sojab0on** [comment]
done that and it stated the strict table things removed that and saved my.ini and restarted the mysql service 
running retrive now to check if it can finsich now

**Comment by Sweepr** [comment]
And? any news on this issue?

Is it working?

**Comment by sojab0on** [comment]
It was running with retrieving spots and comments for quite some time but havent checked was gone for 1 day yesterday

**Comment by Sweepr** [comment]
Alright, no problem, just let us know if it's resolved so we can close the issue

**Comment by Sweepr** [comment]
Since no feedback has been received in over 9 day's i'll assume this has been resolved.
Closing the issue, feel free to re-open is needed.

I hate it when people stop giving feedback.

**Comment by sojab0on** [comment]
It was running fine, but sometines has issues with comments. 

But it overcomes that by it self so in deed no porblems any more
