### ISSUE TITLE
Coding errors in retrieve.php

### ISSUE THREAD

**Issue by hr1232** [spotweb/spotweb#464]
retrieve.php works, but keeps hitting the following warnings:
```
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /httpdocs/spotweb.me/lib/services/Format/Services_Format_ParsingLegacy.php on line 48
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /httpdocs/spotweb.me/lib/services/Format/Services_Format_ParsingLegacy.php on line 56
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /httpdocs/spotweb.me/lib/services/Format/Services_Format_ParsingLegacy.php on line 113
```

also, there deprecated syntax ist being used:
```
Deprecated: Array and string offset access syntax with curly braces is deprecated in /httpdocs/spotweb.me/lib/SpotCommandline.php on line 70
Deprecated: Array and string offset access syntax with curly braces is deprecated in /httpdocs/spotweb.me/lib/SpotCommandline.php on line 73
Deprecated: Array and string offset access syntax with curly braces is deprecated in /httpdocs/spotweb.me/lib/SpotCommandline.php on line 87
```

Warnings are produced by PHP 7.3

**Comment by Sweepr** [comment]
What happens when you run `composer update` from the spotweb root folder?

**Comment by hr1232** [comment]
Look at the messages.

Messages about deprecated syntax are no composer problem. They are what they are, use of deprecated syntax that once was ok, but is about to be phased out. Curly braces were ok in PHP5, now we have PHP7 and they need to be removed from the code. With PHP8, that code will not work anymore.

As for the warning, using continue from within a switch block has never been ok. Use break instead.

**Comment by mesa57** [comment]
For the time being we keep supporting php 5.

**Comment by hr1232** [comment]
Curly braces have been deprecated since 2008 [1], i.e. PHP 5.1. Last Version of PHP5 was published a decade later. To run your code without warnings, one has to use a PHP version with 12 years of security holes.

Using continue withing switch was *NEVER* correct. Even 12 years ago, that was broken code.

[1] https://wiki.php.net/rfc/deprecate_curly_braces_array_access

**Comment by hr1232** [comment]
Fixing the curly braces is easy, patch can be found here:
https://github.com/spotweb/spotweb/compare/develop...hr1232:patch-1

**Comment by hr1232** [comment]
And here is the fix for the break/continue error. continue does exactly the same as break, but it produces a warning. continue is meant to be used as `continue 2` or `continue 3` because it can exit not only the switch statement, but also the while that is around it (if used as `continue 2`) or even the switch that is around the while statement (if used as `continue 3`).
https://github.com/spotweb/spotweb/compare/develop...hr1232:patch-2

**Comment by Sweepr** [comment]
@mesa57 

What are the concequences for users if we change this?

We should fix this, we can no longer run outdated code like this just because updating to the correct syntax might break user's installation's running PHP5, that's their problem, not ours.

What do you think?

**Comment by mesa57** [comment]
I am not going to spend any energy in this until needed.
In my opinion php 5 should still be supported by spotweb.

**Comment by hr1232** [comment]
> What are the concequences for users if we change this?
Not getting errors, warnings, and deprecation notices about stoneage-syntax.

> We should fix this, we can no longer run outdated code like this just because updating to the correct syntax might break user's installation's running PHP5, that's their problem, not ours.
It won't break outdated PHP5-installations. Correct syntax will also run in PHP5.

> I am not going to spend any energy in this until needed.
> In my opinion php 5 should still be supported by spotweb.
Who (except you) said anything about breaking PHP5-support?
True, your curly-braces-syntax has been deprecated for 12 years and the `break`/`continue` use has always been wrong. After the patches, the code will still work in PHP5. However, PHP7 will also run it without telling users, that the code is deprecated and/or broken.

BTW: When was the last security fix for PHP5? Everybody with a modicum of sense for security has moved past PHP5 years ago. However, everybody who wants to keep their server open to all kindes of attack may still do that. **After the patches, *ALL* versions of PHP5 will still be able to run the code and current versions of PHP will run it without complaints about broken stoneage-code.**

**Comment by mesa57** [comment]
Please be not offended. You are welcome to create the changes necessary and push them to develop if tested thoroughly from php 5.4 to 7.4

**Comment by hr1232** [comment]
Who's offendet? I'm not the one behaving as I were offended.

Necessary changes to remove the **broken** code have already been submitted (see above).

**Comment by mesa57** [comment]
That was only for the curly braces and not for the continue / switch.

**Comment by hr1232** [comment]
look again, there are 2 patches

**Comment by Sweepr** [comment]
Created 2 pull-requesrts and merged both patches into develop.

https://github.com/spotweb/spotweb/pull/465

https://github.com/spotweb/spotweb/pull/466

> After the patches, ALL versions of PHP5 will still be able to run the code and current versions of PHP will run it without complaints about broken stoneage-code.
