### ISSUE TITLE
How to use ssl and reverse proxy

### ISSUE THREAD

**Issue by behtjes** [spotweb/spotweb#470]
I'm using a synolody ds218+ with docker. I've installed spotweb, this works fine. But when I use a reverse proxy, css and js is broken. I'v read the following from https://github.com/spotweb/spotweb/wiki/Installation-tips-and-troubleshooting :

> Best solution for this is to include an extra header in the proxy configuration : X_SSL Example:
> 
> proxy_set_header X-SSL 'on';
> 

But I have no idea how to implement this? Do I need putty or something? Please help me out :-)

**Comment by mesa57** [comment]
Needs to be set in you're nginx reverse proxy configuration.

**Comment by Sweepr** [comment]
I think the better place for this question is here: https://community.synology.com/enu/forum/1/post/121960

If you ask your question over there, they might know the answer.

**Comment by Sweepr** [comment]
Closing, not a spotweb issue, merely an local Nginx configuration issue.

**Comment by mesa57** [comment]
Ha, ok. It was not an issue but categorized as 'Help wanted' 😉

**Comment by behtjes** [comment]
Found it in reverse proxy settings. I didn't know there was an option to add a custom header to the proxy rule. I've added X-SSL with the value on, and it's working!

Thanks

**Comment by Sweepr** [comment]
Thank you for letting us know!
