### ISSUE TITLE
The condition $filterColCount == 3 is always false.

### ISSUE THREAD

**Issue by Sweepr** [spotweb/spotweb#472]
see https://scrutinizer-ci.com/g/spotweb/spotweb/inspections/161c54ce-e932-4081-b876-0803658352e8/issues/files/templates/we1rdo/includes/filters.inc.php?status=new&orderField=path&order=asc&fileId=templates/we1rdo/includes/filters.inc.php&messageId=php_analyzer.type_inference.infeasible_condition.generic&honorSelectedPaths=0&issueId=43545159#inspectioncomment-154613886

**Comment by Sweepr** [comment]
Very strange, because the variable `$filterColCount` is being set to `4` in line 157:: https://github.com/spotweb/spotweb/blob/e121beaf429b1ddc809952d31e9c37e773ee7775/templates/we1rdo/includes/filters.inc.php#L157

Then, on line 163: https://github.com/spotweb/spotweb/blob/e121beaf429b1ddc809952d31e9c37e773ee7775/templates/we1rdo/includes/filters.inc.php#L163

```
<ul class="search <?php if ($filterColCount == 3) {
    echo ' threecol';
} else {
    echo ' fourcol';
} ?>">
```

`$filterColCount == 3 ` is always `false`;

Any need for this if/else statment?

**Comment by mesa57** [comment]
No, leftover from testing I guess.

**Comment by Sweepr** [comment]
Ok, i'll put this on the todo list. :+1:
