### ISSUE TITLE
notices on php7.4

### ISSUE THREAD

**Issue by jb044** [spotweb/spotweb#474]
Apparently with php 7.4 (and possibly postgresql which I use) the db fetch command in singleQuery in /var/www/spotweb/lib/dbeng/dbeng_pdo.php can return false and not an array. If I add:
`if (!is_array($row)) {
    return;
}
`
Before:
`return $row[0];`

All is fine.

**Comment by Sweepr** [comment]
Do you see the same notices as in this issue? https://github.com/spotweb/spotweb/issues/467

If so, then this should already be fixed in the Develop branch: https://github.com/spotweb/spotweb/commit/0cc72fedc63b1f32c25544cab60121fe6852dd70

**Comment by jb044** [comment]
Thank you, you are right!
