### ISSUE TITLE
break is not strictly necessary here and could be removed. 

### ISSUE THREAD

**Issue by Sweepr** [spotweb/spotweb#475]
see https://scrutinizer-ci.com/g/spotweb/spotweb/issues/develop/files/lib/dbeng/dbeng_abs.php?orderField=path&order=asc&honorSelectedPaths=0&issueId=43543417#inspectioncomment-154601647

**Comment by Sweepr** [comment]
According Scrutinzer `break;` is not strictly necessary here and could be removed in:

https://github.com/spotweb/spotweb/blob/87613bb99f0ad2e4637b87a75f9ad4073c421fc3/lib/dbeng/dbeng_abs.php#L15-L22

```
		switch ($engine) {
			case 'mysql'		:
			case 'pdo_mysql'	: return new dbeng_pdo_mysql(); break; 
			case 'pdo_pgsql' 	: return new dbeng_pdo_pgsql(); break;
			case 'pdo_sqlite'	: return new dbeng_pdo_sqlite(); break;

			default				: throw new Exception("Unknown database engine (" . $engine . ") factory specified");
		} // switch
```

According: https://rules.sonarsource.com/php?search=switch this is non-compliant.

Compliant Solution

```
switch ($param) {
  case 0:
    doSomething();
    break;
  case 1:
    doSomethingElse();
    break;
  default:
    error();
    break;
}

```

@mesa57, if i remove the break; from each case in the switch it will check all untill a match is found, or use the `default`. if not as soon as a match for a case is found i will break from the switch.

Question: would it do any harm if i remove the `break`;

```
		switch ($engine) {
			case 'mysql'		:
			case 'pdo_mysql'	: return new dbeng_pdo_mysql();
			case 'pdo_pgsql' 	: return new dbeng_pdo_pgsql();
			case 'pdo_sqlite'	: return new dbeng_pdo_sqlite();

			default				: throw new Exception("Unknown database engine (" . $engine . ") factory specified");
		} // switch
```

**Comment by mesa57** [comment]
That would be fine.

**Comment by Sweepr** [comment]
PR merged!
