### ISSUE TITLE
The condition $userVerified is always false. 

### ISSUE THREAD

**Issue by Sweepr** [spotweb/spotweb#479]
IssueId: 43543407  Message: The condition ``$userVerified`` is always ``false``.  Filename: lib/SpotInstall.php  LineNumber: 324  Link: https://scrutinizer-ci.com/g/spotweb/spotweb/code-structure/develop/class/SpotInstall?issueId=43543407

**Comment by Sweepr** [comment]
The condition $userVerified is always false, is that for a reason?

In line 275 of this file: https://github.com/spotweb/spotweb/blob/57c03fb8e05c2074a9f1f1083b503d967350e617/lib/SpotInstall.php#L275  the variable `$userVerified = false;`  is set.

In lines 324-L329 : https://github.com/spotweb/spotweb/blob/57c03fb8e05c2074a9f1f1083b503d967350e617/lib/SpotInstall.php#L324-L329

```
        if (!$userVerified) {
            static::showTemplate('step-004.inc.php', [
                'form'         => $form,
                'userVerified' => $userVerified
            ]);
        }
```

**Comment by mesa57** [comment]
is userVerified not used or set in step-004.inc.php ?

**Comment by Sweepr** [comment]
@mesa57 I just looked but no reference about that variable..

I'll test this tomorrow to see what happens if removed.

**Comment by mesa57** [comment]
Looks indeed like some old leftovers.

**Comment by Sweepr** [comment]
Scrutinizer has found some more leftovers, unused code and other things, but i'm little anxious to fix them all at once. 

So i've started cleaning up slowly one by one, and keep testing inbetween.

**Comment by mesa57** [comment]
That's a good approach. Otherwise you don't know what to test anymore.

**Comment by Sweepr** [comment]
Fixed this in commit: https://github.com/spotweb/spotweb/commit/ab57d3d30f5480ac1624f778c007d42a95fd4db2

I have tested the installation and didn't run into any issue.
