### ISSUE TITLE
TMDB table's?

### ISSUE THREAD

**Issue by Sweepr** [spotweb/spotweb#49]
Can anyone explain me how and whatfor these table's are?

they are and stay empty,

There are these scripts: precacheTmdbInfo.php and queryTmdb.php 

-> php precacheTmdbInfo.php
Done precaching tmdb information collections  (that's it, table's stay empty)

-> php queryTmdb.php
queryTmdb.php - query tmdb distribution script

You have to give the filename as a parameter which you received first

??

tmdb_cast	Browse Browse	Structure Structure	Search Search	Insert Insert	Empty Empty	Drop Drop	~0	InnoDB	ascii_general_ci	48 KiB	-
	tmdb_credits	Browse Browse	Structure Structure	Search Search	Insert Insert	Empty Empty	Drop Drop	~0	InnoDB	ascii_general_ci	32 KiB	-
	tmdb_crew	Browse Browse	Structure Structure	Search Search	Insert Insert	Empty Empty	Drop Drop	~0	InnoDB	ascii_general_ci	48 KiB	-
	tmdb_images	Browse Browse	Structure Structure	Search Search	Insert Insert	Empty Empty	Drop Drop	~0	InnoDB	ascii_general_ci	32 KiB	-
	tmdb_info	Browse Browse	Structure Structure	Search Search	Insert Insert	Empty Empty	Drop Drop	~0	InnoDB	ascii_general_ci	32 KiB	-
	tmdb_trailers	Browse Browse	Structure Structure	Search Search	Insert Insert	Empty Empty	Drop Drop	~0	InnoDB	ascii_general_ci	32 KiB

**Comment by Muis** [comment]
The acronym 'tmdb' seems related to https://www.themoviedb.org/

So I think someone started to implement support for that database, but never finished it? Otherwise I have no clue.

**Comment by dsadsdadsadsadsds** [comment]
Recent Spotweb releases introduced something called collections (or mastercollections as it is called in the code).

If you run the most recent release, you can see the collection bit on the Spot details page (it automatically recognizes media and adds season/episode/etc selection to the system). If your system does not do this, please enable 'Create collections' on the settings page, and then run 'recreate-collections.php' on the CLI (it will take forever to run).

For the TMDB tables, this is related to those collecitons so it seems. If you run 'exportmc.php' to export the master collections, you then are able to fetch the TheMovieDb data using 'queryTmdb.php'  which seems to export it to some kind of CSV file. You then are able to import this using  'importMc.php'.  My guess as to why this is so convulated is that it can be made to run in parallel or something (exportmc allows to split the export file into multiple chunks).

I do think it is not finished yet (at all!), but it seems rather nice as it can also pre-cache a lot of TMDB information which has a lot of potential to further enrich the UI part of Spotweb.

By the way, do not bother doing this on your Synology, it is a real dog wrt performance and also do not do this if you are really attached to large freespace of your diskspace.

**Comment by Sweepr** [comment]
Yes, i have been playing around this this, but not in a synology ;-)

Anyway.. 

 php exportmc.php


SpotWeb crashed

Export of collections failed:
   42000: 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ON (mc.title, mc.year)
                                           mc.id AS mcid,' at line 1 (SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ON (mc.title, mc.year)
                                           mc.id AS mcid,' at line 1)


#0 /home/public_html/spotweb/lib/dbeng/dbeng_pdo.php(146): dbeng_pdo->exec('SELECT DISTINCT...', Array)
#1 /home/public_html/spotweb/exportmc.php(40): dbeng_pdo->arrayQuery('SELECT DISTINCT...')

So yes, indeed it's not finished yet. ;-)

**Comment by dsadsdadsadsadsds** [comment]
Try on PostgreSQL as the "distinct on" is a PostgreSQL specific bit, or rewrite the query to be compatible with MySQL.
