### ISSUE TITLE
Newznab imdb search not working (returning 301 for every imdb id)

### ISSUE THREAD

**Issue by jeroenbeuz** [spotweb/spotweb#494]
Since today the IMDB search does not work any more. Don't know if it's something in my configuration or that IMDB made some breaking changes. But this call for example:
`http://192.168.1.10/spotweb/api?imdbid=8579674&apikey=xxx&t=movie&extended=1&cat=2000`
Returns the following:
`<?xml version="1.0" encoding="utf-8"?>
<error code="301" description="IMDB information returned is invalid"/>`

I've tried a lot of movies but none seem to work. I'm running the latest master branch on a Raspberry Pi 4.

**Comment by mesa57** [comment]
Could well be as IMDB information is gathered via webscraping.

**Comment by Sweepr** [comment]
error code="301" means redirect. https://en.wikipedia.org/wiki/HTTP_301

**Comment by mesa57** [comment]
@jeroenbeuz : could you check php ini if open base dir is set ?

```
       // Only use these curl options if no open base dir is set and php mode is off.
        $manualRedirect = false;
        if (ini_get('open_basedir') != '') {
            $manualRedirect = true;
            curl_setopt($ch, CURLOPT_FOLLOWLOCATION, false);
            curl_setopt($ch, CURLOPT_MAXREDIRS, 1);
        } else {
            curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
        } // else
```

**Comment by jeroenbeuz** [comment]
Thanks for the quick response! 

The open base dir is not set in my php.ini. Maybe good to know, searching for tv shows does work.

**Comment by mesa57** [comment]
Ok. Clear. @Sweepr : the 301 is from the api redirect (.htaccess)

**Comment by mesa57** [comment]
@jeroenbeuz : the api call to imdb works fine here (returns 1917). So maybe something else is wrong with you're configuration.

**Comment by jeroenbeuz** [comment]
Do you have any idea as to what can cause this to happen?

**Comment by jeroenbeuz** [comment]
Thanks again for the help, really appreciate this and all the work you've done!

**Comment by Sweepr** [comment]
Here it's also working, can you share us your .htaccess file?
You also say searching for tv shows does work,

By default the .htaccess contains this:

```
<IfModule mod_rewrite.c>
	RewriteEngine on  
	RewriteCond %{REQUEST_URI} !api/  
	RewriteRule api/?$ index.php?page=newznabapi [QSA,L]  
</IfModule>

```

**Comment by jeroenbeuz** [comment]
I'm hosting Spotweb with Lighttpd. Here is my lighttpd.conf:
`server.modules  = (
        "mod_fastcgi",
        "mod_access",
        "mod_alias",
        "mod_accesslog",
        "mod_compress",
        "mod_redirect",
        "mod_rewrite"
)

server.document-root        = "/var/www/html"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/var/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 80

# strict parsing and normalization of URL for consistency and security
# https://redmine.lighttpd.net/projects/lighttpd/wiki/Server_http-parseoptsDetails
# (might need to explicitly set "url-path-2f-decode" = "disable"
#  if a specific application is encoding URLs inside url-path)
server.http-parseopts = (
  "header-strict"           => "enable",# default
  "host-strict"             => "enable",# default
  "host-normalize"          => "enable",# default
  "url-normalize-unreserved"=> "enable",# recommended highly
  "url-normalize-required"  => "enable",# recommended
  "url-ctrls-reject"        => "enable",# recommended
  "url-path-2f-decode"      => "enable",# recommended highly (unless breaks app)
 #"url-path-2f-reject"      => "enable",
  "url-path-dotseg-remove"  => "enable",# recommended highly (unless breaks app)
 #"url-path-dotseg-reject"  => "enable",
 #"url-query-20-plus"       => "enable",# consistency in query string
)

index-file.names            = ( "index.php", "index.html" )
url.access-deny             = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )

#For SpotWeb
url.rewrite-once = ( "^/spotweb/api\?(.*)" => "/spotweb/index.php?page=newznabapi&$1" )

compress.cache-dir          = "/var/cache/lighttpd/compress/"
compress.filetype           = ( "application/javascript", "text/css", "text/html", "text/plain" )

# default listening port for IPv6 falls back to the IPv4 port
include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
include_shell "/usr/share/lighttpd/create-mime.conf.pl"
include "/etc/lighttpd/conf-enabled/*.conf"

#server.compat-module-load   = "disable"
server.modules += (
        "mod_compress",
        "mod_dirlisting",
        "mod_staticfile",
)
`

**Comment by jeroenbeuz** [comment]
The following request is working without any problem:
`http://192.168.1.10/spotweb/api?apikey=xxx&t=movie&q=1917`
It only returns a 302 when I use the imdbid parameter.

**Comment by Sweepr** [comment]
Seems ok,

Does this work?

http://192.168.1.10/spotweb/index.php?page=newznabapi&$1imdbid=8579674&apikey=xxx&t=movie&extended=1&cat=2000

**Comment by jeroenbeuz** [comment]
That one is working, although I get lots of different movie in the response.

**Comment by mesa57** [comment]
Conclusion is that you're lighttpd rewrite is not working as expected.

**Comment by jeroenbeuz** [comment]
After trying the url you suggested the original call (http://192.168.1.10/spotweb/api?imdbid=8579674&apikey=xxx&t=movie&extended=1&cat=2000) is now also working. Strange, but it's working now. Thanks again for the help.

**Comment by Sweepr** [comment]
Seems like the good old caching ghost of the past friend has returned. 

https://kb.intermedia.net/article/1160

As this seems to be revolved i will close this.

**Comment by mesa57** [comment]
Mind you that spotweb is using it's own cache for http (to imdb) calls.
@Sweepr : you made a nice cache clear function (develop branch ?)
Maybe @jeroenbeuz should use that once ....

**Comment by Sweepr** [comment]
@mesa57, Yes that's right!

@jeroenbeuz, Info can be found here: https://github.com/spotweb/spotweb/wiki/Spotweb-reset-database-or-clear-local-cache

**Comment by michpas** [comment]
Hi all. Sorry to reopen/add to this discussion.
I'm experiencing the exact same issue as the original poster jeroenbeuz.
Eg.  a (manual) http query search from Sonarr works great to a local spotweb (docker jgeusebroek) version.
Also a manual query without an imdbcode works fine: http://192.168.0.170:9191/api?t=movie&cat=2000,5000&extended=1&apikey=xxx&offset=0&limit=50&q=1917
but as soon as I add an imdbid in the request ( http://192.168.0.170:9191/api?t=movie&cat=2000,5000&extended=1&apikey=7d46b65671555874b4d8c2629cdd6785&offset=0&limit=50&imdbid=8579674)
I get: 
'' This XML file does not appear to have any style information associated with it. The document tree is shown below.
<error code="301" description="IMDB information returned is invalid"/>''

Have tried:
*) Retrieving the latest docker image. 
*) Ran the php upgrade-db.php --clear-cache -yes. Didn't solve the issue
*) Ran the check-cache.php. Didn't solve the issue
*) Ran the php upgrade-db.php --reset-db. Didn't solve the issue

It seems that when an imdbid is passed, spotweb always returns the 301 error. Have run out of ideas to solve it.
Would really appreciate any steer/guidance from teh experts on how to fix this.
Thanks

**Comment by michpas** [comment]
Just to add to the above; sharing in case someone else bumps into the same problem.
I changed dockers. from Jgeusebroek to erikdevries spotweb docker. This version worked perfectly. No issues anymore.

**Comment by mesa57** [comment]
@michpas : did you check out the develop branch ?

**Comment by jeroenst** [comment]
> Hi all. Sorry to reopen/add to this discussion.
> I'm experiencing the exact same issue as the original poster jeroenbeuz.
> Eg. a (manual) http query search from Sonarr works great to a local spotweb (docker jgeusebroek) version.
> Also a manual query without an imdbcode works fine: http://192.168.0.170:9191/api?t=movie&cat=2000,5000&extended=1&apikey=xxx&offset=0&limit=50&q=1917
> but as soon as I add an imdbid in the request ( http://192.168.0.170:9191/api?t=movie&cat=2000,5000&extended=1&apikey=xxx&offset=0&limit=50&imdbid=8579674)
> I get:
> '' This XML file does not appear to have any style information associated with it. The document tree is shown below.
> error code="301" description="IMDB information returned is invalid'
> 
> Have tried:
> *) Retrieving the latest docker image.
> *) Ran the php upgrade-db.php --clear-cache -yes. Didn't solve the issue
> *) Ran the check-cache.php. Didn't solve the issue
> *) Ran the php upgrade-db.php --reset-db. Didn't solve the issue
> 
> It seems that when an imdbid is passed, spotweb always returns the 301 error. Have run out of ideas to solve it.
> Would really appreciate any steer/guidance from teh experts on how to fix this.
> Thanks

I have the same problem.. I just pulled the latest docker image (jgeusebroek/spotweb) without any result. 
Now it's impossible to use Radarr with spotweb.

**Comment by michpas** [comment]
> > Hi all. Sorry to reopen/add to this discussion.
> > I'm experiencing the exact same issue as the original poster jeroenbeuz.
> > Eg. a (manual) http query search from Sonarr works great to a local spotweb (docker jgeusebroek) version.
> > Also a manual query without an imdbcode works fine: http://192.168.0.170:9191/api?t=movie&cat=2000,5000&extended=1&apikey=xxx&offset=0&limit=50&q=1917
> > but as soon as I add an imdbid in the request ( http://192.168.0.170:9191/api?t=movie&cat=2000,5000&extended=1&apikey=xxx&offset=0&limit=50&imdbid=8579674)
> > I get:
> > '' This XML file does not appear to have any style information associated with it. The document tree is shown below.
> > error code="301" description="IMDB information returned is invalid'
> > Have tried:
> > *) Retrieving the latest docker image.
> > *) Ran the php upgrade-db.php --clear-cache -yes. Didn't solve the issue
> > *) Ran the check-cache.php. Didn't solve the issue
> > *) Ran the php upgrade-db.php --reset-db. Didn't solve the issue
> > It seems that when an imdbid is passed, spotweb always returns the 301 error. Have run out of ideas to solve it.
> > Would really appreciate any steer/guidance from teh experts on how to fix this.
> > Thanks
> 
> I have the same problem.. I just pulled the latest docker image (jgeusebroek/spotweb) without any result.
> Now it's impossible to use Radarr with spotweb.
> 
> ![image](https://user-images.githubusercontent.com/2833940/128630540-335cdca4-f207-430d-8cec-b0c914d229b3.png)
> 
> I can't find the version of spotweb anywhere in the webpage unfortunatly.

Try  erikdevries spotweb docker
This one worked for me

**Comment by jeroenst** [comment]
@michpas Your tip works great! 
Thank you very much!

**Comment by Fossil01** [comment]
Experiencing the same issue on the master branch.

`<error code="301" description="IMDB information returned is invalid"/>`

**Comment by Sweepr** [comment]
Yes, thats because the changez havent made it to Master, maybe its time to merge Develop with Master.

@mesa57, do you agree?

**Comment by Fossil01** [comment]
Any big changes in dev?

**Comment by h3llrais3r** [comment]
I'm still facing this issue.
Do we still need to switch to develop branch?
I tried all proposed solutions (clear cache, upgrade db) but still no luck.
I'm running latest master (version 1.5.1)

**Comment by mesa57** [comment]
No, it's on master branch.

**Comment by h3llrais3r** [comment]
That's what I thought, but still having the same error... 😞 
I did run the `php upgrade-db.php --clear-cache`... anything else that is required?

**Comment by mesa57** [comment]
No, maybe wait for an update of package https://packagist.org/packages/imdbphp/imdbphp

**Comment by h3llrais3r** [comment]
I found the issue. Just in case someone else might face the same issue in future: 
The reason was my php curl setup: it was not properly supporting ssl.
After fixing curl ssl in xampp (https://odan.github.io/2017/03/30/xampp-curl-ssl-setup.html) it started working.
