### ISSUE TITLE
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.

### ISSUE THREAD

**Issue by Sweepr** [spotweb/spotweb#495]
Problem:
Console in developer mode reports:

![image](https://user-images.githubusercontent.com/2857865/77844355-76364780-71a6-11ea-82ee-37da04662b3d.png)

This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”.

Solution:
The non-standard zoom CSS property can be used to control the magnification level of an element. transform: scale() should be used instead of this property, if possible. However, unlike CSS Transforms, zoom affects the layout size of the element.

Replace all `zoom:` 1 by `transform: scale(1)` in 

https://github.com/spotweb/spotweb/blob/develop/templates/we1rdo/css/jquery-ui-1.8.23.custom.css

https://github.com/spotweb/spotweb/commit/a9594158b183f84c6cf5d34171a0036e5cf44a63

**Comment by mesa57** [comment]
Be carefull. This works different in different browsers.

**Comment by Sweepr** [comment]
@mesa57 Yes, that's true, for the most they pretty old and mostly deprecated in CSS.

`transform` is support by these browers in it's earliest version:

![image](https://user-images.githubusercontent.com/2857865/77848456-01263a80-71c5-11ea-8b8b-138c3bce3057.png)

https://www.w3schools.com/css/css3_2dtransforms.asp

I think we shouldn't keep supporting +10 year old browsers, i've also found CSS code for IE5/6 which is almost 20 years old!, people who still stubbornly keep using that old kind of software should be banned from the internet. ;-)

**Comment by mesa57** [comment]
Agreed 👍

**Comment by mesa57** [comment]
Uh, closed ? Thought you we're working in it ?

**Comment by Sweepr** [comment]
Oh, i already made a commit and tested this change on Edge/IE/Firefox and Chrome, to me looks fine.

https://github.com/spotweb/spotweb/commit/a9594158b183f84c6cf5d34171a0036e5cf44a63

**Comment by mesa57** [comment]
Sorry, didn't see that commit 👍
