### ISSUE TITLE
Add SMTP-Mail-support via PHPMailer

### ISSUE THREAD

**Issue by hr1232** [spotweb/spotweb#497]
Using PHP's mail()-function has never been a really good solution as it has certain limitations. The Class PHPMailer provides the possibility to use SMTP mail including SMTP-Auth and TLS.

I would be willing to provide the necessary code for
- adding smtp host and auth values to the settings page
- using phpmailer to send email for user registration
- using phpmailer to send email notifications

Just wanted to ask befor I start writing code. Would you be willing to import that code? Are there any other email functions aside the user registration message and the email notification, that I don't know of?

**Comment by Sweepr** [comment]
Any improvement on the current code base is welcome, so go ahead if you wish.

@mesa57 , what's your opinion?

**Comment by mesa57** [comment]
Same with me. People like to have improvements, so why not contribute ?

**Comment by hr1232** [comment]
OK, starting with [ hr1232/spotweb:phpmailer ](https://github.com/hr1232/spotweb/tree/phpmailer)

**Comment by Sweepr** [comment]
How are things progressing? still work in progress?

**Comment by Sweepr** [comment]
No sure if the work on the branch hr1232/spotweb:phpmailer is done, but i went ahead and checked out this feature.

A few things in ran into:

On the `?page=editsettings` 

![image](https://user-images.githubusercontent.com/2857865/78970211-14ac9c00-7b09-11ea-9eda-c505e69a76fd.png)

![image](https://user-images.githubusercontent.com/2857865/78970332-5ccbbe80-7b09-11ea-9362-d3dbcfe0bc17.png)

You should add on line 57:

`$this->setIfNot('smtp', ['use' => false, 'host' => '', 'user' => '', 'pass' => '', 'port' => 587]);`

After: 

https://github.com/hr1232/spotweb/blob/6bf5a515a5ad50e522ceefe5abdbf3f79692cce3/lib/services/Upgrade/Services_Upgrade_Settings.php#L56

This will fix this issue.

**Comment by Sweepr** [comment]
And then, when i check `Use SMTP (keep disabled to use PHP's internal mail function)` and click `change`: 

![image](https://user-images.githubusercontent.com/2857865/78973497-53922000-7b10-11ea-9582-3ee3baf84b3f.png)

I get this:

![image](https://user-images.githubusercontent.com/2857865/78973519-6573c300-7b10-11ea-8d6b-1d5b36133042.png)

**Comment by hr1232** [comment]
Sorry for not answering. I had to go to hospital and could not continue. It is therefor not finished yet.

**Comment by hr1232** [comment]
Wondered about the non-existend function showResults myself. I did not put that in, however, i just removed it. Probably a remnant from some debugging you guys did long about.

**Comment by Sweepr** [comment]
No problem, just take your time!

**Comment by Sweepr** [comment]
@mesa57 

I have completed the PHPMailer function in https://github.com/spotweb/spotweb/tree/phpmailer please checkout, review and merge if you approve.

**Comment by Sweepr** [comment]
Added to develop branch.
