### ISSUE TITLE
[API] There are multiple root elements. Line 2, position 2.

### ISSUE THREAD

**Issue by Mickroz** [spotweb/spotweb#498]
When using spotweb as indexer for Sonarr of Radarr i get:
An error occurred while processing feed. /api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=50&tvmazeid=1371&season=3&ep=3: There are multiple root elements. Line 2, position 2.
a call to this in browser gives:
![image](https://user-images.githubusercontent.com/994362/78147558-f9b89880-7433-11ea-817c-5a38b9c8e0ec.png)
and view-source gives:
```

<br />
--
  | <b>Notice</b>:  Trying to access array offset on value of type bool in <b>/lib/services/Providers/Services_Providers_Http.php</b> on line <b>398</b><br />

```

which is:
```
        return ['http_code' => $http_code,
            'data'          => $data,
            'finalurl'      => $effectiveUrl,
            'successful'    => ($http_code == 200 || $http_code == 304),
            'errorstr'      => 'http returncode: '.$http_code.' / '.$errorStr,
            'curl_info'     => $curl_info, ];
```
Running on:
archlinux
64 bits
php 7.4.3
mariadb 10.4.8

**Comment by mesa57** [comment]
It is caused by the notice send after the XML.
A lower php version would probably fix this, but we will look into this.

**Comment by Mickroz** [comment]
it not that line btw, im on master so its:
`$tmpData = $this->perform($url, $content['stamp']);`

**Comment by mesa57** [comment]
Issue should be solved at the develop branch. Please verify, and if needed reopen this issue.

**Comment by Mickroz** [comment]
fixed!

**Comment by mesa57** [comment]
Thanks for the feedback !

**Comment by hekc0211** [comment]
Hi guys... i got this problem  with php7.4.25 Does this mean i need to upgrade from stable to developer branche??

**Comment by mesa57** [comment]
No I think this already has been merged with the master branch.

**Comment by hekc0211** [comment]
Thanks... for the quick reply...
