### ISSUE TITLE
Resync posts not working when change retention date/days in settings.

### ISSUE THREAD

**Issue by fgerrits** [spotweb/spotweb#499]
I have a new newsprovider which holds a 1200 day retention, the old on has 720 day retention.
When i adjust this in the settings, 700 to 1200 retention and the date to 20-12-2016 and let the retrieve.php run no older posts are added.
It stays at 1 year and 9 months in the spotweb view.

Is there any solution to fix this or must i delete the database ?

Kind regards.

**Comment by Sweepr** [comment]
When switching newsprovider you have to clear the database, the reason behind that is that different newsproviders hold different article count's, so changing to another newsprovider without clearing the DB can cause issue's with article count's, so my advice is to run:

php upgrade-db.php --reset-db

https://github.com/spotweb/spotweb/wiki/Spotweb-reset-database-or-clear-local-cache

**Comment by fgerrits** [comment]
Oke, thanks for your advice.
Must I after that do a new retrieve from the command line, or will it sync automatically using the task planner?

**Comment by Sweepr** [comment]
If you have scheduled a task, this task will start to run from scratch.

**Comment by fgerrits** [comment]
Hi,

When i use ;
:/volume1/web/spotweb/bin# php upgrade-db.php --reset-db
PHP Fatal error:  Undefined class constant 'MYSQL_ATTR_FOUND_ROWS' in /volume1/web/spotweb/lib/dbeng/dbeng_pdo_mysql.php on line 28

Fatal error: Undefined class constant 'MYSQL_ATTR_FOUND_ROWS' in /volume1/web/spotweb/lib/dbeng/dbeng_pdo_mysql.php on line 28

But when im using /usr/local/bin/php73 upgrade-db.php --reset-db
it's only validating the tables, nothing is removed from the database.

For the above error i have add an extra webstation-extensions.ini in the php73 folder, but that didn't help anything.

Any advise to cleanup the database ?

**Comment by Sweepr** [comment]
In /usr/local/etc/php56/conf.d place:

`cat >/usr/local/etc/php56/conf.d/spotweb.ini`

with: 

extension = bcmath.so
extension = bz2.so
extension = curl.so
extension = gd.so
extension = gettext.so
extension = openssl.so
extension = pdo_mysql.so
extension = zip.so

And in /usr/local/etc/php70/conf.d:

`cat >/usr/local/etc/php70/conf.d/spotweb.ini`

With this contents:

```
extension = bcmath.so
extension = bz2.so
extension = curl.so
extension = gd.so
extension = gettext.so
extension = openssl.so
extension = pdo_mysql.so
extension = zip.so
```

Be sure to restart the NAS afterwards, then try again.

**Comment by fgerrits** [comment]
Did not help, still same error.

**Comment by Sweepr** [comment]
Can you post the outcome of 

`php -v` and `php --ini` here from the commandline?

**Comment by fgerrits** [comment]
root@TopStation:~# php -v
PHP 5.6.11 (cli) (built: May 10 2019 04:50:45)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
root@TopStation:~# php --ini
Configuration File (php.ini) Path: /etc/php
Loaded Configuration File:         /etc/php/php.ini
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)

**Comment by Sweepr** [comment]
Try putting 

```
extension = bcmath.so
extension = bz2.so
extension = curl.so
extension = gd.so
extension = gettext.so
extension = openssl.so
extension = pdo_mysql.so
extension = zip.so
```

Into the extension's section of `/etc/php/php.ini` and restart the webserver

**Comment by fgerrits** [comment]
When i do that then i got an error that extension pdo_mysql.so is not found.

When i copy the 5.6 version from `/volume1/@appstore/PHP5.6/usr/local/lib/php56/modules/` to `/usr/lib/php/modules/` ill get the following error.

`root@TopStation:/volume1/web/spotweb/bin# php upgrade-db.php --reset-db
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/pdo_mysql.so' - /usr/lib/php/modules/pdo_mysql.so: undefined symbol: mysqlnd_allocator in Unknown on line 0
PHP Fatal error:  Undefined class constant 'MYSQL_ATTR_FOUND_ROWS' in /volume1/web/spotweb/lib/dbeng/dbeng_pdo_mysql.php on line 28

Fatal error: Undefined class constant 'MYSQL_ATTR_FOUND_ROWS' in /volume1/web/spotweb/lib/dbeng/dbeng_pdo_mysql.php on line 28`

**Comment by baruser123** [comment]
in the past i had some strange problems with php commands. i solved them to command php56 otherwise seems like server used another php version.

i do the retrieve now with following command
php56 /volume1/web/spotweb/retrieve.php

i think for your reset you must use 
php56 /volume1/web/spotweb/bin/upgrade-db.php --reset-db

you can try that maybe

**Comment by fgerrits** [comment]
@baruser123, already tried that.

Then ill get no error but instead off emptying the tables that should, it only validates the database.

```
`php56 upgrade-db.php --reset-db
Updating schema..(pdo_mysql)

```
        Validating spots(messageid)
        Validating spots(poster)
        Validating spots(title)
        Validating spots(tag)
` ~~
`        

```
Validating index idx_filtercounts_1
        Validating index idx_spotteridblacklist_1
        Validating index idx_spotteridblacklist_2
        Validating index idx_cache_1
        Validating index idx_cache_2
        Validating index idx_moderatedringbuffer_1
Schema update done
Updating settings
Settings update done
Updating users
Users' update done
Performing basic analysis of database tables
Basic database optimalisation done`
```

**Comment by baruser123** [comment]
ok now no errors. so this is good. now im thinking how up to date is your spotweb version?

**Comment by fgerrits** [comment]
this version ->  Spotweb_noarch-all_20190917-1.spk

**Comment by baruser123** [comment]
yeah looks like it's too old and the option wasn't there. therefore i use the github version and not a spk so i can get the updates when they are there. so if your handy you should can do that. 

otherwise maybe @Sweepr can say which actions you must do manually in the database to do a reset

**Comment by fgerrits** [comment]
Oke, i have downloaded the zip in the web folder, copied the db settings from old to new folder, permissions and ownership fixed.
running the upgrade_db.php, after that running the reset_DB, now i got the empty warning :), testing if website is running - oke.
im running retrieve.php now, so will see how it ends.

Thanks for the help guys, helped me allot to fix it.

**Comment by mesa57** [comment]
New spk is excpected in the coming weeks.
