### ISSUE TITLE
Fresh intallation of Spotweb does not contain install.php

### ISSUE THREAD

**Issue by suheyl** [spotweb/spotweb#500]
Hi,

I've done a fresh installation of my PC with Ubuntu and installed Spotweb on it. Installation looks fine and Spotweb is running as I can access it in the browser. However the install.php page does not exist en therefore I cannot configure Spotweb. I've searched the file on disk, but it doesn't exist. 
I've removed Spotweb and installed it again, but with the same result. I can access Spotweb, create a user, but not an admin user, and therefore I cannot set the usenet server nor configure it.
Any ideas? I've added the logging and it's successful apart from one error which I fixed by removing the IGNORE statement in the script, which is a known issue.
[spotweb_install.txt](https://github.com/spotweb/spotweb/files/4421901/spotweb_install.txt)

**Comment by Sweepr** [comment]
I'm seeing a few PHP Deprecated error's which are a trigger for me, which PHP version are you using?

Minimum PHP = 5.6 or up, anything lower we cannot guarantee proper function.

P.S. the admin account is created at the same time you create a users, so the admin account, has the same password as the first created user.

Goodluck.

**Comment by Sweepr** [comment]
Which source of spotweb are you using for you install?

**Comment by suheyl** [comment]
Hi,

It was a fresh install of everything thus newest version:
suheyl@KODI:~$ php --version
PHP 7.2.24-0ubuntu0.18.04.3 (cli) (built: Feb 11 2020 15:55:52) ( NTS )

**Comment by suheyl** [comment]
And I've

**Comment by Sweepr** [comment]
No, the DB user is not the same as the admin account you use to login to spotweb.

DB user is setup once during install, and that's it.

**Comment by suheyl** [comment]
Yes, but the spotweb login is not created. Installation stops, Spotweb is running, but after this there's no install.php page or something to create users, nor the page to add the usenet server... 
http://x.x.x.x./spotweb/install.php gives an 404 page not found. The file just doesn't exist...

sudo find / -name install.php
find: ‘/run/user/1000/gvfs’: Permission denied
suheyl@KODI:~$

I've installed and removed an reinstalled it 3 times now, after a fresh install of my complete OS

**Comment by Sweepr** [comment]
From where do you install ? are you using GIT? or did you download the ZIP file?

**Comment by suheyl** [comment]
I just typed sudo apt install spotweb. So GIT? Or is that a different source?

**Comment by Sweepr** [comment]
If possible try install using `git clone -b master https://github.com/spotweb/spotweb.git .` into the public folder http://x.x.x.x./spotweb/ then retry to install.php

**Comment by suheyl** [comment]
I just removed the previous install by using  sudo apt-get purge --auto-remove spotweb
 and deleted all spotweb files left behind in cache and tmp. 
Then  followed the steps described on https://github.com/spotweb/spotweb/wiki/Spotweb-installeren-op-Ubuntu-18 and then git clone -b master https://github.com/spotweb/spotweb.git 
copied the files to /var/www/html, but with the same result. install.php 404 page not found.
But the file does exist and running it on command line gives this result added in the file
[install_php.txt](https://github.com/spotweb/spotweb/files/4422865/install_php.txt)

It looks like php.ini is not configured but it is:

 timedatectl status | grep "Time zone"
                       Time zone: Europe/Amsterdam (CEST, +0200)

 
I don't get it....

**Comment by Sweepr** [comment]
What do you see when you browse to http://x.x.x.x./spotweb/  it almost looks like the webserver isn't pointing to the right direction.,

**Comment by suheyl** [comment]
Not Found
The requested URL was not found on this server.

Apache/2.4.29 (Ubuntu) Server at x.x.x Port 80

**Comment by Sweepr** [comment]
I think you have to double check you apache/webserver configuration, there's something wrong with the public folder.

**Comment by suheyl** [comment]
almost there. You we're right about the apache configuration. I've edited the next file:

apache.conf  (changed the directory to /var/www)

now http://x.x.x/spotweb/install.php works!
I think still one issue left. When adding my custom newsgroup I get the next error

A server portnumber has to be entered [response: ""]
Please correct the errors in below form and try again

I'm using reader.usenetbucket.com and tried several ports 563 (used in my Sab), but also 119 and 443.

When I skip the validation I get the screen where I can create the system and admin user. I choose shared and fill in my details, click create system. Also created the dbsettings.inc.php file. Then finish. I return to the apache test page. When I then visit http://x.x.x/spotweb I still get the apache page...

**Comment by suheyl** [comment]
I think I f*cked up completely now. I will reinstall everything from scratch... I might screwed certificates and can't even download from GIT. Thanx anyway. If after this fresh install still doesn't work, I'll create a new issue.
