### ISSUE TITLE
Known issue: "upgrade-db.php --clear-cache" fgets(STDIN) fails on Windows PHP7.4 rc4/5

### ISSUE THREAD

**Issue by Sweepr** [spotweb/spotweb#505]
Using "upgrade-db.php --clear-cache" option 

https://github.com/spotweb/spotweb/blob/ab86a2b459587a7c8294fb5588a38671466d9284/bin/upgrade-db.php#L135

fgets(STDIN) asks the user for input and returns the results, but this instantly fails on Windows using certain 7.4 rc's (4-5) - it immediately returns false.

Linux and Windows using PHP 7.3 works fine. 

PHP bug report: https://bugs.php.net/bug.php?id=78883

**Comment by mesa57** [comment]
Tested this with php 7.4.1 but it seemed to work fine ...

**Comment by Sweepr** [comment]
@mesa57, then PHP already fixed that in 7.4.1 , this is in RC4,and RC5 as far as i know.
