### ISSUE TITLE
Would be nice to have user registration via API

### ISSUE THREAD

**Issue by bdegier** [Spotweb/Spotweb#51]
It would be nice to be able to register users via the API. Limited to certain user groups (admins for ex.).

That way I can create Spotweb accounts from my own website.

**Comment by Sweepr** [comment]
Why would you want to do that?

I don't see the point.

**Comment by bdegier** [comment]
To be able to create a Spotweb account when a user signs up for another website/system/service...

**Comment by Sweepr** [comment]
We need a more detailed description with what you want so we can understand your idea better, this is a little vague and this way we can't tell if it's even possible using the existing code.

**Comment by bdegier** [comment]
Just an API function to be able to register user accounts like Newznab has. But with some limits so only  administrators can use that API function.

See: http://newznab.readthedocs.org/en/latest/misc/api/#register

**Comment by Sweepr** [comment]
I understand now, 

But i have my doubts about this,

1. How would you distinguish who to allow and which you don't want?
2. This idea is great if you have maybe 1 or 2 registrations a week, but what if you have 50-100 applications a day?  I mean, Are you seriously planning to manually allow or deny all those requests? i'm not ;-)
3. You could also let them ask for an account by sending you an E-mail

**Comment by bdegier** [comment]
1. By user group. Should be fairly easy to detirmine if the API key used is owned by an admin account.
2. That's exactly what the API is for. More than just a few registrations per day which are now done manually. The API would make it possible to automate that.
3. Too much hassle.

**Comment by Sweepr** [comment]
Yes, but there will always be human interaction needed to allow or disallow user, the description states:

It is at the server administration discretion to allow or deny registrations based on for example the validity of the email address or the current client host address.

The Admin receives the request, the Admin has to then allow / deny the user, this cannot be done automatically.

The API itself does not decide for you, you need.. and personally i think that i would go insane if i have to confirm all those accounts one by one even if it would take my 1 click of a button.

**Comment by bdegier** [comment]
That's not the point. The point is to have an API function only some user accounts (mine) can call. Then when a user signs up for my website I can have that PHP script call the Spotweb API to create an  account. The account would then already be activated and ready for use.

No need to check because it isn't a public API function.

**Comment by Muis** [comment]
It would be easy to implement this, but I think it will turn into a mess, because both tables will get out of sync over time (since deleted users / password changes on your website are not replicated in the Spotweb users table).

Maybe its better to keep the Spotweb users table empty, and let Spotweb do some kind of OpenID or oAuth to your forum to validate logins. That way users can login to Spotweb without entering their password or username, since they are already logged in to your site. And the advantage is that nothing can get out of sync between the two tables, because there is only 1 table :)

**Comment by bdegier** [comment]
Unless there's an API delete/update function :-)

**Comment by dsadsdadsadsadsds** [comment]
While the BL code in Spotweb is centralized within services, no one ever bothered to make them loousely coupled (probably for performance reasons, as a lot of redirections are rather slow in PHP).

The easiest way to do what you want would probably to create your own page and use the provided business logic (see lib/Services and lib/Actions) within this new page. I think you would be able to make this happen with very few lines of code.

**Comment by Muis** [comment]
Exactly
