### ISSUE TITLE
NZB handling not working

### ISSUE THREAD

**Issue by suheyl** [spotweb/spotweb#511]
Hi all,

Last week I've did a fresh install (actually twice), but since then my NZB Handling in SpotWeb wth SAB is not working anymore. I've been using it or years, but somehow, I'm not managing to get it working again.
The issue is, I've configured SpotWeb to call SAB through HTTP, added the URL http://xxx.nl:9094/ (yes, SAB is running on that port) and added the API key from SAB. When I try to send a spot to SAB, the arrow changes in a circle and keeps turning. SAB doesn't receive anything.
I've also generated a new key from within SAB and tried that one in SpotWeb, with the same result. 
Then, I tried it with a new test user in SpotWeb, added the same credentials als above to send NZB's to SAB. Now, the circle appears, then it seems it NZB is sent to SAB as the check mark appears, but nothing in SAB.
I use the same API on other sites, like NZBPlanet, and there it does work, therefore my conclusion is that something is not handled right in SpotWeb. Any ideas?

**Comment by Sweepr** [comment]
I've tested this on my local spotweb with Sabnzbd running local, (127.0.0.1) but it seems to be working fine.

@mesa57 Do you see any issue regarding this?

**Comment by mesa57** [comment]
I will test this. I have a sabnzbd server running on another machine.

**Comment by mesa57** [comment]
Works fine here (sabnzbd located on other machine, same network)

**Comment by Sweepr** [comment]
@suheyl  
Double check the settings, i will close this for now, as it seems to be a localized issue. 

Feel free to re-open if help is required.

**Comment by suheyl** [comment]
I found the issue, php-curl was not installed, but also not mentioned on the installer page. I've added it to https://github.com/spotweb/spotweb/wiki/Spotweb-installeren-op-Ubuntu-18

**Comment by mesa57** [comment]
Should have been indicated by install.php 👍 

![afbeelding](https://user-images.githubusercontent.com/6350469/79236594-70f71f00-7e6d-11ea-9714-683a71d4a3bb.png)

**Comment by suheyl** [comment]
It did, but I clicked too fast, caught my eye after installing it again. Thanks anyway
