### ISSUE TITLE
SpotPage_getnzbmobile was not found, do we still need this reference in index.php?

### ISSUE THREAD

**Issue by Sweepr** [spotweb/spotweb#512]
The type SpotPage_getnzbmobile was not found. Maybe you did not declare it correctly or list all dependencies? 

https://github.com/spotweb/spotweb/blob/5b8d84680a3b98a7577ca1da0c5f2d440d1d9ea8/index.php#L144

**Comment by Sweepr** [comment]
IssueId: 43598825  Message: The type ``SpotPage_getnzbmobile`` was not found. Maybe you did not declare it correctly or [list all dependencies](/docs/tools/php/php-scrutinizer/#list-dependency-paths)?  Filename: index.php  LineNumber: 145  Link: https://scrutinizer-ci.com/g/spotweb/spotweb/issues/develop/files/index.php?orderField=path&order=asc&honorSelectedPaths=0&issueId=43598825

**Comment by mesa57** [comment]
As it indeed doesn't exists, those lines can be removed.

**Comment by Sweepr** [comment]
Done.

**Comment by mesa57** [comment]
😄
