### ISSUE TITLE
The variable $dbsettings seems to never exist and therefore empty should always be true. 

### ISSUE THREAD

**Issue by Sweepr** [spotweb/spotweb#514]
The variable $dbsettings seems to never exist and therefore empty should always be true. 
Is there (code-wise) a chance that an empty `dbsettings.inc.php` file get's created?

In other words, this check `if (empty($dbsettings))` can also be `else` i.m.o. there's no way an empty `dbsettings.inc.php` can be made unless done on purpose.

Otherwise we can change this code:

```
        if (file_exists(__DIR__.'/../dbsettings.inc.php')) {
            require __DIR__.'/../dbsettings.inc.php';
        }
        if (empty($dbsettings)) {
            throw new DatabaseConnectionException("No database settings have been entered, please use the 'install.php' wizard to install and configure Spotweb.".PHP_EOL.
                                                      'If you are upgrading from an earlier version of Spotweb, please consult https://github.com/spotweb/spotweb/wiki/Frequently-asked-questions/ first');
        } // if
```

Into:

```
        if (!file_exists(__DIR__.'/../dbsettings.inc.php'))
		{
			throw new DatabaseConnectionException("No database settings have been entered, please use the 'install.php' wizard to install and configure Spotweb.".PHP_EOL.'If you are upgrading from an earlier version of Spotweb, please consult https://github.com/spotweb/spotweb/wiki/Frequently-asked-questions/ first');
        }   
			else
		{        
			require __DIR__.'/../dbsettings.inc.php';
		}
```

**Comment by Sweepr** [comment]
Fixes and some others.

https://github.com/spotweb/spotweb/pull/515

Please review @mesa57

**Comment by mesa57** [comment]
I think the empty test should be present.
dbsettings are often manually edited by users.

**Comment by Sweepr** [comment]
Only way to trigger this code: `(empty($dbsettings))` is to have a totally empty file, any other misconfiguration of this file produces:

White screen of death, 
This:
![image](https://user-images.githubusercontent.com/2857865/78901956-5c83e280-7a79-11ea-8722-cc82c6c0582a.png)

Or: 
![image](https://user-images.githubusercontent.com/2857865/78902001-73c2d000-7a79-11ea-9221-879baddf6d9e.png)

**Comment by mesa57** [comment]
Als jij dat genoeg vindt, ben ik het ook mee eens 😉
