### ISSUE TITLE
duto

### ISSUE THREAD

**Issue by frank1238** [Spotweb/Spotweb#52]
Wat heeft Duto te maken met spotweb/spotnet? Hoe kan ik Duto als eindgebruiker gebruiken? Vind er niks over terug...

**Comment by Wally73** [comment]
t lijkt een voorbeeld spotweb install te zijn

2015-03-16 12:02 GMT+01:00 frank1238 <notifications@github.com>:

**Comment by Muis** [comment]
Nothing, it's just a demo so people can try before setting up their own install.
