### ISSUE TITLE
[BUG] Versienummers verschillen

### ISSUE THREAD

**Issue by Tosko4** [spotweb/spotweb#526]
I'm currently running the dev branch and if i look at the code i see:

`<meta name="generator" content="SpotWeb v0.68.31.33"> `

Release on git is: Spotweb 1.0.68.31.33 [Github](https://github.com/spotweb/spotweb/releases/tag/1.4.5) 

Missing the 1. in the generator.

**Comment by Sweepr** [comment]
I know it might seems confusing but the actual release = v1.4.5

![image](https://user-images.githubusercontent.com/2857865/79681337-cdfe2680-8219-11ea-99d0-472bcf580f25.png)

This number v0.68.31.33 represents a way for developers and the code to inform users there has been a change in de database, so whenever one of those numbers increases you will get a message in your browser telling you have to update the database.

![image](https://user-images.githubusercontent.com/2857865/79681354-fdad2e80-8219-11ea-96f2-bfaff1ec6acd.png)

Actual releases (Master branch only) can be found here:

https://github.com/spotweb/spotweb/releases

Master is the stable branch, and is recommended for production use.
Develop is ahead of master, with some changes and if stable will be pushed to Master.

Hope that clear things up for you.

**Comment by Tosko4** [comment]
Yes the difference between dev and master was already clear. Plus I don’t mind running dev, it helps the community crush bugs etc (if there are any ;) ) before it’ll reach master. The more testers you have, the better.

The release tags, and that code is now clear 👍🏻

**Comment by Sweepr** [comment]
> 
> 
> Yes the difference between dev and master was already clear. Plus I don’t mind running dev, it helps the community crush bugs etc (if there are any ;) ) before it’ll reach master. The more testers you have, the better.
> 
> The release tags, and that code is now clear 👍🏻

Sure, no problem, any help from debuggers is welcome at all times!
