### ISSUE TITLE
Can't login using Microsoft Edge (chromium based)

### ISSUE THREAD

**Issue by jeroenbeuz** [spotweb/spotweb#529]
Logging in with Google Chrome is no issue, but I can't login using Microsoft Edge Chromium based at all. The login popup appears, and when I enter my credentials the popup disappears but then nothing happens.

I'm now using version 81.0.416.64

**Comment by Sweepr** [comment]
Tried this myself using 81.0.416.64 on Windows 10 64bit.

Server running the latest develop branch, running PHP 7.4 and unix OS.

![afbeelding](https://user-images.githubusercontent.com/2857865/80460473-2cbb5280-8934-11ea-99a3-6f5b0687c1a3.png)

Login seems to work fine,

Can you provide us:

-Which branch or release?
-Which platform?
-Which PHP version?

Is Microsoft Edge Chromium a clean install? did you try to factory reset the browser and/or disable any plugin's or addon's?

**Comment by jeroenbeuz** [comment]
After completely reinstalling Edge it now works. Thanks for the quick reply.

**Comment by Sweepr** [comment]
No problem.
