### ISSUE TITLE
Remove spot button on spot overview

### ISSUE THREAD

**Issue by Sweepr** [spotweb/spotweb#53]
Add a "remove" spot button on spot overview to delete spot without having to go to the edit dialog.?

**Comment by dsadsdadsadsadsds** [comment]
You cannot do this. 

Spotweb is self-healing and will automatically reload that spot. The only thing you could do is add an boolean to the 'spots' table marking the spot as deleted (or any other way where you keep a list of spots which are deleted), but I personally do not think this is worth the CPU power.

Do note though, if you do decide to update the spots table, many people will hate you for it as it means an huge table rewrite for anyone that upgrades.

**Comment by Sweepr** [comment]
What about the current delete option that is already on the edit page?

Can't we somehow use that?

**Comment by dsadsdadsadsadsds** [comment]
Let me check what it does.

**Comment by dsadsdadsadsadsds** [comment]
Ok.

1. https://github.com/spotweb/spotweb/blob/master/templates/we1rdo/editspot.inc.php#L127 contains the 'deletespot' button. As you can see it posts the value 'submitdelete' to the page 'editspot'.
2. https://github.com/spotweb/spotweb/blob/master/lib/page/SpotPage_editspot.php is where the 'editspot' page is. On line 50 the 'delete' code begins, and this one calls the 'service layer' of Spotweb on line 58 (https://github.com/spotweb/spotweb/blob/master/lib/page/SpotPage_editspot.php#L58)
3. You can find the service class here: https://github.com/spotweb/spotweb/blob/master/lib/services/Posting/Services_Posting_Editor.php and line 18 contains the```` deleteSpot()```` code.
4. The ````deleteSpot()```` code in the editor service, is just a small wrapper around the DAO layer which calls the ````removeSpots()```` DAO function. 

The removeSpots() dao function - https://github.com/spotweb/spotweb/blob/master/lib/dao/Base/Dao_Base_Spot.php#L311 - just removes the entry from the database, so this is in no way reliable. 

It might work :)

**Comment by mesa57** [comment]
In the latest spotnet protocol you have the option to send DISPOSE messages to usenet which are signed with you're own key. Spotnet 1.8.5.9 and V2 support that protocol. Of course only spots posted with the same public key as the dispose message are eligable to be disposed.
Also spotnet 1.8.5.9 (and v2 ?) enforce a limit of 5 days for a spot to be disposed.

**Comment by Sweepr** [comment]
@mesa57, i am watching the Dev of it.. very interesting!

**Comment by mesa57** [comment]
First pull request is a change so Spotweb will process those dispose requests and not discard them any more. This will prevent spots from being seen as duplicate.

**Comment by Sweepr** [comment]
Closing,
