### ISSUE TITLE
Option to enable/disable the image preview.

### ISSUE THREAD

**Issue by Sweepr** [spotweb/spotweb#54]
Option to enable/disable the image preview.

**Comment by Sweepr** [comment]
https://github.com/Spotweb/Spotweb/issues/34

**Comment by dsadsdadsadsadsds** [comment]
Instead of disabling it, another option might be to try to load the image dynamically as soon as the tooltip is shown. That way you do not have the performance penalty but still the feature.

My guess is that you are able to hook the 'enter' API and dynamically load the content.

**Comment by WorkaholicGoT** [comment]
I don't have any image preview and I am using the master branch. Is this something from another branch?

**Comment by Sweepr** [comment]
@WorkaholicGoT

It's not in Master but Media branch.

**Comment by WorkaholicGoT** [comment]
@Sweepr 

ah.. no wonder! Are there any risks involved with migrating to this branch and can you tell me how to do this from a shell with git commands? Are the branches kept in sync with each other (in other words, if a bugfix or feature is added to the master branch --> is it also added to the media)?

If it were me I would love to see the image popup feature added to the master branch (with a possible on/off button in the settings)

**Comment by Sweepr** [comment]
I wouldn't suggest upgrade or migrate, don't think it's even possible, just create a clean install of the media branch next to your current running master branch.

The image preview in the mediainfo branch can be disabled (see here: https://github.com/spotweb/spotweb/issues/34)

**Comment by spoelly** [comment]
Will this be added to the mainbranch in the future?

**Comment by Sweepr** [comment]
@spoelly 

See: https://github.com/spotweb/spotweb/issues/64

**Comment by piejanssens** [comment]
+1 I don't like the image preview

**Comment by Sweepr** [comment]
I have added the option to enable/disable the imagepreview in the spotsoverview.

You can add the changes manually, or do a git clone.
If you edited the changes manually, run upgrade-db.php once.

The setting can be set trough "settings" -> "Performance" -> "Enable imagepreview in spot overview"

https://github.com/spotweb/spotweb/commit/e8c1c9cdafee9c25ed755f0106bab9626b1663fe
https://github.com/spotweb/spotweb/commit/354d9d0a0bcc088ea222b9d9bc0c3d1f7692f648
https://github.com/spotweb/spotweb/commit/bafd34a1d01b4c03969a33c715dbc707473b9c23
https://github.com/spotweb/spotweb/commit/06b24e4d96080227bb1095c0ef5422fdfc9bf483

**Comment by Sweepr** [comment]
Also added this to the media branch now.

https://github.com/spotweb/spotweb/commit/3447eb794ebd1ae83cbab0d4bfaa3f300923fe04
https://github.com/spotweb/spotweb/commit/f3b6d29a091f42e2bffa91a91bc50cca6069aa9f
https://github.com/spotweb/spotweb/commit/5347067258afd8cb6d43c8c52719c9e1cfa885b2
https://github.com/spotweb/spotweb/commit/470ae398f202f9ce868a3177734f4bdbfdfd0d2c
