### ISSUE TITLE
CSS question

### ISSUE THREAD

**Issue by HeMaN-NL** [spotweb/spotweb#540]
Not a bug, just something I do not understand completely ;)

I recently updated spotweb to the latest version and noticed the different colors of the spots within a category. Saw this only happened when the number of comments is 10 or more; they are all colored light green.

I did not like this and looked for the option to disable it, but could not find it. 
- is there an option to disable the coloring of spots with >10 comments?

To solve this for now I saw this in the style.css of the we1rdo template, and commented it out:

`/* Option to change color setting of highlighted spots based on comments: eg #09ba09 */
/*.hg1	{ background-color: #edfeed !important; }*/`

is this the way to go or is there another option?

- If there is a bug at all, for me it is that when you hover a spot with more then 10 comments, the background color of that spot does not change to white, it stays green

info on my systems: 
spotweb running on linux ubuntu 18.04 lts server
client is windows 10 pc with firefox browser most recent version
we1rdo template

**Comment by mesa57** [comment]
It is correct that this 1) has changed 2) is not configurable
If you want it configurable you can always try to build that youreself and put a pull request agains te develop branch.

**Comment by Sweepr** [comment]
There is a way to disable this, i wrote that code myself.

Go to "Settings" -> "Performance" , look for:

![afbeelding](https://user-images.githubusercontent.com/2857865/80999336-c5763480-8e44-11ea-9637-41a91edc5dcd.png)

Two options, either un-mark the "Highlight spots based on amount of comments" or change "Amount of comments to highlight spot" into a ridiculous high number like 50000, (There is yet a spot to be seen that has more then 50000 comments.)

**Comment by HeMaN-NL** [comment]
@Sweepr Thank you, completely overlooked this option. Reverted my css change and set the option to 100. Working like a charm.

@mesa57 It was a genuine question, I just had not noticed this behaviour before and could not find how to change this the right way.
My qualities are hopefully other than coding, I do not think it will make you happy if I would touch the code :)

Both of you thank you for keeping spotweb up to date and still improving it!

**Comment by mesa57** [comment]
Oeps I was wrong. @Sweepr : thank you for correcting me !
Really a stupid mistake. I take the blame on me.

**Comment by Sweepr** [comment]
No problem guys.
