### ISSUE TITLE
[request] mass add spots

### ISSUE THREAD

**Issue by m0rse** [spotweb/spotweb#548]
Maybe some way of mass adding say at least 10 spots at a time,

**Comment by Sweepr** [comment]
Maybe you can convince me otherwise but i'm not seeing the added value of this other then a potential way to facilitate spam.

Maybe you can ellaborate your feature request with some example's.

**Comment by m0rse** [comment]
Maybe spotweb would have more spots, as a end user adding a spot the time and effort it takes to add one by one, you just end up getting fed up and stop adding.

Maybe set it out like phpadmin where you can say edit 10 or more entries with all options available in one screen Then click add.

**Comment by mesa57** [comment]
Every spot should differ from each other. If not, you can also put multiple files in you're nzb.
What maybe could be usefull for spots which don't differ too much in content (description) is a kind of user selectable template. An option save as template and load template could be added to the spot create screen.
