### ISSUE TITLE
too many connections

### ISSUE THREAD

**Issue by Longshot** [spotweb/spotweb#55]
[Fri Mar 20 23:20:02 2015] [error] [client 192.168.2.254] SpotWeb Exception occured: Server refused connection [response: "Too many connections."] [response: ""], referer: https://spotweb.server.nl/?search[tree]=&search[unfiltered]=true

I'm getting a lot of these in my log when I log in to my spotweb server.
Page loads normally but the mouse over doesn't work on a lot of the spots.
Pictures are shown without problem if I click on a spot.
If I go back to the index it still doesn't show the picture on mouse over.

To make it even weirder.. after a few minutes most pictures do show on mouse over :)

I'm not downloading at the moment so I've got all my threads to Pure usenet available.
I've even switched to textnews.kpn.nl for a while (because of the recent 6hr delay on Pure) but that didn't solve the problem.

Strange thing is that I don't get this error when running retrieve.php.

Maybe related... I'm also getting this error a few times a day:
[Fri Mar 20 23:07:13 2015] [error] [client 192.168.2.254] SpotWeb Exception occured: Cache is corrupt, could not find on-disk resource for: 3927 ./cache//web/c63/642/8b5/355/0e4/100/471/bbc/624/59c/9d0/bec/f989.http -> ./cache//web/3/3927.http, referer: https://spotweb.server.nl/

But like I said, All pictures show when I click on a spot.

Spotweb is a clean install (arouynd 2 weeks old) on Debian Wheezy.

**Comment by Sweepr** [comment]
If you make too many connection's in a short period of time your usenet provider could reply with an deny, check the time between your retrieve's, suggested once per hour is good enough.

If you do not have retrieve full spots activated, everytime you open a spot or hover on a spot a connection to the usenet server is made to download the image as they are not stored locally, which in turn can cause excessive connections.

You could try to disable the "Show subcats on mouseover in spots list" in your preferences to see if that make's any difference.

**Comment by Sweepr** [comment]
./cache//web/c63/642/8b5/355/0e4/100/471/bbc/624/59c/9d0/bec/f989.http -> ./cache//web/3/3927.http

About the above, i notice there is an extra forward slash here: ./cache//web/  ... this should be /cache/web/

**Comment by Sweepr** [comment]
Any update?

**Comment by Longshot** [comment]
Sadly if I set spotweb to retrieve full spots I get an array of new problems.
The job runs for many minutes instead of the normal few seconds and I get article not found (error 430) pictures on mouse over and in the posts (maybe because the job takes too long and it is killed by the system?).

The cache error has disappeared after I removed the folder and ran check-cache.php.
I hope it stays that way :)

> You could try to disable the "Show subcats on mouseover in spots list" in your preferences to see if that make's any difference.

Nope, no difference.
What is it supposed to do?

**Comment by Sweepr** [comment]
@Longshot 

What about the "SpotWeb Exception occured: Server refused connection [response: "Too many connections."] [response: ""]," errors?

**Comment by Longshot** [comment]
Yes, I'm still getting those but only from other people that use my spotweb.
The show subcat option is turned on by default and most people don't change anything in their settings :)

Only way to get rid of most them is caching all pictures and keep them cached for at least a day or so.
The the error will only show up with searches.

Getting a paid USP with 12+ threads just for spotweb headers will do the trick as well I guess ;)

**Comment by Sweepr** [comment]
Yes, having a decent USP is mandatory, the regular, cheaper one's just aren't cutting it if you are using it for spotweb and private use. (downloading etc.)

**Comment by Longshot** [comment]
True.
It would be nice if you could set the maximum number of threads for header retrieval though.

**Comment by Sweepr** [comment]
@longshot

Spotweb uses only 1 thread, retrieve is not multi threaded.

I think your USP does not allow account sharing. Meaning you cannot connect from multiple ip's at the same time.

**Comment by Longshot** [comment]
Yes, sorry. I meant the retrieval of images.
I'm using textnews.kpn.nl at the moment for retrieval and that's limited to 3 threads.

So I'm guessing every time someone refreshes the index page, spotweb retrieves 3 images and for the remaining images it floods the log with too many connection errors.
Better behaviour would be allowing spotweb to use only an x number of connections for image retrieval.
Or, for spotweb to get 1 image at the time and not all at once.

**Comment by Sweepr** [comment]
@Longshot 

Loading the image's should not cause such issue's as above because an image on average is around 200-300KB.

- How many spots does your main page show upon listing?

You can change this for all users at once using:

 php upgrade-db.php mass-userprefchange perpage=25   or 10, or 50.

- Does your USP allows account sharing? 

- If you connect all from the same IP, make sure you have plenty bandwidth free.

- Use Retrieve full spots to keep the amount of connections to a minimum and set retrieval to 15-30min's, when it catched up retrieval will be fast.

**Comment by Sweepr** [comment]
Closing this since there has not been an update in a week.

Feel free to re-open if needed

**Comment by dsadsdadsadsadsds** [comment]
I think Longshot is right - your browser tries to parallize retrieval of images, and can do so - with ease - for four images at the same time.

If you have an connection limit of 4, or other programs' are also accessing the system, it will definitely start throwing these kind of errors.
