### ISSUE TITLE
PHP Warnings (fileperms(): stat failed) when running retrieve.php

### ISSUE THREAD

**Issue by Marcoevich** [spotweb/spotweb#550]
Hello,

I have revived my old spotweb installation and upgraded it to the latest version (running master branch). Have done upgrade-db.php and now retrieve.php. All working well except these warnings generated by running retrieve.php. What do these mean? And can they be resolved?

Thanks

Here's the log:

Processed a total of 0 reports
Finished retrieving reports.

PHP Warning:  fileperms(): stat failed for /volume1/web/spotweb/lib/../cache/web/2 in /volume1/web/spotweb/lib/dao/Base/Dao_Base_Cache.php on line 329

Warning: fileperms(): stat failed for /volume1/web/spotweb/lib/../cache/web/2 in /volume1/web/spotweb/lib/dao/Base/Dao_Base_Cache.php on line 329
PHP Warning:  fileowner(): stat failed for /volume1/web/spotweb/lib/../cache/web/2 in /volume1/web/spotweb/lib/dao/Base/Dao_Base_Cache.php on line 330

Warning: fileowner(): stat failed for /volume1/web/spotweb/lib/../cache/web/2 in /volume1/web/spotweb/lib/dao/Base/Dao_Base_Cache.php on line 330
PHP Warning:  filegroup(): stat failed for /volume1/web/spotweb/lib/../cache/web/2 in /volume1/web/spotweb/lib/dao/Base/Dao_Base_Cache.php on line 331

Warning: filegroup(): stat failed for /volume1/web/spotweb/lib/../cache/web/2 in /volume1/web/spotweb/lib/dao/Base/Dao_Base_Cache.php on line 331
Unable to write to cache directory (/volume1/web/spotweb/lib/../cache/web/2/2624.http),  owner=,  group=,  thisUser=admin,  perms=
Finished updating blacklist. Added 0, removed 118, skipped 121 of 10751 lines.
PHP Warning:  fileperms(): stat failed for /volume1/web/spotweb/lib/../cache/web/2 in /volume1/web/spotweb/lib/dao/Base/Dao_Base_Cache.php on line 329

Warning: fileperms(): stat failed for /volume1/web/spotweb/lib/../cache/web/2 in /volume1/web/spotweb/lib/dao/Base/Dao_Base_Cache.php on line 329
PHP Warning:  fileowner(): stat failed for /volume1/web/spotweb/lib/../cache/web/2 in /volume1/web/spotweb/lib/dao/Base/Dao_Base_Cache.php on line 330

Warning: fileowner(): stat failed for /volume1/web/spotweb/lib/../cache/web/2 in /volume1/web/spotweb/lib/dao/Base/Dao_Base_Cache.php on line 330
PHP Warning:  filegroup(): stat failed for /volume1/web/spotweb/lib/../cache/web/2 in /volume1/web/spotweb/lib/dao/Base/Dao_Base_Cache.php on line 331

Warning: filegroup(): stat failed for /volume1/web/spotweb/lib/../cache/web/2 in /volume1/web/spotweb/lib/dao/Base/Dao_Base_Cache.php on line 331
Unable to write to cache directory (/volume1/web/spotweb/lib/../cache/web/2/2625.http),  owner=,  group=,  thisUser=admin,  perms=
Finished updating whitelist. Added 0, removed 0, skipped 1062 of 1062 lines.
Starting to create statistics
Finished creating statistics

**Comment by Sweepr** [comment]
First run: php upgrade-db.php --clear-cache see if that sorts the permission problems, then which user run's retrieve? don't use root.

**Comment by Marcoevich** [comment]
I run retrieve.php as admin user, no root. It's running on a Synology NAS.

I've run the clear cache command. It comes wit it's own set of warnings:

Warning: rmdir(/volume1/web/spotweb/cache/image/0): Permission denied in /volume1/web/spotweb/bin/upgrade-db.php on line 15
PHP Warning:  rmdir(/volume1/web/spotweb/cache/image/1): Permission denied in /volume1/web/spotweb/bin/upgrade-db.php on line 15

After running the clear-cache command retrieve.php runs without warnings. Can the warnings above be ignored or is this still something to investigate?

thx

**Comment by Sweepr** [comment]
Seems that there were two folders with permission's higher the user running the retrieve command, that's the cause of the error, after the folder has been cleared using "php upgrade-db.php --clear-cache" the folders should delete regardless and re-create with the correct permission's, 0777 (SUID4) which should clear out the problem.

**Comment by Sweepr** [comment]
There is a change that when you ran `php upgrade-db.php --clear-cache` as `admin` that account did not have sufficient rights to `rmdir` the folder owned by root? hence the error about permissions.  `PHP Warning: rmdir(/volume1/web/spotweb/cache/image/1): Permission denied `

Altough those directories remain on disk, the DB is empty so shouldn't cause any issue, in order to fully solve this issue you could run `php upgrade-db.php --clear-cache ` once as `root` then retrieve normally as `admin`

**Comment by Marcoevich** [comment]
Thank you for the explanation. I edited the /etc/sudoers file to temporarily give root permissions to the admin user by appending `admin ALL = NOPASSWD: ALL` to the end of the file. Root access is otherwise impossible with latest DSM versions.

Now I ran `php upgrade-db.php --clear-cache` and the files and folders where deleted successfully.

Thanks for your help!
