### ISSUE TITLE
Unable to add multiple downloads to NZBget

### ISSUE THREAD

**Issue by Rouzax** [spotweb/spotweb#551]
I have my Spotweb linked to NZBget and that works fine for single click downloads
![image](https://user-images.githubusercontent.com/4103090/84033657-7cf8ec00-a999-11ea-9ef2-b936d822e5b1.png)
However, when adding multiple spots at once , like this
![image](https://user-images.githubusercontent.com/4103090/84034214-512a3600-a99a-11ea-8fdb-fa42b33cdfb8.png)
After hitting the `Download X Spots`
![image](https://user-images.githubusercontent.com/4103090/84033810-bdf10080-a999-11ea-8c04-106a0f6eab13.png)
I see that all download icons spin, also the ones that are not selected, and finally all show the check mark (again also the ones that were not selected) but it only adds 1 of the selected to NZBget.

Is there some logging I can view on this?

Running the latest Dev from GitHub.

**Comment by Sweepr** [comment]
I think it's default behaviour to merge all into one NZB, which will then be all downloaded as one.

![image](https://user-images.githubusercontent.com/2857865/84052071-57c3a800-a9b0-11ea-9b87-0d63a767deca.png)

Creating a ZIP file will send all NZB separately to NZBget of SABnzbd

![image](https://user-images.githubusercontent.com/2857865/84052227-90638180-a9b0-11ea-9bbd-bad028d3a5dc.png)

**Comment by Rouzax** [comment]
I tried both preferences and got the same result, only 1 download is added.

**Comment by Sweepr** [comment]
Weird i tested it using sabnzbd and it's working fine, i don't use nzbget.

@mesa57

Can you verify this using nzbget?

**Comment by Rouzax** [comment]
Also see a weird issue if I keep clicking on the individual downloads that after a few it errors and I can't and anymore.

**Comment by Sweepr** [comment]
Which browser do you use? did you clean out any cache or try another browser to rule out ?

**Comment by mesa57** [comment]
Looks like this is behaviour as designed. If you select multiple NZB's they will alway being sent as 1 NZB with as name the last selected one. Of course this will lead to multiple downloads.
This is the same for NZBGET and SABNZBD.

**Comment by Rouzax** [comment]
I'm using Chrome and Firefox and both have the issue, when I select multiple it really just sends the one download, it is not merged.
Is there any logging that I can check for this?

**Comment by mesa57** [comment]
To answer you're question : there is no logging.

**Comment by Sweepr** [comment]
You could chexk your PHP error log's , or the error log of NZBget for clue's into why this occurs, we both checked the code and it's working as intended.

We can't reproduce this on our machine's.

**Comment by Sweepr** [comment]
There are a couple of situation's were this issue may occur:

1. A missing NZB on the server which will show `getBody(): Failed to retrieve article:` (For this we will implement a warning message)
2. Unrepairable downloads. (No enough repairblocks)

-. Did you have time to check your error log's?

-. Do you see something that looks like this in your log files? `getBody(): Failed to retrieve article:`

-. Which USP do you use?

-. Provide some basic settings like:

![image](https://user-images.githubusercontent.com/2857865/84167091-13024480-aa76-11ea-9cba-5af29b60410b.png)

**Comment by Rouzax** [comment]
Sorry, didn't have time today to further test with this.
The multiple files that won't go together, still work perfectly when done individually so that would rule out bad NZB etc.
Hoping that I have some free time tomorrow to test and play around with this again.
Thanks for the help so far.

**Comment by Rouzax** [comment]
Just tested and both the settings

- Merge NZB files
- Compress NZB files to 1 zip-file

No work and do the same thing.
I indeed get 1 download in NZBget that combines the 2 downloads. Would have thought/hoped that `Compress NZB files to 1 zip-file` would still give me separate downloads since it should be separate NZB files in the zip but that does not seem to happen.

Thank you for fixing this.

**Comment by mesa57** [comment]
Like I stated before : this is behaviour as desigened. The combined NZB (or zip) should however contain all the files of the download selected (which is does).
There was an issue when one of the nzb's was missing, that was not reported.

**Comment by Rouzax** [comment]
I understand.
