### ISSUE TITLE
new change in sabnzbd will break a part of spotweb sabnzbd integration

### ISSUE THREAD

**Issue by Hydranet** [spotweb/spotweb#554]
I run the development branch of sabnzbd and in one of the newest [commits](https://github.com/sabnzbd/sabnzbd/commit/308c0ec621026cf08b12dd761f7975112499d4a7) they removed some very old API code. 

In short spotweb still sends the nzb to sabnzbd but you get a weird  http returncode code type message in the apache error logs, sabnzbd receives the nzb file and downloads it but in spotweb the green download arrow gets a red cross in it as if it failed to send it to sabnzbd.

They are wanting to include this change in the next major release. Here is the github [issue](https://github.com/sabnzbd/sabnzbd/issues/1501) with all the details. Can something be done on the spotweb side to fix this?

**Comment by mesa57** [comment]
Please check develop branch

**Comment by Hydranet** [comment]
> Please check develop branch
Yes that fixed the problem. Thanks! @mesa57

**Comment by Hydranet** [comment]
@mesa57 Is it better to stay on the master branch er better to switch my installation to the develop branch?

**Comment by mesa57** [comment]
You may use the develop branch. It is pushed only once in 1-2 month's to master,
