### ISSUE TITLE
spotweb not parsing nzb head metadata

### ISSUE THREAD

**Issue by mrnatrium** [spotweb/spotweb#559]
Several NZB's downloaded recently contain the .zip (or likewise) password in the NZB head metadata, e.g.:

```
<head>
 <meta type="password">yc9nASD7686AAT7j12A1RuD3vu</meta>
</head>
```

Spots retrieved via other sources, e.g. spotnet, do contain this head information in the nzb xml allowing the download client to automatically use the password during unpacking of the spot. Spotweb does not include this head information in the spot causing the unpack to fail without the password.

Could this head information also be included into the nzb obtained via spotweb.

**Comment by mesa57** [comment]
This is correct, nzb metadata is not supported.

**Comment by mrnatrium** [comment]
That is unfortunate, is metadata support something that could be included in the future? this type of metadata would be very useful.

**Comment by koter84** [comment]
i noticed that when i change my preferences from merge nzb to compress into 1 zip file the head meta stays intact

**Comment by Sweepr** [comment]
@koter84 Thanks for the contribution, i'll considering this issue as resolved.

Be aware this change isn't in the Master branch before the next release.
