### ISSUE TITLE
Spotweb and SABnzbd 3.x: two API bugs in Spotweb

### ISSUE THREAD

**Issue by sanderjo** [spotweb/spotweb#561]
SABnzbd 3.x (now in RC1, final release ETA august 2020) has cleaned up the API and is stricter on correct input, and on output. This reveals two bugs in Spotweb:

https://github.com/sabnzbd/sabnzbd/issues/1501 so "spotweb gives error when pushing to sabnzbd"
https://forums.sabnzbd.org/viewtopic.php?f=11&t=24851 so "However with 3.0.0RC1 the NZB still gets passed and it processes correctly, however the Spotweb icon indicates an error."

**Problem 1: A typo `jsnop`:**

https://github.com/sabnzbd/sabnzbd/issues/1501#issuecomment-643041279
So

A typo `jsnop`:

> looks like spotweb sends output=jsonp which is invalid. should be json. so all this time sab just silently handled that typo and now we dont
> 
> https://github.com/spotweb/spotweb/blob/develop/lib/services/NzbHandler/Services_NzbHandler_Clientsabnzbd.php#L14

and

**Problem 2: text instead of json:**

`output=text`, which should be json:

> https://github.com/sabnzbd/sabnzbd/issues/1501#issuecomment-643042104
> 
> spotweb uses output=text and then checks if 'ok' was returned
> https://github.com/spotweb/spotweb/blob/develop/lib/services/NzbHandler/Services_NzbHandler_Pushsabnzbd.php#L56
> 
> they should just update to json and handle that.. as that will fix 3.x+ support and still work fine with 2.x and older as well

If you could fix that, that would be great for Spotweb users.

HTH

**Comment by Sweepr** [comment]
I think this issue was adressed and resolved in: https://github.com/spotweb/spotweb/issues/554

Please confirm.

**Comment by sanderjo** [comment]
> I think this issue was adressed and resolved in: #554
> 
> Please confirm.

Ah, I see.

I'm not a Spotweb user myself, so I will inform users that they should check / upgrade.

Thanks.

**Comment by Sweepr** [comment]
Its still in dev branch, not sure when @mesa57 will push a new release.

@mesa57, can we release a new version to master?

**Comment by mesa57** [comment]
Yes, looks like a good idea to release to master now.

**Comment by Sweepr** [comment]
See: https://github.com/spotweb/spotweb/releases/tag/1.4.6

Closing this, feel free to re-open if needed.
