### ISSUE TITLE
spotweb on mobile device error after last git pull.

### ISSUE THREAD

**Issue by ckruijntjens** [spotweb/spotweb#569]
Hi All,

On the last git pull i now recieve a error on my mobile phone. Desktop is working as it should.

![Screenshot_20200723-100851](https://user-images.githubusercontent.com/6084672/88265031-086dd880-cccd-11ea-9cdc-13a150a31e4c.jpg)

**Comment by Sweepr** [comment]
What type of installation do you have?

You don't have right to "Display overview spots"  permissions issue.. first fix that.

**Comment by ckruijntjens** [comment]
> What type of installation do you have?
> 
> The user doesn't have the proper rights to "Display overview spots" permissions issue.. first fix that.

Hi Sweepr,

I have a closed system. I have to login before i see spots. Before the git pull it was working. When enter the page from a desktop it works and i see the login screen. On my mobile i dont see the login screen. rights are good because it works on a desktop.

**Comment by Sweepr** [comment]
@ckruijntjens Can you try running `composer dump-autoload` from the spotweb folder?

I see it's complaining about a missing variable "results"

**Comment by ckruijntjens** [comment]
> @ckruijntjens Can you try running `composer dump-autoload` from the spotweb folder?
> 
> I see it's complaining about a missing variable "results"

@Sweepr 

The command is not recognised. I AM running on Debian buster.

**Comment by Sweepr** [comment]
@mesa57 Do you have any idea why this could be happening?

Do we support Debian buster?

**Comment by Sweepr** [comment]
Which platform are you using and how did you install spotweb

Using git

**Comment by ckruijntjens** [comment]
> Which platform are you using and how did you install spotweb
> 
> Using git ?

Yes using git

**Comment by Sweepr** [comment]
If you use your PC to set the template back to we1rdo for fhe mobile devices, do you see the normal spotweb on your mobile device then?

**Comment by Sweepr** [comment]
Still think the anonymous user does not have the permissions to view the spots, maybe this can be because you have a closed system.

**Comment by ckruijntjens** [comment]
> If you use your PC to set the template back to we1rdo for the mobile devices, do you see the normal spotweb on your mobile device then?

No same issue

**Comment by mesa57** [comment]
@Sweepr In a close system normally somebody should be presented with a login screen before the list of spots is shown. This is the behaviour in a normal desktop browser. I suppose the mobile template contains the listing of spots together with the login popup, which does not work because an unauthorized user is not allowed to see spots.

**Comment by ckruijntjens** [comment]
> Still think the anonymous user does not have the permissions to view the spots, maybe this can be because you have a closed system.

Ik dont think do. Before the git pull there are no issues

**Comment by mesa57** [comment]
The mobile template has been changed, That's why.

**Comment by ckruijntjens** [comment]
> The mobile template has been changed, That's why.

Ok thank you. What van we do to resolve this?

**Comment by mesa57** [comment]
Nothing for the moment. I am busy as it is.

**Comment by Sweepr** [comment]
Please let us know if that fixed this issue for you.

**Comment by Sweepr** [comment]
Closing, if needed re-open.
