### ISSUE TITLE
spotweb statistics page

### ISSUE THREAD

**Issue by Hydranet** [spotweb/spotweb#571]
This is more of a question. I used to have a full statistic page when clicking on the statistics menu(under Quick links) option, this was a long time ago. I do get statistics but there is a lot of white space on the page, I don't see any errors in my webserver logs when generating this page.  All the required php extensions have been installed, so I actually have no idea where else to look.

apache: 2.4
php: 7.4
mariadb: 5.5

I attached a file so you can see what it looks like. 

![Screenshot from 2020-07-31 07-00-14](https://user-images.githubusercontent.com/22844936/89002107-8ac55080-d2fc-11ea-9bd5-c983c8e3ab22.png)

**Comment by Sweepr** [comment]
Under "Settings" -> "Performance:" enable "Prepare statistics during retrieve" then run retrieve.php so the statistics get populated.

![image](https://user-images.githubusercontent.com/2857865/89002607-cdd3f380-d2fd-11ea-9738-f9939ccbb888.png)

**Comment by Hydranet** [comment]
@Sweepr Thanks for replying. I already have that option enabled.
Removing Spot information which is beyond retention period,, done
Last retrieve at Fri 31 Jul 2020 07:00:17 AM CEST
```
Retrieving new Spots from server news.newsleecher.com...
Appr. Message count:    3428917
First message number:   2
Last message number:    3428919
Current article number: 3428912

Retrieving 3428912 till 3428920 (parsed: 7, in DB: 1, signed: 7, invalid: 0, rtntn.skip: 0, mod: 0, full: 7, total: 8) in 3.18 seconds
Processed a total of 8 spots
Finished retrieving spots.

Calculating how many spots are new, done.
Last retrieve at Fri 31 Jul 2020 07:27:36 AM CEST
Retrieving new comments from server news.newsleecher.com...
Appr. Message count:    17709188
First message number:   2
Last message number:    17709190
Current article number: 17709166

Retrieving 17709166 till 17709191, found 25 comments in 0.81 seconds
Processed a total of 25 comments
Finished retrieving comments.

Last retrieve at Fri 31 Jul 2020 07:27:41 AM CEST
Retrieving new reports from server news.newsleecher.com...
Appr. Message count:    261231
First message number:   2
Last message number:    261233
Current article number: 261233

Processed a total of 0 reports
Finished retrieving reports.

Finished updating blacklist. Added 0, removed 0, skipped 3 of 10787 lines.
Finished updating whitelist. Added 0, removed 0, skipped 1070 of 1070 lines.
Starting to create statistics 
Finished creating statistics 

Sending notification to user: 18 for filter: Television, it has 1 new spots
Sending notification to user: 18 for filter: Erotica, it has 6 new spots
Sending notification to user: 19 for filter: Television, it has 1 new spots
Sending notification to user: 19 for filter: Erotica, it has 6 new spots
Sending notification to user: 15 for filter: Television, it has 1 new spots
Sending notification to user: 15 for filter: Erotica, it has 6 new spots
Sending notification to user: 28 for filter: Television, it has 1 new spots
Sending notification to user: 28 for filter: Erotica, it has 6 new spots
Sending notification to user: 29 for filter: Television, it has 1 new spots
Sending notification to user: 29 for filter: Erotica, it has 6 new spots
Sending notification to user: 31 for filter: Television, it has 1 new spots
Sending notification to user: 31 for filter: Erotica, it has 6 new spots
Sending notification to user: 32 for filter: Television, it has 1 new spots
Sending notification to user: 32 for filter: Erotica, it has 6 new spots

```

**Comment by Sweepr** [comment]
I understand, i will see if we can do something about the size since currently the size is set to a fixed size: 800x500

**Comment by Hydranet** [comment]
> I understand, i will see if we can do something about the size since currently the size is set to a fixed size: 800x500

Thanks @Sweepr . I thought it was an error or a bad configuration or setting on my end why it was never being giving a full display anymore. Never knew there was a fixed size for the the statistics page.

**Comment by Sweepr** [comment]
@Hydranet 

Not sure exactly what you want, but i have made this:

Image now adapts to the size of the window and is click-able, clicking on the image will open a new tab with the larger image.

![image](https://user-images.githubusercontent.com/2857865/89045092-34cbc980-d34b-11ea-92fd-f88841b53d43.png)

![image](https://user-images.githubusercontent.com/2857865/89045558-03073280-d34c-11ea-98c2-3c241013e5ad.png)

Is this what you like?

If so let me know and i can push the commits to develop branch.

**Comment by Hydranet** [comment]
Yes that sounds good, if you could push it to the develop branch then I will test it out.

**Comment by mesa57** [comment]
Wow nice work @sweepr<mailto:sweepr@outlook.com>

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Sweepr** [comment]
@Hydranet , Pull-request has been merged with Develop branch.

**Comment by Hydranet** [comment]
> @Hydranet , Pull-request has been merged with Develop branch.

@Sweepr Thanks that looks great! Now I have a nice overview of the statistics page instead of having to scroll down as how it is in the master branch now. Thank you!!

**Comment by Sweepr** [comment]
Thank you, closing as it's resolved.

**Comment by Sweepr** [comment]
> 
> 
> > @Hydranet , Pull-request has been merged with Develop branch.
> 
> @Sweepr Thanks that looks great! Now I have a nice overview of the statistics page instead of having to scroll down as how it is in the master branch now. **Would it be possible to have the smaller windows a tad bigger than they are now?**

Sure, you can play around with the settings in here:

https://github.com/spotweb/spotweb/blob/2b1cd492d94c61f3c21a6ad54a213a10eb33c81f/templates/we1rdo/statistics.inc.php#L14

Try chaning max-width: 25%; into max-width: 30%; or 35%;

**Comment by Hydranet** [comment]
> > > @Hydranet , Pull-request has been merged with Develop branch.
> > 
> > 
> > @Sweepr Thanks that looks great! Now I have a nice overview of the statistics page instead of having to scroll down as how it is in the master branch now. **Would it be possible to have the smaller windows a tad bigger than they are now?**
> 
> Sure, you can play around with the settings in here:
> 
> https://github.com/spotweb/spotweb/blob/2b1cd492d94c61f3c21a6ad54a213a10eb33c81f/templates/we1rdo/statistics.inc.php#L14
> 
> Try changing max-width: 25%; into max-width: 30%; or 35%;
Thanks so much! I find 42% it looking the most overview efficient, I think others will too. Could you make that the default?

**Comment by Sweepr** [comment]
What kind of screen type do you use?

I'm using 1x 55 inch and 2 x 24 inch here, for me the 25% looked good, but this will probably differ per PC-screen.

When i set 42% it looks like this:

![image](https://user-images.githubusercontent.com/2857865/89063988-69e71480-d369-11ea-9277-bb114ab7a4a4.png)

**Comment by Hydranet** [comment]
I used in a my 15inch laptop screen and my other screen is 27inch, on both 42% looked good.
![Screenshot from 2020-07-31 20-13-21](https://user-images.githubusercontent.com/22844936/89064470-5a1c0000-d36a-11ea-9361-3fb29329fc20.png)

**Comment by Sweepr** [comment]
Alright then, 42% it will be..

I'll push the change to develop branch.

**Comment by Sweepr** [comment]
Done: https://github.com/spotweb/spotweb/commit/ed2693ebe7a4ddd55badba2ef2b786d3ebc94349

**Comment by Hydranet** [comment]
> Done: [ed2693e](https://github.com/spotweb/spotweb/commit/ed2693ebe7a4ddd55badba2ef2b786d3ebc94349)

Thanks a lot @Sweepr Is there anway I can donate to the spotweb project?

**Comment by Sweepr** [comment]
> 
> 
> > Done: [ed2693e](https://github.com/spotweb/spotweb/commit/ed2693ebe7a4ddd55badba2ef2b786d3ebc94349)
> 
> Thanks a lot @Sweepr Is there anway I can donate to the spotweb project?

@Hydranet That's very kind of you, for now we do not have to option to receive any donation's, we will discuss the option's with the team.

**Comment by Hydranet** [comment]
> > > Done: [ed2693e](https://github.com/spotweb/spotweb/commit/ed2693ebe7a4ddd55badba2ef2b786d3ebc94349)
> > 
> > 
> > Thanks a lot @Sweepr Is there anway I can donate to the spotweb project?
> 
> @Hydranet That's very kind of you, for now we do not have the option to receive any donation's, we will discuss the option's with the team.

@Sweepr I have been running spotweb for some years now, and have found it an easy way of running my own indexer without having to spend too much time on maintenance compared to indexers like newznab.  When reporting an issue it has always been looked into with a fast response time. Knowing you are all volunteers the least I can do is give a donation here and there to show my appreciation for the work you do. I have made donations to other opensource projects which I use a lot, thought it was time to see what the donation options are for spotweb.
