### ISSUE TITLE
Question about Git cloning over an existing spotweb installation

### ISSUE THREAD

**Issue by spoelly** [spotweb/spotweb#582]
I know this maybe is not the place for asking questions, but i did not know where i should do this.

I installed spotweb which is running fine on a Ubuntu installation. Using the wget method.
Now i would like to know if it's posible to do a git clone over the existing installation and do a git pull for updating spotweb?

**Comment by Sweepr** [comment]
@spoelly 

I have never tried this so use at your own risk,

You could try first:

`git init`
then
`git remote add spotweb https://github.com/spotweb/spotweb.git`
then try
`git checkout`
`git pull`

**Comment by spoelly** [comment]
@Sweepr thanks will try it!

**Comment by baruser123** [comment]
i think for now and the future is better to start with a new spotweb git pull. if something in the future is wrong its hard to find. and almost everything is in the database and you still can use the same database. i think you should try that first.

apt install git
cd /var/www/html
git clone https://github.com/spotweb/spotweb.git /var/www/html/spotweb or
git clone https://github.com/spotweb/spotweb.git /var/www/html/spotwebtest if you want to test or something

then copy the dbsettings.inc.php from your spotweb dir now to this new dir and go start your browser and go to new spotweb install. and check if everything is working

**Comment by spoelly** [comment]
The test instance seems to be working.. but something is not fine.. images are not loading and when clicking download i get this:

![image](https://user-images.githubusercontent.com/752857/90506868-3d970a80-e155-11ea-88ce-f24041103e72.png)

**Comment by mesa57** [comment]
The cache folder needs permission to write to.

**Comment by Sweepr** [comment]
@spoelly 

Check the permission's of the cache folder, e.g. 777? and if the file owner is correct

**Comment by spoelly** [comment]
It was the owner which was root :)

**Comment by Sweepr** [comment]
Closing this one, if you need any further assistance feel free to re-open.
