### ISSUE TITLE
Cannot leave comment

### ISSUE THREAD

**Issue by DarkAllMan** [spotweb/spotweb#598]
When I write comment I always get error:
{"result":"failure","data":[],"info":[],"warnings":[],"errors":["Authentication rejected [response: \"Authentication Failed\"] [response: \"\"]"]}

(Running Linux behind NGINX reverse proxy)

**Comment by mesa57** [comment]
Please contact you're USP provider to get authorisation to post messages.

**Comment by DarkAllMan** [comment]
I have write permission. But I changed some server settings and then it started working!
Thx for the pointing in the right direction!
