### ISSUE TITLE
Explanation about versions and upgrades

### ISSUE THREAD

**Issue by dsadsdadsadsadsds** [spotweb/spotweb#61]
Dear,

As there continues to be some confusion about versions, upgrades and likewise, let us try to discuss the issue once and for all in this particular issue. 

My experience is this:
1. The "mediainfo" branch is as far as I can tell the most recent version of Spotweb available. It is stable, and should be used by anyone.
2. The "mediainfo"-part is optional (it contains both 'collections' and TMDB integration of some sorts), and should only be enabled on well equipped hardware. 
3. You can safely *upgrade* from your current installation to the mediainfo branch.
4. You can *never* downgrade an Spotweb installation succesfully.

With regards to the database itself:

1. Databases don't go stale, they don't start to smell bad and they do not grow mouldy green hairs. There is no need to "start fresh" or anything like that. The only reason for that would be to severely reduce the size of the database. You never hear of your local bank starting fresh with their database so why would Spotweb need to?
2. Starting from scratch with an empty database is very seldom a valid troubleshooting tactic. Please stop advising it unless the user has messed around in the database entries yourselve of you have tried a downgrade.
3. Do not downgrade your Spotweb version.
4. Do not manually modify the Spotweb database.
5. You can safely run ````upgrade-db```` as many times that you like.

**Comment by Sweepr** [comment]
Well said and i agree on this.

**Comment by slug1982** [comment]
How do you enable the  "mediainfo"-part ? Am using that branch and see no
TMDB info or any mention of it in the settings.

TIA

On Mon, Apr 27, 2015 at 6:51 PM, dsadsdadsadsadsds <notifications@github.com

**Comment by mbirth** [comment]
I assume this isn't up-to-date information anymore? The last commit in the [media](/spotweb/spotweb/tree/media) branch is from 18th of June whereas the master had some commits and merges since then.

**Comment by Sweepr** [comment]
@slug1982, the mediainfo part is not finished, the person who started it didn't finish the project and left probably.

@mbirth, info is pretty much up to date, both branch's can be used

**Comment by mbirth** [comment]
@Sweepr Is the mediainfo going to be finished some day or do you just maintain it in case the developer comes back?

**Comment by Sweepr** [comment]
Probably it won't get finished untill someone experienced picks up where the previous left of, and then it's still a question what his intentions were, what was he trying to accomplish. for now we just stick to the current code Master and Media branch provide.

**Comment by mbirth** [comment]
What about porting single features over, like e.g. the two new notification services? I believe this would be rather easy and maybe I can help with that.

**Comment by dsadsdadsadsadsds** [comment]
This is probably still an accurate issue -- the mediainfo branch was rather more advanced than the mainline branch.

Some features of the Mediainfo branch which - i reckon - are interesting:

* Collections: The system automatically cleans up Spotweb titles and runs some silly heuristics on them to create collections. Eg it will group all Ubuntu 11.0 Linux DVD spots into one collection. In the Spotweb interface you can either search on collections, or from the Spot detail you could view the other collections. It also does this for seasons, episodes, and the likes.

* Mediainfo: This part is not finished. It allows you to interface (the collections) with TheMovieDB to download additional information and additional media (eg: trailers, covers, etc) for the collection. The collection and downloading part is already finished, it needs a frontend UI though.

**Comment by mesa57** [comment]
"This branch is 57 commits ahead, 42 commits behind master."
First those 42 commits from master should be merged.
This begins to look like a job for somebody unemployed.

**Comment by mesa57** [comment]
No more feedback, closing issue.
