### ISSUE TITLE
Error on line 2 at column 1: Extra content at the end of the document (Tvmazeid error on api request )

### ISSUE THREAD

**Issue by blikzy** [spotweb/spotweb#616]
Im getting an error on the following request, its generated from sonarr (2.0.0.5344). Its a manual search on an episode.
I couldn't find any similar issue in here.
URL:
http://spotweb/api?t=tvsearch&cat=5030,5040&extended=1&apikey=<apikey>&offset=0&limit=250&tvmazeid=17405&season=12&ep=8

Error:
This page contains the following errors:
error on line 2 at column 1: Extra content at the end of the document
Below is a rendering of the page up to the first error.

Both sonarr and spotweb are running under Freenas 11.3-u5.

**Comment by Sweepr** [comment]
Can you have a look at this: https://github.com/spotweb/spotweb/issues/93


Im getting an error on the following request, its generated from sonarr (2.0.0.5344). Its a manual search on an episode.
I couldn't find any similar issue in here.
URL:
http://spotweb/api?t=tvsearch&cat=5030,5040&extended=1&apikey=&offset=0&limit=250&tvmazeid=17405&season=12&ep=8

Error:
This page contains the following errors:
This is the actual error: --> **error on line 2 at column 1: Extra content at the end of the document**
Below is a rendering of the page up to the first error.

Both sonarr and spotweb are running under Freenas 11.3-u5.

**Comment by mesa57** [comment]
You mean me ?

**Comment by Sweepr** [comment]
No to @blikzy

**Comment by Sweepr** [comment]
@blikzy Did you sort it out?

Closing this, re-open if you feel the need.

**Comment by blikzy** [comment]
![tvmazeid error](https://user-images.githubusercontent.com/1174068/116821782-8d025700-ab7b-11eb-88e3-cda87fd5c634.JPG)
Ik krijg nog steeds de zelfde error als ik spotweb als indexer aan sonarr hang. Als 
I am still getting the same error when i try Spotweb as indexer for my sonarr. When i try the generated url from sonarr in my broser i am getting this error. Question is the url wrong generated or is it something else. When i delete tvmazeid in the url it shows some data.
URL generated is:
http://192.168.1.138/api?t=tvsearch&cat=5030,5040&extended=1&apikey=[apiverwijderd]&offset=0&limit=250&tvmazeid=41530&season=1&ep=11
It doesnt matter which show i try, keeps gettings this error.

Thank u

**Comment by Sweepr** [comment]
See: https://github.com/spotweb/spotweb/issues/93#issuecomment-327285244

**Comment by blikzy** [comment]
i haven't changed anything but it works now :-)
