### ISSUE TITLE
Unable to re-open webview after logging out

### ISSUE THREAD

**Issue by frankvHoof93** [spotweb/spotweb#619]
**Describe the bug/issue**
 - A clear and concise description of what the bug is.
After logging out my admin user, I can no longer bring up the GUI

**To Reproduce**
1. Go to 'server/spotweb'
2. Click on 'user (admin)'
3. Click Logout

Notice: Array to string conversion in /volume1/web/spotweb/lib/dbeng/dbeng_pdo.php on line 68 Notice: Array to string conversion in /volume1/web/spotweb/lib/dbeng/dbeng_pdo.php on line 68 Notice: Array to string conversion in /volume1/web/spotweb/lib/dbeng/dbeng_pdo.php on line 68 Notice: Undefined index: userid in /volume1/web/spotweb/lib/SpotSecurity.php on line 141 Notice: Undefined index: prefs in /volume1/web/spotweb/lib/services/User/Services_User_Authentication.php on line 159 Notice: Undefined index: userid in /volume1/web/spotweb/lib/services/User/Services_User_Authentication.php on line 79 Notice: Undefined index: prefs in /volume1/web/spotweb/index.php on line 63 Notice: Undefined index: prefs in /volume1/web/spotweb/index.php on line 64 Notice: Undefined index: userid in /volume1/web/spotweb/index.php on line 72 Notice: Undefined index: userid in /volume1/web/spotweb/index.php on line 452 Fatal error: Uncaught Error: Class 'SpotTemplateHelper_' not found in /volume1/web/spotweb/lib/page/SpotPage_Abs.php:104 Stack trace: #0 /volume1/web/spotweb/lib/page/SpotPage_Abs.php(43): SpotPage_Abs->getTplHelper(Array) #1 /volume1/web/spotweb/lib/page/SpotPage_index.php(11): SpotPage_Abs->__construct(Object(Dao_Mysql_Factory), Object(Services_Settings_Container), Array) #2 /volume1/web/spotweb/index.php(458): SpotPage_index->__construct(Object(Dao_Mysql_Factory), Object(Services_Settings_Container), Array, Array) #3 {main} thrown in /volume1/web/spotweb/lib/page/SpotPage_Abs.php on line 104

**Expected behavior**
 - A clear and concise description of what you expected to happen.
Login-screen

**Desktop (please complete the following information):**
 - OS: Synology DSM 6
 - Spotweb Version: Latest on master
 - Which branch  Master
 -  PHP version 7.4
 -  Device information Synology DS413j

**Comment by Sweepr** [comment]
@frankvHoof93 

Something in your database messed up, can you try to run `upgrade-db.php` from the CLI and see if that fixes your missing indexes?

**Comment by frankvHoof93** [comment]
@Sweepr 
Upgrade-db completed without errors, but the result is the same.

**Comment by Sweepr** [comment]
Did you install using git clone, and which setup type did you choose?

![image](https://user-images.githubusercontent.com/2857865/95606975-60f67b80-0a5b-11eb-9f98-71c641f14186.png)

**Comment by Sweepr** [comment]
@frankvHoof93 

I cannot reproduce the, i installed the latest master using `git clone -b master https://github.com/spotweb/spotweb.git .` on my DS218 running DSM 6.2.3-25426 and MariaDB Server version: 5.5.62 on PHP 5.6.11 and on MariaDB 10.3.21, PHP 7.4.2, both running fine.

I can login and logout using the admin account without seeing this issue.

Please take a look at this older and resolved issue:

https://github.com/spotweb/spotweb/issues/352

**Comment by frankvHoof93** [comment]
Deleting dbsettings.inc.php and re-running the install-script seems to have resolved this issue...
Now back to what I was actually trying to do: find the API-key.. I thought it was supposed to be visible under the 'change user'-menu?

**Comment by Sweepr** [comment]
@frankvHoof93 Correct.. it is.

an admin actually does not have an API key, the first user does.
