### ISSUE TITLE
retrieve very slow on media branch

### ISSUE THREAD

**Issue by klara31** [spotweb/spotweb#62]
My usenet provider (extremeusenet) switched to a new platform. Hence I had to make a full, initial retrieve. This is taking very, very long on the media branch. I have decreased the number of spots parameter to 1000 and notice that there looks to be a 1:1 relation between the number of full posts and the time it takes to process them:
````
...
Retrieving 2309309 till 2310310 (parsed: 1001, in DB: 0, signed: 1, invalid: 1000, rtntn.skip: 0, mod: 0, full: 1, total: 1001) in 0.5 seconds
Retrieving 2310310 till 2311311 (parsed: 1001, in DB: 0, signed: 6, invalid: 995, rtntn.skip: 0, mod: 0, full: 6, total: 1001) in 2.64 seconds
Retrieving 2311311 till 2312312 (parsed: 1001, in DB: 0, signed: 113, invalid: 870, rtntn.skip: 0, mod: 18, full: 113, total: 1001) in 15.06 seconds
Retrieving 2312312 till 2313313 (parsed: 1001, in DB: 0, signed: 936, invalid: 3, rtntn.skip: 0, mod: 62, full: 936, total: 1001) in 114.84 seconds
...
````
My server (intel i3, Ubuntu with 12G memory) is already processing for more than a day, whereas it used to take only a couple of hours on the same system. What has happened?

**Comment by Sweepr** [comment]
Why not disable to retrieval of fullspots then? and try again?

**Comment by Sweepr** [comment]
Maybe also disable retrieval of comments full

**Comment by klara31** [comment]
I guess that there a a number of ways to speed the retrieve up. I am only wondering why it is taking so long now, whereas it took a lot less time with the same settings before!

**Comment by Sweepr** [comment]
Not sure what went wrong there, only thing i can come up with:

The switch with your usenetprovider caused issue's in retrieval where it now tries to retrieve spots which already do exist in the spots and comments table's, this causes timeout, .

What does your error_log tell? and did could you try to run retrieve --debug?

**Comment by Sweepr** [comment]
You could also try to set this option in your settings to May 9th 2015 and then start an retrieval so i would skip most of the maybe already retrieved spots, let it finish so it catches up and continue normal retrieval from there.

![untitled](https://cloud.githubusercontent.com/assets/2857865/7550711/7f1245bc-f66c-11e4-8973-2830ac592bc5.png)

**Comment by klara31** [comment]
I started with an empty database. Can you help me where to find the error_log?

**Comment by Sweepr** [comment]
Should be in your spotweb root.. if you have enabled error logging in the php.ini

**Comment by Sweepr** [comment]
Any news?

**Comment by klara31** [comment]
I have switched off 'full spots' to make it quicker...

**Comment by Sweepr** [comment]
Closing.
