### ISSUE TITLE
Error parsing nzb-file: Start tag expected, '<' not found when trying to open nzb

### ISSUE THREAD

**Issue by Cyclone47** [spotweb/spotweb#623]
For a while I've noticed that my Sonarr and Radarr cannot download anything coming from spotweb anymore.
errorcode:
**Request Failed. POST /api/release: Data at the root level is invalid. Line 2, position 1.**

Now to troubleshoot it I have tried to manually download the nzb file from Spotweb and open them in NZBGet, and I get the following error:
**Error parsing nzb-file: Start tag expected, '<' not found**

Does anyone have a clue what I can do to fix this?

I have tried running spotweb from apache and nginx and php version 5.6. Both give me the same issue.

If needed I can create a testaccount on my spotweb.

**Comment by Sweepr** [comment]
Could you attach the NZB to this issue so we can have a look at the actual file?

**Comment by Sweepr** [comment]
I also would like to know which version's you are running?

Spotweb: v? / branch?
Sonarr: v?
Radarr: v?
NZBGet: v?

**Comment by Cyclone47** [comment]
> Could you attach the NZB to this issue so we can have a look at the actual file?
[sample nzb file.zip](https://github.com/spotweb/spotweb/files/5470512/sample.nzb.file.zip)


> I also would like to know which version's you are running?
> 
> Spotweb: v? / branch?
Not entirely sure, I see this at latest change in the changelog file
1-9-2019 Sweepr: fix for: https://github.com/spotweb/spotweb/issues/437
> Sonarr: v?
2.0.0.5344
> Radarr: v?
0.2.0.1504
> NZBGet: v?
Currently installed: 21.0

Also good to mention is that I have tried opening the nzb file in Spotnet and Synology DS Downloader, and it also didn't want to eat it.

**Comment by Sweepr** [comment]
The error you get is: **Error parsing nzb-file: Start tag expected, '<' not found**

Which is correct looking at the XML itself. the first lines start with:

Warning: fileperms(): stat failed for /volume1/web/spotweb/lib/../cache/nzb/0 in /volume1/web/spotweb/lib/dao/Base/Dao_Base_Cache.php on line 329

Warning: fileowner(): stat failed for /volume1/web/spotweb/lib/../cache/nzb/0 in /volume1/web/spotweb/lib/dao/Base/Dao_Base_Cache.php on line 330

Warning: filegroup(): stat failed for /volume1/web/spotweb/lib/../cache/nzb/0 in /volume1/web/spotweb/lib/dao/Base/Dao_Base_Cache.php on line 331

Where the parser expects: <

These three lines should not be there, please resolve that permissions issue and it will work.

I have attached the edited NZB for you to try.

[editednzb.zip](https://github.com/spotweb/spotweb/files/5470551/editednzb.zip)

**Comment by Sweepr** [comment]
You could use this for validation: https://www.w3schools.com/xml/xml_validator.asp or https://www.xmlvalidation.com/

**Comment by Cyclone47** [comment]
Thanks for finding out it's related to the xml. I have followed your advice and tried to run the upgrade-db command. 
```
Schema update done
Updating settings
Settings update done
Updating users
Users' update done
No argument passed, type --clear-cache -yes to bypass this.
 The cache in DB and files on-disk will be cleared, are you sure?

 Type 'yes' to confirm or any other key to abort:

yes
Checking if retriever is running, if so wait for it to finish.
Retriever is not running.
Continuing...
Clear on-disk cache folder.
Truncating cache table.
Cleared cache succesfully!

Performing basic analysis of database tables
Basic database optimalisation done

```
It appears to be that the problem still exists. I have tried retrieving a few new nzb files and imported these in nzbget.
[Uploading sample_nzb_2.zip…]()

**Comment by Sweepr** [comment]
Ok, the NZB attached isn't uploaded properly.

Can you check in your php.ini file if **display_errors = On** ? If so set to **Off**

**Comment by Cyclone47** [comment]
[sample_nzb_3.zip](https://github.com/spotweb/spotweb/files/5470590/sample_nzb_3.zip)
Hi, display_errors is set to off. Here is another nzb file.

**Comment by Sweepr** [comment]
@Cyclone47 
File is also wrong, somehow your webserver cannot enter directory `/volume1/web/spotweb/cache/nzb/0`

Could you paste the results of :
`ls -alF /volume1/web/spotweb/cache/ | grep -Ei ' ./'`
and
`ls -alF /volume1/web/spotweb/cache/nzb | grep -Ei ' ./'`
and
`ls -alF /volume1/web/spotweb/cache/nzb/0 | grep -Ei ' ./'`

**Comment by Cyclone47** [comment]
**signed in as root:**
`root@Synology-NAS:/volume1/web/spotweb# ls -alF /volume1/web/spotweb/cache/ | grep -Ei ' ./'
d---------+ 1 root     root   16 Nov  1 12:00 ./
root@Synology-NAS:/volume1/web/spotweb# ls -alF /volume1/web/spotweb/cache/nzb | grep -Ei ' ./'
ls: cannot access '/volume1/web/spotweb/cache/nzb': No such file or directory
root@Synology-NAS:/volume1/web/spotweb# ls -alF /volume1/web/spotweb/cache/nzb/0 | grep -Ei ' ./'
ls: cannot access '/volume1/web/spotweb/cache/nzb/0': No such file or directory
root@Synology-NAS:/volume1/web/spotweb#
`

Looks like the cache/nzb is not there

**Comment by Cyclone47** [comment]
@Sweepr It looks like manually creating these folders and giving using chmod 755 -R /cache solved the issue. Not sure if it's an acceptable solution though?

**Comment by Sweepr** [comment]
Cache folder must be 777 

Also /volume1/web/spotweb/cache/ is owned by `root:root` which is not correct, this should be owned by `nobody:nobody` or `www-data:www-data` so the webserver which run's as such can read/write there..  if the folder is owned by **root**, the webserver can't access it.

You could do `chown -R http:http cache` from `/volume1/web/spotweb`

**Comment by Cyclone47** [comment]
I have changed it to 777 and fixed the ownership.

Infinito@Synology-NAS:/volume1/web/spotweb$ ls -alF /volume1/web/spotweb/cache/nzb | grep -Ei ' ./'
drwxrwxrwx 1 http http  2 Nov  1 12:19 ./
drwxrwxrwx 1 http http 14 Nov  1 12:25 0/
Infinito@Synology-NAS:/volume1/web/spotweb$ ls -alF /volume1/web/spotweb/cache/nzb/0 | grep -Ei ' ./'
drwxrwxrwx 1 http http    14 Nov  1 12:25 ./
Infinito@Synology-NAS:/volume1/web/spotweb$

Looks like everything works, thank you very much! Feel free to close this if you want.

**Comment by Sweepr** [comment]
Perfect!, some issue's these wrong permissions can cause sometimes.
