### ISSUE TITLE
PHP Notice:  Trying to access array offset on value of type null 

### ISSUE THREAD

**Issue by udovdh** [spotweb/spotweb#627]
**Describe the bug/issue**
I see PHP Notice:  Trying to access array offset on value of type null in /var/www/spo
tweb/lib/services/Retriever/Services_Retriever_Spots.php on line 505 in emails from cron jobs.

**Have you searched the internet or Github for an answer?**
Yes.

**To Reproduce**
1. Go to CLI
2. Type `mailx`
3. See emails from spotweb cron jobs

**Expected behavior**
Cron job without emails reporting php issue

**Screenshots**
& 12
Message 12:
From root@hierzo  Fri Dec  4 13:01:10 2020
Return-Path: <root@hierzo>
Date: Fri, 4 Dec 2020 13:01:10 +0100
From: "(Cron Daemon)" <root@hierzo>
To: root@hierzo
Subject: Cron <root@hierzo> run-parts /etc/cron.hourly
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
Precedence: bulk
X-Cron-Env: <LANG=en_US.UTF-8>
X-Cron-Env: <SHELL=/bin/bash>
X-Cron-Env: <PATH=/sbin:/bin:/usr/sbin:/usr/bin>
X-Cron-Env: <MAILTO=root>
X-Cron-Env: <HOME=/root>
X-Cron-Env: <LOGNAME=root>
X-Cron-Env: <USER=root>
Status: R

/etc/cron.hourly/spotweb_spots:

PHP Notice:  Trying to access array offset on value of type null in /var/www/spo
tweb/lib/services/Retriever/Services_Retriever_Spots.php on line 505

**Desktop (please complete the following information):**
 Fedora 32
Firefox
Git latest
Master?
php-7.4.13-1.fc32.x86_64

 -  Device information (ReadyNAS/Synology/FreeNAS)
PC with AMD Ryzen 5 3400G with Radeon Vega Graphics

**Additional context**
I was at home...

**Comment by udovdh** [comment]
# cd /var/www/spotweb/
[root@surfplank2 spotweb]# git branch
  develop
* master
# git pull
Already up to date.

**Comment by Sweepr** [comment]
Do you have these option's enabled?

![image](https://user-images.githubusercontent.com/2857865/101183056-3dad0e80-364f-11eb-8f50-227adadd1c00.png)

If so, you could try to disable all 3, or revert to 7.3 as it's just a notice being generated by PHP7.4

**Comment by udovdh** [comment]
Thanks. Settings adjusted.
Can verify workings in a quarter of an hour.

**Comment by udovdh** [comment]
Can we disable the php 7.4 notice in the code?

**Comment by Sweepr** [comment]
You can in your `php.ini` file

By doing this: error_reporting = E_ALL & ~E_NOTICE in the php.ini, this disables the PHP Notices

**Comment by udovdh** [comment]
That appears to be the default value in my php.ini.
But we'll make it explicit.

**Comment by Sweepr** [comment]
Can this issue be closed? @udovdh

**Comment by udovdh** [comment]
After making error_reporting = E_ALL & ~E_NOTICE explicit instead of the same but commented out things remain quiet.
Please go ahead and close the issue.
