### ISSUE TITLE
delete spots with more than 5 spam reports: SQL Query not working.

### ISSUE THREAD

**Issue by Sweepr** [spotweb/spotweb#63]
From https://github.com/spotweb/spotweb/wiki/Handy-SQL-Query%27s
I got:

To delete spots with more than 5 spam reports:

DELETE FROM spots WHERE messageid IN (SELECT nntpref FROM reportsxover)
GROUP BY nntpref
HAVING ( COUNT(nntpref) > 5 );

But.. it's not working, i get an error saying:

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'GROUP BY nntpref HAVING ( COUNT(nntpref) > 5 )' at line 2

Can anyone using SQL tell me what the correct query must be?

**Comment by Raver099** [comment]
I have the exact same problem using MariaDB through phpMyAdmin and no clue where it goes wrong. 

Any ideas?

**Comment by Sweepr** [comment]
No sure.. tried to fix this, took me an hour then i gave up and using this ever since:

DELETE FROM `spots` WHERE `reportcount` >= 3;  (Or any other number you like)

**Comment by Sweepr** [comment]
Added this to https://github.com/spotweb/spotweb/wiki/Handy-SQL-Query%27s 

Closing this now.
