### ISSUE TITLE
[New issue] This query is not allowed!

### ISSUE THREAD

**Issue by Hydranet** [spotweb/spotweb#632]
**Describe the bug/issue**
 - Search spotweb gives error: "This query is not allowed!"

**Have you searched the internet or Github for an answer?**
 - I can't find a previous issue relating to this.

**To Reproduce**
1. In the search type a search pattern with double quotes; ie: **"test"**
2.  Press Enter, which results in the error.
3.  If I do the search pattern with single quotes or without quotes it seems to work; ie: **test** and ie: **'test'**

**Expected behavior**
- The search always used to work with double quotes.

**Additional context**
I enabled "stacktrace" within spotweb which didn't show anything and my apache logs don't show any errors so I suspect it may have something to do with a recent security [issue](https://github.com/spotweb/spotweb/issues/629) I found in the closed issues. 
I think it's this commit(b5415d6b6ad25fc6cfd302cd2e73f6799ef34044):

```
--- a/lib/dao/Base/Dao_Base_Spot.php
+++ b/lib/dao/Base/Dao_Base_Spot.php
@@ -29,55 +29,53 @@ class Dao_Base_Spot implements Dao_Spot
          * which are always available in the query
          */
         $criteriaFilter = ' WHERE (bl.spotterid IS NULL) ';
-        if (!empty($parsedSearch['filter'])) {                 
+        if (!empty($parsedSearch['filter'])) {
             $criteriaFilter .= ' AND '.$parsedSearch['filter'];
-               
-                       /* Blacklisted SQL commands */
-
-                       $notAllowedCommands = array(
-                       'DELETE',
-                       'TRUNCATE',
-                       'AS',
-                       'DROP',
-                       'USE',
-                       'SELECT',
-                       'SLEEP',


```
And I found the error which I am getting in the file which was updated:
`lib/dao/Base/Dao_Base_Spot.php:                echo 'alert("This query is not allowed!")';`

I just wanted to be sure because I find this behavior strange because searching with double quotes always used to work. Can you verify that the fix for the security issue disabled searching with double quotes because I don't know php so am unable to verify it myself, if not then this is a new issue.

**Comment by Sweepr** [comment]
Please check the latest commit, this should be fixed now.

**Comment by Hydranet** [comment]
> Please check the latest commit, this should be fixed now.

Yes that fixed it, thank you!
