### ISSUE TITLE
Deprecated: Function libxml_disable_entity_loader() is deprecated 

### ISSUE THREAD

**Issue by WoBBeLnl** [spotweb/spotweb#634]
**Describe the bug/issue**
 - When using the latest version of spotweb ("master" branch) with PHP 8.0 I get the following error: Deprecated: Function libxml_disable_entity_loader() is deprecated in lib/Bootstrap.php on line 82

**Have you searched the internet or Github for an answer?**
Cant find anything through Google or in the know nissues

**To Reproduce**
Open random page in spotweb

**Expected behavior**
No error :-)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10
 - Spotweb Version: latest master
 - Which branch  (Master/Develop): master
 -  PHP version: PHP 8, libxml 2.9.10 
 -  Device information (ReadyNAS/Synology/FreeNAS): a real physical machine :-)

**Additional context**
The function has been deprecated: https://www.php.net/manual/en/migration80.deprecated.php
Commenting the libxml_disable_entity_loader(true); command works

The function is not required anymore with PHP 8 / libxml 2.9. 

Im too retarded (no clue how git works) to fix this issue in the code on github itself :-) and my PHP skills are quite low haha.
```

if ( LIBXML_DOTTED_VERSION < "2.9" )
{

	libxml_disable_entity_loader(true) 

}
```

**Comment by Sweepr** [comment]
@WoBBeLnl 

I added a fix for this is in the dev branch, you could add this to your install for the time being untill it has been merged into master.

Let us know if this solved the issue.

**Comment by WoBBeLnl** [comment]
I can confirm this fix works (manually changed Bootstrap.php). 🥇 

Just curious: what does the \ before PHP_VERSION_ID do?

**Comment by mesa57** [comment]
@Sweepr : are you sure this doesn't affect previous php version installations ?

**Comment by WoBBeLnl** [comment]
It doesnt, it checks if PHP version is 8 or higher so no issues with previous versions.

**Comment by Sweepr** [comment]
@WoBBeLnl The \ is used in PHP 5.3 for namespaces. See http://www.php.net/manual/en/language.namespaces.rationale.php for more information on namespaces and PHP.

**Comment by Sweepr** [comment]
@mesa57 Should be fine for lower version, it only removes this when PHP 8.0 is used, because it's already (true) enabled by default.
