### ISSUE TITLE
Spotweb reversed proxy and non working API

### ISSUE THREAD

**Issue by rourke** [spotweb/spotweb#643]
**Describe the bug/issue**
 - I've setup Spotweb through docker, behind a reversed proxy through Traefik. Traefik is taking care of all the https/ssl traffic, so after a bit of searching I found that I had to add `$settings['ssloverride'] = true;` to the `ownsettings.php` file. The web interface is working well with this setting.
 - However, I'm also using NZBHydra through docker on the same server. Internally they can reach each other by hostname and no https is required. So NZB Hydra is communicating to Spotweb with the hostname `spotweb`. An example API request would be to `http://spotweb/api?apikey=[hidden]&t=search&extended=1&q=maastricht&password=1&limit=100&offset=0`.
 - Because `ssloverride` is `true` all enclosure urls from the API are also https. NZB Hydra is 'Unable to find' these URLs and because of that always returning 0 results.

**Have you searched the internet or Github for an answer?**
 - Yes, endlessly.

**To Reproduce**
N/A

**Expected behavior**
 - When I do a call to `http://spotweb/api...` I expect the returned urls to also use http.
 - When I do a call to `https://spotweb.example.com/api...` I expect the returned urls to also use https.
 - Also a suggestion to use `//` on the front-end, which will always use the right protocol.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Whichever OS the docker container uses
 - Browser: Shouldn't be relevant, but Chrome
 - Spotweb Version 1.4.9
 - Which branch: Master
 - PHP version: docker supplied version
 - Device information (ReadyNAS/Synology/FreeNAS): Dedicated server with Ubuntu Server 20.04

**Smartphone if applicable (please complete the following information):**
N/A

**Additional context**
Provide any other information about the bug or issue that can further help debugging here.

**Comment by Sweepr** [comment]
I am not able to recreate your setup so quickly, but after reading your issue it seem that this is a problem of NZBhydra, not Spotweb, would it be possible to rewrite the spotweb's API response from HTTPS to HTTP so NZBhydra can handle them?

**Comment by mesa57** [comment]
Just took a glance at you're problem. It is not possible to use ssl and non-ssl both with ssloverride.

**Comment by Sweepr** [comment]
@rourke 

Any update?

**Comment by rourke** [comment]
Sorry, I wasn't able to work on the problem after my previous post. I'm trying to contact the NZBHydra team because after a bit more investigation this might indeed be something on their side. Or it might be some configuration mistake on my end. Hopefully I can give an update here soon.

Even though it isn't my specific intention, might it not be easier for you as developers and for the end-users to use [the shorthand protocol `//`](https://stackoverflow.com/a/9646435)? That would make `ssloverride` obsolete because it adapts to the protocol used by the end-user.

**Comment by Sweepr** [comment]
Protocol-relative URL used to be recommended when sites were mixed http/https, nowadays it's considered bad practice.

Protocol-relative URLs

This is a URL that leaves of the http:// or https:// bit. This type of relative URL does have its uses, but it should not be deployed outside of those useful cases. The useful cases are when it's used inside JavaScript or CSS, so files are served over the same protocol as the current page, especially because when you're on a https URL, serving anything over http basically breaks the security. Using protocol relative URLs within links or canonical URLs is a very bad idea though, because you can still have duplicate content issues between http and https versions of a website.

**Comment by rourke** [comment]
Yes, that is definitely true.

In the meantime the NZB Hydra developer [provided me with the solution](https://github.com/theotherp/nzbhydra2/issues/668#issuecomment-759474563). NZB Hydra was expecting `application/x-nzb` as `type` in the `enclosure` tag, while the Spotweb API returned `application/zip`. To fix this the option below should be set to 'Merge NZB files'.

![image](https://user-images.githubusercontent.com/2820753/104465614-817f2600-55b4-11eb-8e5c-e1437f83340d.png)

I changed this to zip a while ago because NZBGet can handle zip files and it would look cleaner to have separate downloads instead of 1 large download processing 2 movies for example.

Anyway, thanks for your help!
