### ISSUE TITLE
API page 404

### ISSUE THREAD

**Issue by PascalBu** [spotweb/spotweb#644]
**Describe the bug/issue**
I cannot figure out how to access the api page to use in Sonarr/Radarr

**Have you searched the internet or Github for an answer?**
Tried a lot after searching

**To Reproduce**
N/A

**Expected behavior**
Seeing the API page when going to [ serverip]/api?t=c

**Desktop (please complete the following information):**
 - Ubuntu-server 20.04 VM on Proxmox
 - Browser Chrome
 - Spotweb Version latest
 - Which branch Master)
 -  PHP version 7.4.3
 -  Device information Intel NUC with Proxmox Hypervisor

**Additional context**
Started with a fresh install of Ubuntu Server 20.04 in a VM on Proxmox. Then followed the wiki on install on linux. Spotweb is working just fine, however cannot reach the api page.

Webserver is running from /var/www/spotweb;

edited /etc/apache2/sites-available/000-default.conf and /etc/apache2/sites-enabled/000-default.conf
>     DocumentRoot /var/www/spotweb

edited /var/www/spotweb/.htaccess to reflect:
RewriteEngine on
RewriteCond %{REQUEST_URI} !api/
RewriteRule ^api/?$ index.php?page=newznabapi [QSA,L]

Also tried some different directory configs for apache2.conf, this lead to internal server errors

Could anyone guide me in the right direction?

**Comment by baruser123** [comment]
i use nginx what's need another config, but did some search and i found the following for htcaccess

<IfModule mod_rewrite.c>
   RewriteEngine on
   RewriteCond %{REQUEST_URI} !api/
   RewriteRule api/?$ index.php?page=newznabapi [QSA,L]
</IfModule>

it looks the same but i got <IfModule mod_rewrite.c> and </IfModule> with. maybe that's the problem

**Comment by Sweepr** [comment]
Does your user have permission to access the api?

**Comment by PascalBu** [comment]
You mean with folder/file permission?

Just changed with sudo chmod -R a+rwx /var/www/spotweb but no difference

**Comment by Sweepr** [comment]
@PascalBu 

What do you see when you browse to `[serverip]/api` and `[serverip]/?page=newznabapi`

**Comment by PascalBu** [comment]
/api gives a 404

/?page=newsnabapi gives another error:

this XML file does not appear to have any style information associated with it. The document tree is shown below.
<error code="200" description="Missing parameter"/>

**Comment by Sweepr** [comment]
@PascalBu Seems like you do not have mod_rewrite enabled in apache.

Can you check with `apache2ctl -M` and see if there is a mod_rewrite enabled?

See here for instructions: https://www.digitalocean.com/community/tutorials/how-to-rewrite-urls-with-mod_rewrite-for-apache-on-ubuntu-20-04

_**Step 1 — Enabling mod_rewrite**

In order for Apache to understand rewrite rules, we first need to activate mod_rewrite. It’s already installed, but it’s disabled on a default Apache installation. Use the a2enmod command to enable the module:

`sudo a2enmod rewrite`

This will activate the module or alert you that the module is already enabled. To put these changes into effect, restart Apache.

`sudo systemctl restart apache2`

mod_rewrite is now fully enabled. In the next step, we will set up an .htaccess file that we’ll use to define rewrite rules for redirects._

**Comment by PascalBu** [comment]
Yes, I have rewrite module enabled now, what's next...?

**Comment by Sweepr** [comment]
@PascalBu Check again if browsing to `[serverip]/api?t=c` works for you, which should work fine now.

**Comment by PascalBu** [comment]
@Sweepr still not working with same error(s)

**Comment by Sweepr** [comment]
@PascalBu 

You did restart Apache right?
Post the outcome of `apache2ctl -M` here.

**Comment by PascalBu** [comment]
Yes I did, even rebooted the VM

Output shows:

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
Loaded Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 mime_module (shared)
 mpm_prefork_module (shared)
 negotiation_module (shared)
 php7_module (shared)
 reqtimeout_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 status_module (shared)

rewrite_module is in there...

**Comment by Sweepr** [comment]
Strange, if rewrite_module is enabled, and the exact correct rules are in .htaccess then there is no reason why it should not work unless there is some other configuration error which sadly enough is hard for me to determine from here.

Maybe you could ask Proxmox for help on this.

**Comment by PascalBu** [comment]
I don't think it is related to proxmox, that is just the hypervisor.

I spun up a new Ubuntu 20.04 VM and followed the wiki again to the letter, but the problem persists... :(

**Comment by Sweepr** [comment]
@PascalBu 

Double check your httpd configuration to this (the path may differ with one another, it's placed at /etc/apache2/sites-available/default):

DocumentRoot /var/www

<Directory /var/www/>
    Options Indexes FollowSymLinks MultiViews
    AllowOverride all
    Order allow,deny
    allow from all
</Directory>

Or try first to add `Options +FollowSymLinks -MultiViews` to your `.htaccess` ?

**Comment by Sweepr** [comment]
Or check this: https://docs.bolt.cm/4.0/howto/making-sure-htaccess-works#test-if-mod-rewrite-is-working

**Comment by PascalBu** [comment]
Finally fixed! You did point me in the right direction.

It was in the </Directory> in apache2.conf

For future reference:

Apache2.conf (guess this could also go in sites-enabled/000-default.conf ?):

<Directory /var/www/>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Require all granted
</Directory>

And .htaccess:

RewriteEngine on
RewriteCond %{REQUEST_URI} !api/
RewriteRule api/?$ index.php?page=newznabapi [QSA,L]

**Comment by radarrnewb** [comment]
I had similar issues where this one helped me as well. Now working in both couchpotato and radarr.
