### ISSUE TITLE
blacklist/whitelist in settings swapped

### ISSUE THREAD

**Issue by hunter-nl** [spotweb/spotweb#648]
**Describe the bug/issue**
 - In settings are blacklist and whitelist urls swapped. Is this done on purpose? I guess this is a mistake.

https://github.com/spotweb/spotweb/blob/86b6b8492938a3e22ae9023cf40eaf7fe06c421b/lib/services/Upgrade/Services_Upgrade_Settings.php#L72
https://github.com/spotweb/spotweb/blob/86b6b8492938a3e22ae9023cf40eaf7fe06c421b/lib/services/Upgrade/Services_Upgrade_Settings.php#L74

**Comment by Sweepr** [comment]
Good spotting, that's indeed an mistake.
