### ISSUE TITLE
Azure Cognitive Translator

### ISSUE THREAD

**Issue by coolspot18** [spotweb/spotweb#659]
**Describe the bug/issue**
Does Microsoft Cognitive Services still work in SpotWeb? I entered in my Azure Subscription Key for the Translator Service but nothing is being translated? In Azure's control panel I am not seeing any requests.

**Have you searched the internet or Github for an answer?**
I see the SpotWeb's legacy Translator APIs were updated in 2017 to the v2 Azure APIs. Those APIs are now deprecated but nevertheless should still work.

Right now, I've entered in my key, but no translation requests are being sent by SpotWeb.

Does SpotWeb have any logs to help debug the issue?

**To Reproduce**
Settings --> Cognitive Services --> Enter Key --> Click Change.

**Expected behavior**
Non-English (User Language) text is translated in Spot Descriptions and Comments.

I'm running jgeusebroek/docker-spotweb.

**Comment by Sweepr** [comment]
Do know, never used it, i cannot verify because i do not own an Azure account.

**Comment by mesa57** [comment]
Resolved on develop branch.
