### ISSUE TITLE
Data too long for column 'fromhdr' at row 1

### ISSUE THREAD

**Issue by Wally73** [spotweb/spotweb#66]
during retrieve reports

    Retrieving 41941 till 43942, found 1987 reports in 0.22 seconds
    Retrieving 43942 till 45943, found 2001 reports in 0.3 seconds
    Retrieving 45943 till 46306, found 363 reports in 0.07 seconds

       SpotWeb v0.68.29.32 on PHP v5.6.7-1 crashed

    Fatal error occured retrieving reports: 
     22001: 1406: Data too long for column 'fromhdr' at row 1

    #0 /var/www/spotweb/lib/dao/Base/Dao_Base_SpotReport.php(69): dbeng_pdo-     >batchInsert(Array, 'INSERT INTO rep...', Array, Array)
    #1 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Reports.php(124): Dao_Base_SpotReport->addReportRefs(Array)
    #2 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(227): Services_Retriever_Reports->process(Array, 45943, 46306, 1431679277.447)
    #3 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(319): Services_Retriever_Base->loopTillEnd(27934, '2000')
    #4 /var/www/spotweb/retrieve.php(214): Services_Retriever_Base->perform()
    #5 {main}

PHP 5.6.7-1 (cli) (built: Mar 24 2015 12:30:15)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

mysql:  10.0.19-MariaDB-1~sid mariadb.org binary distribution

on Debian Jessie

**Comment by Sweepr** [comment]
Never seen an error like that, not even sure what this means.

What happens if you try again?

**Comment by Wally73** [comment]
exactly the same so i've turned off report retrieval for now

fromhdr is in table reportsxover

**Comment by Sweepr** [comment]
I'll monitor the retrieval of reports here and see if i see the something similar

**Comment by Sweepr** [comment]
Sofar i have not seens this error during retrieval.

Could you find out some more info?

**Comment by Wally73** [comment]
i already pasted the complete error message

i can try to run retrieve with debug

**Comment by Wally73** [comment]
```
wally@debian:/var/www/spotweb$ php retrieve.php --debug
Last retrieve at Fri 15 May 2015 11:43:02 AM CEST
Retrieving new Spots from server reader.easyusenet.nl...


SpotWeb v0.68.29.32 on PHP v5.6.7-1 crashed

Fatal error occured retrieving reports:
  22001: 1406: Data too long for column 'message' at row 1 (SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'message' at row 1)



#0 /var/www/spotweb/lib/dbeng/dbeng_pdo.php(74): dbeng_pdo->exec('INSERT INTO deb...', Array)
#1 /var/www/spotweb/lib/dao/Base/Dao_Base_DebugLog.php(25): dbeng_pdo->modify('INSERT INTO deb...', Array)
#2 /var/www/spotweb/lib/SpotDebug.php(28): Dao_Base_DebugLog->add(10, 1431683064.3145, 'searchMessageId...')
#3 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(126): SpotDebug::msg(10, 'searchMessageId...')
#4 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(308): Services_Retriever_Base->searchMessageId('7559697', 'p048uwN2oAUkb5V...', Array)
#5 /var/www/spotweb/retrieve.php(155): Services_Retriever_Base->perform()
#6 {main}
```

that is with debug on

**Comment by Sweepr** [comment]
Try php upgrade-db.php to check the table's
Otherwise, perform a repair on the entire DB, something probably messed up the table field length's

**Comment by Sweepr** [comment]
In the Database certain field length's are limited to 128 character, If the data you are trying to enter into that field length exceeds the set field/length you get: 

22001: 1406: Data too long for column 

Basiclly means that the data does not fit into the column space.

**Comment by Wally73** [comment]
i found the issue i have
somehow the db is turned into having different storage engines on tables (some are still myisam and some are innodb) 

since i don't succeed to alter the tables i will setup db a new during the weekend (but for now i keep running without report retrieval on)

**Comment by isuftin** [comment]
I am seeing this same issue...

```
Last retrieve at Tue Jun  2 04:50:19 2015
Retrieving new reports from server ssl.astraweb.com...
Appr. Message count:    125712
First message number:   148
Last message number:    125860
Current article number: 120171

Retrieving 120171 till 125172, found 5001 reports in 1.63 seconds


SpotWeb v0.68.29.32 on PHP v5.5.12-2ubuntu4.4 crashed

Fatal error occured retrieving reports:
  22001: 1406: Data too long for column 'fromhdr' at row 7



#0 /var/www/spotweb/lib/dao/Base/Dao_Base_SpotReport.php(69): dbeng_pdo->batchInsert(Array, 'INSERT INTO rep...', Array, Array)
#1 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Reports.php(124): Dao_Base_SpotReport->addReportRefs(Array)
#2 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(227): Services_Retriever_Reports->process(Array, '120171', 125172, 1433238620.1096)
#3 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(319): Services_Retriever_Base->loopTillEnd('120171', '5000')
#4 /var/www/spotweb/retrieve.php(214): Services_Retriever_Base->perform()
#5 {main}
```

Spotweb running on fresh MySQL 5.6.24

**Comment by cliv** [comment]
This fixed things for me.

ALTER TABLE `spotweb`.`reportsxover` 
CHANGE COLUMN `fromhdr` `fromhdr` VARCHAR(256) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL DEFAULT '' ;

**Comment by Wally73** [comment]
thx cliv that sql (without the dbname before tablename ) worked fine for me afaik  with mariadb 10.0.19

**Comment by LeonB** [comment]
Had the same issue. @cliv's solution worked:

``` sql
ALTER TABLE reportsxover 
CHANGE COLUMN fromhdr fromhdr VARCHAR(256) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL DEFAULT '' ;
```

**Comment by isuftin** [comment]
@LeonB :+1: I need to port this back into my [Docker container](https://github.com/isuftin/spotweb) for Spotweb now
