### ISSUE TITLE
Spotweb throws SQL error when visiting default quick links.

### ISSUE THREAD

**Issue by PiekJ** [spotweb/spotweb#665]
**Describe the bug/issue**
When clicking on the default quick links the page throws an PHP error mentioning a SQL syntax error (message posted below).

**To Reproduce**
1. Setup a new instance of Spotweb with a PostgreSQL database (for a single user).
2. Do an initial retrieve posts (not sure if needed).
3. Click on any quick link and it will throw an error (see comment below describing which quick links throw the error).

**Expected behavior**
 - The selected quick link to be working.

**Screenshots**
```
SpotWeb v0.68.32.33 on PHP v7.4.3 crashed
object(SqlErrorException)#32 (8) {
  ["message":protected]=>
  string(197) "42P01: 7: ERROR:  missing FROM-clause entry for table "l"
LINE 35: ...             WHERE (bl.spotterid IS NULL)  AND ( (l.watch IS...
                                                              ^"
  ["string":"CustomException":private]=>
  NULL
  ["code":protected]=>
  int(-1)
  ["file":protected]=>
  string(40) "/var/www/spotweb/lib/dbeng/dbeng_pdo.php"
  ["line":protected]=>
  int(70)
  ["trace":"Exception":private]=>
  array(5) {
    [0]=>
    array(5) {
      ["file"]=>
      string(40) "/var/www/spotweb/lib/dbeng/dbeng_pdo.php"
      ["line"]=>
      int(186)
      ["function"]=>
      string(4) "exec"
      ["class"]=>
      string(9) "dbeng_pdo"
      ["type"]=>
      string(2) "->"
    }
    [1]=>
    array(5) {
      ["file"]=>
      string(47) "/var/www/spotweb/lib/dao/Base/Dao_Base_Spot.php"
      ["line"]=>
      int(93)
      ["function"]=>
      string(10) "arrayQuery"
      ["class"]=>
      string(9) "dbeng_pdo"
      ["type"]=>
      string(2) "->"
    }
    [2]=>
    array(5) {
      ["file"]=>
      string(71) "/var/www/spotweb/lib/services/Providers/Services_Providers_SpotList.php"
      ["line"]=>
      int(27)
      ["function"]=>
      string(8) "getSpots"
      ["class"]=>
      string(13) "Dao_Base_Spot"
      ["type"]=>
      string(2) "->"
    }
    [3]=>
    array(5) {
      ["file"]=>
      string(44) "/var/www/spotweb/lib/page/SpotPage_index.php"
      ["line"]=>
      int(105)
      ["function"]=>
      string(13) "fetchSpotList"
      ["class"]=>
      string(27) "Services_Providers_SpotList"
      ["type"]=>
      string(2) "->"
    }
    [4]=>
    array(5) {
      ["file"]=>
      string(26) "/var/www/spotweb/index.php"
      ["line"]=>
      int(462)
      ["function"]=>
      string(6) "render"
      ["class"]=>
      string(14) "SpotPage_index"
      ["type"]=>
      string(2) "->"
    }
  }
  ["previous":"Exception":private]=>
  NULL
  ["string":"Exception":private]=>
  string(0) ""
}
42P01: 7: ERROR:  missing FROM-clause entry for table "l"
LINE 35: ...             WHERE (bl.spotterid IS NULL)  AND ( (l.watch IS...
                                                              ^
```

**Desktop (please complete the following information):**
 - OS: Unraid
 - Browser: Edge (Chromium)
 - Spotweb Version: It says 0.68.32.33, but I think it's outdated.
 - Which branch: Master
 -  PHP version: 7.4
 -  Device information: Running via Docker. See additional context.

**Additional context**
Spotweb and PostgreSQL both running in a seperate Docker container.
Docker container used: 
- Spotweb: https://hub.docker.com/r/jgeusebroek/spotweb (updates frequently by pulling master).
- PostgreSQL: https://hub.docker.com/_/postgres

Edit: changed quick filters to quick links.

**Comment by mesa57** [comment]
My guess is that this only happens when you click on 'watchlist'. Is that correct ?

**Comment by PiekJ** [comment]
This applies to the following filters:
- Recently viewed;
- Downloaded;
- Watchlist;
- New.

**Comment by mesa57** [comment]
Please test the change on the **develop** branch.

**Comment by PiekJ** [comment]
I'll test the develop branch in the weekend.

**Comment by mesa57** [comment]
Ok, thanks

**Comment by mesa57** [comment]
Closed due to no confirmation

**Comment by bvrielink** [comment]
Was this ever commited to the main branch? Using a docker image  (jgeusebroek/spotweb) which still has this problem.

**Comment by mesa57** [comment]
You need to check out the develop branch.

**Comment by bvrielink** [comment]
> You need to check out the develop branch.

I tested the above commit and it fixes the problem. So when does this fix gets promoted to the production branch?
