### ISSUE TITLE
Extra content at end-of-page

### ISSUE THREAD

**Issue by TerrorSource** [spotweb/spotweb#667]
**Describe the bug/issue**
Downloaded de Github ZIP, extracted to /web/spotweb on my Synology (DSM 7.0 beta_. run the install. Everything runes fine.
After retrieving spots i see a lot of info on the end of each page. I have already re-downloaded the ZIP, same issue.
Also the same with the latest Docker image

**Have you searched the internet or Github for an answer?**
Searched Github, no results
Search Google. no similar issues

**To Reproduce**
1. Download Spotweb-master.zip from Github
2. Extract to /web/spotweb/
3. Run installer
4. Retrieve spots

**Expected behavior**
 I didn't expect this behavior.

**Screenshots**
see bottom of this issue

**Desktop (please complete the following information):**
 - OS: DSM 7.0 beta
 - Browser: Chrome, Firefox and Safari
 - Spotweb Version: Spotweb develope branch, 27-feb-2021
 - Which branch: Develop
 -  PHP version: 7.4
 -  Device information: Synology 918+
 - MariaDB version 1:10.5.9 in Docker on same Synology

**Additional context**
Provide any other information about the bug or issue that can further help debugging here.

<img width="2048" alt="Screenshot 2021-02-28 at 15 42 42" src="https://user-images.githubusercontent.com/20524866/109422415-b7009700-79db-11eb-8b7e-aa3724fd39c4.png">

**Comment by TerrorSource** [comment]
Fixed for now

Emptied the following tables via PhpMyAdmin:
- cache
- filters
- grouppermissions
- securitygroups
- sessions
- settings
- usenetstate
- usergroups
- users
- usersettings

and recreated the /spotweb/cache/ folder with 777 permissions.

**Comment by Sweepr** [comment]
Note for future reference:
In this case it would have been sufficient to disable this option in your "admin" account.

![image](https://user-images.githubusercontent.com/2857865/109775924-5dc67c80-7c02-11eb-93c8-863683bf115f.png)
