### ISSUE TITLE
Database crashed after switching to Media branch?

### ISSUE THREAD

**Issue by Northguy** [spotweb/spotweb#67]
Yesterday evening I switched to the Media branch of Spotweb. After switching I was required to run upgrade-db.sh. This took quite some time, but ended in a crash. Now I cannot run spotweb anymore, but also the upgrade-db routine keeps crashing with the message below. Anyone got a suggestion on how to fix this? I preferably don't want to start from scratch with my database.

<<Validating messages removed>>
        Validating index idx_tmdbimages_1
Schema update done
Updating settings
Settings update done

SpotWeb crashed

Database schema or settings upgrade failed:
   23000: 1062: Duplicate entry '3-31-pushover' for key 'idx_grouppermissions_1'

#0 /volume1/web/spotweb/lib/services/Upgrade/Services_Upgrade_Users.php(468): dbeng_pdo->rawExec('INSERT INTO gro...')
#1 /volume1/web/spotweb/lib/services/Upgrade/Services_Upgrade_Users.php(19): Services_Upgrade_Users->updateSecurityGroups(false)
#2 /volume1/web/spotweb/lib/services/Upgrade/Services_Upgrade_Base.php(35): Services_Upgrade_Users->update()
#3 /volume1/web/spotweb/upgrade-db.php(50): Services_Upgrade_Base->users(Object(Services_Settings_Container))
#4 {main}DiskStation>

**Comment by Sweepr** [comment]
Probably you have been editting the database manually prior to the upgrade to media branch.

php upgrade-db --reset-groupmembership

**Comment by Northguy** [comment]
Thanks for the fast reply. I have not been editing the db manually. Unfortunately, the command you proposed does not resolve the issue. The result is the same message as above. :-(

**Comment by Sweepr** [comment]
You could try to manually remove any duplicate entry's in the table grouppermissions.
So anything that is in there twice should be removed.

**Comment by Northguy** [comment]
I was already looking into it, but am unfamiliar with the database structure and SQL. Please find below a text dump of the grouppermissions table. I see a lot of the same values in the colums GroupId and permissionid. Should I remove all of them? They have different Objectid's? 

===Databank spotweb

== Tabelstructuur voor tabel grouppermissions

|------
|Kolom|Type|Leeg|Standaardwaarde
|------
|//**id**//|int(11)|Nee|
|**groupid**|int(11)|Nee|0
|**permissionid**|int(11)|Nee|0
|**objectid**|varchar(128)|Nee|
|deny|tinyint(1)|Nee|0
== Gegevens worden geÃ«xporteerd voor tabel grouppermissions

|1|1|1| |0
|2|2|0| |0
|3|2|1| |0
|4|2|2| |0
|5|2|3| |0
|6|2|4| |0
|7|2|7| |0
|8|2|9| |0
|9|2|10| |0
|10|2|22| |0
|11|2|26| |0
|12|3|5| |0
|13|3|6| |0
|14|3|8| |0
|15|3|11| |0
|16|3|12| |0
|17|3|14| |0
|18|3|15| |0
|19|3|16| |0
|20|3|17| |0
|21|3|18| |0
|22|3|19| |0
|23|3|20| |0
|24|3|23| |0
|25|3|24| |0
|26|3|33| |0
|27|3|34| |0
|28|3|36| |0
|29|3|37| |0
|30|3|38| |0
|31|3|39| |0
|32|2|7|avatar|0
|33|3|24|rss|0
|34|3|24|newznabapi|0
|35|3|24|getnzb|0
|36|3|24|getspot|0
|37|3|24|getnzbmobile|0
|38|3|5|disable|0
|39|3|5|client-sabnzbd|0
|40|3|31| |0
|41|2|31|welcomemail|0
|42|3|31|email|0
|43|3|31|notifo|0
|44|3|31|twitter|0
|45|3|31|prowl|0
|46|3|31|nma|0
|47|3|31|boxcar|0
|48|4|31|growl|0
|49|3|32| |0
|50|3|32|watchlist_handled|0
|51|3|32|spot_posted|0
|52|3|32|nzb_handled|0
|53|3|32|report_posted|0
|54|4|5|push-sabnzbd|0
|55|4|5|save|0
|56|4|5|runcommand|0
|57|4|5|nzbget|0
|58|4|18|erasedls|0
|59|5|13| |0
|60|5|21| |0
|61|5|25| |0
|62|5|27| |0
|63|5|28| |0
|64|5|29| |0
|65|5|30| |0
|66|5|35| |0
|67|5|40| |0
|68|5|41| |0
|69|5|32|retriever_finished|0
|70|5|32|user_added|0
|71|3|32|newspots_for_filter|0
|72|3|23|we1rdo|0
|73|3|23|mobile|0
|74|5|42| |0
|75|5|43| |0
|76|5|44| |0
|77|5|45| |0
|78|3|31|pushover|0
|79|3|31|pushalot|0

**Comment by Sweepr** [comment]
|78|3|31|pushover|0
|79|3|31|pushalot|0

Delete row 79 ;-)

**Comment by Sweepr** [comment]
3-31-pushover  Delete row 78.. and perform another upgrade-db.

**Comment by Northguy** [comment]
haha..Deleting those entries fixed the problem.. sometimes you are too afraid :-)

**Comment by Sweepr** [comment]
Nice.. Better safe to ask than try and cry.
