### ISSUE TITLE
No result api request when multiple cat

### ISSUE THREAD

**Issue by Casburggraaf** [spotweb/spotweb#670]
**Describe the bug/issue**
When doing a api request the result is 0 when in the query multiple catories is used

**To Reproduce**
Do api request with cat=5020,5030,5040,5050,5060,5070
**Expected behavior**
api results

**Screenshots**
<img width="1679" alt="Screenshot 2021-03-01 at 13 44 57" src="https://user-images.githubusercontent.com/373753/109518859-f34ef880-7aaa-11eb-9a1d-3a7cd8c35aa4.png">

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Which branch  Develop
 -  PHP version 7.2
 -  Device information Ubuntu

**Comment by Sweepr** [comment]
Tried a random one here using Develop branch and it works fine.

http://spotweb/api?t=tvsearch&apikey=***removed***&season=1&maxage=3350&cat=5000%2C5030%2C5040%2C5050&q=Charmed&limit=100&offset=0&ep=5

Could you copy/paste in the URL are you using exactly, since that's some information that's missing in your report.

**Comment by Casburggraaf** [comment]
after some tries it seems there is a threshold of 3-4 cat's.
https://spotweb.test/api?t=tvsearch&cat=5000,5020,5030,5040,5050,5060,5070&extended=1&apikey=(removed)&offset=0&limit=50&rid=47980&tvmazeid=8668&season=13&ep=4

**Comment by mesa57** [comment]
Strange even if I use cats 5000,5020,5030,5060,5070 it doesn't give an result.
If you leave out cat 5060 and 5070 it works ok (as a workaround).

**Comment by Casburggraaf** [comment]
That's strange, the request is valid and I get a valid response, only with no results..
yes did that already as a workaround. Just post it for other users, took me some time to find this was the problem because there was no error

**Comment by Sweepr** [comment]
So this only seems to happen whenever these categories are involved, other categories are not affected.
       
```
 'Sport'	            => '5060',
 'Anime'	            => '5070',
```

**Comment by Casburggraaf** [comment]
yes, that seems to be the problem. I don't know the specs of the newznab but even if you search for example the non existing "5084" I would get back a result for 5020?

**Comment by mesa57** [comment]
Yes, @Sweepr , if you leave out selection for specific genre's it works. This is because the genre is always added to the query with an AND relation (instead of the different formats which are added using OR).
I cannot change this, because it work break defined filters.
@Casburggraaf : if you specify 5084 it should be ignored.

**Comment by Sweepr** [comment]
@mesa57, So this is a designed, or are we missing a bug?

I did spot a few things, this however does not have anything to do with this issue b.t.w. but needs fixing i.m.h.o.

Seems to be a typo here:  https://github.com/spotweb/spotweb/blob/16ef0c059d744e1e87c12b2f62f9ebb4d83a8333/lib/page/SpotPage_newznabapi.php#L1018

`8  => '6000|65040',`

And this can be simplified:

https://github.com/spotweb/spotweb/blob/16ef0c059d744e1e87c12b2f62f9ebb4d83a8333/lib/page/SpotPage_newznabapi.php#L957-L963

```
            case 5000: return 'cat0_z1';
            case 5020: return 'cat0_z1_a0,cat0_z1_a1,cat0_z1_a2,cat0_z1_a3,cat0_z1_a4,cat0_z1_a6,cat0_z1_a7,cat0_z1_a8,cat0_z1_a9,cat0_z1_a10';
            case 5030: return 'cat0_z1_a0,cat0_z1_a1,cat0_z1_a2,cat0_z1_a3,cat0_z1_a10';
            case 5040: return 'cat0_z1_a4,cat0_z1_a6,cat0_z1_a7,cat0_z1_a8,cat0_z1_a9';
            case 5050: return 'cat0_z1_a0,cat0_z1_a1,cat0_z1_a2,cat0_z1_a3,cat0_z1_a4,cat0_z1_a6,cat0_z1_a7,cat0_z1_a8,cat0_z1_a9,cat0_z1_a10';
            case 5060: return 'cat0_z1_d18';
            case 5070: return 'cat0_z1_d29';
```

Into:

```
            case 5000: return 'cat0_z1';
            case 5050:
            case 5020: return 'cat0_z1_a0,cat0_z1_a1,cat0_z1_a2,cat0_z1_a3,cat0_z1_a4,cat0_z1_a6,cat0_z1_a7,cat0_z1_a8,cat0_z1_a9,cat0_z1_a10';
            case 5030: return 'cat0_z1_a0,cat0_z1_a1,cat0_z1_a2,cat0_z1_a3,cat0_z1_a10';
            case 5040: return 'cat0_z1_a4,cat0_z1_a6,cat0_z1_a7,cat0_z1_a8,cat0_z1_a9';
            case 5060: return 'cat0_z1_d18';
            case 5070: return 'cat0_z1_d29';
```

**Comment by mesa57** [comment]
@Sweepr The duplicates I want to leave in (because of future changes).
I will correct the error you found.
@Casburggraaf Apologees, I found a solution for this problem by adding genre selection (all) to all other newsnab category's
I will implement this soon on the develop branch.

**Comment by Sweepr** [comment]
@mesa57 

There won't be any removal of duplicates, just a simplified 'case' for 5050 and 5020, since they are both identical.

**Comment by mesa57** [comment]
5020 stands for TV/Foreign 
Do you know how to identify those in Spotweb ?

**Comment by mesa57** [comment]
Should be resolved by latest commit on develop branch
