### ISSUE TITLE
Running upgrade-db.php with php 7.3 give errors

### ISSUE THREAD

**Issue by mikeo999** [spotweb/spotweb#672]
Just did a git pull and after that running upgrade-db.php and getting soms errors when running it with php73

`PHP Warning:  PHP Startup: Unable to load dynamic library 'mcrypt.so' (tried: /usr/local/lib/php73/modules/mcrypt.so (/usr/local/lib/php73/modules/mcrypt.so: cannot open shared object file: No such file or directory), /usr/local/lib/php73/modules/mcrypt.so.so (/usr/local/lib/php73/modules/mcrypt.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'mysql.so' (tried: /usr/local/lib/php73/modules/mysql.so (/usr/local/lib/php73/modules/mysql.so: cannot open shared object file: No such file or directory), /usr/local/lib/php73/modules/mysql.so.so (/usr/local/lib/php73/modules/mysql.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
Updating schema..(pdo_mysql)
`

Running the same with php72 is working fine and was always working without problems.

Running it with Synology DSM.

**Comment by mesa57** [comment]
This has nothing to do with spotweb. You have serveral php modules missing in you're installation.
Please ask you're question on the synology forum.
