### ISSUE TITLE
Stored XSS and Blind Stored XSS found in the Spotweb.

### ISSUE THREAD

**Issue by s-kustm** [spotweb/spotweb#675]
**Describe the bug/issue**
1. Stored XSS (Open the link to read more) - https://portswigger.net/web-security/cross-site-scripting
2. Blend XSS (Open the link to read more) - https://www.acunetix.com/blog/articles/blind-xss/

**Have you searched the internet or Github for an answer?**
Yes, this issue is not found.

**To Reproduce**
Please visit the link for more details:

**Expected behavior**
 The application should sensitize the user input to prevent execution of Script.

**Screenshots**
Please check the attached files.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser -  Ghrome 89.0.4389.114 &  Firefox 87.0
 - Spotweb Version - 1.4.9 Commit 9e53a03
 - Which branch N/A
 -  PHP Version 7.3.27
 -  Device information  N/A

Thanks

**Comment by Sweepr** [comment]
Thank you for reporting, we will have a look at this as quick as possible.

**Comment by Sweepr** [comment]
See:

https://github.com/spotweb/spotweb/commit/8c0e321d6af74fe3fb9333b90e8e17b5dc5460b9

https://github.com/spotweb/spotweb/commit/0dac3020e8c01cebe236744d563b827fdc17c2fa

https://github.com/spotweb/spotweb/commit/59d9704b5924b6b0b1690bd40f3c99febb8b450a

**Comment by mesa57** [comment]
Top 👍
