### ISSUE TITLE
Parse error when sending to SabNZB

### ISSUE THREAD

**Issue by tudstudent** [spotweb/spotweb#676]
**Describe the bug/issue**
 - When in overview of all spots, just click, send to sabnzbd the following error pops up:
```
<br />
<b>Parse error</b>:  syntax error, unexpected '&lt;&lt;' (T_SL), expecting function (T_FUNCTION) or const (T_CONST) in <b>/media/sf_Intranet/html/spotweb/lib/services/Actions/Services_Actions_DownloadNzb.php</b> on line <b>8</b><br />
```

**Have you searched the internet or Github for an answer?**
 - No similar anomaly found

**Expected behavior**
 - Just send the nzb to sab

**Additional context**
Running latest git pull & on master
Also dbupgrade & checkcache = OK

**Comment by tudstudent** [comment]
In general it is an old install periodically updated with git pull (and db update and cache check).
It was not sending nzb to sab already some time.

Yesterday it git clone the repository again and copied the files over my original install. However same result.
Looking how I can transfer my cache to a new clean download...

**Comment by Sweepr** [comment]
Last update to master has been done on Nov 12, 2020, i have checked master and for me i can send NZB's normally to sabnzbd

**Comment by tudstudent** [comment]
is there an option to transfer my current cache (or is it not usefull)?
The dbd I can connect to the new clone, no problem.

**Comment by Sweepr** [comment]
Cache is mainly used for larger installation with more users so you do not stress the ISP with the same requests.

**Comment by tudstudent** [comment]
One user
I was only afraid I would lose many years of info

**Comment by Sweepr** [comment]
No, the info is on the USP.

**Comment by mesa57** [comment]
What do you mean by cache ? Spotweb keeps a cache on disk (which you should clear) and all the spots and reactions are stored in the database. The latter is not a 'cache'.

**Comment by Sweepr** [comment]
Closing this, re-open if needed.
