### ISSUE TITLE
Spotweb in one php file

### ISSUE THREAD

**Issue by twepl** [spotweb/spotweb#677]
hello, I want to integrate Spotweb into a web shell, but I need all Spotweb to be in one php file
You can make a mini version of the whole Spotweb in one file.

**Comment by Sweepr** [comment]
Ain't going to happen, too much work.

But feel free to fork the project and try..

**Comment by twepl** [comment]
@Sweepr I would do it for you but you have a lot of deprivation starting with templates.
Can you at least create a stripped-down version without unnecessary components?
