### ISSUE TITLE
black/whitelist no longer available?

### ISSUE THREAD

**Issue by rcrommentuijn** [spotweb/spotweb#68]
Non-fatal: Updating black/whitelist failed, most likely unreachable!Expiring debuglog entries, if any, done.

http://jij.haatmij.nl/spotnet/blacklist.txt
http://jij.haatmij.nl/spotnet/whitelist.txt
these sites automatically redirect to duckduckgo.com

Are there new url for the white/blacklist or should i just ignore this issue?

**Comment by Sweepr** [comment]
Yes, these are unreachable, offline.. no idea since when.

You could ignore this, by disabeling "Fetch the external blacklist during retrieve" and "Fetch the external whitelist during retrieve"  under settings -> performance. you will no longer see this message.

Or setup your own blacklist/whitelist.txt by editting the settings table, lines 38 and 40

![untitled](https://cloud.githubusercontent.com/assets/2857865/7671897/4e94c11e-fce1-11e4-8da1-6d812f16ff30.png)

**Comment by Wally73** [comment]
i have an reasonable up to date one 
will share the url's tomorrow CET 

On 17 May 2015 22:09:39 GMT+02:00, Sweepr <notifications@github.com> wrote:
>Yes, these are unreachable, offline.. no idea since when.
>
>You could ignore this, by disabeling "Fetch the external blacklist
>during retrieve" and "Fetch the external whitelist during retrieve" 
>under settings -> performance. you will no longer see this message.
>
>Or setup your own blacklist/whitelist.txt by editting the settings
>table, lines 38 and 40
>
>![untitled](https://cloud.githubusercontent.com/assets/2857865/7671897/4e94c11e-fce1-11e4-8da1-6d812f16ff30.png)
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/spotweb/spotweb/issues/68#issuecomment-102845307

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Wally73** [comment]
blacklist url:

http://jijhaatmij.hopto.me/blacklist.txt

whitelist url:

http://jijhaatmij.hopto.me/whitelist.txt

**Comment by rcrommentuijn** [comment]
thanks sharing these, the non-fatal error is gone now

**Comment by LeonB** [comment]
I updated the black- and whitelist:

``` sql
update settings set value = 'http://jijhaatmij.hopto.me/blacklist.txt' where name = 'blacklist_url';
update settings set value = 'http://jijhaatmij.hopto.me/whitelist.txt' where name = 'whitelist_url';
```

Error is gone now!
