### ISSUE TITLE
PHP803 Function openssl_free_key() is deprecated

### ISSUE THREAD

**Issue by Mickroz** [spotweb/spotweb#680]
PHP Deprecated:  Function openssl_free_key() is deprecated in /lib/services/Signing/Services_Signing__Openssl.hp on line 45

**Comment by Sweepr** [comment]
See: https://github.com/spotweb/spotweb/commit/81200b91333f543ca09543533f8613bbfa8ea94a

**Comment by Mickroz** [comment]
Thanks, searching on mobile sucks

**Comment by Sweepr** [comment]
@Mickroz, no problem.
