### ISSUE TITLE
Splendid Template

### ISSUE THREAD

**Issue by gerarddvb** [spotweb/spotweb#681]
Hello,

I would really like to install the splendid theme.

**Describe the bug/issue**
If I install the splendid template and enable it in settings, I am not able to log in SpotWeb anymore.
I get this error when I log in to SpotWeb;

Fatal error: Uncaught Error: Class 'SpotTemplateHelper_Splendid' not found in /volume1/web/spotweb-develop/lib/page/SpotPage_Abs.php:104 Stack trace: #0 /volume1/web/spotweb-develop/lib/page/SpotPage_Abs.php(43): SpotPage_Abs->getTplHelper(Array) #1 /volume1/web/spotweb-develop/lib/page/SpotPage_index.php(11): SpotPage_Abs->__construct(Object(Dao_Mysql_Factory), Object(Services_Settings_Container), Array) #2 /volume1/web/spotweb-develop/index.php(458): SpotPage_index->__construct(Object(Dao_Mysql_Factory), Object(Services_Settings_Container), Array, Array) #3 {main} thrown in /volume1/web/spotweb-develop/lib/page/SpotPage_Abs.php on line 104

**To Reproduce**
1. Download https://github.com/supershadow/Splendid-Template
2. Copy to ./templates
3. Enable theme in user settings
4. Enable theme in settings
5. See error

**Desktop (please complete the following information):**
 - OS: Synology DSM 6.2.3
 - Safari
 - Spotweb 1.4.9
 - Develop branch
 -  PHP 7.3
 -  Synology

**Comment by Sweepr** [comment]
That theme is almost 10 years old, and not really supported.

you could try `composer dump-autload` to import the class, but i highly doubt it will work 100% because alot has been changed and nobody ever bothered to update the theme's.

We also do not want to waste time on it and stick with the We1rdo and Mobile theme because updating those consume alot of time already.

**Comment by gerarddvb** [comment]
Thanks for reply. 
Will try the composer dump-autoload when I have ssh access to the nas.

My problem is that my dad keeps using Spotnet because he likes the UI.
This splendid template looks somewhat like that.

Do you think it will work on an older version on this repo?
Just tried 1.0.0 but couldn't run the install.php (haven't checked why)

**Comment by Sweepr** [comment]
No idea, i have never tried..  here is another version, but not sure if it is more recent then the one on github.

https://sourceforge.net/projects/spotwebsplendid/files/SpotWeb%20Splendid%20Template%200.4a/

**Comment by gerarddvb** [comment]
Tried that too. and didn't work same error. 
But I meant an older version of SpotWeb on this repo.
Do you think that could work with the template?

**Comment by Sweepr** [comment]
The original repo has been deleted, and this repo was created around 2016.

https://github.com/spotweb/spotweb/releases/tag/1.0.0 

I don't think that version will work either, maybe it does, but most core elements won't work.

**Comment by gerarddvb** [comment]
OK clear, no chance that will work.
Do you know any templates that do work besides we1rdo and mobile nowadays?
May help me with figuring out how to make it work.

**Comment by Sweepr** [comment]
No, also all the other ones aren't working anymore, there is also https://github.com/Goeny/BootSpot, but the creator didn't have time to update it too.

**Comment by gerarddvb** [comment]
Thanks for info, guess I have to figure out php and css to make it work.
Nice project, doubt my mental capabilities :)
