### ISSUE TITLE
[New issue] spotweb does not support the following categories

### ISSUE THREAD

**Issue by Hydranet** [spotweb/spotweb#683]
![2021-06-12_18_50_16](https://user-images.githubusercontent.com/22844936/121783476-19f2f400-cbaf-11eb-8660-6d5738abd4ec.jpg)
**Describe the bug/issue**
 - Radarr log files shows that certain categories are not available in spotweb, eventually  Rardarr gives an error in the interface that spotweb is unavailable. 

`2021-06-12 17:51:28.1|Warn|Newznab|spotweb does not support the following categories: 2010, 2020, 2035, 2045. You should probably remove them.`

**Have you searched the internet or Github for an answer?**
 - Please search google if similar issue has been reported and fixed before.
 In 2017 there seems to have been a similar [issue](https://github.com/spotweb/spotweb/issues/278) which was fixed.

**To Reproduce**
1. Follow your radar.txt log file.
2. Click on settings and select Indexers.
3. Open spotweb indexer and click  on "Test"
4. The error message appears, see error.

**Expected behavior**
- I expect the categories to be found by Radarr in spotweb so that the Radarr message of the spotweb indexer failing doesn't show up because of a failed check because of missing categories.

**Desktop (please complete the following information):**
 - OS: RHEL Clone
 - Browser: It happens with all browser, it's not a  browser problem.
 - Spotweb Version:  commit 482f9048fb71060d04e6927355efba2d523c093c (HEAD -> develop, origin/develop, origin/HEAD)
 - Which branch  (Develop)
 -  PHP version: 73
 -  Mariadb version: 10

**Additional context**
When I check the following file, /lib/page/SpotPage_newznabapi.php, that contains the categories in the section of the case statement where all the categories are mentioned I only see the 2010 category. The 2020, 2035 and 2045 are not defined.
When I check my apache logs I see the following request coming in from Radarr.
`GET /api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060
`
I find it strange that Radarr is complaining about category 2020 being missing even though it's defined in the case statement or is that because there is no return of a category after the 2010 is defined?
```
case 2000: return 'cat0_z0';
case 2010:
case 2030: return 'cat0_z0_a0,cat0_z0_a1,cat0_z0_a2,cat0_z0_a3,cat0_z0_a10';  // Movies/SD
case 2040: return 'cat0_z0_a4,cat0_z0_a7,cat0_z0_a8,cat0_z0_a9';              // Movies/HD
case 2050: return 'cat0_z0_a6';                                               // Movies/BluRay
case 2060: return 'cat0_z0_a14';                         
```

**Comment by mesa57** [comment]
I don't know what radar does, but the empty case 2010: is like an OR with the next 2020.
So 2010 en 2020 should return the same filter.

**Comment by Hydranet** [comment]
So I should create a issue for Radarr instead?

**Comment by mesa57** [comment]
Maybe the exact radar error message + spotweb request which radar executes can shed some light on this issue.

**Comment by Hydranet** [comment]
This is what Radarr is showing while debugging is turned on.
```
2021-06-12 21:57:37.7|Debug|Newznab|Downloading Feed https://spotweb.feedmebits.nl/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=50
2021-06-12 21:57:38.0|Warn|Newznab|spotweb does not support the following categories: 2010, 2020, 2035, 2045. You should probably remove them.
2021-06-12 21:57:38.0|Debug|Api|[POST] /api/v3/indexer/test: 200.OK (250 ms)
```

This is the request spotweb receives from Radarr
`1.2.3.4  - - [12/Jun/2021:21:57:37 +0200] "GET /api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=50 HTTP/1.1" 200 49240 "-" "Radarr/3.2.2.5080 (rhel 8.4)"`

This is the trace log file from Radarr.
[radarr.trace.txt](https://github.com/spotweb/spotweb/files/6642832/radarr.trace.txt)

**Comment by mesa57** [comment]
The trace log gives good results, and i see only a warning level message about category's.
You can try to issue the request directly to spotweb and see what it returns in you're browser.

**Comment by Hydranet** [comment]
In the browser it works, I thought the warning about a category not being available in spotweb caused the issue seems not. Looks like it is a Radarr issue then, I'll close this issue and create a new issue on the Radarr github project page. Thanks for your time @mesa57!
