### ISSUE TITLE
[New issue] Custom news provider fail on install

### ISSUE THREAD

**Issue by BakasuraRCE** [spotweb/spotweb#685]
**Describe the bug/issue**
 - When start a fresh install and select a custom usenet provider, can't fill all fields and return error

**To Reproduce**
1. Start a fresh install
2. Select custom provider on step 3 and fill the server
3. Click to validate server
4. Return error "A server portnumber has to be entered"

**Expected behavior**
 - Show fields for SSL, server, port, buggy, and if it will be used to header, nzb and post

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser chrome
 - Which branch Master
 -  PHP version 7.4
 -  Device information Docker

**Comment by mesa57** [comment]
You can just hit 'skip validation' and change the newsserver configuration in the settings.
I am thinking that even we should leave out the whole step on the install dialog.

**Comment by Sweepr** [comment]
Did you try skipping validation, then fill in the usenet server in settings ?

**Comment by BakasuraRCE** [comment]
haha, I add my provider to XML file and done hehe

**Comment by Sweepr** [comment]
Perfect, closing then.
