### ISSUE TITLE
Cannot handle database connections without port number

### ISSUE THREAD

**Issue by watnuweer** [spotweb/spotweb#686]
With my hosting provider the environment is set up so that php can connect only to the MySql database without a port number.
Not setting the port number would add 3306 and I will get the following error:
SQLSTATE[HY000] [2005] Unknown MySQL server host 'localhost:3306' (-2)

When I set the port number to blank in Spotweb dbsettings it still adds a : to the host name so the error remains.

A simple fix would be to change the file lib/dbeng/dbsettings.inc.php on line 25.
My suggestion would be something like the following.
                $db_conn = 'host='.$host.($port==""?"":':'.$port);

In my case this worked like a charm but it would be nice to see it in future versions

**Comment by mesa57** [comment]
Localhost does not work on Linux. Try 127.0.0.1 or the real IP address

**Comment by watnuweer** [comment]
> Localhost does not work on Linux. Try 127.0.0.1 or the real IP address

not sure how this comment makes sense.
I said localhost works fine. the issue only occurs when a port is added. Spotweb always adds a port and in my case it should not.
my suggested change would solve that without breaking it for others.

**Comment by mesa57** [comment]
You don't need to add a port, 3306 is the default. Did you use the install dialog ?

**Comment by watnuweer** [comment]
> You don't need to add a port, 3306 is the default. Did you use the install dialog ?

I know it is the default. The issue is that Spotweb automatically adds :3306 to the hostname if no port is specified.
If an empty port is specified still a colon is added to the hostname.
My hosting provider does not allow that. It must be only the hostname.

Mmy installation was migrated to a new provider so the install was done with the previous provider where they did allow the port number after localhost.

**Comment by mesa57** [comment]
@Sweepr I don't run linux. What's up with such a provider that he doesn't allow for an MySQL connection port ?

**Comment by Sweepr** [comment]
"localhost" means local socket connection while 127.0.0.1 is TCP/IP.  Whenever you specify "localhost" or "localhost:port" as server, the MySQL client library will override this and try to connect to a local socket.

**Comment by Sweepr** [comment]
I find it weird, 127.0.0.1:3306 is the way to go in this case, get is running.

Make sure you can connect to your DB from terminal on 127.0.0.1:3306 and you should be fine, if not contact your hosting provider and let them sort it out.

**Comment by Sweepr** [comment]
Maybe interesting : https://singlebrook.com/2013/01/07/avoid-localhost-when-connecting-to-databases/

**Comment by watnuweer** [comment]
For me the socket option did the trick.
$dbsettings['host'] = '/var/lib/mysql/mysql.sock';

Entering 127.0.0.1 without a port works also fine for my provider.
I don't see what would be against not specifying a port if you don't need it.
From the many issues I saw like mine I think mine is not the only provider with this setup.
But I guess it is up to you to make sense of it or not.

As far as I am concerned you can close the issue.

**Comment by Sweepr** [comment]
Nice, thank you for the update.

P.S. if you do not need to connect remotely, you could go to the next level and disable networking, this also increases security and has a big speed advantages over TCP/IP.

https://www.a2hosting.com/kb/developer-corner/mysql/restricting-mysql-port-access
