### ISSUE TITLE
Random duplicate key value for 'idx_spotsfull_1' errors when using the Spotweb web interface

### ISSUE THREAD

**Issue by bvrielink** [spotweb/spotweb#687]
**Describe the bug/issue**
 - Got the same issue as described in: https://github.com/spotweb/spotweb/issues/566.

**Have you searched the internet or Github for an answer?**
 - Yes. Found the same issue here: https://github.com/spotweb/spotweb/issues/566.

**To Reproduce**
See: https://github.com/spotweb/spotweb/issues/566

**Expected behavior**
 - No errors when using web interface Spotweb.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/8544667/124006183-3af27c00-d9da-11eb-8254-bd5f3db74f75.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge

**Server:**
 - Which branch:  Tried Master & Develop
 -  Database: Postgres 13
 -  PHP version: 7.4.3 
 -  Device information: Asustor NAS with Docker

Using the jgeusebroek/spotweb Docker image (which uses the master branch) but also tried the Develop branch. Both branches give this error. Tried "upgrade-db.php --clear-cache" and "upgrade-db.php --reset-db" but the error is not solved with these statements.

Was the fix from #566 only for MariaDB or also for Postgres? I am using Postgres instead of MariaDB which was used in #566.

If you need more information let me know.

**Comment by mesa57** [comment]
No, this was not done for PostGres.
If you want you can create a change and file a pull request for it.

**Comment by bvrielink** [comment]
> No, this was not done for PostGres.
> If you want you can create a change and file a pull request for it.

Can you or @Sweepr point me to the exact changes which were made to fix this for MariaDB?

**Comment by Sweepr** [comment]
@bvrielink, 

I believe this is the change, and was done around 16 aug 2020.

https://github.com/spotweb/spotweb/commit/31ba213346e5e2126acbc60827a33d069affa84f

**Comment by Sweepr** [comment]
This file should be edited https://github.com/spotweb/spotweb/blob/develop/lib/dao/Postgresql/Dao_Postgresql_Spot.php for postgres, line 23..

Instead of using INSERT with the IGNORE keyword for MySQL try using ON CONFLICT DO NOTHING keywords.

**Comment by bvrielink** [comment]
> This file should be edited https://github.com/spotweb/spotweb/blob/develop/lib/dao/Postgresql/Dao_Postgresql_Spot.php for postgres, line 23..
> 
> Instead of using INSERT with the IGNORE keyword for MySQL try using ON CONFLICT DO NOTHING keywords.

Thanks. Will take a look if I can fix it later on this week.

**Comment by mesa57** [comment]
ON CONFLICT is only availabe from Postgres 9.5 and on.

**Comment by bvrielink** [comment]
> ON CONFLICT is only availabe from Postgres 9.5 and on.

That shouldn't be a problem as even version 9.5 is already EOL. Tried a couple of things in the mean time like:

ON CONFLICT ON CONSTRAINT xxx DO NOTHING
ON CONFLICT xxx DO NOTHING

But it doesn't seem to help. Will try some other things.

**Comment by bvrielink** [comment]
Also tried only "ON CONFLICT DO NOTHING" but even that doesn't solve it. If I disable "Show subcats on mouseover in spots list" in Spotweb I can't reproduce the problem. If it's enabled it only happens if you click before the picture is shown. So probably before it gets it's data from the news server. It looks like it does 2 insert statements at the same time and because of that the "ON CONFLICT DO NOTHING" does not work (separate transactions without commits etc). 

I am currently out of ideas. If you guys have any ideas to try or maybe other files I can look into let me know.

**Comment by mesa57** [comment]
Solution is first to do a select (key only) and the do the insert or an update depending on the result.

**Comment by Sweepr** [comment]
INSERT INTO table_name(column_list) 
VALUES(value_list)
ON CONFLICT target action;

In this statement, the target can be one of the following:

     (column_name) – a column name.
     ON CONSTRAINT constraint_name – where the constraint name could be the name of the UNIQUE constraint.
     WHERE predicate – a WHERE clause with a predicate.

The action can be one of the following:

     DO NOTHING – means do nothing if the row already exists in the table.
     DO UPDATE SET column_1 = value_1, .. WHERE condition – update some fields in the table.

```
            'INSERT INTO spotsfull(messageid, verified, usersignature, userkey, xmlsignature, fullxml)
								  	VALUES',
            [PDO::PARAM_STR, PDO::PARAM_INT, PDO::PARAM_STR, PDO::PARAM_STR, PDO::PARAM_STR, PDO::PARAM_STR],
            ['messageid', 'verified', 'user-signature', 'user-key', 'xml-signature', 'fullxml'
```

Becomes:

```
            'INSERT INTO spotsfull(messageid, verified, usersignature, userkey, xmlsignature, fullxml)
								  	VALUES',
            [PDO::PARAM_STR, PDO::PARAM_INT, PDO::PARAM_STR, PDO::PARAM_STR, PDO::PARAM_STR, PDO::PARAM_STR],
            ['messageid', 'verified', 'user-signature', 'user-key', 'xml-signature', 'fullxml ON CONFLICT messageid DO NOTHING'
```

Above is not tested, let me know if it works.

**Comment by bvrielink** [comment]
> ON CONFLICT messageid DO NOTHING

I tried that already. It's not working. Also tried ON CONFLICT DO UPDATE etc. 

The real problem is that there are 2 exact same inserts (in seperate sessions) when you hoover above a spot and then click on it. What we're trying is to workaround this but maybe we should focus on the fact that only 1 insert should be running. 

Will try to lock the table before an insert but probably this causes other errors.

**Comment by Sweepr** [comment]
Are yoy running with retrieve fullspots on?, probably not, that why you see 2 inserts.

When you hover on the spot, the code will fetch the info from the USP if it does not yet exist in the DB and inserts it fullspots does batch insert,

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by bvrielink** [comment]
That's correct. Tried to lock it but as expected this will give another error: There is already an active transaction.

**Comment by bvrielink** [comment]
Installed it on a MariaDB database and can confirm the problem does not occur there. As I am out of ideas I am going to stay with MariaDB until someone is able to fix it.

**Comment by Sweepr** [comment]
@bvrielink

As you see i have made somet changes in my own branch in hopes of resolving this issue,
Would you be so lkind to check out my branch and use it for a while to see if it runs smoothly for PostGres?, i will do the same for so time with MySQL before merging into Spotweb/Develop.

**Comment by bvrielink** [comment]
@Sweepr Did a clean install and so far I couldn't reproduce the problem on a Postgres database. So that's good. Found another problem during a retrieve though (at the end):

Retrieving 1 till 5002, found 5001 reports in 0.2 seconds
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function dbeng_pdo::batchInsert(), 4 passed in /var/www/spotweb/lib/dao/Base/Dao_Base_SpotReport.php on line 90 and exactly 5 expected in /var/www/spotweb/lib/dbeng/dbeng_pdo.php:219
Stack trace:
#0 /var/www/spotweb/lib/dao/Base/Dao_Base_SpotReport.php(90): dbeng_pdo->batchInsert()
#1 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Reports.php(136): Dao_Base_SpotReport->addReportRefs()
#2 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(238): Services_Retriever_Reports->process()
#3 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(339): Services_Retriever_Base->loopTillEnd()
#4 /var/www/spotweb/retrieve.php(198): Services_Retriever_Base->perform()
#5 {main}
  thrown in /var/www/spotweb/lib/dbeng/dbeng_pdo.php on line 219

This doesn't happen on a MariaDB install using the current branch (news server is the same etc).

**Comment by Sweepr** [comment]
@bvrielink, True, in my rush i forgot to commit some things, they are committed now.

**Comment by bvrielink** [comment]
@Sweepr Nice. Works ok now.

**Comment by mesa57** [comment]
@Sweepr : if you move this to develop I will see what's needs to be done for SQLite in the coming week (although I have lack of time).

**Comment by muis** [comment]
@Sweepr Thanks for the fix! 

When adding parameters to existing functions, it's easier to make them optional (, $sql2 = '') so that you don't need to modify all other calls to that function. 

Just a suggestion, because it's not the first time this caused problems.

**Comment by Sweepr** [comment]
Closing this as resolved.
