### ISSUE TITLE
Error "301" when using imdbid in API call

### ISSUE THREAD

**Issue by berndh1979** [spotweb/spotweb#689]
When running Radarr and search for movies, it will pass the imdbid to Spotweb. Spotweb will try to get the imdb information from it's cache or get it via https://www.imdb.com/title/tt[imdbid]. However the call from Spotweb to imdb gets a "301" as return code.

http://10.0.0.10/api?t=movie&cat=2000,2030,2040,2050&extended=1&apikey=(removed)&offset=0&limit=50&**imdbid=5078204**

This is what I get when I run the url manually:

`<error code="301" description="IMDB information returned is invalid"/>`

If I remove the imdbid from the api, I get nice results from the last spots in Spotweb. If I search manually from the search bar in Spotweb it works as well.

I've searched the internet and found some other reports, all checking the .htacess file, but that one is default on my config:

```
<IfModule mod_rewrite.c>
        RewriteEngine on
        RewriteCond %{REQUEST_URI} !api/
        RewriteRule api/?$ index.php?page=newznabapi [QSA,L]
</IfModule>
```

I've ran db checks and removed the cache, none of them give any results. 

I've also seen that the Information provider module, tries to connect to http://www.imdb.com/..... and gets a redirect to http**s**://www.imdb.com/....  

Any help with this is highly appreciated.

Thanks,
Bernd

**Desktop (please complete the following information):**
 - OS: Linux Debian
 - Browser Edge and Firefox give the same result
 - Spotweb Version : latest development branch cloned via git
 - Which branch  Develop
 -  PHP version php 7.4.15
 -  Device information (ReadyNAS/Synology/FreeNAS) => Just a normal linux server

**Comment by mesa57** [comment]
Apparently IMDB totally changed it's webpage. As no API is available for IMDB info is determined by scraping which doesn't work anymore. Please try tp switch to tvmaze for indexing.

**Comment by berndh1979** [comment]
> 
> 
> Apparently IMDB totally changed it's webpage. As no API is available for IMDB info is determined by scraping which doesn't work anymore. Please try tp switch to tvmaze for indexing.

@mesa57 Indeed, it seems that the change from imdb broke the functionality of Spotweb. However tvmaze can't index the news headers like spotweb can, hence can't integrate that into Radarr. It seems that Sonarr still works, but for how long...

**Comment by mesa57** [comment]
Should be resolved in the develop branch now.
Can you please verify ?

**Comment by berndh1979** [comment]
Wow, amazingly fast to help me. Really apprecicate it. I ran the test and got the following error in Radarr:

`2021-07-20 20:35:13.6|Error|Newznab|An error occurred while processing indexer feed. http://10.0.0.10/api?t=movie&cat=2000,2030,2040,2050&extended=1&apikey=(removed)&offset=0&limit=50&imdbid=1911658

[v3.2.2.5080] System.Xml.XmlException: There are multiple root elements. Line 2, position 2.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NzbDrone.Core.Indexers.RssParser.LoadXmlDocument(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\RssParser.cs:line 114
   at NzbDrone.Core.Indexers.Newznab.NewznabRssParser.PreProcess(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Newznab\NewznabRssParser.cs:line 62
   at NzbDrone.Core.Indexers.RssParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\RssParser.cs:line 55
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 291
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 123
RequestUri: http://10.0.0.10/api?t=movie&cat=2000,2030,2040,2050&extended=1&apikey=(removed)&offset=0&limit=50&imdbid=1911658;StatusCode: OK;ContentType: text/html; charset=utf-8;ContentLength: 1092;ContentSample: <br />
<b>Fatal error</b>:  Uncaught Error: Interface '**Psr\SimpleCache\CacheInterface' not found in /var/www/spotweb/vendor/imdbphp/imdbphp/src/Imdb/Cache.php:14**
Stack trace:
#0 /var/www/spotweb/vendor/composer/ClassLoader.php(444): include()
#1 /var/www/spotweb/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#2 [internal function]: Composer\Autoload\ClassLoader-&gt;loadClass()
#3 /var/www/spotweb/vendor/imdbphp/imdbphp/src/Imdb/MdbBase.php(120): spl_autoload_call()
#4 /var/www/spotweb/vendor/imdbphp/imdbphp/src/Imdb/Title.php(182): Imdb\MdbBase-&gt;__construct()
#5 /var/www/spotweb/lib/services/MediaInformation/Services_MediaInformation_Imdb.php(20): Imdb\Title-&gt;__construct()
#6 /var/www/spotweb/lib/page/SpotPage_newznabapi.php(236): Services_MediaInformation_Imdb-&gt;retrieveInfo()
#7 /var/www/spotweb/lib/page/SpotPage_newznabapi.php(59): SpotPage_newznabapi-&gt;search()
#8 /var/www/spotweb/index.php(210): SpotPage_newznabapi-&gt;render()
#9 {main}
  thrown in <b>/var/www/spotweb/vendor/imdbphp/imdbphp/src/Imdb/Cache.php</b> on line <b>14</b><br />
;FeedUrl: http://10.0.0.10/api?t=movie&cat=2000,2030,2040,2050&extended=1&apikey=(removed)&offset=0&limit=50&imdbid=1911658`

Seems someting wrong with the cache. Any suggestions?

Thanks in advance.

**Comment by mesa57** [comment]
Could you clear the cache by executing :
`bin/upgrade-db --clear-cache`
?

**Comment by berndh1979** [comment]
> 
> 
> Could you clear the cache by executing :
> `bin/upgrade-db --clear-cache`
> ?

Indeed, I tried that too. here the results from Radarr:

```
[v3.2.2.5080] System.Xml.XmlException: There are multiple root elements. Line 2, position 2.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at NzbDrone.Core.Indexers.RssParser.LoadXmlDocument(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\RssParser.cs:line 114
   at NzbDrone.Core.Indexers.Newznab.NewznabRssParser.PreProcess(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Newznab\NewznabRssParser.cs:line 62
   at NzbDrone.Core.Indexers.RssParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\RssParser.cs:line 55
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 291
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 123
RequestUri: http://10.0.0.10/api?t=movie&cat=2000,2030,2040,2050&extended=1&apikey=(removed)&offset=0&limit=50&imdbid=8376234;StatusCode: OK;ContentType: text/html; charset=utf-8;ContentLength: 1092;ContentSample: <br />
<b>Fatal error</b>:  Uncaught Error: Interface 'Psr\SimpleCache\CacheInterface' not found in /var/www/spotweb/vendor/imdbphp/imdbphp/src/Imdb/Cache.php:14
Stack trace:
#0 /var/www/spotweb/vendor/composer/ClassLoader.php(444): include()
#1 /var/www/spotweb/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#2 [internal function]: Composer\Autoload\ClassLoader-&gt;loadClass()
#3 /var/www/spotweb/vendor/imdbphp/imdbphp/src/Imdb/MdbBase.php(120): spl_autoload_call()
#4 /var/www/spotweb/vendor/imdbphp/imdbphp/src/Imdb/Title.php(182): Imdb\MdbBase-&gt;__construct()
#5 /var/www/spotweb/lib/services/MediaInformation/Services_MediaInformation_Imdb.php(20): Imdb\Title-&gt;__construct()
#6 /var/www/spotweb/lib/page/SpotPage_newznabapi.php(236): Services_MediaInformation_Imdb-&gt;retrieveInfo()
#7 /var/www/spotweb/lib/page/SpotPage_newznabapi.php(59): SpotPage_newznabapi-&gt;search()
#8 /var/www/spotweb/index.php(210): SpotPage_newznabapi-&gt;render()
#9 {main}
  thrown in <b>/var/www/spotweb/vendor/imdbphp/imdbphp/src/Imdb/Cache.php</b> on line <b>14</b><br />
;FeedUrl: http://10.0.0.10/api?t=movie&cat=2000,2030,2040,2050&extended=1&apikey=(removed)&offset=0&limit=50&imdbid=8376234
```

**Comment by Sweepr** [comment]
@mesa57

Seems like a call is missing

Uncaught Error: Interface 'Psr\SimpleCache\CacheInterface' not found in /var/www/spotweb/vendor/imdbphp/imdbphp/src/Imdb/Cache.php:

**Comment by berndh1979** [comment]
> 
> 
> @mesa57
> 
> Seems like a call is missing
> 
> Uncaught Error: Interface 'Psr\SimpleCache\CacheInterface' not found in /var/www/spotweb/vendor/imdbphp/imdbphp/src/Imdb/Cache.php:

Indeed. the CacheInterface.php file is located at:

/var/www/spotweb/vendor/imdbphp/imdbphp/src/Psr/SimpleCache/CacheInterface.php

Apparently it can't find it from the class that tries to implement it:


/var/www/spotweb/vendor/imdbphp/imdbphp/src/Imdb/Cache.php on line14. 

I copied the Psr/SimpleCache to the /src/Imdb/ location, but get the same error.

**Comment by mesa57** [comment]
Give me tie to resolve this please.

**Comment by mesa57** [comment]
Please checkout develop again and verify.

**Comment by berndh1979** [comment]
> 
> 
> Please checkout develop again and verify.

Wow, you're fast. Yeah. It works perfectly now. Thanks so much. You really made my day 👍

**Comment by mesa57** [comment]
No problem. Thanks for reporting the issue 😄
