### ISSUE TITLE
Socket read fail? SSL errors?

### ISSUE THREAD

**Issue by Oxize** [spotweb/spotweb#69]
Can anybody explain what below error message is?

![wxnzvlq](https://cloud.githubusercontent.com/assets/3933702/7710258/e13a7130-fe62-11e4-9c2c-88331ea3c10f.png)

And how i can fix it?

**Comment by Sweepr** [comment]
Take a look at this: https://github.com/spotweb/spotweb/issues/65

Known issue related to SSL, try switching to retrieval without SSL, port 119 as a temporary fix.

**Comment by Oxize** [comment]
Do i need to install it again? Or can i change this info somewhere?

**Comment by Sweepr** [comment]
Login as Admin, goto Config -> Settings -> change your USP to non-ssl, change the port to 119, and disable Encryption.  (Don't forget to properly forward the port)

**Comment by Oxize** [comment]
Thanks working agian!
