### ISSUE TITLE
Domme vraag: waar log ik in op spotweb om te reageren op posts?

### ISSUE THREAD

**Issue by Bakkertje01** [spotweb/spotweb#690]
~~Domme vraag: waar log ik in op spotweb om te reageren op posts?~~

Question: Where do i login to comment on posts?

**Comment by mesa57** [comment]
Kijk eens in de wiki hier op github.

**Comment by Sweepr** [comment]
Depends if the current user has rights to comment, normally only "Authenticated" user can do this.

Check for permissions under "Config" -> "User & group management"

![image](https://user-images.githubusercontent.com/2857865/126033146-0007a139-9094-490c-99ba-14fa8e5ba955.png)

![image](https://user-images.githubusercontent.com/2857865/126033118-f6ecd514-2ca5-4094-a251-4eb7b1b96048.png)

Goodluck!
