### ISSUE TITLE
Remove boxcar support from spotweb

### ISSUE THREAD

**Issue by mesa57** [spotweb/spotweb#696]
Boxcar is deprecated.

**Comment by Sweepr** [comment]
Done,

See: https://github.com/spotweb/spotweb/commit/b27b176ff9daaa6a15885d083c04109e7b661b49
See: https://github.com/spotweb/spotweb/commit/52c9baf02dcedd4fcc26909dc280ebbd41b85659

**Comment by mesa57** [comment]
Did you also remove the option on the configuration settings ?

**Comment by Sweepr** [comment]
@mesa57, Yes i did,

https://github.com/spotweb/spotweb/commit/b27b176ff9daaa6a15885d083c04109e7b661b49#diff-14c3e49c41272071356c4de207601a9072c88689cf5ba3824a9a35d3c6fb42ef

**Comment by mesa57** [comment]
Ok, didn't see that diff.
