### ISSUE TITLE
upgrade-db.php error

### ISSUE THREAD

**Issue by vpieper** [spotweb/spotweb#697]
After I upgrade Mariadb from 10.5 to 10.6 I get this error when I want to clear cache:

Retrieving seems to work correctly.

Debian 10.10

```
21:05 # php upgrade-db.php --clear-cache
Updating schema..(pdo_mysql)
        Validating spots(messageid)
        Validating spots(poster)


SpotWeb crashed

Database schema or settings upgrade failed:
   Invalid collation setting for varchar: utf8mb3_unicode_ci
```

**Comment by mesa57** [comment]
Mariadb 10.6 is not tested and not yet supported with spotweb.
You can either rollback to Mariadb 10.5 or report an issue with Mariadb at
https://jira.mariadb.org/secure/Dashboard.jspa

**Comment by vpieper** [comment]
I git pulled the latest master branch (version 1.5.0) and Spotweb gives me this notification:

```Spotweb contains updated global settings settings. Please run 'bin/upgrade-db.php' from a console window 
```

However when I do that I still get the same error as before:

```18:43 # php upgrade-db.php
Updating schema..(pdo_mysql)
        Validating spots(messageid)
        Validating spots(poster)


SpotWeb crashed

Database schema or settings upgrade failed:
   Invalid collation setting for varchar: utf8mb3_unicode_ci
```

I am still on Mariadb 10.6.
