### ISSUE TITLE
Only English text, no Dutch translation shown

### ISSUE THREAD

**Issue by MrHappy** [spotweb/spotweb#698]
**Describe the bug/issue**
The site only displays in English, despite selecting 'Nederlands'

**Have you searched the internet or Github for an answer?**
I have, did not find anything.
Also removed the check in index.php if language settings differ from 'en_US', didn't resolve it.
Checked in the database if settings were saved correctly, they were.

**To Reproduce**
Do not need to tell you how to change language settings ;)

**Expected behavior**
Text displayed in Dutch instead of English.

**Screenshots**
Not necessary.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS 
 - Browser Firefox / Brave
 - Spotweb Version 1.4.9
 - Which branch  Master
 -  PHP version 7.4.3
 -  Device information Docker

**Additional context**
Provide any other information about the bug or issue that can further help debugging here.

**Comment by mesa57** [comment]
Quick links and filters are not translated to dutch.
But all other menu options should.
![afbeelding](https://user-images.githubusercontent.com/6350469/127317305-46f40665-6220-45c3-91fa-ac89128a775b.png)

**Comment by MrHappy** [comment]
That is what I was expecting, but it looks like this:
![image](https://user-images.githubusercontent.com/686360/127318158-bb7aaf05-96a8-40d2-aa59-c3a0f136e1f5.png)

**Comment by mesa57** [comment]
Could you check if you have messages.mo / po in 
spotweb/locales/nl_NL/LC_MESSAGES/
?

**Comment by MrHappy** [comment]
Both are present...
![image](https://user-images.githubusercontent.com/686360/127516029-2934cd25-1d09-48c3-82f4-fc2de98dfa4a.png)

**Comment by mesa57** [comment]
Nog een tip dan : 
_The translation functionality in PHP requires the modules gettext and mbstring. Call phpInfo() from a script to see if these modules are both activated. If you can't see them both install and activate them in the php.ini file._

**Comment by MrHappy** [comment]
Die zijn beide actief....

**Comment by mesa57** [comment]
Ok, I give up. It works in my test environment. And if gettext is installed, only php native functions are used for translation. @Sweepr : any idea's ?

**Comment by MrHappy** [comment]
I think it is weird too.... Hopefully Sweepr has an idea....

**Comment by Sweepr** [comment]
![afbeelding](https://user-images.githubusercontent.com/2857865/127538950-6cca155d-8d56-4079-81ef-1c8e5424fcb2.png)


![afbeelding](https://user-images.githubusercontent.com/2857865/127538991-ec0fe300-6695-40a4-a51c-036b7d8f6431.png)


Here it works fine too, very weird.

**Comment by mesa57** [comment]
Which docker image did you use ?

**Comment by MrHappy** [comment]
I found the cause, the locale nl_NL.utf8 was missing.... :-1: 
After installing it worked.

the image I use is from jgeusebroek/spotweb.
If you can suggest a better image I'm more than willing to try that ;)

**Comment by mesa57** [comment]
No, that image looks fine, although we do not support docker images.
Strange that NL.utf8 was missing. Should that be part of the docker image ?

**Comment by MrHappy** [comment]
I do not know if that should be part of the image or not...  It was not installed/available...

**Comment by mesa57** [comment]
How did you solve it then ?

**Comment by Sweepr** [comment]
@mesa57 
I guess he did install the nl_NL.utf8 using https://askubuntu.com/questions/76013/how-do-i-add-locale-to-ubuntu-server

**Comment by MrHappy** [comment]
`apt update
 apt install locales`
removed # before nl_NL.utf in /etc/locale.gen
and ran
`locale-gen --no-purge nl_NL.UTF-8`
just to be sure I did this for every nl_NL...

**Comment by mesa57** [comment]
Aah, I understand. Not in docker itself but in the host operating system.

**Comment by MrHappy** [comment]
Nope, did that in Docker....
I'm pretty new to Docker. Should I not have done that (that way)?

**Comment by Sweepr** [comment]
@MrHappy Not sure what the best approach is here, never use Docker but maybe you could ask this question on Ubuntu or Docker forums.

Thanks to all for the effort, and as this issue has been resolved i will close it.

**Comment by mesa57** [comment]
If you do it in docker it will be gone when the container is updated.

**Comment by MrHappy** [comment]
It seems to be working fine now, so thanks!
I'll keep it in mind when the image gets updated.

**Comment by mesa57** [comment]
@Sweepr : issue is solved now by the container developer @jgeusebroek

**Comment by Sweepr** [comment]
@mesa57 Great news, thanks for the update!
