### ISSUE TITLE
IP Change notice from external network

### ISSUE THREAD

**Issue by fusiondust** [spotweb/spotweb#70]
Hello, I keep getting a message about my IP address changing after downloading a few nzb's.  This error prevents me from downloading anymore nab's from spotweb for maybe 10 or 20 mins.  It seems to think my ip address changes from the ISP where spotweb is being hosted on and the remote ISP where I am accessing it.  Is there a way to disable this security feature?

**Comment by Sweepr** [comment]
Could you explain a bit more in detail because i'm having a hard time understanding your exact issue.
Typically dynamic IP's are only used in Home LAN's, more often they are static to prevent issue's as these.

**Comment by fusiondust** [comment]
When I click the nzb link to a spot, I get a page with the following json data.

{"result":"failure","data":[],"info":[],"warnings":[],"errors":["Authentication rejected [response: \"Multiple ip login denied. Looks like your ISP changed your ip from 24.108.74.98 to 24.68.141.129\"] [response: \"\"]"]}

**Comment by Sweepr** [comment]
Ah, i see now..

This is a problem with your USP, they probbly don't allow account sharing, thus only allow you to download from 1 IP.

You should ask either your ISP to fix you IP, or find a USP that supports account sharing,.

**Comment by fusiondust** [comment]
Oh, this message is a response from usenet server.  I guess I could prefetch nzb's...Any idea on how much bandwidth that would consume?  I am looking into your advice about alternate usenet services.  I'm open to recommendations.  Thanks again for the assistance.  Issue closed.

**Comment by Sweepr** [comment]
I see your ISP is shawcable.net - Shaw Communications Inc, on their forum i read this: 

https://community.shaw.ca/thread/1491

You could either contact your ISP for assistance first, if this does not help, you could take a look at this and pick one depending on your budget:

These are all allowed account sharing:
http://www.ngprovider.com/shared-usenet-accounts.php

**Comment by fusiondust** [comment]
I'm on Astraweb.  Shaw usenet services are garbage.  I see Astraweb has 1TB of bandwidth for $50.  I could probably save a ton moving to that from existing unlimmited plan.  Thanks again.

**Comment by Sweepr** [comment]
Usenet services that come with the Internet subscription usually are rubbish, best to avoid them if your a poweruser.

Astraweb 1TB for $50 is that for 1 year?

**Comment by fusiondust** [comment]
They have not indicated any time limit so I'm assuming you just buy the bandwidth.  Cheers!

**Comment by Sweepr** [comment]
I really need to monitor the amount of bandwidth spotweb with full spots, full comments, with/or without prefetch nzb/image's uses.
