### ISSUE TITLE
IMDB information returned is invalid

### ISSUE THREAD

**Issue by hollandschevisch** [spotweb/spotweb#700]
Hi all,

I'm having the following problem when using Radarr to search for a movie. When searching it gives the following error ''IMDB information returned is invalid''
I've already cleared the cache, did a full reset of the database and also did a pull request so everything is fully up to date, but still it won't work. Is there a way I can search not using imdbID's? Or is there some other setting I have to check? The program's are running on a normal windows pc.

Thank you in advance, if there is any more info needed, I'm happy to provide them

**Comment by mesa57** [comment]
See #699
