### ISSUE TITLE
Unknown column 'spost.ouruserid' in 'where clause'

### ISSUE THREAD

**Issue by Fossil01** [spotweb/spotweb#703]
```
Calculating how many spots are new


SpotWeb v0.68.33.34 on PHP v7.4.21 crashed

Fatal error occured retrieving reports:
  42S22: 1054: Unknown column 'spost.ouruserid' in 'where clause'

#0 lib/dbeng/dbeng_pdo.php(154): dbeng_pdo->exec()
#1 lib/dao/Base/Dao_Base_Spot.php(751): dbeng_pdo->singleQuery()
#2 lib/services/Actions/Services_Actions_CacheNewSpotCount.php(166): Dao_Base_Spot->getSpotCount()
#3 retrieve.php(159): Services_Actions_CacheNewSpotCount->cacheNewSpotCount()
#4 {main}

Finished retrieving spots.
```

`spost.ouruserid` is only used in `Services_Search_QueryParser.php` in the filterValuesToSql() function.

**Comment by Fossil01** [comment]
Had a user hammering the login page apparently. Shrunk to 15k now.

Still crashes on`spost.ouruserid`. Will edit title.

**Comment by Sweepr** [comment]
'spost.ouruserid' should be 'spots.ouruserid'

Pushed a commit to develop branch:

https://github.com/spotweb/spotweb/commit/baea425146d26bcb2babc2fd98ee1544782ccfb9

**Comment by Fossil01** [comment]
Aha, the entire column does not exist in my DB.

```
Fatal error occured retrieving reports:
1054: Unknown column 'spots.ouruserid' in 'where clause'

Finished retrieving spots.
```

Is this correct? I ran bin/upgrade-db.php after pulling the 1.5.0 version.

**Comment by Sweepr** [comment]
Wait, it's should also not be 

'spots.ouruserid' but infact be 'spotsposted.ouruserid'.

Pushed a new commit to develop branch, it's not in Master..  

https://github.com/spotweb/spotweb/commit/44f7e6b75ad81d3b54313dc7a6e0d3eee50de2c0

**Comment by Fossil01** [comment]
I changed it on my install but still getting the error.  ` Unknown column 'spotsposted.ouruserid' in 'where clause'`

I noticed more `spots` entries in that file. Like `'tablealias'                  => 'spost',` and `$sortFields[] = ['field' => 'spost.stamp',` too.

**Comment by Sweepr** [comment]
Wauw..  how nobody ever noticed that is a mystery.

https://github.com/spotweb/spotweb/commit/c31f4018f425b0aa94f2f309b37f90b7074df466

**Comment by Fossil01** [comment]
That fixed it, cheers.

**Comment by mesa57** [comment]
> 
> 
> Wauw.. how nobody ever noticed that is a mystery.
> 
> [c31f401](https://github.com/spotweb/spotweb/commit/c31f4018f425b0aa94f2f309b37f90b7074df466)

Seems to me that tablealias was set to 'spost'  so first error should indeed not appear !
