### ISSUE TITLE
upgrade-db.php error

### ISSUE THREAD

**Issue by vpieper** [spotweb/spotweb#704]
See: https://github.com/spotweb/spotweb/issues/697

I git pulled the latest master branch (version 1.5.0) and Spotweb gives me this notification:

`Spotweb contains updated global settings settings. Please run 'bin/upgrade-db.php' from a console window 
`
However when I do that I still get the same error as before:

```Updating schema..(pdo_mysql)
        Validating spots(messageid)
        Validating spots(poster)


SpotWeb crashed

Database schema or settings upgrade failed:
   Invalid collation setting for varchar: utf8mb3_unicode_ci
```

I am still on Mariadb 10.6. Any suggestions? I am unable to downgrade Mariadb unfortunately.

**Comment by Sweepr** [comment]
See: https://github.com/spotweb/spotweb/issues/697#issuecomment-886105897

**Comment by vpieper** [comment]
I know, however no versions are mentioned in Spotweb's release notes.

For now I will try to migrate to a temp 10.5 or 10.4 setup and run the upgrade script there, and report back here. See if that helps other 10.6 users.

**Comment by Sweepr** [comment]
MariaDB isn't mentioned in the release notes at all.. Even though MariaDB is a fork of MySQL it might work, it's not guaranteed.. 

![afbeelding](https://user-images.githubusercontent.com/2857865/129941434-f29abfeb-f421-451d-8246-2e39268f0c1a.png)

**Comment by vpieper** [comment]
Please note that Mysql is not part of Debian 10 and 11 anymore, nowadays Mariadb 10.3 and 10.5 are.

Oracle Mysql needs a third party repo: https://www.digitalocean.com/community/tutorials/how-to-install-the-latest-mysql-on-debian-10

Anyway I will test the upgrade in a Debian/Mariadb 10.3 base setup and report back with any results.

**Comment by mesa57** [comment]
In the past I tried changing the collation to utf8 / mb4. This however takes hours to process on a filled database. I don't want to confront thousands of users with hours of waiting time for a conversion.
Please file a ticket with mariadb if you want to use 10.6

**Comment by vpieper** [comment]
I moved my DB to a fresh Deb 10 / PHP 7 / Mariadb 10.5 setup and ran the upgrade-db.php script there. Then dumped that db and moved it back to 10.6 which seems to have fixed it. My DB is rather large and the script did not take very long. I hear what you say but I'm not a dev, would love to help out however. I do think Mariadb is the mainstream these days.

Thanks, can be closed.

**Comment by Sweepr** [comment]
When you dump a DB the collation is set using 10.5, then imported, when you fresh install using 10.6 the collation is set according the default on 10.6

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vpieper** [comment]
I know but I wasnt't able to workaround the notification I got after the update to 1.5.0 ```Spotweb contains updated global settings settings. Please run 'bin/upgrade-db.php' from a console window``` any other way. I did not _fresh_ install 10.6. I just dropped old db in existing 10.6 and existing Spotweb and imported the db processed in 10.5.

**Comment by mesa57** [comment]
Solved now in Develop branch. Are you able to test this ?

**Comment by vpieper** [comment]
Sure I will test it later today.

**Comment by vpieper** [comment]
Seems to work as for the upgrade-db.php script. Steps te reproduce: see above and git cloned dev version and pointed Apache to dev, then ran upgrade-db.php (and check-cache.php) from dev which both ran with no errors. Spotweb dev then still available, then pointed Apache back to stable and also still available. So all ok. If you need anything else let me know.

**Comment by mesa57** [comment]
Ok, thanks. We will merge this to the master branch.
