### ISSUE TITLE
Back button does not work anymore

### ISSUE THREAD

**Issue by riemers** [spotweb/spotweb#71]
With the latest commits with the preview pictures (which is a nice addition) you can no longer use the "back" button on your browser. You can still click on the back button in the website which will work but no longer outside of that. I normally use my mouse back button to go back but that fails now.

**Comment by Sweepr** [comment]
I'll look into this.

Update you later.

**Comment by riemers** [comment]
p.s. if you click back, the url changes but nothing happens. Click it again and then it goes back (but to the main screen instead of the genre you where in)

**Comment by Sweepr** [comment]
Did you try a different browser?

Also did you add any code to the footer?

**Comment by riemers** [comment]
This was on Chrome, no didn't change the footer, just did the default git clone to update to the latest. Checked with IE, same issue.

**Comment by Wally73** [comment]
no issues here with back button (or backspace)  in chrome (Version
43.0.2357.124 m (64-bit)), Opera (30.0.1835.52) and FireFox (38.0.5)

**Comment by riemers** [comment]
Tried on windows and on my macbook, same issues. So its something with the code i have installed, anyway i can verify that easilly? I only git clone every once every xx months.

**Comment by Sweepr** [comment]
What version do you have installed?

**Comment by riemers** [comment]
Is there a particular version then? I updated with git clone to the version you did a commit on 28 days ago.

**Comment by riemers** [comment]
Escape + U, doesn't do much but seperate does. So if i escape or press the letter "U" it goes back the way it should do when i do the back command with my mouse.

**Comment by Sweepr** [comment]
Ok. which PHP version are you running?

**Comment by riemers** [comment]
PHP 5.4.36-0+deb7u3, loaded with fastci, i'll try using apache instead as test. (although i doubt it will help)

**Comment by Sweepr** [comment]
Do you still have this issue?

You say you have this on diffent computer, using different platforms, and different browsers?

**Comment by riemers** [comment]
I still have this issue yes. And yes on different computers, different browsers it has the same issue (referring here different 'clients', not servers) i just have 1 server installation which i use.

**Comment by Sweepr** [comment]
I installed Spotweb using Xampp and Wamp, on windows and another instance on my Unix box and on all install's the back button is working fine, so it has nothing to do with the code.

I'm thinking of somekind of server configuration problem, but no sure where to look for, 

Maybe this could point into the right direction;

**Comment by Sweepr** [comment]
Or this; http://stackoverflow.com/questions/21706067/apache-doesnt-serve-files-in-javascript-directory-why

**Comment by riemers** [comment]
Strangely enough, if i do a "git reset --hard 85545a899dd39ca329d8dda71aaa9ede64b9c2de"  (Sweepr authored on May 13) that one shows me the picture and the back button still works too! but it doesn't have that latest optimisation.

**Comment by Sweepr** [comment]
That strange indeed, but like i said earlier i have the lastest master installed on 3 different machine's and 2 different platform's on my end which do work fine up to the last commit, so i suspect somekind of problem with javascript or something else not being served from your server..

Do you see any problems in your apache error_log?

**Comment by riemers** [comment]
I see something though: [Sun Jun 14 15:06:26 2015] [warn] [client xxxx] mod_fcgid: stderr: SpotWeb Exception occured: String could not be parsed as XML, referer: https://url/?page=index&search[tree]=cat0_z0_a4,cat0_z0_a6,cat0_z0_a7,cat0_z0_a8,cat0_z0_a9&search[value][]=

**Comment by Sweepr** [comment]
This has probably something to do with a corrupt NZB file, i once so often see these in my error_log aswell, just ignore them.

**Comment by riemers** [comment]
Was looking through the handy sql links, did that "remove all spots form external list" well i cant access mysql anymore, so i assume its a heavy call too.. so i need to wait before i can access the web again ;)

**Comment by Sweepr** [comment]
Of it takes too long, you could do a service MySQL restart

**Comment by riemers** [comment]
mysql was a bit sluggish, forgot that it commits on every query (you get raid sync 100% io) fix that and insta finished.. but back to the issue, i can't find anything in apache logs or dmesg or anything remotely that gives me something solid at the moment.

**Comment by riemers** [comment]
When using F12, i can also see this, again i doubt this is the source though ;p

?page=statics&type=js&lang=en_US&mod=1434287578:2625 Uncaught ReferenceError: ao is not defined(anonymous function) @ ?page=statics&type=js&lang=en_US&mod=1434287578:2625p.event.dispatch @ ?page=statics&type=js&lang=en_US&mod=1434287578:2p.event.add.g.handle.h @ ?page=statics&type=js&lang=en_US&mod=1434287578:2p.event.trigger @ ?page=statics&type=js&lang=en_US&mod=1434287578:2(anonymous function) @ ?page=statics&type=js&lang=en_US&mod=1434287578:2p.extend.each @ ?page=statics&type=js&lang=en_US&mod=1434287578:2p.fn.p.each @ ?page=statics&type=js&lang=en_US&mod=1434287578:2p.fn.extend.trigger @ ?page=statics&type=js&lang=en_US&mod=1434287578:2$.address._trigger @ ?page=statics&type=js&lang=en_US&mod=1434287578:1746$.address._update @ ?page=statics&type=js&lang=en_US&mod=1434287578:1820$.address._popstate @ ?page=statics&type=js&lang=en_US&mod=1434287578:2011p.event.dispatch @ ?page=statics&type=js&lang=en_US&mod=1434287578:2p.event.add.g.handle.h @ ?page=statics&type=js&lang=en_US&mod=1434287578:2

**Comment by Sweepr** [comment]
IS it possible for you to brwose to this for example?

**Comment by riemers** [comment]
Yes i can, but towards "js/jquery/jquery.min.js" since its on a seperate domain.

**Comment by Sweepr** [comment]
What do you mean by that?  "js/jquery/jquery.min.js" on a seperate domain?

Isn't this "js/jquery/jquery.min.js" located on the same server as your spotweb source?

**Comment by riemers** [comment]
Yes its the same, but its at https:///example.com/js/jquery/jquery.min.js

**Comment by Sweepr** [comment]
which branch are you running now?

**Comment by riemers** [comment]
master branch

**Comment by riemers** [comment]
I just tried it on another machine with mariadb instead of mysql, and a different version of php (so not using plesk) and i have the same issue again. On Chrome/IE too, i made it open so perhaps you can see it too, it only has a few spots as test: http://www.lethal-zone.eu/spotweb/

**Comment by Sweepr** [comment]
I have tried it from my side and to make things even stranger it's working from my side.

IE, Chrome, and Firefox.

**Comment by riemers** [comment]
I have an old laptop lying around here, i'll try that one (has windows 7 on it i believe) i am currently on windows 8. I did try once on my macbook though.. let me double check again.

**Comment by riemers** [comment]
Well i tried that windows 7, with IE and Chrome, Same issue. To make sure it wasn't my line or anything, i called up a friend in Aruba, shared screens and he also has the same issue with that url i gave earlier. Just to clarify, if you use the "back" button of your mouse or the browser itself, it fails. (not the back button IN the website)

**Comment by WzL** [comment]
Just to be sure, you do not make use of any caching or transparent proxy of any kind in this case right?!

**Comment by riemers** [comment]
Correct, as tested, i tested it from a Macbook, Windows 8, Windows 7, windows 2003, 3 different internet lines and with and without plugins enabled/disabled on common browsers (IE/Chrome/FF) all different machines. And as i also mentioned, if i go back a few versions it does work.

**Comment by riemers** [comment]
https://youtu.be/aynTDRsBZtM , made a video of it. At this point i have no clue how to progress any further.. if anyone has idea's.. i am all ears :)

**Comment by riemers** [comment]
I mentioned the error, but no bells where ringing..

https://github.com/spotweb/spotweb/blob/master/templates/we1rdo/js/scripts.js line 4, there is a typo. It has the text "ao" after the function. Remove that and it will fix it.

Still remains a mystery to me why other people didn't have this issue, it should affect all people that cloned the latest.

**Comment by Sweepr** [comment]
I just saw that typo too.. but you were faster..

Well its still weird because i have that typo in my script.js, but no such issues like you have.

Anyway its good that its fixed..

**Comment by riemers** [comment]
Indeed, but that might be because of the theme name :)
