### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by bouwew** [spotweb/spotweb#712]
Just now, when trying to load the local spotweb page, I see this error in the browser:

```
Fatal error: Uncaught Error: Undefined class constant 'MYSQL_ATTR_FOUND_ROWS' in /var/www/html/spotweb/lib/dbeng/dbeng_pdo_mysql.php:33 Stack trace: #0 /var/www/html/spotweb/lib/Bootstrap.php(154): dbeng_pdo_mysql->connect() #1 /var/www/html/spotweb/lib/Bootstrap.php(42): Bootstrap->getDaoFactory() #2 /var/www/html/spotweb/index.php(19): Bootstrap->boot() #3 {main} thrown in /var/www/html/spotweb/lib/dbeng/dbeng_pdo_mysql.php on line 33
```

**Desktop (please complete the following information):**
 - OS: spotweb runs on Debian 11 in Proxmox 7 CT
 - Both Chromium and Firefox browsers running on the latest Linux Mint
 - Spotweb latest master branch version pulled from github, develop branch shows the same error
 -  PHP version: 7.4.21

**Comment by Sweepr** [comment]
Can you check if php-mysql and php-curl are installed and loaded by php.ini?

**Comment by bouwew** [comment]
How do I check that?

**Comment by Sweepr** [comment]
Rename your dbsettings.inc.php. and run install.php, check if there are any errrors or is something is not ok.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Sweepr** [comment]
Rename dbsettings.inc.php and run the installer again, check for errors on the first page, make sure all checks are pass.

**Comment by bouwew** [comment]
Thnx for the pointer!
![image](https://user-images.githubusercontent.com/11290930/135575374-87a35c10-a925-4e5e-9beb-331257a6f8de.png)

I've recently upgraded Debian 10 to 11, this must be the reason.
Tnx, I know how to fix this :)
