### ISSUE TITLE
XSS on login page

### ISSUE THREAD

**Issue by Xitro01** [spotweb/spotweb#718]
**Describe the bug/issue**
The parameter data[performredirect] on the login page is vulnerable to XSS attacks.
This issue was found in the latest Docker package by jgeusebroek (jgeusebroek/docker-spotweb) and seems to involve the latest Spotweb 1.5.1 as random Spotweb servers on the internet are also vulnerable.

**To Reproduce**
Go to this URL: http://[ip]:[port]/?data[performredirect]=%22%3E%3Cscript%3Ealert(0)%3C/script%3E&page=login

**Screenshots**
![XSS](https://user-images.githubusercontent.com/19844787/141432661-87399ad5-9a0e-4544-9397-91ad1b8f0463.PNG)

**Comment by Xitro01** [comment]
![Schermafbeelding 2023-06-22 125944](https://github.com/spotweb/spotweb/assets/19844787/0420f7cd-4639-4d65-a800-6835d2106ff6)

I'm afraid that it's still possible. I get the "Script is not allowed" alert, but after that it will simply execute my XSS.
I'm using the following payload:
```http://192.168.1.7:8081/?data[performredirect]=%22%3E%3Cscript%3Ealert(document.location)%3C/script%3E&data[renderhtml]=1&loginform[http_referer]=https%3a%2f%2f192.168.1.7%3a8081%2f%3f&page=login&loginform[xsrfid]=1687430765%3aloginform%3a1%3acf7767e526ef26267fa6e655d069f16a653fe95f&loginform[username]=&loginform[submitlogin]=Login&loginform[password]=```

**Comment by mesa57** [comment]
Feel free to submit a PR

**Comment by Xitro01** [comment]
> Feel free to submit a PR

To be honest, I would if I could. Yet I spend hours and hours developing my offensive security skillset and little time in my programming skills. Despite that I still felt it was my duty to report this issue.
