### ISSUE TITLE
Docker container using SQlite gives error "HY000: 1: no such table: settings"

### ISSUE THREAD

**Issue by jerheij** [spotweb/spotweb#719]
**Describe the bug/issue**
I attempt to maintain a Docker container with Spotweb / Apache that supports all the databases. Unfortunately I have done some troubleshooting to fix another issue and found out that I receive the following error when trying to set up the container with sqlite and try to retrieve spots.

```
Fatal error occured retrieving reports:
  HY000: 1: no such table: settings



#0 /var/www/spotweb/lib/dbeng/dbeng_pdo.php(186): dbeng_pdo->exec()
#1 /var/www/spotweb/lib/dao/Base/Dao_Base_Setting.php(25): dbeng_pdo->arrayQuery()
#2 /var/www/spotweb/lib/services/Settings/Services_Settings_DbContainer.php(29): Dao_Base_Setting->getAllSettings()
#3 /var/www/spotweb/lib/Bootstrap.php(217): Services_Settings_DbContainer->initialize()
#4 /var/www/spotweb/lib/Bootstrap.php(43): Bootstrap->getSettings()
#5 /var/www/spotweb/retrieve.php(12): Bootstrap->boot()
#6 {main}

PHP Notice:  Undefined variable: retriever in /var/www/spotweb/retrieve.php on line 296
PHP Fatal error:  Uncaught Error: Call to a member function quit() on null in /var/www/spotweb/retrieve.php:296
Stack trace:
#0 {main}
  thrown in /var/www/spotweb/retrieve.php on line 296

```

**Have you searched the internet or Github for an answer?**
Yes, didn't find anything that helped me out.

**To Reproduce**
1. Install fresh spotweb with PHP7 and apache
2. Go to http://[host]/install.php
3. Check if all requirements are met for SQLite installation
4. Configure SQLite
5. Configure spotnet account/server
6. Finish installation
7. Attempt to retrieve spots

**Expected behavior**
Successfully retrieving spots.

**Platform**
 - OS: Alpine
 - Image: https://hub.docker.com/r/jerheij/spotweb
 - Spotweb Version: master branch
 -  PHP version: 7.4.25

**Additional context**
When I do the exact same setup but with mysql/mariadb database it works completely fine.

**Comment by Sweepr** [comment]
So the main question is why are you missing table: `settings`
The database structure is created upon install, there have not been any changes in the code to my knowledge.

**Comment by Sweepr** [comment]
@mesa57 

I do not have a docker configuration so i cannot verify this, can you have a look at it?

**Comment by jerheij** [comment]
I am not sure. When using sqlite it just creates a database from scratch at the configured file location, right? For reference, this is the docker-compose configuration I used for testing:

```
---
version: "2.1"
services:
  spotweb:
    image: jerheij/spotweb:stable
    container_name: spotweb
    restart: always
    ports:
      - "80:80"
    environment:
      TZ: Europe/Amsterdam
      SQL: sqlite
      UUID: 1000
      GUID: 1000
      SPOTWEB_CRON_CACHE_CHECK: "*/10 * * * *"
      SPOTWEB_CRON_RETRIEVE: "*/5 * * * *"
    volumes:
      - ./spotweb-sqlite:/var/www/spotweb
```

**Comment by Sweepr** [comment]
Not sure, i am not a huge docker fan or know much about it..

Maybe the creator might be able to assist.

**Comment by jerheij** [comment]
> Not sure, i am not a huge docker fan or know much about it..
> 
> Maybe the creator might be able to assist.

I am the creator of the container image. I know it has worked before and it works perfectly fine with mariadb. It's literally a container with apache, php7 + required modules and either sqlite/mariadb/postgre support.

**Comment by mesa57** [comment]
@Sweepr I noticed this issue in the past, but I do not know in what conditions that was.
Also it corrected itself on start of spotweb interface.
So I did not look into that issue further, but it was outside of docker.
Do you have time to execute an SQLite test ?

**Comment by Sweepr** [comment]
Mabye tomorrow if i find the time for it i can have a look.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Sweepr** [comment]
@jerheij 

`Also it corrected itself on start of spotweb interface.` <-- does that work for you?

Could you try to run `php upgrade-db.php` or `upgrade-db.php --reset-db` and paste the output?

In order to reproduce this i installed spotweb 1.5.1 with sqlite on my Wamp server using PHP 7.4.0 and Apache 2.4.4.1 but the setting table got created without problems, so i am not able to reproduce this here.

![afbeelding](https://user-images.githubusercontent.com/2857865/141672542-7ffe9bd3-8a8d-43ed-99b7-0d94b7a2848f.png)

![afbeelding](https://user-images.githubusercontent.com/2857865/141672510-215f3a21-ae8d-490a-b59c-8107929c6949.png)

![afbeelding](https://user-images.githubusercontent.com/2857865/141672641-3442855b-dab5-4415-951f-667670305868.png)

**Comment by mesa57** [comment]
Is that from the master branch ?
Maybe it depends on the type of spotweb install (open, closed, public) ?

**Comment by Sweepr** [comment]
Master branch yes.. this is on Public install...

**Comment by mesa57** [comment]
If I find time today I will try his docker image.

**Comment by jerheij** [comment]
I performed a fresh install with my container, I configured a usenet server and did the following:
```
sqlite> .open /var/www/spotweb/spotweb.sql  
sqlite> .databases                                                    
main: /var/www/spotweb/spotweb.sql r/w                          
sqlite> .tables                                                       
sqlite> .tables                                                 
cache                 idx_fts_spots_idx     spotsfull                 
commentsfull          moderatedringbuffer   spotsposted         
commentsposted        notifications         spotstatelist        
commentsxover         permaudit             spotteridblacklist  
filtercounts          reportsposted         usenetstate         
filters               reportsxover          usergroups          
grouppermissions      securitygroups        users               
idx_fts_spots         sessions              usersettings        
idx_fts_spots_config  settings            
idx_fts_spots_data    spots               
sqlite> .tables
cache                 idx_fts_spots_idx     spotsfull           
commentsfull          moderatedringbuffer   spotsposted         
commentsposted        notifications         spotstatelist       
commentsxover         permaudit             spotteridblacklist  
filtercounts          reportsposted         usenetstate         
filters               reportsxover          usergroups          
grouppermissions      securitygroups        users               
idx_fts_spots         sessions              usersettings        
idx_fts_spots_config  settings            
idx_fts_spots_data    spots               
sqlite> 

/ # php /var/www/spotweb/retrieve.php 


SpotWeb v0.68.33.34 on PHP v7.4.25 crashed

Fatal error occured retrieving reports:
  HY000: 1: no such table: settings



#0 /var/www/spotweb/lib/dbeng/dbeng_pdo.php(186): dbeng_pdo->exec()
#1 /var/www/spotweb/lib/dao/Base/Dao_Base_Setting.php(25): dbeng_pdo->arrayQuery()
#2 /var/www/spotweb/lib/services/Settings/Services_Settings_DbContainer.php(29): Dao_Base_Setting->getAllSettings()
#3 /var/www/spotweb/lib/Bootstrap.php(217): Services_Settings_DbContainer->initialize()
#4 /var/www/spotweb/lib/Bootstrap.php(43): Bootstrap->getSettings()
#5 /var/www/spotweb/retrieve.php(12): Bootstrap->boot()
#6 {main}

PHP Notice:  Undefined variable: retriever in /var/www/spotweb/retrieve.php on line 296
PHP Fatal error:  Uncaught Error: Call to a member function quit() on null in /var/www/spotweb/retrieve.php:296
Stack trace:
#0 {main}
  thrown in /var/www/spotweb/retrieve.php on line 296
```
That's the original error. Then I did what you suggested:

```
/ # php /var/www/spotweb/bin/upgrade-db.php 
Updating schema..(pdo_sqlite)
```

No errors and it seemed to update the database.

```
/ # php /var/www/spotweb/retrieve.php            
PHP Notice:  Undefined index: xsrfsecret in /var/www/spotweb/lib/services/Settings/Services_Settings_Container.php on line 70                                  
PHP Notice:  Undefined index: settingsversion in /var/www/spotweb/lib/services/Settings/Services_Settings_Container.php on line 70                             
                                                                               
                                                                               
SpotWeb v0.68.33.34 on PHP v7.4.25 crashed                                  
                                                                               
Fatal error occured retrieving reports:                       
  Unknown SettingsNotUpgradedException          

/ # sqlite3                                      
SQLite version 3.35.5 2021-04-19 18:32:05                                      
Enter ".help" for usage hints.                     
Connected to a transient in-memory database.                  
Use ".open FILENAME" to reopen on a persistent database.                       
sqlite> .open /var/www/spotweb/spotweb.sql                                     
sqlite> .database                                                              
main: /var/www/spotweb/spotweb.sql r/w                                    
sqlite> .tables                                                 
cache                 idx_fts_spots_idx     spotsfull                  
commentsfull          moderatedringbuffer   spotsposted         
commentsposted        notifications         spotstatelist                      
commentsxover         permaudit             spotteridblacklist                                                                                                 
filtercounts          reportsposted         usenetstate                                                                                                        
filters               reportsxover          usergroups          
grouppermissions      securitygroups        users                         
idx_fts_spots         sessions              usersettings        
idx_fts_spots_config  settings                                        
idx_fts_spots_data    spots                                                                                                                                    
sqlite>                                                                                                                                                        
```

**Comment by mesa57** [comment]
Sorry, can't get you're container to install. 
Volumes point to a snap, UUID 0 and GUID 100 doesn't work.
I am not able to create an sqlite database on ubuntu 18 due to my lack of knowlegde

**Comment by jerheij** [comment]
If you create a folder "spotweb" in the directory you're in, then use the following docker-compose to start the container it should create it on port 80 and you should be able to reach it:
```
---
version: "2.1"
services:
  spotweb:
    image: jerheij/spotweb:stable
    container_name: spotweb
    restart: always
    ports:
      - "80:80"
    environment:
      SQL: sqlite
    volumes:
      - ./spotweb:/var/www/spotweb
```

Alternatively you could run it like this as well:
```
docker run --restart=always -d -p 80:80 \
		--hostname=spotweb \
		--name=spotweb \
		-v ./spotweb:/var/www/spotweb \
		-e SQL='sqlite' \
		jerheij/spotweb:stable
```

**Comment by mesa57** [comment]
That's what i did, but apart from the fact that the volume is accessed in /tmp/docker.snap/tmp ,,,
it say's 'database not writeable' on last page of install.
I have 777 everything without result. My docker/ubuntu knowlegde is apparently lacking here.

**Comment by jerheij** [comment]
You can leave the volume out and then it's completely managed by docker, that'll only mean that when you stop / remove the container your userdata is gone. But that's not a big issue for a test setup.

**Comment by mesa57** [comment]
What do you specify then as SQLite database ?

**Comment by jerheij** [comment]
> What do you specify then as SQLite database ?

What do you mean with specifying as SQLite database? During the spotweb configuration?

**Comment by mesa57** [comment]
Yes, what do you fill in then ? (sorry, only tested in windows, never in linux).

**Comment by jerheij** [comment]
Just `spotweb.sql` so I know which exact file it is. It will be created in `/var/www/spotweb/`.

**Comment by mesa57** [comment]
Seems to work fine when retrieving spots ;
```
bash-5.1# php retrieve.php
WARNING: Using slow PHP based RSA, please enable the PHP OpenSSL extension whenever possible
Last retrieve at Thu Jan  1 01:00:00 1970
Retrieving new Spots from server news.supernews.com...
Appr. Message count:    5199523
First message number:   3118
Last message number:    5202641
Current article number: 3118

Retrieving 3118 till 7148 (parsed: 32, in DB: 0, signed: 0, invalid: 32, rtntn.skip: 0, mod: 0, full: 0, total: 32) in 0.18 seconds
Retrieving 7148 till 11627 (parsed: 40, in DB: 0, signed: 0, invalid: 40, rtntn.skip: 0, mod: 0, full: 0, total: 40) in 0.07 seconds
Retrieving 11627 till 15976 (parsed: 20, in DB: 0, signed: 0, invalid: 20, rtntn.skip: 0, mod: 0, full: 0, total: 20) in 0.14 seconds
Retrieving 15976 till 18840 (parsed: 8, in DB: 0, signed: 0, invalid: 8, rtntn.skip: 0, mod: 0, full: 0, total: 8) in 0.12 seconds
```

**Comment by jerheij** [comment]
Is that with the container or a regular installation?

**Comment by mesa57** [comment]
That is you're container. But retrieve.php is executed in a bash window (user root).
I will try once more, because I needed to go into spotweb to set my newsserver.

**Comment by mesa57** [comment]
Same result.

**Comment by jerheij** [comment]
> That is you're container. But retrieve.php is executed in a bash window (user root). I will try once more, because I needed to go into spotweb to set my newsserver.

I found the issue I think! When I run this:
`php /var/www/spotweb/retrieve.php` it throws an error. But when I run `cd /var/www/spotweb && php retrieve.php` it works.

**Comment by mesa57** [comment]
It works fine if you specify the folder of the sqlite database. E.g. /var/www/spotweb/spotweb.db instead of just spotweb.db

Btw. you should include openssl in you're image for performance reasons

**Comment by jerheij** [comment]
> It works fine if you specify the folder of the sqlite database. E.g. /var/www/spotweb/spotweb.db instead of just spotweb.db
Ah okay, that's the problem! Thanks a lot!

> Btw. you should include openssl in you're image for performance reasons
I will have a look at this when I update my image next.
