### ISSUE TITLE
Spotweb on Synology upgrade-db.php db setting not persistent.

### ISSUE THREAD

**Issue by twinden** [spotweb/spotweb#722]
after pulling the spotweb master branch and updating I keep getting the error 
“Spotweb contains updated global settings settings. Please run 'bin/upgrade-db.php' from a console window”.
This happens once a day, and dissapears after running php56 upgrade-db.php.
After a day, sometimes sooner (few hours) the message comes back.
In between spotweb runs fine.

I can’t find the same error on Google or GitHub.

It seems session related, or not persistent settings in the database.
I have mariadb10.3.29-0070 running.

$uname -a
Linux DiskStation 3.2.40 #25556 SMP PREEMPT Thu Jul 1 14:28:54 CST 2021 i686 GNU/Linux synology_evansport_214play
$uname -m
i686

$more /etc.defaults/VERSION
majorversion="6"
minorversion="2"
major="6"
minor="2"
micro="4"
productversion="6.2.4"
buildphase="GM"
buildnumber="25556"
smallfixnumber="2"
nano="0"
base="25556"
builddate="2021/08/28"
buildtime="19:18:12"

**Comment by Sweepr** [comment]
When this happens again could you runs this SQL query before and after you run upgrade-db.php and post these values here?

`SELECT `value` FROM `settings` WHERE `id` = 2 OR `ID` = 3 OR `ID` = 408; `

Normally this message only appears when these value's in the database do not match the bootstrap.

**Comment by twinden** [comment]
i slightly altered the sql statement to
   SELECT id, value FROM `settings` WHERE `id` = 2 OR `ID` = 3 OR `ID` = 408
after i got the the error mentioned above
id    value
2	0.33
3	0.34

after upgrade-db.php
id    value
2	0.33
3	0.34

i got no errors or warnings during upgrade-db.php
$ php56 upgrade-db.php
Updating schema..(pdo_mysql)
        Validating spots(messageid)
        Validating spots(poster)
        Validating spots(title)
        Validating spots(tag)
        Validating spots(category)
        Validating spots(subcata)
        Validating spots(subcatb)
        Validating spots(subcatc)
        Validating spots(subcatd)
        Validating spots(subcatz)
        Validating spots(stamp)
        Validating spots(reversestamp)
        Validating spots(filesize)
        Validating spots(moderated)
        Validating spots(commentcount)
        Validating spots(spotrating)
        Validating spots(reportcount)
        Validating spots(spotterid)
        Validating spots(editstamp)
        Validating spots(editor)
        Validating spotsfull(messageid)
        Validating spotsfull(verified)
        Validating spotsfull(usersignature)
        Validating spotsfull(userkey)
        Validating spotsfull(xmlsignature)
        Validating spotsfull(fullxml)
        Validating usenetstate(infotype)
        Validating usenetstate(curarticlenr)
        Validating usenetstate(curmessageid)
        Validating usenetstate(lastretrieved)
        Validating usenetstate(nowrunning)
        Validating commentsxover(messageid)
        Validating commentsxover(nntpref)
        Validating commentsxover(spotrating)
        Validating commentsxover(moderated)
        Validating commentsxover(stamp)
        Validating reportsxover(messageid)
        Validating reportsxover(fromhdr)
        Validating reportsxover(keyword)
        Validating reportsxover(nntpref)
        Validating spotstatelist(messageid)
        Validating spotstatelist(ouruserid)
        Validating spotstatelist(download)
        Validating spotstatelist(watch)
        Validating spotstatelist(seen)
        Validating commentsfull(messageid)
        Validating commentsfull(fromhdr)
        Validating commentsfull(stamp)
        Validating commentsfull(usersignature)
        Validating commentsfull(userkey)
        Validating commentsfull(spotterid)
        Validating commentsfull(hashcash)
        Validating commentsfull(body)
        Validating commentsfull(verified)
        Validating commentsfull(avatar)
        Validating settings(name)
        Validating settings(value)
        Validating settings(serialized)
        Validating commentsposted(ouruserid)
        Validating commentsposted(messageid)
        Validating commentsposted(inreplyto)
        Validating commentsposted(randompart)
        Validating commentsposted(rating)
        Validating commentsposted(body)
        Validating commentsposted(stamp)
        Validating spotsposted(messageid)
        Validating spotsposted(ouruserid)
        Validating spotsposted(stamp)
        Validating spotsposted(title)
        Validating spotsposted(tag)
        Validating spotsposted(category)
        Validating spotsposted(subcats)
        Validating spotsposted(filesize)
        Validating spotsposted(fullxml)
        Validating reportsposted(ouruserid)
        Validating reportsposted(messageid)
        Validating reportsposted(inreplyto)
        Validating reportsposted(randompart)
        Validating reportsposted(body)
        Validating reportsposted(stamp)
        Validating usersettings(userid)
        Validating usersettings(privatekey)
        Validating usersettings(publickey)
        Validating usersettings(avatar)
        Validating usersettings(otherprefs)
        Validating users(username)
        Validating users(firstname)
        Validating users(passhash)
        Validating users(lastname)
        Validating users(mail)
        Validating users(apikey)
        Validating users(lastlogin)
        Validating users(lastvisit)
        Validating users(lastread)
        Validating users(lastapiusage)
        Validating users(deleted)
        Validating sessions(sessionid)
        Validating sessions(userid)
        Validating sessions(hitcount)
        Validating sessions(lasthit)
        Validating sessions(ipaddr)
        Validating sessions(devicetype)
        Validating securitygroups(name)
        Validating grouppermissions(groupid)
        Validating grouppermissions(permissionid)
        Validating grouppermissions(objectid)
        Validating grouppermissions(deny)
        Validating usergroups(userid)
        Validating usergroups(groupid)
        Validating usergroups(prio)
        Validating notifications(userid)
        Validating notifications(stamp)
        Validating notifications(objectid)
        Validating notifications(type)
        Validating notifications(title)
        Validating notifications(body)
        Validating notifications(sent)
        Validating filters(userid)
        Validating filters(filtertype)
        Validating filters(title)
        Validating filters(icon)
        Validating filters(torder)
        Validating filters(tparent)
        Validating filters(tree)
        Validating filters(valuelist)
        Validating filters(sorton)
        Validating filters(sortorder)
        Validating filters(enablenotify)
        Validating filtercounts(userid)
        Validating filtercounts(filterhash)
        Validating filtercounts(currentspotcount)
        Validating filtercounts(lastvisitspotcount)
        Validating filtercounts(lastupdate)
        Validating spotteridblacklist(spotterid)
        Validating spotteridblacklist(ouruserid)
        Validating spotteridblacklist(idtype)
        Validating spotteridblacklist(origin)
        Validating spotteridblacklist(doubled)
        Validating cache(resourceid)
        Validating cache(cachetype)
        Validating cache(stamp)
        Validating cache(metadata)
        Validating cache(ttl)
        Validating moderatedringbuffer(messageid)
        Validating permaudit(stamp)
        Validating permaudit(userid)
        Validating permaudit(permissionid)
        Validating permaudit(objectid)
        Validating permaudit(result)
        Validating permaudit(ipaddr)
        Validating index idx_spots_1
        Validating index idx_spots_2
        Validating index idx_spots_3
        Validating index idx_spots_4
        Validating index idx_spots_5
        Validating FTS idx_fts_spots
        Validating index idx_usenetstate_1
        Validating index idx_spotsfull_1
        Validating index idx_commentsfull_1
        Validating index idx_commentsxover_1
        Validating index idx_commentsxover_2
        Validating index idx_reportsxover_1
        Validating index idx_reportsxover_2
        Validating index idx_reportsposted_1
        Validating index idx_reportsposted_2
        Validating index idx_reportspostedrel_1
        Validating index idx_commentsposted_1
        Validating index idx_commentspostedrel_1
        Validating index idx_spotsposted_1
        Validating index idx_spotspostedrel_1
        Validating index idx_settings_1
        Validating index idx_usersettings_1
        Validating index idx_users_1
        Validating index idx_users_2
        Validating index idx_users_3
        Validating index idx_users_4
        Validating index idx_sessions_1
        Validating index idx_sessions_2
        Validating index idx_sessions_3
        Validating index idx_sessionsrel_1
        Validating index idx_spotstatelist_1
        Validating index idx_spotstatelistrel_1
        Validating index idx_securitygroups_1
        Validating index idx_grouppermissions_1
        Validating index idx_usergroups_1
        Validating index idx_usergroupsrel_1
        Validating index idx_notifications_1
        Validating index idx_notifications_2
        Validating index idx_filters_1
        Validating index idx_filtercounts_1
        Validating index idx_spotteridblacklist_1
        Validating index idx_spotteridblacklist_2
        Validating index idx_cache_1
        Validating index idx_cache_2
        Validating index idx_moderatedringbuffer_1
Schema update done
Updating settings
Settings update done
Updating users
Users' update done

I noticed just now that afterwards the GUI still wouldn't load and still gave me the error "“Spotweb contains updated global settings settings. Please run 'bin/upgrade-db.php' from a console window”.

**Comment by Sweepr** [comment]
What you see is `Spotweb contains updated **global settings** setting`

```
catch (SettingsNotUpgradedException $x) {
    echo "Spotweb contains updated global settings settings. Please run 'bin/upgrade-db.php' from a console window".PHP_EOL;
} // SecurityNotUpgradedException
```

From: https://github.com/spotweb/spotweb/blob/9e53a0304b629c43ab1492a64450f426bff9b2d9/index.php#L509

Which is checked in here: https://github.com/spotweb/spotweb/blob/9e53a0304b629c43ab1492a64450f426bff9b2d9/lib/Bootstrap.php#L171

By: `if (!$settings->settingsValid())`

In: https://github.com/spotweb/spotweb/blob/9e53a0304b629c43ab1492a64450f426bff9b2d9/lib/Bootstrap.php#L184

Here the comparison is done: https://github.com/spotweb/spotweb/blob/9e53a0304b629c43ab1492a64450f426bff9b2d9/lib/services/Settings/Services_Settings_Base.php#L232

`return $this->_settings->get('settingsversion') == SPOTWEB_SETTINGS_VERSION;`

 So the question is, why does `get('settingsversion') == SPOTWEB_SETTINGS_VERSION;` return false in your case, causing the info message while in fact `'settingsversion') == SPOTWEB_SETTINGS_VERSION;` seem to match as seen in https://github.com/spotweb/spotweb/issues/722#issuecomment-974514025

_

> after i got the the error mentioned above
> id value
> 2 0.33
> 
> after upgrade-db.php
> id value
> 2 0.33

_

https://github.com/spotweb/spotweb/blob/3cacf1e894a02c9b84f169c378cb7dec16db964b/lib/Bootstrap.php#L7

@twinden 
Could you check in file: spotweb/lib/Bootstrap.php
What you have on line 7:

![afbeelding](https://user-images.githubusercontent.com/2857865/142722975-a343ebae-f826-4a77-8b82-91ac033c1049.png)

**Comment by twinden** [comment]
Well, that seems fine.
![image](https://user-images.githubusercontent.com/18450278/142727143-dc901aed-c2e2-4026-b299-87cd4d5a83db.png)

**Comment by Sweepr** [comment]
Have you tried creating a new DB and see if it happens again?

**Comment by twinden** [comment]
This is practically a new MariaDB 10 database, since 5 weeks.
Not imported from 5 but newly created by install.php (or whatever that file is called).

Retrieving takes ages on a new database.

catch (SettingsNotUpgradedException $x) {
    echo "Spotweb contains updated global settings settings. Please run 'bin/upgrade-db.php' from a console window".PHP_EOL;
} **// SecurityNotUpgradedException**

I just spotted a wrong comment btw. 😇

**Comment by Sweepr** [comment]
> This is practically a new MariaDB 10 database, since 5 weeks. Not imported from 5 but newly created by install.php (or whatever that file is called).
> 
> Retrieving takes ages on a new database. 
> 
> catch (SettingsNotUpgradedException $x) { echo "Spotweb contains updated global settings settings. Please run 'bin/upgrade-db.php' from a console window".PHP_EOL; } **// SecurityNotUpgradedException**
> 
> I just spotted a wrong comment btw. 😇

**Comment by Sweepr** [comment]
No idea what is going on here.

I'd suggest to start over from scratch, fresh DB, fresh install.. and try to upgrade PHP, PHP5.6 is ancient.

**Comment by twinden** [comment]
Will try. Thanks !
