### ISSUE TITLE
show info url in “add show” tru blankrefer.com does not work anymore.

### ISSUE THREAD

**Issue by twinden** [spotweb/spotweb#723]
after searching a new show in “add show” the info url by clicking the title does not work anymore.
for example [https://blankrefer.com/?https://thetvdb.com/?tab=series&id=308178&lid=7](https://blankrefer.com/?https://thetvdb.com/?tab=series&id=308178&lid=7) is opened.

I believe the site blankrefer.com is gone . . .

**Comment by mesa57** [comment]
We don't use "add show" in spotweb.
But I know Sickchill has that problem.

**Comment by twinden** [comment]
oops :-O
