### ISSUE TITLE
PHP 8.1

### ISSUE THREAD

**Issue by damousys** [spotweb/spotweb#724]
The readme.md states PHP v5.6 or higher, but PHP 8.1 gives me errors.
Think it is more a feature request instead of a bug

**Comment by Sweepr** [comment]
Closing this since "gives me errors." is not enough information and Spotweb is not tested on PHP8.1 (yet.)

**Comment by damousys** [comment]
That's why I made it a Feauture request.
I can give you the errors I receive ?

**Comment by Sweepr** [comment]
@damousys 

Yes, posting the error's that would be a good starting point, i will reopen this then.

**Comment by damousys** [comment]
This are the errors I receive when PHP 8.1 enabled
`
Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/html/lib/dao/Base/Dao_Base_UserFilter.php on line 254
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/lib/dao/Base/Dao_Base_UserFilter.php:254) in /var/www/html/lib/page/SpotPage_Abs.php on line 63
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/lib/dao/Base/Dao_Base_UserFilter.php:254) in /var/www/html/lib/page/SpotPage_Abs.php on line 64
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/lib/dao/Base/Dao_Base_UserFilter.php:254) in /var/www/html/lib/page/SpotPage_Abs.php on line 89
Deprecated: Function strftime() is deprecated in /var/www/html/lib/SpotTemplateHelper.php on line 1058
`

**Comment by CptChaos** [comment]
The retrieve.php starts with a deprecated warning:
`PHP Deprecated:  Function strftime() is deprecated in /var/www/spotweb/lib/services/Retriever/Services_Retriever_Spots.php on line 146`
 but eventually crashes out with an error much like above:
`PHP Fatal error:  Type of CustomException::$file must be string (as in class Exception) in /var/www/spotweb/lib/exceptions/CustomException.php on line 27`

**Comment by damousys** [comment]
Did not try that, but get error's on that one to

**Comment by mesa57** [comment]
Please checkout the develop branch.

**Comment by CptChaos** [comment]
I just pulled the `develop` branch, as I already am using this branch on my setup. I just reinstalled `php8.1` again on my Debian or Ubuntu (not sure anymore) VM. When I try to retrieve posts (by running `php retrieve.php`) manually. It ran perfectly, but I got some deprecation warnings. Most were like
`PHP Deprecated:  Implicit conversion from float 92.74999999999999 to int loses precision in /var/www/spotweb/vendor/pchart/class/pDraw.class.php on line 1106` 
and others (but way less) like 
`PHP Deprecated:  imagecolorallocatealpha(): Passing null to parameter #2 ($red) of type int is deprecated in /var/www/spotweb/vendor/pchart/class/pDraw.class.php on line 1358`
`PHP Deprecated:  imagecolorallocatealpha(): Passing null to parameter #3 ($green) of type int is deprecated in /var/www/spotweb/vendor/pchart/class/pDraw.class.php on line 1358`
`PHP Deprecated:  imagecolorallocatealpha(): Passing null to parameter #4 ($blue) of type int is deprecated in /var/www/spotweb/vendor/pchart/class/pDraw.class.php on line 1358`

So I am guessing some vendor packages need to be updated.

**Comment by Sweepr** [comment]
@CptChaos 

![afbeelding](https://user-images.githubusercontent.com/2857865/148249751-9ed566b6-b854-4aba-85a9-acc3ad1f18ec.png)

The package is currently not PHP 8.1 ready, so no statistics for PHP 8.1

**Comment by Sweepr** [comment]
![afbeelding](https://user-images.githubusercontent.com/2857865/148249936-9e510f25-8c56-46a5-b515-7d43d5a83496.png)

You may follow progress here:

https://github.com/bozhinov/pChart2.0-for-PHP7

**Comment by CptChaos** [comment]
@Sweepr Thanks for pointing that out. As I ran into issues on the commandline, I tried again on commandline obviously. But because of it, I did not see the update help. So once again, thanks for pointing that out! :)

**Comment by Sweepr** [comment]
No problem, i should have updated the bootstrap for it because i set the default for statistics prepare to "False" for now.

![afbeelding](https://user-images.githubusercontent.com/2857865/148250454-047fca9a-965b-41b5-962d-b227974b8d2b.png)

**Comment by CptChaos** [comment]
I wouldn't force it to off currently. As they are just deprecation notices, it will only clog the logging, the script itself remains functional as far as I can see.

**Comment by Sweepr** [comment]
Script runs OK, but no statistics are created and the error's as you see already caused confusion. ;-)\

Plus: the statistics page shows broken images.

But this package is beyond Spotweb so we have no power there, we must wait for the creator to update it.

**Comment by damousys** [comment]
When PHP8.1 enabled the newznabapi doesn't work
I am getting an error while opening the page

[code]
This page contains the following errors:
error on line 2 at column 1: Extra content at the end of the document
Below is a rendering of the page up to the first error.
[/code]

Only nothing below

**Comment by Sweepr** [comment]
@damousys Check out this link : https://github.com/spotweb/spotweb/issues/93#issuecomment-327285244

**Comment by damousys** [comment]
Don't no why it fixed it, but it did, thanks
