### ISSUE TITLE
Statistics generation is currently not working on PHP8.1, the package is not PHP 8.1 ready. 

### ISSUE THREAD

**Issue by Sweepr** [spotweb/spotweb#733]
Statistics is currently broken for PHP8.1, the package is not PHP 8.1 ready. 

Advise to keep the option disabled:

![afbeelding](https://user-images.githubusercontent.com/2857865/148251698-e446df4d-114c-4db3-a501-1b695290c02d.png)

See: https://github.com/spotweb/spotweb/issues/724

**Comment by mesa57** [comment]
Q: why is the pchart package not in composer ?
Further : the author created a seperate package for php 8.1, can we not use that ?

**Comment by mesa57** [comment]
Yes, but the current package is existing on packagist but not used ?

**Comment by Sweepr** [comment]
True, everyone uses the same version.

Should be added to composer, you are right.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mesa57** [comment]
That package anyway does not work with spotweb.
Also https://github.com/bozhinov/pChart2.0-for-PHP81 is not compatible.

**Comment by Sweepr** [comment]
This is the current version used:

https://github.com/spotweb/spotweb/blob/8d0bd07f4f66814eae612b542489ba6522fb6946/vendor/pchart/composer.json

**Comment by mesa57** [comment]
Also that one is not usable (any more ?) as the pImage class is missing ? Or am i wrong ? At least the includes won't work any more:

```
require __DIR__.'/../../../vendor/pchart/class/pData.class.php';
require __DIR__.'/../../../vendor/pchart/class/pDraw.class.php';
require __DIR__.'/../../../vendor/pchart/class/pImage.class.php';
require __DIR__.'/../../../vendor/pchart/class/pPie.class.php';

```

**Comment by Sweepr** [comment]
Should be working normally when using < php 8.1 and enabling the option in preferences.

![afbeelding](https://user-images.githubusercontent.com/2857865/154094995-70fa696b-e47c-42b3-b38e-082646235502.png)

**Comment by mesa57** [comment]
Yes, but the code is now different from what is in the repo mentioned in the composer.json
This is a tricky one.

**Comment by BakasuraRCE** [comment]
Hey, I made a library change by https://github.com/szymach/c-pchart that is maintained and supported in PHP versions from 5.4 to 8.1.

https://github.com/spotweb/spotweb/pull/778

I didn't know how to build the composer.lock without breaking the vendor folder.

I would like to know his thoughts about it.

**Comment by mesa57** [comment]
Still get some error during retrieve. Takes time to look into that.
I will update spotweb with that package. 
Also needed some update for postgre sql to work properly
So thanks for suggestion and I will copy you're change, but will NOT implement this specific pull request.
Closing for the moment, but still gratefull for the update.

**Comment by BakasuraRCE** [comment]
> Still get some error during retrieve. Takes time to look into that. I will update spotweb with that package. Also needed some update for postgre sql to work properly So thanks for suggestion and I will copy you're change, but will NOT implement this specific pull request. Closing for the moment, but still gratefull for the update.

Nice, let me know if you need help with some other code, problem, research

**Comment by mesa57** [comment]
Develop branch is updated for this issue now. So closing this.
@BakasuraRCE : Thanks for helping !
