### ISSUE TITLE
Empty blacklist and whitelist

### ISSUE THREAD

**Issue by Zepmann** [spotweb/spotweb#739]
**Describe the bug/issue**
The current whitelist and blacklist URLs return empty files:
http://spotcloud.spotnet.wf/spotnet/lists.new/blacklist.csv
http://spotcloud.spotnet.wf/spotnet/lists.new/whitelist.csv

Furthermore, these files should REALLY be retrieved over HTTPS by default, especially considering it is 2022 and TLS is the norm for obvious reasons. The web server seems to support it, so why not?

**Have you searched the internet or Github for an answer?**
Came upon issue #401, but nothing else so far.

**To Reproduce**
Steps to reproduce the behavior on a fresh SpotWeb installation:
1. Run retrieve.php.
2. Observe at the end:

```
Blacklist not modified, no need to update

Non-fatal: Updating black/whitelist failed, most likely unreachable!Starting to create statistics
```

Furthermore, download the noted files manually. They are 0 bytes. Invalid file names from the same path give an error.

**Expected behavior**
A proper blacklist and whitelist should be offered on the offered URLs. Furthermore, SpotWeb should use TLS by default to retrieve these files.

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
Not applicable.

**Smartphone if applicable (please complete the following information):**
Not applicable.

**Additional context**
Not applicable.

**Comment by mesa57** [comment]
Problem is known and is being worked on. 
The BL/WL is not maintained by spotweb or associates.
It is btw not possible to use TLS, that depends on the BL/WL server. Besides that: it is not relevant.

**Comment by mesa57** [comment]
Solved on develop branch. Please test.
