### ISSUE TITLE
search with keyword 'order' gives an error

### ISSUE THREAD

**Issue by JeePee1981** [spotweb/spotweb#742]
**Describe the bug/issue**
 - A clear and concise description of what the bug is.

_When using any search mechanic API or direct search with a title that contains the word 'order', you get an error message that 'this query is not allowed'._

**Have you searched the internet or Github for an answer?**
 - Please search google if similar issue has been reported and fixed before.

**To Reproduce**
_1. Go to search screen / use API call with a string that contains the word 'order'
2. See error: This query is not allowed_

**Expected behavior**
 - A clear and concise description of what you expected to happen.

_I expect to see a working search result_

**Screenshots**

**Desktop (please complete the following information):**
 - Spotweb Version [e.g. 1.4.8]
 - Which branch  (Master/Develop)
 -  PHP version
 -  Device information (ReadyNAS/Synology/FreeNAS)

**Smartphone if applicable (please complete the following information):**
 - Spotweb Version [e.g. 1.4.8]
 - Which branch  (Master/Develop)
-  PHP version
-  Device information (ReadyNAS/Synology/FreeNAS)

**Additional context**
Provide any other information about the bug or issue that can further help debugging here.

**Comment by mesa57** [comment]
Order is a reserved sql word.
See also https://github.com/spotweb/spotweb/issues/653

**Comment by Sweepr** [comment]
You could remove line 59 from https://github.com/spotweb/spotweb/blob/5d728c51a07efe78dc069671e8eeabce02ec5fa5/lib/dao/Base/Dao_Base_Spot.php#L58 locally if you want, that would make you able to search for "order" but its not recommended.
