### ISSUE TITLE
Is there a way to limit Spotweb's database size?

### ISSUE THREAD

**Issue by SuperHenkie** [spotweb/spotweb#747]
I recently installed a Spotweb instance on a hosting server where I have somewhat limited database space.

Within one or two weeks, the database grew to around 7 GB.

Is there a way to configure Spotweb to set a maximum database size? Either by discarding redundant data (if there is any) or by limiting the number of NZBs it indexes? For example by automatically discarding the oldest NZBs in the database until the given size limit is matched?

**Comment by Sweepr** [comment]
Couple things that might be usefull.

![afbeelding](https://user-images.githubusercontent.com/2857865/154581097-5
d6e53b2-9a25-42d8-9a93-c7357e6efd8a.png)

![afbeelding](https://user-images.githubusercontent.com/2857865/154581133-c05a9e86-b703-4dc1-8c56-510a3774959b.png)

![afbeelding](https://user-images.githubusercontent.com/2857865/154581346-86782a25-0aa6-483f-80b6-d86591d1d40c.png)


All found in Config -> Settings - Retrieve tab.

**Comment by mesa57** [comment]
About 3/4 of the database is filled with comments. So if you don't need them, dont retrieve them. Reports can also be left out.

**Comment by mesa57** [comment]
Change all of these:

![afbeelding](https://user-images.githubusercontent.com/6350469/154685967-6f98a7d6-7903-4c75-8d76-9fe40103d040.png)

**Comment by SuperHenkie** [comment]
Thanks a lot, much appreciated!
