### ISSUE TITLE
error: failed to symlink 'vendor/bin/phpunit': File name too long

### ISSUE THREAD

**Issue by Fossil01** [spotweb/spotweb#749]
Getting merge conflicts which I am unable to neatly resolve:

`error: failed to symlink 'vendor/bin/phpunit': File name too long`

**Comment by Fossil01** [comment]
Happens on both Linux and MacOS.

**Comment by Sweepr** [comment]
@mesa57 

https://stackoverflow.com/questions/18411200/git-unable-to-create-symlink-file-name-too-long

Does this have any correlation with the /vendor/bin/phpunit symlink issue that we have now?

**Comment by Fossil01** [comment]
`git config core.symlinks false` "fixes" the issue for now.

**Comment by mesa57** [comment]
I supposes so.
I see only one solution:
 
1)      Get rid of phpunit by using the composer -no-dev option (cleans up
vendor folder any way)
2)      Get rid of references to phpunit commands in scrutinizer.yml
3)      Using composer V2 the proper way (not by installing it, scrutinizer
is already updated, see docs)
 
Agree ?
Grtz.  Jan

**Comment by Sweepr** [comment]
Agreed.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mesa57** [comment]
Roel,
 
I did a run on my own repo with -no-dev and only this error came up:
 

 
CU, Jan

**Comment by hlugt** [comment]
Is this now fixed then? I get the idea that the composer.json still says --required-dev, and using the current in a docker build for linux leads to the same mentioned error? (Admit: not tried with own/changed fork yet)

**Comment by hlugt** [comment]
Hi, was this issue fixed? 
A git clone still breaks vendor/bin/phpunit file on my linux environment, so I can not use it directly without modifications. Which should be possible, not?

**Comment by mesa57** [comment]
Apperently not fixed then.

**Comment by hlugt** [comment]
Check...
Pity though.
