### ISSUE TITLE
install.php should set admin password

### ISSUE THREAD

**Issue by beta990** [spotweb/spotweb#75]
Leaving the password of the Administrator account to the default 'install' isn't a really good idea.
Not everyone reads the FAQ.

My suggestion would be updating the admin password with the newly created user account (password) at install.

**Comment by Sweepr** [comment]
Why? this is fine as it is.

# Change the administrators' account password to that of this created user

			$adminUser = $svcUserRecord->getUser(SPOTWEB_ADMIN_USERID);
			$adminUser['newpassword1'] = $spotUser['newpassword1'];
			$svcUserRecord->setUserPassword($adminUser);

**Comment by beta990** [comment]
Sorry, but don't understand you post. The default will be 'install'.

**Comment by Sweepr** [comment]
No, upon install you are asked to create a new user, you have to set the username and a password for it, now this new user password will automatically be the password set for the admin account aswell.

If you fail to miss that you need glasses.

**Comment by beta990** [comment]
Oh! Sorry, thought this would still be 'admin' since it was stated in the FAQ. :)

**Comment by Sweepr** [comment]
No problem,.  i corrected the FAQ by removing this part since it is outdated.

Thank you for bringing this to our attention!
