### ISSUE TITLE
PHP Deprecated:  explode(): Passing null to parameter #2 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by Fossil01** [spotweb/spotweb#750]
`2022/02/18 15:50:20 [error] 38710#38710: *323106370 FastCGI sent in stderr: "PHP message: PHP Deprecated:  explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/spotweb/lib/page/SpotPage_newznabapi.php on line 470PHP message: PHP Deprecated:  explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/spotweb/lib/page/SpotPage_newznabapi.php on line 470PHP message: PHP Deprecated:  explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/spotweb/lib/page/SpotPage_newznabapi.php on line 470"`

**Request:**
`/api?apikey=removed&t=tvsearch&extended=1&tvdbid=92411&season=6&ep=9&maxage=5000&password=1&cat=5000&limit=1000&offset=0`

**Comment by mesa57** [comment]
You should at least specify which version of php you are using.

**Comment by mesa57** [comment]
Solved on develop branch

**Comment by mesa57** [comment]
Tested with php 8.1 and
`&t=tvsearch&extended=1&tvdbid=92411&season=6&ep=9&maxage=5000&password=1&cat=5000&limit=1000&offset=0&q=somesearchtermhere`
No problem whatsoever.
