### ISSUE TITLE
SpotWeb v0.68.34.34 on PHP v8.1.1 crashed 42000: 1064: syntax error, unexpected $end 

### ISSUE THREAD

**Issue by Fossil01** [spotweb/spotweb#753]
`SpotWeb v0.68.34.34 on PHP v8.1.1 crashed 42000: 1064: syntax error, unexpected $end `

Also finding these in nginx error logs:

`PHP message: SpotWeb Exception occured: 42000: 1064: syntax error, unexpected '+'" while reading response header from upstream,`

Both don't specify which file.

**Comment by Fossil01** [comment]
Ah the first one looks to be happening when you perform a tvsearch without `&season=` or `&ep=`

Sonarr does those requests if you accidentally enable "RSS Search"

**Comment by mesa57** [comment]
Works fine here without season or ep parameter.
Please try to extract the exact query.

**Comment by Fossil01** [comment]
`/api?t=tvsearch&q=Suits&apikey=<API_KEY>` results in the error on PHP 8.1.1

**Comment by mesa57** [comment]
Sorry, then I must close this issue as not reproducable (php 8.1.0 under IISExpress)

**Comment by Fossil01** [comment]
Holy crap, IISExpress?  I guess PHP behaves differently under Linux.

**Comment by mesa57** [comment]
Not that I ever experienced.
