### ISSUE TITLE
Doesent update over port 80

### ISSUE THREAD

**Issue by ClubNZB** [spotweb/spotweb#754]
**Describe the bug/issue**
 - Spotweb doesent update since 22 hours.
 Account is still working and open (tested)

**Have you searched the internet or Github for an answer?**
 - No Answer

**To Reproduce**
login as admin, update now button.
1 into 2 seconds all update (no new files visible)
Second time updating more than 2 hrs

Always working, now second usenet account but same result

**Comment by Sweepr** [comment]
1. There is still a retriever running.
2. Switching usenet providers on an existings account doesn't work.
3. Maybe the providers renumbered their article count.

Either way i suggest: https://github.com/spotweb/spotweb/wiki/Spotweb-reset-database-or-clear-local-cache

You will be able to reset the DB, using the command

php upgrade-db.php --reset-db , and confirm with yes.

This will reset the following table's: spots, spotsfull, spotsposted, spotstatelist, commentsfull, commentsposted, commentsxover, moderatedringbuffer, reportsposted, reportsxover, usenetstate, cache

Table's: users, usergroups, usersettings, sessions, settings, grouppermissions, security groups and filters are left intact.

**Comment by ClubNZB** [comment]
for option 3: I don`t have ssh/root access :-(
Clean database after new install.php same error.

**Comment by Sweepr** [comment]
Consider solved, reopen if needed.

**Comment by Sweepr** [comment]
Please post the exact error?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
