### ISSUE TITLE
Remove erotica

### ISSUE THREAD

**Issue by onknows** [spotweb/spotweb#757]
**Is your feature request related to a problem? Please describe.**
I tried to remove all erotica posts by removing erotica filter but I still see erotica type posts.

**Describe the solution you'd like**
I really don't want these type of posts so I would really would like to be able to configure spotweb not to fetch and show these posts. 

**Describe alternatives you've considered**

**Additional context**

**Comment by Sweepr** [comment]
There is an option under "preferences named" -> "general" -> "Hide erotic spots in index?"

To remove any retrieved erotica look here: https://github.com/spotweb/spotweb/wiki/Handy-SQL-Query's#remove-pr0n

**Comment by onknows** [comment]
Thanks!
