### ISSUE TITLE
Errors when retrieving spots should end with $retriever->quit();

### ISSUE THREAD

**Issue by beta990** [spotweb/spotweb#76]
Since crashes/issues can occur when retrieving spots, it should close the Retriever when it happens (e.g. on NntpException/Exception).

At the moment I've added the following string to retrieve.php, but there may be nicer/cleaner solutions for this:
catch(NntpException $x) {
        $retriever->quit(); // close retriever
}
..
catch(Exception $x) {
        $retriever->quit();
}

The reason why is very simple: when running retrieve.php as cron it doesn't start again because 'it' still thinks it's receiving spots, but actually a crash occurred.

A better solution would be an option to stop the retriever as a crash occurs (e.g. --quit-on-crash/exception), instead of simple forcing it to quit.

**Comment by Sweepr** [comment]
It already does actually,  but it take's some time, eventually the process if crashed will time-out and die after that will be able to start again,.

**Comment by beta990** [comment]
But it takes too much time, it should quit the retriever. This also stops the process still being active.

**Comment by Sweepr** [comment]
Yes, i understand. i will test this..

If it works i'll add this to the branch.

**Comment by Sweepr** [comment]
See:

**Comment by Sweepr** [comment]
Nice work and thanks for the effort.

**Comment by beta990** [comment]
Thanks for adding it to the master branch! :)
