### ISSUE TITLE
Deprecated Function in PHP 8.1 strftime()

### ISSUE THREAD

**Issue by Radar5k** [spotweb/spotweb#761]
High there,

Got a few pages full of...

"Deprecated: Function strftime() is deprecated in /var/www/spotweb/lib/SpotTemplateHelper on line 1058" (it is also called at line 1068).

...after upgrading Ubuntu 20.04 to 22.04.

I couldn't find how to get Apache2 to use PHP7.4, and saw that updates were made to Spotweb to support PHP8.1.

Tried git pull, but got the same result.

Deleted everything in the Spotweb directory, and did a new install using "git clone master", and ran install.php, and got the same result again.

 - OS: Ubuntu 22.04 
 - Browser: Firefox 
 - Spotweb Version: Unable to find it. (Cloned 23:39 UTC June 7th, 2022, if that helps).
 - Branch: Master
 -  PHP version: 8.1
 - Device: QNAP TS-659 Pro+
 - CPU: Intel Atom 1.8GHz
 - Memory: 2GB
 
**Smartphone if applicable (please complete the following information):**
 - Device: Samsung Galaxy Tab A (SM-T290)
 - OS: Android v11
 - Browser: Firefox 
 - Spotweb Version: See Above 
 - Branch: Master 
-  PHP Version: 8.1
-  Device: See Above

After typing all ^^^ that, I tried replacing  strftime() with date(), and now it works nicely.

I left the problem description up there in case anyone else has the same issue.

I just found and replaced another strftime entry in spotweb/templates/we1rd.

**Comment by mesa57** [comment]
Ok, closing.
