### ISSUE TITLE
Failed loading XML:  Non-fatal: Updating black/whitelist failed, most likely unreachable!

### ISSUE THREAD

**Issue by johnrosen1** [spotweb/spotweb#764]
**Describe the bug/issue**
 - A clear and concise description of what the bug is.

```
Failed loading XML: 
Non-fatal: Updating black/whitelist failed, most likely unreachable!
```

**Have you searched the internet or Github for an answer?**
 - Please search google if similar issue has been reported and fixed before.

**To Reproduce**

php retrieve.php

**Expected behavior**
 - A clear and concise description of what you expected to happen.

**Screenshots**

![image](https://user-images.githubusercontent.com/48143913/186591339-fb86231e-9c4c-4785-b33f-fe97b1729f6a.png)

**Desktop (please complete the following information):**
 - Spotweb Version [e.g. 1.4.8]
 - Which branch  (Master/Develop)
 -  PHP version
 -  Device information (ReadyNAS/Synology/FreeNAS)

Debian11

Latest commit (develop)

php 8.1.9

**Smartphone if applicable (please complete the following information):**
 - Spotweb Version [e.g. 1.4.8]
 - Which branch  (Master/Develop)
-  PHP version
-  Device information (ReadyNAS/Synology/FreeNAS)

**Additional context**
Provide any other information about the bug or issue that can further help debugging here.

**Comment by Sweepr** [comment]
Try PHP 8.0.

**Comment by johnrosen1** [comment]
@Sweepr still not working

**Comment by johnrosen1** [comment]
![image](https://user-images.githubusercontent.com/48143913/186593797-3696424c-f339-43a1-a40d-8ed5cde34cf5.png)

**Comment by johnrosen1** [comment]
composer.json file

```
{
  "name": "spotweb/spotweb",
  "description": "A decentralized usenet community based on the Spotnet protocol.",
  "type": "project",
  "license": "MIT",
  "require": {
    "mobiledetect/mobiledetectlib": "^2.5.2",
    "phpseclib/phpseclib": "^2.0.2",
    "abraham/twitteroauth": "^0.2.0",
    "xenji/prowlphp": "^1.0.0",
    "ext-mbstring": "*",
    "php": ">=5.3.0",
    "monolog/monolog": "^1.23.0",
    "laminas/laminas-xml2json": "^3.0",
    "spotweb/nntp": "1.0.*",
    "squizlabs/php_codesniffer": ">=2.6.0",
    "phpcompatibility/php-compatibility": "*",
    "php-coveralls/php-coveralls": ">=2.0",
    "phpmailer/phpmailer": "^6.1",
    "symfony/polyfill-mbstring": "^1.15",
    "imdbphp/imdbphp": "^7.2",
    "spotweb/fts_parser": "^1.0"
  },
  "require-dev": {
    "phpunit/phpunit": "^9.5.23"
  },
  "autoload": {
    "classmap": [
      "lib/",
      "templates/"
    ]
  }
}
```

**Comment by johnrosen1** [comment]
dbsettings.inc.php file

```
<?php

$dbsettings['engine'] = 'pdo_mysql';
$dbsettings['host'] = 'localhost';
$dbsettings['dbname'] = 'spotweb';
$dbsettings['user'] = 'spotweb';
$dbsettings['pass'] = 'spotweb';
$dbsettings['port'] = '3306';
$dbsettings['schema'] = '';
```

**Comment by Sweepr** [comment]
Not sure which branch you are using but you could try upgrading or install a temporary 2nd instance of Spotweb 1.5.1 (latest Develop branch) as i see you are using 1.4.8..

There have been many fixes since that time that support PHP 8, although PHP 8.1 and higher hasn't been fully tested we cannot guarantee it will work on PHP 8.1.9 for 100%

**Comment by Sweepr** [comment]
Those composer.json and dbsettings file are not relevant to the issue, i have removed them.

**Comment by johnrosen1** [comment]
ok then

**Comment by johnrosen1** [comment]
@Sweepr 

redownload 1.5.1

reinstall

php8.0

still not working 

![image](https://user-images.githubusercontent.com/48143913/186601062-bc81fff0-2a6c-4837-85e8-4e4b4924e3e4.png)

![image](https://user-images.githubusercontent.com/48143913/186601097-94261aaf-5b57-4fec-9e9b-1afe8014f88f.png)

![image](https://user-images.githubusercontent.com/48143913/186601206-5bad68e9-aefd-4866-85e1-496bbed3414e.png)

![image](https://user-images.githubusercontent.com/48143913/186601249-58e2b7cf-3e2e-4895-a4cf-d25bbda69b39.png)

**Comment by Sweepr** [comment]
Funny, here it's working fine:

![image](https://user-images.githubusercontent.com/2857865/186606436-9b47a9a9-40db-4fe2-a0cf-4ce08a297f3e.png)

On the console, what is the output of: 

 `curl http://bit.do/sp4white`
 `curl http://bit.do/sp4black`

And 

`http://spotlist.tk/spotnet/whitelist.xml`
`http://spotlist.tk/spotnet/blacklist.xml`

Try changing these:

![image](https://user-images.githubusercontent.com/2857865/186605470-afef4194-59dd-47b9-b821-9c73f0c0dbd0.png)

Into: 

http://spotlist.tk/spotnet/whitelist.xml

http://spotlist.tk/spotnet/blacklist.xml

Does that help?

**Comment by johnrosen1** [comment]
@Sweepr 

![image](https://user-images.githubusercontent.com/48143913/186607604-0390b6d8-ac3b-4cd5-82e2-5e69e09ed547.png)

**Comment by johnrosen1** [comment]
![image](https://user-images.githubusercontent.com/48143913/186607716-76433db6-a411-44d5-943b-e24a4f7d7fde.png)

maybe network issue

**Comment by johnrosen1** [comment]
![image](https://user-images.githubusercontent.com/48143913/186608759-1fb2fcfc-e4f9-4c22-b9d0-36a9b6e43f0a.png)

disable xml list seems to be ok , but what these files are used for anyway ?

**Comment by johnrosen1** [comment]
![image](https://user-images.githubusercontent.com/48143913/186609103-cbe2c6fa-b4fb-4668-86b3-10222826566f.png)

seems they use cloudflare , maybe because ip or firewall block ?

**Comment by johnrosen1** [comment]
i wiil try to download the list to local system and try again.

**Comment by johnrosen1** [comment]
![image](https://user-images.githubusercontent.com/48143913/186610719-6bf1773f-3085-4942-82b4-39726408c190.png)

still not working ...

**Comment by johnrosen1** [comment]
![image](https://user-images.githubusercontent.com/48143913/186610860-3bf2f7dd-bd9c-4f2d-882f-8ae77edcb07b.png)

any idea ?

**Comment by Sweepr** [comment]
> ![image](https://user-images.githubusercontent.com/48143913/186610719-6bf1773f-3085-4942-82b4-39726408c190.png)
> 
> still not working ...

Why are you adding a port there?

**Comment by johnrosen1** [comment]
ok then , let me try

**Comment by Sweepr** [comment]
> ![image](https://user-images.githubusercontent.com/48143913/186608759-1fb2fcfc-e4f9-4c22-b9d0-36a9b6e43f0a.png)
> 
> disable xml list seems to be ok , but what these files are used for anyway ?

Files are used to whitelist and blacklist certain posters that in the past have posted fake spots, or viruses stuff like that.

**Comment by johnrosen1** [comment]
![image](https://user-images.githubusercontent.com/48143913/186612334-887c1935-cf27-408a-b498-70fe900f3c23.png)

no luck , lol

**Comment by johnrosen1** [comment]
can i manually import ?

**Comment by Sweepr** [comment]
Let me understand you setup first, are you running this on your local PC or a NAS of remote server?

**Comment by johnrosen1** [comment]
debian server x86

![image](https://user-images.githubusercontent.com/48143913/186613151-d6babf44-43fd-4fda-8b3b-86485ae2d32f.png)

**Comment by Sweepr** [comment]
On your local network?

**Comment by johnrosen1** [comment]
yes

**Comment by johnrosen1** [comment]
https://337hhh.xyz:8444/

instance url

**Comment by Sweepr** [comment]
I am not able to reproduce this using my setup, both URLs are working fine, 

`http://bit.do/sp4white` is a redirect to `http://spotlist.tk/spotnet/whitelist.xml`
`http://bit.do/sp4black` is a redirect to `http://spotlist.tk/spotnet/blacklist.xml`

If you place the files on your server, can you reach them using your browser?
There must be something wrong with the setup on your server.

**Comment by johnrosen1** [comment]
@Sweepr 

https://337hhh.xyz:8444/whitelist.xml

it works.

**Comment by johnrosen1** [comment]
not sure why php returns error

**Comment by Sweepr** [comment]
> @Sweepr
> 
> https://337hhh.xyz:8444/whitelist.xml
> 
> it works.

Ok, then if you place this URL into the settings it must work too..

https://337hhh.xyz:8444/whitelist.xml

https://337hhh.xyz:8444/blacklist.xml

![image](https://user-images.githubusercontent.com/2857865/186615130-ddb6fbb8-dbe1-4624-b8d0-04445bc5276a.png)

Using your files, on your server:

![image](https://user-images.githubusercontent.com/2857865/186615188-029548b7-4c01-482e-8de8-d767e4f4e4a7.png)

**Comment by johnrosen1** [comment]
let me try then

**Comment by Sweepr** [comment]
> not sure why php returns error

Which error?

**Comment by johnrosen1** [comment]
![image](https://user-images.githubusercontent.com/48143913/186617495-6f8ac5fc-a735-48f6-9129-a293cd1d3f78.png)

how can i write address into php file ?

maybe that will solve the problem

**Comment by johnrosen1** [comment]
![image](https://user-images.githubusercontent.com/48143913/186618317-c559c281-f445-4845-af92-efc0e9f0712f.png)

![image](https://user-images.githubusercontent.com/48143913/186618401-5585ec9c-1da5-4854-a938-214a79fe520e.png)

curl works

**Comment by Sweepr** [comment]
Try this and post the result here:
```

try {
        //# External blacklist
        if ($settings->get('external_blacklist')) {
            $svcBwListRetriever = new Services_BWList_Retriever($daoFactory->getBlackWhiteListDao(), $daoFactory->getCacheDao());
            $bwResult = $svcBwListRetriever->retrieveBlackList($settings->get('blacklist_url'));
			var_dump($settings->get('blacklist_url'));
			var_dump($bwResult);
            if ($bwResult === false) {
                echo 'Blacklist not modified, no need to update'.PHP_EOL;
            } else {
                echo 'Finished updating blacklist. Added '.$bwResult['added'].', removed '.$bwResult['removed'].', skipped '.$bwResult['skipped'].' of '.$bwResult['total'].' lines.'.PHP_EOL;
            } // else
        } // if

        //# External whitelist
        if ($settings->get('external_whitelist')) {
            $bwResult = $svcBwListRetriever->retrieveWhiteList($settings->get('whitelist_url'));
			var_dump($settings->get('whitelist_url'));
			var_dump($bwResult);
            if ($bwResult === false) {
                echo 'Whitelist not modified, no need to update'.PHP_EOL;
            } else {
                echo 'Finished updating whitelist. Added '.$bwResult['added'].', removed '.$bwResult['removed'].', skipped '.$bwResult['skipped'].' of '.$bwResult['total'].' lines.'.PHP_EOL;
            } // else
        } // if
    } catch (CorruptBWListException $e) {
        echo PHP_EOL.'Non-fatal: Updating black/whitelist failed, most likely unreachable!';
    }
```

**Comment by johnrosen1** [comment]
ok

**Comment by johnrosen1** [comment]
![image](https://user-images.githubusercontent.com/48143913/186620880-4cb8be43-4efa-4fd0-ab18-bd41551b4b0c.png)

**Comment by Sweepr** [comment]
Ok, so `$bwResult = $svcBwListRetriever->retrieveWhiteList($settings->get('whitelist_url'));` returns `false` 

Earlier it caused an exception:
```

} catch (CorruptBWListException $e) {
        echo PHP_EOL.'Non-fatal: Updating black/whitelist failed, most likely unreachable!';
    }
```

Question is, why is `$bwResult` returning `false `in your case.

**Comment by johnrosen1** [comment]
https://github.com/spotweb/spotweb/blob/develop/lib/services/BWList/Services_BWList_Retriever.php

no idea

**Comment by Sweepr** [comment]
In your database "spotteridblacklist" does it contain any data?
If so, can you "empty" the table?  and retrieve again, check if it imports anything?

It is possible to import the XML files into the table using phpmyadmin, but it will be a patch for the problem.

**Comment by johnrosen1** [comment]
ok

**Comment by johnrosen1** [comment]
![image](https://user-images.githubusercontent.com/48143913/186624982-392f3e01-10db-4307-b68c-32792b639f7a.png)

**Comment by Sweepr** [comment]
Ok, so i emptied mine:

And ran the retrieve.php and as you can see it imports the files without a problem.

![image](https://user-images.githubusercontent.com/2857865/186625350-c99f5f8c-bb05-4b01-9051-e6059c8f1790.png)

**Comment by johnrosen1** [comment]
yeah

**Comment by mesa57** [comment]
Cache ?

**Comment by johnrosen1** [comment]
what cache ?

**Comment by mesa57** [comment]
Spotweb cache

**Comment by johnrosen1** [comment]
how to clear?

**Comment by mesa57** [comment]
@Sweepr I dont remember the command ?

**Comment by Sweepr** [comment]
php bin/upgrade-db.php --clear-cache

**Comment by johnrosen1** [comment]
ok

**Comment by johnrosen1** [comment]
![image](https://user-images.githubusercontent.com/48143913/186626347-aebf154d-b261-4c83-90f1-76a083b41d9b.png)

**Comment by johnrosen1** [comment]
![image](https://user-images.githubusercontent.com/48143913/186626505-1f82e5c4-2d92-4219-8517-6429224ad610.png)

not working

**Comment by mesa57** [comment]
At least you got back the error ;)

**Comment by johnrosen1** [comment]
![image](https://user-images.githubusercontent.com/48143913/186626703-69119fa9-00de-4376-b433-3740e96a0a3a.png)

php file is still the same

**Comment by johnrosen1** [comment]
i will try later

**Comment by Sweepr** [comment]
Check if simplexml_load_string is working.

**Comment by johnrosen1** [comment]
![image](https://user-images.githubusercontent.com/48143913/186639046-45a1511c-c78d-48e9-87da-360ed2fefd70.png)

**Comment by Sweepr** [comment]
> ![image](https://user-images.githubusercontent.com/48143913/186639046-45a1511c-c78d-48e9-87da-360ed2fefd70.png)

Haha, [that ](https://github.com/spotweb/spotweb/issues/764#issuecomment-1227004741)was a snippet with a pointing to where the error originates from, it's not an updated code with an intend to try it.

**Comment by Sweepr** [comment]
I can only reproduce this if i intentionally fill in a wrong or non-existing URL for the black and white list:

![image](https://user-images.githubusercontent.com/2857865/186640269-f7bf8512-b772-4a2a-ae31-7a9e2674ba6a.png)

Note the extra: **`Failed loading XML:`** error, which inb your case i do not see.
Juat the: **`Non-fatal: Updating black/whitelist failed, most likely unreachable!`**

**Comment by johnrosen1** [comment]
@Sweepr it seems that the url does not support https

![image](https://user-images.githubusercontent.com/48143913/186641278-103fc94c-4613-4025-a0d8-58b46a0bddd4.png)

change url to http solves the problem

**Comment by johnrosen1** [comment]
it would be best if we can have https though

**Comment by johnrosen1** [comment]
it can not be to hard to implement , so please implement https , thx

**Comment by mesa57** [comment]
Sorry, https will not be supported.

**Comment by Sweepr** [comment]
Both works with https and http, it's Nginx..

**Comment by Sweepr** [comment]
@johnrosen1 

![image](https://user-images.githubusercontent.com/2857865/186644924-f0f7d484-87fe-427d-9ebd-f7ca7c6f129c.png)

![image](https://user-images.githubusercontent.com/2857865/186645072-4f017b81-fbd3-44b6-ad45-78af65aa8900.png)

The problem lies within your server..

**Comment by mesa57** [comment]
You can go to bit.do with https, but it redirects to http

**Comment by Sweepr** [comment]
![image](https://user-images.githubusercontent.com/2857865/186706533-885874b6-db08-4cda-bd72-95a2e4d73b14.png)


> You can go to bit.do with https, but it redirects to http

True, but going directly to https://spotlist.tk/spotnet/whitelist.xml or https://spotlist.tk/spotnet/blacklist.xml does not redirect, stay's with https

![image](https://user-images.githubusercontent.com/2857865/186706533-885874b6-db08-4cda-bd72-95a2e4d73b14.png)
