### ISSUE TITLE
grab information from imdb for posting

### ISSUE THREAD

**Issue by mohitjoshi155** [spotweb/spotweb#766]
**Is your feature request related to a problem? Please describe.**
right now for posting everything like image ,description etc needs to be provided by the poster

**Describe the solution you'd like**
a solution where poster just needs to provide imdb id or link and everything is fetched from imdb like description picture etc so poster does not have to do it manually

**Comment by mesa57** [comment]
Sorry but spotweb posts are 99% in dutch language which is not supported by IMDB.
Furthermore IMDB has no api to get the information you requested.

**Comment by mohitjoshi155** [comment]
> Sorry but spotweb posts are 99% in dutch language which is not supported by IMDB. Furthermore IMDB has no api to get the information you requested.

ok

another issue i faced was there seems to be a word limit for title...can anything be done to increase it because some times release names are long and full name does not fit in title

**Comment by mesa57** [comment]
Also this one we have to deny. 
The spotnet protocol, on which spotnet is based, does not permit longer titles.
Spotweb is not the only client, there are multiple implementations not maintained by us.
