### ISSUE TITLE
Password not saved into NZB file

### ISSUE THREAD

**Issue by Devisius** [spotweb/spotweb#767]
In the header the password option is missing.
Like in this header it is included;

?xml version="1.0" encoding="iso-8859-1" ?
!DOCTYPE nzb PUBLIC "-//newzBin//DTD NZB 1.0//EN" "http://www.nzbindex.com/nzb-1.0.dtd"
!-- NZB Generated by NZBIndex --
nzb xmlns="http://www.newzbin.com/DTD/2003/nzb"
head>
meta type="password">7V89UMLEUK</meta

**Comment by Devisius** [comment]
meta type="password">7V89UMLEUK</meta>

**Comment by Sweepr** [comment]
Please create a new issue and use the form, the information provided is not sufficient enough to debug this issue.

https://github.com/spotweb/spotweb/issues/new?assignees=&labels=&template=bug-issue-report.md&title=%5BNew+issue%5D
