### ISSUE TITLE
PHP 8+ issue: GD image support has been disabled

### ISSUE THREAD

**Issue by GeoffreyDijkstra** [spotweb/spotweb#768]
Hi there, just upgrade to ubuntu 22 and PHP 8.1 and retrieve.php sometimes now spams these errors once in a while:

PHP Warning:  imagecreatefromgd(): GD image support has been disabled
 in lib/services/Image/Services_Image_BmpConverter.php on line 33
PHP Warning:  imagecreatefromgd(): "/tmp/SpotWeb_03ZJhi" is not a valid GD file in lib/services/Image/Services_Image_BmpConverter.php on line 33
PHP Deprecated:  Implicit conversion from float 167.5 to int loses precision in lib/services/Image/Services_Image_Error.php on line 31
PHP Deprecated:  Implicit conversion from float 161.5 to int loses precision in lib/services/Image/Services_Image_Error.php on line 51

I also noticed that I seem to have broken images for latest retrieved spots, so I started to dig around a bit:
1. According to the docs the method imagecreatefromgd is considered obsolete, see https://www.php.net/manual/en/function.imagecreatefromgd.php so I guess this needs to get replaced, just no clue yet with what.
2. All phpgd methods like imagejpeg return a GdImage class since php 8.0.0 I noticed for example in Services_Image_BmpConverter it still only checks is_resource which will return false because it's an object and not a resource anymore since php 8. I also saw this somewhere else but forgot where.

So just a heads up, I will see if I got time this week to dive a bit further into this.

**Comment by CptChaos** [comment]
It most of the times means that you don't have the correct module installed on your system. Make sure you either enabled it on Windows, or install the correct package on Linux.

**Comment by GeoffreyDijkstra** [comment]
@CptChaos haha normally I do that, didn't notice, updated.

However, you say install correct module, if the module was missing you would have had an exception saying that a module was missing, instead I get deprecated warnings. Also the module in question "php8.1-gd" is installed.

**Comment by mesa57** [comment]
/tmp/SpotWeb_03ZJhi what is that for strange image extension ?

**Comment by mesa57** [comment]
No answer. I am closing this issue. Please feel free to reopen if necessary.
