### ISSUE TITLE
Issue on db update

### ISSUE THREAD

**Issue by Razwer** [spotweb/spotweb#77]
After a few months running old spotweb i figured i'd update by getting a fresh clone.
This forced the dbupdate to be run and threw me an error:
php upgrade-db.php
Updating schema..(pdo_mysql)
        Validating spots(messageid)
        Validating spots(poster)
        Validating spots(title)
                Modifying column title (type) on spots

SpotWeb crashed

Database schema or settings upgrade failed:
   01000: 1265: Data truncated for column 'title' at row 2762

I checked the DB and the spotweb.spots.name table was varchar(250) while all other tables are varchar(128). The db-update script seems to decrease to varchar(128) which throws this error as some data exceeds varchar(128)

I fixed it by running: UPDATE spotweb.spots SET title=SUBSTRING(title, 1, 128);

This should be verified/fixed in the update script.

**Comment by Sweepr** [comment]
Could you tell me the version you ran prior upgrade?

Also monitor for any issues you experience which you did not have before?

Keep in mind that there might be a valid reason for the change.

**Comment by Sweepr** [comment]
A quick scan trough the change history of SpotStruct_abs.php did not show any changes, i'll re-check this later today.

Do you still have the old source code?

If so could you look for a line like below in /lib/dbstruct/SpotStruct_abs.php?

If what you are saying is correct then your file should have:

$this->validateColumn('title', 'spots', 'VARCHAR(250)', NULL, false, 'utf8');

If not then the code did not change and something else messed up the DB.

**Comment by Sweepr** [comment]
Found a difference between the Mediainfo branch and Master branch, https://github.com/spotweb/spotweb/commit/f90b9d7d317dd9ab4f544ebbb631a68ac8e3e835

Master branch contains:
-		$this->validateColumn('title', 'spotsposted', 'VARCHAR(128)', NULL, false, 'utf8');
Mediainfo branch contains:
+		$this->validateColumn('title', 'spotsposted', 'VARCHAR(250)', NULL, false, 'utf8');

**Comment by Razwer** [comment]
I've overwritten the old source and didn't make a backup (yes i know, shoot me :) )
I did however make a dump of the DB prior to upgrading.
Tonight (or when i have time/ i'm currently working) i will try and scoop through it to find the version I was running.

Note that I've used "out of the box" functionality only, thus the entries in the db and the table size were "caused" by earlier code.

**Comment by Razwer** [comment]
interesting as I'm sure i was using the master branch and not mediainfo.

**Comment by Sweepr** [comment]
This isn't casuing any major issue, don't see a reason now to fix this.
