### ISSUE TITLE
Exception thrown upon retrieving spots

### ISSUE THREAD

**Issue by CptChaos** [spotweb/spotweb#771]
**Describe the bug/issue**
 - Upon retrieving spots (on latest commit in the `develop` branch) I get an error

**Have you searched the internet or Github for an answer?**
 - Yes

**To Reproduce**
1. Checkout `develop` branch
2. Run `retrieve.php` from commandline
3. See Exception being thrown

**Expected behavior**
 - Spots being retrieved succesfully

**Screenshots**
I have an error message I received:
`PHP Fatal error:  Type of CustomException::$file must be string (as in class Exception) in /var/www/spotweb/lib/exceptions/CustomException.php on line 27`

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Debian (Testing)
 - Browser [e.g. chrome, safari] Firefox
 - Spotweb Version [e.g. 1.4.8] Latest `develop` commit
 - Which branch  (Master/Develop)  `develop`
 -  PHP version `8.1.12`
 -  Device information (ReadyNAS/Synology/FreeNAS) VMWare VM.

**Additional context**
I have an error message I received:
`PHP Fatal error:  Type of CustomException::$file must be string (as in class Exception) in /var/www/spotweb/lib/exceptions/CustomException.php on line 27`

**Comment by CptChaos** [comment]
Unfortunately I don't have much more info than this. This error pops up immediately after pressing `enter` when I try to do `php retrieve.php` manually from commandline.

**Comment by mesa57** [comment]
If possible try a lower php version. I don't think we've tested with php 8.1.12

**Comment by CptChaos** [comment]
@mesa57 Unfortunately, I can't downgrade to a lower version, it's not available anymore in Debian Testing.

**Comment by mesa57** [comment]
A kind of stack trace would be helpfull.

**Comment by Sweepr** [comment]
In PHP 8.1 type declaration must be specified, so $file should be declared as string.

Downside, it's not backward compatible with older PHP version so it considerd a breaking change, older versions are not strict.

**Comment by mesa57** [comment]
Retrieve run's fine here under oho 8.1.0
Is suppose the error is triggered by something else. Without knowing what it is impossible to determine a fix.

**Comment by CptChaos** [comment]
@mesa57 If there's anything I can do to get a larger stacktrace (as this sentence is the only output I got from running retrieve from CLI), I am more than happy to help.

**Comment by mesa57** [comment]
Please try to change line 5 of lib/exceptions/CustomException.php into this and tell us the result

`set_error_handler(function (int $err_severity, string $err_msg, string $err_file, int $err_line) {
`

**Comment by CptChaos** [comment]
For what it's worth, I also get the error when I run `php bin/upgrade-db.php` from command line.

**Comment by mesa57** [comment]
Ok, you've got the file from the master (not php 8.1 compatible) branch en not from the develop branch.
Please clean and clone the develop branch.

**Comment by CptChaos** [comment]
Thanks for the help! To be sure I was on the actual `develop` branch I removed the `spotweb` folder and cloned the repository directly to the develop branch. Re-tested it and it worked right away! :) It's working again for me, without any errors now too! Thanks for all the help! I am closing this issue!
