### ISSUE TITLE
My Spots crashing

### ISSUE THREAD

**Issue by xpunkt** [spotweb/spotweb#774]
SpotWeb v0.68.34.34 on PHP v7.4.33 crashed 42P01: 7: ERROR: missing FROM-clause entry for table "spotx" LINE 44: ORDER BY spotx.stamp DESC, x.rev... ^

postgresql, php code from github, if more info is needed i can provide it on request

**Comment by mesa57** [comment]
Please specify which action you are performing.
If you can switch to mariadb/mysql I am sure it will work.

**Comment by xpunkt** [comment]
used Quick link "My spots"

**Comment by mesa57** [comment]
Please check out the Develop branch to test if the issue is solved.

**Comment by xpunkt** [comment]
resolved thanks

**Comment by mesa57** [comment]
Thanks for testing.
