### ISSUE TITLE
Fresh installation not retrieving old posts

### ISSUE THREAD

**Issue by suheyl** [spotweb/spotweb#776]
**Describe the bug/issue**
 - I did a fresh installation this week of my system (Ubuntu 22.04). Then I installed spotweb, and start retrieving. I had the retention period set to 1600 days. After retrieving, I only saw spots for the last day. This morning, this was still the same. Then I dropped the database and recreated it. Now with retention set to 0. Same result.
 
**Have you searched the internet or Github for an answer?**
 - I did, and found that I could retrieve with retro. I ran that several times, same result.

**To Reproduce**

**Expected behavior**
 - A clear and concise description of what you expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Chrome
 - Spotweb Version [e.g. 1.4.8]
 - Which branch  (Master)
 -  PHP version 8.1.2
 -  Device information (ReadyNAS/Synology/FreeNAS) x86 pc

**Smartphone if applicable (please complete the following information):**
 - Spotweb Version [e.g. 1.4.8]
 - Which branch  (Master/Develop)
-  PHP version
-  Device information (ReadyNAS/Synology/FreeNAS)

**Additional context**
I've did a select on the spots table, it just counts 187 rows... I ran the retrieve with debug. Created a file from over 7GB, so not sure if I can drop it here

**Comment by mesa57** [comment]
Did the retrieve run to end ?

**Comment by suheyl** [comment]
Yes, several times, with and without retro

**Comment by suheyl** [comment]
![start_retrieve](https://user-images.githubusercontent.com/4746649/201781617-b5e176be-6bbf-4b93-9b93-d8b15ceff9b4.jpg)
![end_retrieve](https://user-images.githubusercontent.com/4746649/201781622-ea5cd833-60be-43c4-90d5-3f799c8e53e5.jpg)

took 40 minutes with retro

**Comment by Sweepr** [comment]
Which date do you have set?

![image](https://user-images.githubusercontent.com/2857865/201832073-ecf90aaf-dd0e-4248-8376-3f343123058e.png)

If for example you set the date to today, Spotweb will only retrieve spot from today..

![image](https://user-images.githubusercontent.com/2857865/201832205-6be8ea78-5406-4190-a5eb-ccb5d93e83fc.png)

**Comment by suheyl** [comment]
Apparently this worked! I'll close it. thnx!
