### ISSUE TITLE
invalid input syntax for type integer: "black"

### ISSUE THREAD

**Issue by xpunkt** [spotweb/spotweb#777]
SpotWeb v0.68.34.34 on PHP v7.4.33 crashed 22P02: 7: ERROR: invalid input syntax for type integer: "black"

change Blacklist to default disabled creates that crash

still using postgresql :=)

**Comment by xpunkt** [comment]
https://example.org/spotweb/?page=editsettings missed that part

**Comment by mesa57** [comment]
If you mean default like this:
![afbeelding](https://user-images.githubusercontent.com/6350469/202849019-23be5fe3-0122-4993-8ee4-dd7202cbf630.png)
That's just works.

**Comment by Sweepr** [comment]
Why would you still fetch external blacklist if the URL is empty ?

Disable the option is the way to go.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by xpunkt** [comment]
yes, yesterday it could only fetch blacklists, try with wget the shortner url, but with postgresql backend it is not possible to disabled black / white lists hence my report on it

**Comment by mesa57** [comment]
The shortener url, bit.do, is down at the moment.

**Comment by mesa57** [comment]
Should work now if you check out develop branch.
