### ISSUE TITLE
git pull reports : error: Your local changes to the following files would be overwritten by merge:

### ISSUE THREAD

**Issue by Pattepat** [spotweb/spotweb#780]
Hi,

Been running spotweb for years and every once in a while i do a git pull to update.    This time i'm  confronted with the below error. (note: i have not changed any of the mentioned files).    Its probably my own lack of knowledge but the 'pull' command always worked to update.

root@xxxxxxxx:/var/www/spotweb# git pull -v
From https://github.com/spotweb/spotweb
 = [up to date]        master     -> origin/master
 = [up to date]        develop    -> origin/develop
 = [up to date]        e1rdo      -> origin/e1rdo
 = [up to date]        media      -> origin/media
error: Your local changes to the following files would be overwritten by merge:
        **lib/Bootstrap.php
        lib/services/Signing/Services_Signing_Openssl.php**
Please commit your changes or stash them before you merge.
Aborting

root@xxxxxxxx:/var/www/spotweb# ls -al lib/Bootstrap.php lib/services/Signing/Services_Signing_Openssl.php
**-rw-r--r-- 1 www-data www-data 7517 Mar 24  2021 lib/Bootstrap.php
-rw-r--r-- 1 www-data www-data 7425 Mar 25  2021 lib/services/Signing/Services_Signing_Openssl.php**
root@xxxxxxxx:/var/www/spotweb#

----------

```
root@xxxxxxx:/var/www/spotweb# git diff
diff --git a/lib/Bootstrap.php b/lib/Bootstrap.php
index fab20733..4e034a1e 100644
--- a/lib/Bootstrap.php
+++ b/lib/Bootstrap.php
@@ -79,7 +79,7 @@ class Bootstrap
          * Disable XML entity loader as this might be an
          * security issue.
          */
-        libxml_disable_entity_loader(true);
+        /*libxml_disable_entity_loader(true);*/

         SpotTiming::stop('bootstrap');

diff --git a/lib/services/Signing/Services_Signing_Openssl.php b/lib/services/Signing/Services_Signing_Openssl.php
index b11d1b11..5e4fd0c5 100644
--- a/lib/services/Signing/Services_Signing_Openssl.php
+++ b/lib/services/Signing/Services_Signing_Openssl.php
@@ -1,5 +1,4 @@
 <?php
-
 use phpseclib\Crypt\RSA;

 class Services_Signing_Openssl extends Services_Signing_Base
@@ -42,13 +41,14 @@ class Services_Signing_Openssl extends Services_Signing_Base
             if ($useCache) {
                 $this->_pubKeyCache[$rsaKey['modulo'].$rsaKey['exponent']] = $openSslPubKey;
             } else {
-                openssl_free_key($openSslPubKey);
+                // openssl_free_key($openSslPubKey);
             } // else
         } // else

         return $verified;
     }

+
     // checkRsaSignature

     /*

```

----------

root@xxxxxxxx:/var/www/spotweb# git log --pretty=oneline
fd75cb3947fb79eda6f2e8da0ed83fe29f0dc6fb (HEAD -> master) Merge branch 'master' of https://github.com/spotweb/spotweb
909b8b57780ce72d2a6adf9266ec3e5c828a2b69 (tag: 1.4.9) Merge pull request #626 from spotweb/develop
469787d7a5608cf349e37152afdfc743657757c0 Merge pull request #625 from mesa57/develop
077fc2d78cb1ec65bbc4bd7a6545537212cd2739 Prob. fix for issue #624 postgres performance on spot list
38ff84672e1a21ac262c3f57b300e8dd9d604fa5 Merge pull request #622 from spotweb/analysis-64Ab3n

**Comment by Sweepr** [comment]
This indicates you have edited local files.
In order to resolve this try:

`git reset --hard`
`git pull`

Note:
**It will override any local changes, they will be gone**
