### ISSUE TITLE
[Question] Add list of docker images to Wiki

### ISSUE THREAD

**Issue by BakasuraRCE** [spotweb/spotweb#785]
Hi @mesa57!

So, this is a fast question, what is your thinking about the [docker images](https://hub.docker.com/search?q=spotweb&sort=updated_at&order=desc) that build your project?

It would be good to have a list of images ready to use, in case someone wants to use them.

There are several flavors, for example, [mine](https://hub.docker.com/r/bakasura/spotweb) focuses on automatic update of the images, the use of OpenLitespeed as a server, PHP 8.x, and the comfort of not being required to edit the `docker-compose` file when the first installation is performed.

Regards :)

**Comment by mesa57** [comment]
Most used docker image is https://github.com/jgeusebroek/docker-spotweb i think.

**Comment by BakasuraRCE** [comment]
Ok, fine :)
