### ISSUE TITLE
Not getting old Spots

### ISSUE THREAD

**Issue by Fossil01** [spotweb/spotweb#787]
Had to reinstall Spotweb because of a broken DB. My backups we're also messed up so I was lucky I could salvage my users, usersettings, filters and settings tables.

I reinstalled Spotweb and overwrote the new tables with the old backupped ones. Seemed to work fine.

But now I only have about a weeks worth of Spots. I checked my settings but the retention is set to 0 and the `retrieve_newer_than` is set to 1257030000 which is 2009.

Any other things I should look at?

I also ran `php retrieve.php --retro` which started from scratch but the spots table never grew further than 1990-ish rows. Sometimes when running retrieve.php I See 2048 rows in the spots table but then it drops down again to 1990 or 1992 total rows etc.

**Comment by Sweepr** [comment]
Question, did you also switch usenet providers?

If not, then probably table `usenetstate` might also been corrupted, you can overcome this by doing: https://github.com/spotweb/spotweb/wiki/Spotweb-reset-database-or-clear-local-cache#reset-your-database

**Comment by mesa57** [comment]
Not heared anything, so suppose it has been resolved.

**Comment by stefaanbolle** [comment]
Whatever I do, I cannot get older spots than the ones I get since I perform reset-db.
Spots before this reset-db date don't come in. Anything I can force manually?

**Comment by Sweepr** [comment]
> Whatever I do, I cannot get older spots than the ones I get since I perform reset-db.
> Spots before this reset-db date don't come in. Anything I can force manually?

See: https://github.com/spotweb/spotweb/issues/776

Next time create a new issue and refer to closed ones, don't hijack closed issue's please.
