### ISSUE TITLE
PHP Deprecated:  Implicit conversion from float 167.5 to int loses precision in  

### ISSUE THREAD

**Issue by Hydranet** [spotweb/spotweb#788]
**Describe the bug/issue**
PHP Deprecated:  Implicit conversion from float 167.5 to int loses precision in /data/www/spotweb/html/lib/services/Image/Services_Image_Error.php on line 31
PHP Deprecated:  Implicit conversion from float 161.5 to int loses precision in /data/www/spotweb/html/lib/services/Image/Services_Image_Error.php on line 51

**Have you searched the internet or Github for an answer?**
No this seems to be a php problem related to upgrade from php 7.4 to 8.1

**To Reproduce**
1. Switch to php 8.1
2. Add retrieve.php as a cronjob: /usr/bin/php /data/www/spotweb/html/retrieve.php
3.  Sometimes it happens and sometimes it doesn't.

**Expected behavior**
I don't expect to get an error from the retrieve.php that run as a cronjob

**Screenshots**

**Desktop (please complete the following information):**
 - VPS OS: Rocky Linux 8
 - Client Browser: Firefox
 - Spotweb Version: 14b83b8d4a5b194ff93d28113173b3bb89d745f1
 - Which branch: Develop
 -  PHP version: 8.1
 -  Device information: -

**Additional context**
This is not an interface bug so it has nothing to do with your browser and it has started happening since I switched my vps from php 7.4 to 8.1

**Comment by mesa57** [comment]
I did not get this error while retrieving with php 8.1
As it seems to be intermitted, could you test if the error occurs when you set prepare statistic during retrieve to 'off' ?

**Comment by Hydranet** [comment]
I just change the setting you mentioned to off, I will see tomorrow if I still see the error. If I don't see the error tomorrow, do you want me to switch it back on and then run retrieve again and save the output to a file?

**Comment by Hydranet** [comment]
It hasn't happened again since I turned that setting you mentioned off last night, do you want me to turn it on again to see if it returns? If it does do you want me to run retrieve several times until I get the same error as I get in my cron mail and save it to a file for you?

**Comment by mesa57** [comment]
It would by nice to have a complete log because retrieve.php has several phases and it is not clear where the error is coming from.

**Comment by Hydranet** [comment]
I can turn that option on again, how can I then generate the complete log you are talking about?

**Comment by mesa57** [comment]
If you execute retrieve via ssh you get a complete log.

**Comment by Hydranet** [comment]
I turned on the setting you mentioned again and ran a retrieve by logging in through ssh, no error this time. I can adjust the cronjoab so that it creates a new files each time it runs until I have a log file you can work with.

**Comment by mesa57** [comment]
Ok, got some time to look into this. It is related to specific spot images, so spot dependend.
I will correct the error if I find some more time, but I am extremely busy at the moment.
For now you can prevent the error during retrieve by changing the setting "Prefetch Images" on "Retrieve full spots" in the settings retrieve tab.

![afbeelding](https://user-images.githubusercontent.com/6350469/208242531-881cce1b-c0df-474b-9887-95318c3e8a72.png)

Furthermore I advise to turn of "retrieve full spots"  as this is greatly impacting the retrieve speed.

**Comment by Hydranet** [comment]
I haven't seen the error since I set my cronjob, this is what my retrrieve looks like without errors.
```
spotlog]$ cat retrieve_2022-12-17_13:45:01.log
Removing Spot information which is beyond retention period,, done
Last retrieve: 2022-12-17 12:40:52
Retrieving new Spots from server news.eweka.nl...
Appr. Message count: 	3814618
First message number:	2
Last message number:	3814620
Current article number:	3814619

Retrieving 3814619 till 3814621 (parsed: 1, in DB: 1, signed: 1, invalid: 0, rtntn.skip: 0, mod: 0, full: 1, total: 2) in 1.07 seconds
Processed a total of 2 spots
Finished retrieving spots.

Calculating how many spots are new, done.
Last retrieve: 2022-12-17 12:45:37
Retrieving new comments from server news.eweka.nl...
Appr. Message count: 	19564308
First message number:	2
Last message number:	19564310
Current article number:	19564303

Retrieving 19564303 till 19564311, found 8 comments in 0.53 seconds
Processed a total of 8 comments
Finished retrieving comments.

Last retrieve: 2022-12-17 12:45:50
Retrieving new reports from server news.eweka.nl...
Appr. Message count: 	271016
First message number:	2
Last message number:	271018
Current article number:	271018

Processed a total of 0 reports
Finished retrieving reports.

Starting to create statistics
Finished creating statistics
```
I only have a few users, what does  "retrieve full spots" do, and what  happens when that is turned off? Images and all Spot information is  still shown when a user clicks on a spot?

**Comment by mesa57** [comment]
Retrieve  full spots fills the database and cache with all the spot information during retrieve. If that information is not present, it will retrieve it during opening of the spot.

**Comment by Hydranet** [comment]
I will leave that off then,  should I turn off  "Retrieve comments" , "Retrieve full comments" and "Retrieve reports" as well then. I have those turned on because I sometimes find reading the comments useful?

**Comment by mesa57** [comment]
I would leave those setting "On"

**Comment by Hydranet** [comment]
Okay I turned it off then, I don't think my, I don't think my cronjob will be of any use since none of the log files have produced an error yet.

**Comment by Hydranet** [comment]
Happy New year @mesa57!

I haven't seen the error since I turned off "prepare statistics" and "retrieve fullspots". To reproduce it again I will have to try and turn on those settings again.

**Comment by mesa57** [comment]
As it is still not fix please leave it like this until fixed.

**Comment by mesa57** [comment]
Solved in develop branch.
