### ISSUE TITLE
NZBServer is geblokkeerd. Gebruik een VPN voor toegang.

### ISSUE THREAD

**Issue by Phanegem** [spotweb/spotweb#789]
VPN gewoon aanwezig / VPN is there. 
Hoe kan ik deze melding voorkomen ? / How to avoid this messages

**Comment by Sweepr** [comment]
Could you provide some more information?
Where are you seeing this?

Not sure if this is a Spotweb related issue, but let's see.

**Comment by mesa57** [comment]
Seems to be this message:
![afbeelding](https://user-images.githubusercontent.com/6350469/209465466-f1726fb5-b1d7-40f1-8657-584c08787d09.png)

And it is not spotweb related.

Btw, I don't receive the message with no VPN.

**Comment by Sweepr** [comment]
Seems to be internetprovider related then?

**Comment by mesa57** [comment]
Could be. Could also be some ad inserted by nzbserver.com themselfs.

**Comment by Phanegem** [comment]
> Seems to be this message: ![afbeelding](https://user-images.githubusercontent.com/6350469/209465466-f1726fb5-b1d7-40f1-8657-584c08787d09.png)
> 
> And it is not spotweb related.
> 
> Btw, I don't receive the message with no VPN.

jep, is this one. 

Could be provider related but no way to test that, Found a work around. Instead of clicking left, Click right and choose, open in differte tab.

**Comment by Sweepr** [comment]
Seems to be a very dirty way of luring people into getting a subscription with the VPN indeed, have you tried an adblocker?

**Comment by Phanegem** [comment]
> Seems to be a very dirty way of luring people into getting a subscription with the VPN indeed, have you tried an adblocker?

Jep, but that does not help.

**Comment by Sweepr** [comment]
It's some kind of widget script that they have added themselves that causes this message, I haven't seen this message before while browsing their site.
Since there isn't much we can do about it, you have to deal with it, or look for an alternative.

```
<script> window.WidgetGlobalTopTitle = 'VPN via VPN Nederland'; window.WidgetGlobalCtaUrl = 'https://www.vpnnederland.nl/cyber-monday-2022?a=4144&utm_source=affiliate&utm_medium=nzbserver&utm_campaign=widget'; window.WidgetGlobalCtaTitle = 'Pak direct 84% korting!' ; window.WidgetGlobalCtaInfoUrl = 'https://www.nzbserver.com/vpn'; window.WidgetGlobalCtaInfoTitle = "Meer informatie" ; window.endDate = "December, 21 2021 18:00:00"  </script>
    <script src="[https://www.nzbserver.com/widget.js?v2.0.1220](view-source:https://www.nzbserver.com/widget.js?v2.0.1220)" defer></script>
```

**Comment by Sweepr** [comment]
Nothing to do, closing.

**Comment by xpunkt** [comment]
imho https://www.privoxy.org/ can disable this <scripts.... if not go with disable javascripts in browser, and add exeptions where is its needed to have js supported, js is not a requirement for not using vpn with own CA :)

note just privoxy is now very old, and i dont know if it still developped at all, there is maybe another solution with noscript blockers

**Comment by mesa57** [comment]
Ahh, thats why I don't see it. I use uBlock origin in firefox.

**Comment by mesa57** [comment]
Ad is now under the NZB button.
![afbeelding](https://user-images.githubusercontent.com/6350469/209477760-e873d3d6-ff5c-474c-bc9a-6e8207b35d69.png)

**Comment by Sweepr** [comment]
So, right before you want to download an NZB using the "download NZB" button
![image](https://user-images.githubusercontent.com/2857865/209524041-3c6f5658-680c-4d95-b787-924b30352688.png)

Disable javascript in Ublock ,
Left click the UBlock addon, and click "</>" so it is red crossed, like below. (don't refresh the page)
![image](https://user-images.githubusercontent.com/2857865/209524274-c1f71ee4-44d5-4510-afb9-c34e54777159.png)

Then click the:
"download NZB" button
![image](https://user-images.githubusercontent.com/2857865/209524041-3c6f5658-680c-4d95-b787-924b30352688.png)

And the NZB is downloaded like normal. (this does not work from main view)

**Comment by mesa57** [comment]
Did not work with me. But disable popup's did work.

**Comment by Yuinbever** [comment]
Disable popup's works for me too.

**Comment by Sweepr** [comment]
> Did not work with me. But disable popup's did work.

Disable pop-ups where? in uBlock? didn't work for me, still see the pop-up
