### ISSUE TITLE
Spotweb on Xampp not working

### ISSUE THREAD

**Issue by Kroesss** [spotweb/spotweb#790]
I'm running xampp with php 8.1.6.

I've downloaded the zip-file and ran the installer. When entering my (custom) NZB-server, it already returned a php-error, but i was able to continue by skipping the server-verification. When the install is finished, I see the main interface without any spots. When I go to settings and then "Newsservers", I also see a lot of warnings about undefined array-keys, and I am not able to change settings.

If helpfull, I can share screenshots of the error-messages.

**Comment by Sweepr** [comment]
Any screenshot would be help full indeed, no begin able to change settings point me into thinking it might be a DB user permission issue..

**"it already returned a php-error, but i was able to continue by skipping the server-verification.."**

What was the error?

**Comment by Kroesss** [comment]
Fatal error: Uncaught ArgumentCountError: Too few arguments to function SpotInstall::ownWarning(), 4 passed in C:\xampp\htdocs\spotweb\lib\services\Nntp\Services_Nntp_Engine.php on line 35 and exactly 5 expected in C:\xampp\htdocs\spotweb\lib\SpotInstall.php:583 Stack trace: #0 C:\xampp\htdocs\spotweb\lib\services\Nntp\Services_Nntp_Engine.php(35): SpotInstall::ownWarning(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 35) #1 C:\xampp\htdocs\spotweb\lib\SpotInstall.php(226): Services_Nntp_Engine->__construct(Array) #2 C:\xampp\htdocs\spotweb\install.php(68): SpotInstall::askNntpSettings() #3 {main} thrown in C:\xampp\htdocs\spotweb\lib\SpotInstall.php on line 583

**Comment by Kroesss** [comment]
for completess, attached is a screenshot of the first install-page (which checks all dependancies), and a screenshot of the newsserver-settings page in spotweb itself, and the errors it shows there.

I have tried checking "encryption", since my news-server does use that, but it won't save and throws the error "Invalid encryption setting".
![install1](https://user-images.githubusercontent.com/17062001/209573402-d7a90352-7867-4da4-a0dc-80227d066187.png)
![spotweb error](https://user-images.githubusercontent.com/17062001/209573407-f5500768-95b1-403a-8765-c53b1b35084c.png)

**Comment by Sweepr** [comment]
I suggest from a terminal you run "upgrade-db.php --reset-db --yes" , delete "dbsetting.inc.php" from the root folder and try "install.php" again, try no to skip things.

**Comment by Kroesss** [comment]
As I am on windows with xampp, I don't think I can run php-scripts from cmd. At least, I have no idea how.

**Comment by Sweepr** [comment]
> As I am on windows with xampp, I don't think I can run php-scripts from cmd. At least, I have no idea how.

There are many guides that explain how to do this:

https://stackoverflow.com/questions/10753024/how-to-access-the-command-line-for-xampp-on-windows

**Comment by Sweepr** [comment]
Did you run the installer while using an existing database? 
Looking at the error's it seems **"nntp_post"** entry in the **"setting"** table is missing, the code is trying to set "nntp_post" ['enc'],  but fails because it doesn't exist.

So with that said the solution to your issue is: run **"php upgrade-db.php --reset-db --yes"** , delete or rename **"dbsetting.inc.php"** from the root folder and try **"install.php"** again.

**Comment by Kroesss** [comment]
Okay, so I added php to the path, and ran the command succesfully. I deleted dbsettings.inc.php and ran the installation again.

When validating the news-server, it again returned the error:
`Fatal error: Uncaught ArgumentCountError: Too few arguments to function SpotInstall::ownWarning(), 4 passed in C:\xampp\htdocs\spotweb\lib\services\Nntp\Services_Nntp_Engine.php on line 35 and exactly 5 expected in C:\xampp\htdocs\spotweb\lib\SpotInstall.php:583 Stack trace: #0 C:\xampp\htdocs\spotweb\lib\services\Nntp\Services_Nntp_Engine.php(35): SpotInstall::ownWarning(2, 'Undefined array...', 'C:\\xampp\\htdocs...', 35) #1 C:\xampp\htdocs\spotweb\lib\SpotInstall.php(226): Services_Nntp_Engine->__construct(Array) #2 C:\xampp\htdocs\spotweb\install.php(68): SpotInstall::askNntpSettings() #3 {main} thrown in C:\xampp\htdocs\spotweb\lib\SpotInstall.php on line 583`

After continuing without validating the server, I have the exact same problems in the settings-menu as described before.

To answer your previous question if I used an existing database, I did use an existing database. I had just created a new one and used that. So it was completely empty when I started, but it was not created by the installer-script.

**Comment by Sweepr** [comment]
Attempted to reproduce this, I download the zip file from here: https://github.com/spotweb/spotweb/archive/refs/tags/1.5.3.zip
Installed it on wampserver, ran through the installer on a fresh DB, skipped validation, finalized install without seeing any error's.

![image](https://user-images.githubusercontent.com/2857865/209812688-39ff28da-2561-4f29-a11d-6f039e9f308f.png)

I am not seeing this?

**Comment by Kroesss** [comment]
Okay, I redid all the steps, and I had the same result as before. Then I noticed in your screenshot that you had it set-up with a standard news-server (from the drop-down list in the installation). When I do that, there are no errors (I skip validation because I don't have correct credentials for one of those servers, but also the settings-page afterwards is functional and without errors).

It seems the errors only occur when you choose a custom server during the installation. When you select a predefined one, it is fine. I hope this gives a little bit of a direction to search for the issue?

**Comment by Sweepr** [comment]
I found the issue, so with "(custom) NZB-server", you actually ment "(custom) nntp-server", only if i would have known earlier.

Anyway i have found the reason for the errors and corrected this in these PR's:

https://github.com/spotweb/spotweb/pull/793

https://github.com/spotweb/spotweb/pull/792

**Comment by Kroesss** [comment]
Sorry to not be clearer beforehand, I'm not very well-known with the technical terms.

Anyway, glad you could find the problems! Thanks for your help!
