### ISSUE TITLE
PDF's Categorised as Movies when sent to SABNZBd or NZBGet

### ISSUE THREAD

**Issue by DrFrankensteinUK** [spotweb/spotweb#791]
**Describe the bug/issue**
Hi - I am not sure if this is by design or a bug in the categorisation / filters in the newznab API - when pushing anything in the 'books' filter to SABNZBD or NZBGet they are added with the category of 'movies'

I am not sure if this is something that can be fixed or not. It would likely require a change to the SpotPage_newznabapi.php in order to have a bespoke book or ebook category for anything in the 7020 newznab Category?

**Have you searched the internet or Github for an answer?**
Yes I had a look at the code for the SpotPage_newznabapi.php I was also initially playing around with the filters on a local install then realised there was some 'translation' taking place. 

**To Reproduce**
1) Setup the Sab/NZBGet Intergration 
2) Go to the books filter in the Spotweb Web Interface 
3) Click to download any spot
4) Check the category in the download client, and it is showing as 'movies'

**Expected behavior**
 - I would expect the category to default to 'books' or  'ebooks' 

**Screenshots**
None added as fairly self-explanatory

**Desktop (please complete the following information):**
 - Spotweb Version 1.5.1
 - Which branch  (Master)

**Additional context**
Provide any other information about the bug or issue that can further help debugging here.

**Comment by mesa57** [comment]
Did a short test with 1 book, but the correct category is included in the sabnzbd api url.
`http://192.168.2.253:8080/api?mode=addfile&apikey=xxx&output=json&nzbname=Sutcliff%2C+Rosemary+-+De+sage+van+Finn+Mac+Cool&cat=books`

**Comment by DrFrankensteinUK** [comment]
Oh right - is there a way to reset the filters to their defaults maybe something is wrong with my local docker version? it has been running for years, so maybe I changed something!

**Comment by mesa57** [comment]
Please give me an example where it is going wrong.

**Comment by joshuisman** [comment]
I can reproduce it with any post in the books sections containing pdf file(s)

**Comment by DrFrankensteinUK** [comment]
``

**Comment by mesa57** [comment]
> I can reproduce it with any post in the books sections containing pdf file(s)

OK, pdf is a fairly recent type book added. This is not yet incorperated in the default settings.
If you want you can (until a change is made) put following code into you're ownsettings.php file 👍 

```
$settings['sabnzbd']['categories'] = [
    0	=> ['default' 	=> 'movies',				// Default categorie when nothing else matches
        'a5'		       => 'books',
        'a11'		       => 'books',
        'd2'		       => 'anime',
        'd11'		      => 'tv',
        'd29'		      => 'anime',
        'z3'		       => 'erotica', ],
    1	=> ['default'	=> 'music'],
    2	=> ['default'	=> 'games'],
    3	=> ['default'	=> 'apps',
        'a3'		      => 'consoles',
        'a4'		      => 'consoles',
        'a5'		      => 'consoles',
        'a6'		      => 'consoles',
        'a7'		      => 'consoles',
        'a8'		      => 'consoles',
        'a9'		      => 'consoles',
        'a10'		     => 'consoles',
        'a11'		     => 'consoles',
        'a12'		     => 'consoles',
        'a13'		     => 'pda',
        'a14'		     => 'pda',
        'a15'		     => 'pda', ],
];



```

**Comment by mesa57** [comment]
@DrFrankensteinUK The first 3 are format pdf (use above ownsettings).
The last one is an ePub, which should be categorized as 'book'. For that one make sure sabnzbd contains the category 'book'.

**Comment by DrFrankensteinUK** [comment]
Hey sorry for the delayed reply, thanks for looking at this, I personally don't grab many books but I know others do. I will wait for this be appear in a release

Thanks again!

**Comment by mesa57** [comment]
Develop branch now contains the correct settings. If it is not working, please reopen this issue.
