### ISSUE TITLE
Issue with API interactive search.

### ISSUE THREAD

**Issue by Junktroep** [spotweb/spotweb#795]
I am using Sonarr with spotweb as an indexer.
On interactive searches from within sonarr I would always get an error:

An error occurred while processing feed. https://localhost:9095/spotweb/api?t=tvsearch&cat=5030,5040&extended=1&apikey=(removed)&offset=0&limit=250&tvmazeid=15299&season=1&ep=8: There are multiple root elements. Line 2, position 2.

Pasting the url in a browser would show:
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/8348697/209976878-af3c80b4-cd83-463e-a056-9911c2b0badc.png">

Doing some research I stumbled upon a modify of the index.php.
Uncommenting the first two lines would resolve the issue

<img width="248" alt="image" src="https://user-images.githubusercontent.com/8348697/209977056-0af9515e-2659-401d-a9f1-9b8b8b545247.png">

And true it resolves the issue and provides an valid xml:
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/8348697/209977346-d4a3f7f9-a46b-4518-a5a1-97f0fc28a30a.png">

And also spotweb is showing as a result with interactive searches in sonarr and doesn't trow an index error anymore.
But since this is not a longterm fix and will probably be overwriten with a git pull.

I am using:

Ubuntu 20.04 lts
PHP 7.4.3
MySQL 8.0.31
NGINX 1.18

**Comment by Sweepr** [comment]
Good question, this is a reoccurring thing so i am considering to disable those lines by default, there is no need for normal users to see debug information unless necessary.
