### ISSUE TITLE
Question: it it possible to exclude cam and TS?

### ISSUE THREAD

**Issue by AlwinHummels** [Spotweb/Spotweb#8]
Can I exclude thos from my list? same as I can exclude porn from the list? If yes can anyone tell me how or if no maybe it would be nice in a future version ;-)

Thanks anyway

**Comment by kooimens** [comment]
Anyone? I would like to know how this can be done for a certain user.

**Comment by Sweepr** [comment]
Use http://www.brainbytez.nl/spotweb-filter-creator/ to create your own filters.
