### ISSUE TITLE
Spotweb API identical as newznab API?

### ISSUE THREAD

**Issue by kooimens** [spotweb/spotweb#80]
Does spotweb have identical api as newznab?

**Comment by Sweepr** [comment]
Yes, you can find it if you hover over your username and select "change user", there you can find the API key.

**Comment by kooimens** [comment]
Ok, Thanks!

**Comment by Sweepr** [comment]
https://spotweburl/api?t=search&q=Linux&apikey=f765fcb9d7747cf3c0b50a8266103de0&o=json
Isn't that Json?
