### ISSUE TITLE
"This query is not allowed!" error popup when entering search string "right"

### ISSUE THREAD

**Issue by simkin** [spotweb/spotweb#802]
**Describe the bug/issue**
Search for some normal strings not allowed. e.g. "right" produces a popup error

`<script language="javascript">alert("This query is not allowed!")</script><script language = "javascript">window.location.href = "/?search[tree]=&search[unfiltered]=true"</script>`

**Have you searched the internet or Github for an answer?**
https://github.com/spotweb/spotweb/issues/632

**To Reproduce**
In search field enter value "right" and press error

**Expected behavior**
Search results containing string "right" are returned

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Mozilla
 - Spotweb Version: master
 - Which branch  (Master/Develop)
 -  PHP version
 -  Device information (ReadyNAS/Synology/FreeNAS): Debian Bullseye

**Additional context**
Test URL: https://www.clubnzb.com/?sortdir=ASC&sortby=&search%5Bunfiltered%5D=true&search%5Bvalue%5D%5B%5D=Title%3A%3D%3ADEF%3Aright

**Comment by sagieuchnet** [comment]
same error for search string "as s" 'as s' or just as s

**Comment by Sweepr** [comment]
You will have the same with all words below:

```
/* Blacklisted SQL commands */

			$notAllowedCommands = array(
			'DELETE',
			'TRUNCATE',
			'AS',
			'DROP',
			'USE',
			'SELECT',
			'SLEEP',
			'UPDATE',
			'ALTER',
			'CREATE',
			'RENAME',
			'GRANT',
			'REVOKE',
			'BETWEEN',
			'COMMIT',
			'SAVEPOINT',
			'EXISTS',
			'GROUP',
			'HAVING',
			'IN',
			'INTO',
			'INSERT',
			'ORDER',
			'BY',
			'UNION',
			'LEFT',
			'RIGHT',
			'FULL'
			);	
```

**Comment by Sweepr** [comment]
Should have a look which words could be removed from this list, if any.

**Comment by Sweepr** [comment]
@mesa57 

Whats your opinion about this?

**Comment by mesa57** [comment]
There are a number of words often used in titles like:
left, right, in, into, sleep, between, as, into.
I don't think it would pose a security risk to remove them from the blacklist.

**Comment by Sweepr** [comment]
Resolved.
