### ISSUE TITLE
Api json output

### ISSUE THREAD

**Issue by Hellowlol** [spotweb/spotweb#81]
Spotweb ignores the o=json and serves me xml when I'm calling t=caps. Is this a bug or isn't json output supported. If it isn't I'd like to request a feature request for it.

https://github.com/Hellowlol/HTPC-Manager/issues/244

**Comment by Sweepr** [comment]
http://spotweburl/api?t=search&q=Linux&apikey=APIKEY&o=json

Removed the t=caps, now i do get Json?

**Comment by Sweepr** [comment]
Test this API string on nZEDb aswell and above string without "t=caps" outputs Json, but as soon as i add the t=caps i get XML again, so it's only related to Spotweb itself, there's more to it,

**Comment by toaomatis** [comment]
I run into the same issue as welll when I try to connect from NZB+ (Android app). Unfortunately the app itself isn't developed anymore.

**Comment by mesa57** [comment]
Resolved with commit https://github.com/spotweb/spotweb/commit/fc90d5dfccb5540b1ef29c7b8932e46fdb1273c0
