### ISSUE TITLE
Backfilling doesn't work if prefetch images is on

### ISSUE THREAD

**Issue by Diniboy1123** [spotweb/spotweb#811]
**Describe the bug/issue**
 - A clear and concise description of what the bug is.

If I fetch all posts on a clean installation with prefetch images on, it finishes, seemingly scrapes all posts, however only the current day's content gets added to the database not the whole 10 years worth of content.

If I untick fetch full spots then it finishes and everything is perfectly backfilled.

Is there any way to have the pictures backfilled too? I tried running retrieve first without pre fetching pictures and then ran retrieve, but it didn't actually backfill anything.

Not sure why its broken in the first place since there is no error.

**Have you searched the internet or Github for an answer?**
 - Please search google if similar issue has been reported and fixed before.

https://github.com/spotweb/spotweb/issues/805#issuecomment-1415687897

This comment seems to suggests to simply disable the prefetching feature in order for the retrieving to succeed. I wonder why.

**To Reproduce**
 1. Tick pre fetch images on a clean installation
 2. Start retrieving

**Expected behavior**
 - A clear and concise description of what you expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Fedora 37
 - Browser [e.g. chrome, safari] firefox
 - Spotweb Version [e.g. 1.4.8] latest github master
 - Which branch  (Master/Develop)
 -  PHP version 
 -  Device information (ReadyNAS/Synology/FreeNAS)

**Smartphone if applicable (please complete the following information):**
 - Spotweb Version [e.g. 1.4.8]
 - Which branch  (Master/Develop)
-  PHP version
-  Device information (ReadyNAS/Synology/FreeNAS)

**Additional context**
Provide any other information about the bug or issue that can further help debugging here.

**Comment by Sweepr** [comment]
Unable to reproduce this issue, seems to work accordingly, also Images and NZB are stored in cache during retrieve.

Started with a fresh install and clean DB, set setting like below, and ran a retrieve.

![Untitled](https://user-images.githubusercontent.com/2857865/226095989-f76fea3c-7b53-487c-98b3-cc3446464daa.jpg)

![2](https://user-images.githubusercontent.com/2857865/226095994-60be250f-72df-470a-86b9-47509b7af559.jpg)

**Comment by Diniboy1123** [comment]
I am not sure what am I doibg wrong then. I am using a mariadb container and spotweb also runs in its own container. Cleared the mariadb volume and restarted mariadb to confirm that there was indeed no data there.

Then started up spotweb, logged in and set up my provider + the same config like you had.

It scraped all the history, but the db (spots table) only has a count with 3 digits. Spotweb interface also only shows today's spots.

If I redo the same thing without querying full spots it all works fine, I see all the spots.

I am thinking that I am maybe lacking the on disk cache config/mount for the images?

Or maybe its my provider (usenetserver)?

**Comment by Diniboy1123** [comment]
With 2013 March I am getting further, but I encounter a fatal error:

```
getHeader(): Failed to retrieve article: <sskmteR7D6Y33lHUQswFB@spot.net>
PHP Warning:  Trying to access array offset on value of type null in /app/lib/services/Retriever/Services_Retriever_Spots.php on line 505
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /app/lib/services/Format/Services_Format_Parsing.php on line 86
PHP Deprecated:  preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /app/lib/services/Format/Services_Format_Parsing.php on line 29
PHP Warning:  gzinflate(): data error in /app/lib/services/Nntp/Services_Nntp_SpotReading.php on line 164
PHP Warning:  preg_match(): Compilation failed: unrecognized character follows \ at offset 1 in /app/lib/services/Providers/Services_Providers_HttpNzb.php on line 278
PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /app/lib/services/Providers/Services_Providers_HttpNzb.php:281
Stack trace:
#0 /app/lib/services/Providers/Services_Providers_HttpNzb.php(243): Services_Providers_HttpNzb->downloadNzbFromBinsearch()
#1 /app/lib/services/Providers/Services_Providers_HttpNzb.php(84): Services_Providers_HttpNzb->downloadNzbFrom()
#2 /app/lib/services/Providers/Services_Providers_HttpNzb.php(29): Services_Providers_HttpNzb->getNzb()
#3 /app/lib/services/Providers/Services_Providers_Nzb.php(58): Services_Providers_HttpNzb->hasNzb()
#4 /app/lib/services/Retriever/Services_Retriever_Spots.php(537): Services_Providers_Nzb->fetchNzb()
#5 /app/lib/services/Retriever/Services_Retriever_Base.php(238): Services_Retriever_Spots->process()
#6 /app/lib/services/Retriever/Services_Retriever_Base.php(339): Services_Retriever_Base->loopTillEnd()
#7 /app/retrieve.php(142): Services_Retriever_Base->perform()
#8 {main}
  thrown in /app/lib/services/Providers/Services_Providers_HttpNzb.php on line 281
run-parts: /etc/periodic/5min/spotweb: exit status 255
```

Should I open a separate issue for this?

**Comment by mesa57** [comment]
May I ask which php version is used ?

**Comment by Diniboy1123** [comment]
Sure, I am using PHP 8.1.16.



> It looks like an invalid NZB is retrieved. Could you set prefetch NZB's off ?

Indeed that seems to be the case. I have disabled it and doing a clean retrieval right now.

**Comment by mesa57** [comment]
Btw. I strongly advise NOT to prefetch spots (retrieve full spots) unless you have a large shared user base.
Data is more then often invalid depending on you're USP and the age of spots.
Moreover, retrieve will take exponential more time.

**Comment by Diniboy1123** [comment]
Seems to be all fine from March 18, 2013.
