### ISSUE TITLE
[New issue]

### ISSUE THREAD

**Issue by ClubNZB** [spotweb/spotweb#816]
**Describe the bug/issue**
 - After clean install can`t login, goes back to login without error or something.

**Have you searched the internet or Github for an answer?**
 - Please search google if similar issue has been reported and fixed before.

**To Reproduce**
1. Go to 'left login'
2. Click on 'login'
3. fill in: 'username and password'
4. NO error error no login

Tips?

**Comment by Sweepr** [comment]
Have you tried a different browser or tried cleaning the cache?

If applicable disable any proxies or cloud services like for example Cloudflare or Akmai.

**Comment by Sweepr** [comment]
Try enabling developer mode for cloudflare and empty any cache locally, maybe a session is still active, but i suspect CF is messing around with a outdated copy.

**Comment by ClubNZB** [comment]
Hi Sorry, When I add the wrong details I get: Login Failed
When I add the correct details the error remove but no pulldown menu for configuration

**Comment by mesa57** [comment]
![afbeelding](https://user-images.githubusercontent.com/6350469/231253477-d877fc94-6c29-4325-b8b9-4ab2d644fc3d.png)

**Comment by ClubNZB** [comment]
login at: beta.clubnzb.com (new server)
User: Demo
Pass: rbd49jpe0

**Comment by mesa57** [comment]
I am missing the POST of the login data. Seems to me there is something wrong with you're configuration as @Sweepr already said.

**Comment by ClubNZB** [comment]
OK, but I do a pull from Github....
What is the tip now?

**Comment by ClubNZB** [comment]
> See: #385

I can`t connect to SSH :-(
Strange on the forst domain (www.clubnzb.com) is normaly working.
On a fresh pull it doesent work 👎

**Comment by Sweepr** [comment]
How do you mean, you can't connect to it using SSH?  

Dis you not configure this or is this an unmanaged server?

**Comment by ClubNZB** [comment]
Sorry, I found it (terminal under Cpanel)
php upgrade-db.php --reset-securitygroups
And
php upgrade-db.php --reset-groupmembership
Give: Could not open input file: upgrade-db.php

**Comment by Sweepr** [comment]
> Sorry, I found it (terminal under Cpanel)
> php upgrade-db.php --reset-securitygroups
> And
> php upgrade-db.php --reset-groupmembership
> Give: Could not open input file: upgrade-db.php


It's in the "bin" folder.

**Comment by ClubNZB** [comment]
LOL, Again:
Run both + no erros...
No result :-(
Pffff

**Comment by Sweepr** [comment]
I assume your "admin" account, is the 2nd user on the system, besides "anonymous" , if so could you run and copy/paste the outcome of the SQL query `SELECT * FROM `usergroups` WHERE `userid` = "2";` and post the outcome here?

**Comment by ClubNZB** [comment]
![image](https://user-images.githubusercontent.com/98832776/231269863-0b995a70-a94a-4822-9a6a-419e870fe821.png)

**Comment by Sweepr** [comment]
> ![image](https://user-images.githubusercontent.com/98832776/231269863-0b995a70-a94a-4822-9a6a-419e870fe821.png)

Seems ok, how about `SELECT * FROM `grouppermissions` WHERE `groupid` = "5";`

**Comment by ClubNZB** [comment]
![image](https://user-images.githubusercontent.com/98832776/231344323-c03a62a1-71b1-4bc5-86bd-28b1aca9e988.png)

**Comment by Sweepr** [comment]
Seems ok, whats the output when you run upgrade-db.php ?

**Comment by ClubNZB** [comment]
![image](https://user-images.githubusercontent.com/98832776/231381584-841524cb-c979-4ac8-8a65-e4ebaeba7602.png)

**Comment by Sweepr** [comment]
Weird, and still you can't login?

Seems something is messed up, but its difficult to figure out for me
Best thing is to rename or delete your "dbsettings.inc.php" and run the install.php again.. see if any error pops-up.. if that fails then create a new database would be the best option.

**Comment by ClubNZB** [comment]
I do that 3 times today but no result....
For now we stop this project and try to get the "old" server back online.
But updating the database is terror.
There is something wrong in the code.

On the old server a new pull same error, so something...

**Comment by Sweepr** [comment]
By means of test i have installed the develop branch on PHP 8.1 and followed the installation as usual, i was able to ling without issue's:

![image](https://user-images.githubusercontent.com/2857865/231547703-e9c1ac62-b105-4b50-ad34-19c4797ce3e8.png)

It's always easy to blame the code, while the error usually can be found between the computer and the chair.
Looking at your domain i noticed you have also been playing around with code and permissions here and there:

![image](https://user-images.githubusercontent.com/2857865/231547982-17808224-f841-4552-b1f1-eb8b0a6ba5e7.png)

![image](https://user-images.githubusercontent.com/2857865/231548226-19d49c1b-5c8b-4933-abe7-0c58bb8b930c.png)

So in this case no warranty can be given.

**Comment by ClubNZB** [comment]
DONT LOOK AT THE WORKING SITE FREND.
It was the betasite where the problems where and where the original code wasent work.

I hate when people turns stories!

Now you can close this, but BE REAL!

> By means of test i have installed the develop branch on PHP 8.1 and followed the installation as usual, i was able to login without issue's:
> 
> ![image](https://user-images.githubusercontent.com/2857865/231547703-e9c1ac62-b105-4b50-ad34-19c4797ce3e8.png)
> 
> It's always easy to blame the code, while the error usually can be found between the computer and the chair. Looking at your domain i noticed you have also been playing around with code and permissions here and there:
> 
> ![image](https://user-images.githubusercontent.com/2857865/231547982-17808224-f841-4552-b1f1-eb8b0a6ba5e7.png)
> 
> ![image](https://user-images.githubusercontent.com/2857865/231548226-19d49c1b-5c8b-4933-abe7-0c58bb8b930c.png)
> 
> So in this case no warranty can be given.

**Comment by mesa57** [comment]
If you speak dutch i can recommend you this forum :
https://gathering.tweakers.net/forum/list_messages/1478602/last

**Comment by ClubNZB** [comment]
Problem is you take two websites.
1 is working and you make reffers to the working site.
The problem was on the new server/domain BETA (non working.

You send I change the code, it is onthe WORKING SITE.
On the BETA website there was no changing code.
Fresh pull form here!

Don`t lie and make a story of 2 different sites!
Good day!
