### ISSUE TITLE
QoQ whitelist

### ISSUE THREAD

**Issue by piejanssens** [spotweb/spotweb#82]
Hoe kan je bij je eigen spotweb installatie de valse QoQ releases wegfilteren/(automatisch) verwijderen?

Vb. van valse post: http://i.imgur.com/fsuLscY.png
QoQ smartfilter met uitleg: http://bit.do/Q-Smartfilter 
Helaas beperkt de uitleg ivm spotweb zich tot een verwijzigen naar een publieke spotweb instance.

**Comment by Wally73** [comment]
je moet gewoon de goeie qoq (C7w1uw) whitelisten en flter mee maken 
rest negeren
