### ISSUE TITLE
Question about Spotweb usenet connections

### ISSUE THREAD

**Issue by Hydranet** [spotweb/spotweb#820]
I have a question which I can't find the answer to in the wiki. How many connections does Spotweb use when running a retrieve.php?

**Comment by Sweepr** [comment]
Just one, it's not multi-threaded if that's your question.

**Comment by Hydranet** [comment]
Yes that was my question, I have always wondered how many connections I should keep free for Spotweb, since I alway have always used 15 less connections in my usenet reader just to be sure that Spotweb would have a enough connections. Now that I know for sure I will just use 1 less than the max connections of my usenet reader. You can close the question. Thanks for the answer!

**Comment by Sweepr** [comment]
Sure, this has been discussed in the past, only thing to lookout for is IP-sharing limits from the USP, some do not allow IP sharing, which could affect you if you have 14 connections left but Spotweb run's from another IP then there rest of the connection that are still free.
