### ISSUE TITLE
[New issue] Spotweb search “Law & Order” gives error

### ISSUE THREAD

**Issue by mitchelv07** [spotweb/spotweb#829]
**Describe the bug/issue**
 - Searching for Law & Order on Spotweb gives an “Query is not allowed” error

**Have you searched the internet or Github for an answer?**
 - Not a known issue

**To Reproduce**
1. Go to spotweb homepage
2. Click on search bar on the top left
3. Search for “Law & Order”

**Expected behavior**
 - I expect it to search the item just like every other item.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Spotweb Version: Latest docker version
 - Which branch  master
 -  PHP version 8.1.22
 -  Device information: Linux OVM6

**Additional context**
Provide any other information about the bug or issue that can further help debugging here.

**Comment by mesa57** [comment]
Probably caused by sql injection prevention.
Try +Law +Order

**Comment by mitchelv07** [comment]
Hello Mesa, this still gives the same error

> Probably caused by sql injection prevention.
> Try +Law +Order

This still gives the same error unfortunately.

**Comment by mesa57** [comment]
Keyword 'order' is not allowed.
