### ISSUE TITLE
Crash on retrieval due to Postgres character varying limit

### ISSUE THREAD

**Issue by jwallden** [spotweb/spotweb#83]
When i run `php retrieve.php --force`i get : 

Last retrieve at Thu 30 Jul 2015 11:16:53 PM CEST
Retrieving new reports from server news.Usenetserver.com...
Appr. Message count: 	140637
First message number:	2
Last message number:	140639
Current article number:	120023

Retrieving 120023 till 125024, found 5001 reports in 2.78 seconds

SpotWeb v0.67.28.31 on PHP v5.6.11 crashed

Fatal error occured retrieving reports:
  22001: 7: ERROR:  value too long for type character varying(128)

#0 /srv/http/lib/dao/Base/Dao_Base_SpotReport.php(69): dbeng_pdo->batchInsert(Array, 'INSERT INTO rep...', Array, Array)
#1 /srv/http/lib/services/Retriever/Services_Retriever_Reports.php(124): Dao_Base_SpotReport->addReportRefs(Array)
#2 /srv/http/lib/services/Retriever/Services_Retriever_Base.php(227): Services_Retriever_Reports->process(Array, 120023, 125024, 1438291014.0332)
#3 /srv/http/lib/services/Retriever/Services_Retriever_Base.php(319): Services_Retriever_Base->loopTillEnd(120023, '5000')
#4 /srv/http/retrieve.php(206): Services_Retriever_Base->perform()
#5 {main}

PHP Fatal error:  Uncaught SqlErrorException '25P02: 7: ERROR:  current transaction is aborted, commands ignored until end of transaction block' in /srv/http/lib/dbeng/dbeng_pdo.php(59)
#0 /srv/http/lib/dao/Base/Dao_Base_UsenetState.php(91): dbeng_pdo->exec('UPDATE usenetst...', Array)
#1 /srv/http/lib/services/Retriever/Services_Retriever_Base.php(260): Dao_Base_UsenetState->setRetrieverRunning(false)
#2 /srv/http/retrieve.php(313): Services_Retriever_Base->quit()
#3 {main}
  thrown in /srv/http/lib/dbeng/dbeng_pdo.php on line 59

From what i can see in Dao_Base_SpotReport.php, line 69, we are inserting into reportsxover table and from what I understand from the error message it is simply a too large of a number we are trying to insert.

**Comment by Sweepr** [comment]
In SQl run:

ALTER TABLE reportsxover 
CHANGE COLUMN fromhdr fromhdr VARCHAR(256) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL DEFAULT '' ;

See: https://github.com/spotweb/spotweb/issues/66

**Comment by jwallden** [comment]
Thanks!
This is Postgres though so above didn't work. I used
`ALTER TABLE reportsxover ALTER COLUMN fromhdr TYPE VARCHAR(256);`
which seems to have done the trick!

**Comment by Sweepr** [comment]
Ofcourse, i was just about to write that, but good that it's fixed now.
