### ISSUE TITLE
(502) Authentication rejected [response: "Too many connections"] [response: ""]

### ISSUE THREAD

**Issue by Suspect-byte** [spotweb/spotweb#830]
**Have you searched the internet or Github for an answer?**
 - Yes a lot even old post but without a solution

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Chrome
 - Spotweb Version v0.68.34.34
 -  PHP version v8.1.22
 -  Device information: Unraid Docker with MySQL

Hello,
Everything works amazing except on 1 thing. Spotweb is sending nzbs to my nzbget. That works but as soon I want to add multiple in queue I'm getting this error:

SpotWeb v0.68.34.34 on PHP v8.1.22 crashed
Fatal error occured while connecting to the newsserver:
(502) Authentication rejected [response: "Too many connections"] [response: ""]

#0 /var/www/spotweb/lib/services/Nntp/Services_Nntp_Engine.php(143): Services_Nntp_Engine->connect()
https://github.com/jgeusebroek/docker-spotweb/issues/1 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(118): Services_Nntp_Engine->selectGroup()
https://github.com/jgeusebroek/docker-spotweb/issues/2 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(298): Services_Retriever_Base->connect()
https://github.com/jgeusebroek/docker-spotweb/issues/3 /var/www/spotweb/retrieve.php(142): Services_Retriever_Base->perform()
https://github.com/jgeusebroek/docker-spotweb/issues/4 {main}

Then I have to wait till my download is fully complete and we can download 1 again. So nothing works when I want to put it in queue.
My newsserver is eweka and I got at least 50 connections. So I don't understand the problem maybe someone can help me?

Thanks in advance!

**Comment by Sweepr** [comment]
Reduce the amount of connections used by nzbget.

The error is clear: "Too many connections"

**Comment by mesa57** [comment]
Closing. Not a spotweb problem.
