### ISSUE TITLE
Default blacklist/whitelist URLs are offline

### ISSUE THREAD

**Issue by zooool** [spotweb/spotweb#833]
http://bit.do/sp4black and http://bit.do/sp4white are used as the default blacklist and whitelist URLs but they are offline and seem to have been for a long time.

**Comment by mesa57** [comment]
bit.do has gone.
you can manually change them to spotblack.tk and spotwhite.tk

**Comment by zooool** [comment]
> bit.do has gone. you can manually change them to spotblack.tk and spotwhite.tk

Still needs to be fixed in the code.

**Comment by damousys** [comment]
those .TK domains are also down for me ?

**Comment by ramonskie** [comment]
any update on this?

**Comment by Sweepr** [comment]
> any update on this?

Add these manually.

http://spotlist.tk/spotnet/blacklist.xml

http://spotlist.tk/spotnet/whitelist.xml

**Comment by Sweepr** [comment]
> those .TK domains are also down for me ?

See previous comment.
