### ISSUE TITLE
unable to run retrieve.php

### ISSUE THREAD

**Issue by Sjengstah** [spotweb/spotweb#834]
**unable to run retrieve.php**
I followed the exact steps. from https://github.com/spotweb/spotweb/wiki/Spotweb---Windows-(English)
Either this tutorial is incomplete or not up2date. 

**Have you searched the internet or Github for an answer?**
 - I googled for XAMPP+spotweb
 Xampp+windows+spotweb
 XAMPP+spotweb run retrieve.php
 if i go to spotweb via localhost/spotweb and click retrieve it spins for a second and stops. 

**To Reproduce**
1. install xampp
2. create DB and DB User
3. install spotweb
4. after installing followed the additional steps. 
5. opened the retrieve.php with php.exe by right clicking open with then navigate to xampp/php/php.exe. briefly a window opens and closes
**Expected behavior**
 - spotweb to retrieve data/spots

**Desktop (please complete the following information):**
 - OS:Win11
 - Browser EDGE
 - Spotweb Version [e.g. 1.4.8]

 -  XAMPP for Windows 8.0.28 PHP version Apache/2.4.56 PHP Version 8.0.28
 -  Device information (Windows 11, R7 3700x 36gb ram RX 6650 XT)

**Additional context**
when checking spotweb in the bottom left it shows: Last update: unknown

**Comment by Sweepr** [comment]
Tutorial is correct, you must use the full path when calling php or add it to the PATH environment inside windows and retrieve or be in the root of spotweb.


C:\xampp\php\php-win.exe c:\spotweb\retrieve.php

**Comment by Sweepr** [comment]
Try to open a CMD window and try to execute 'php.exe --version', what does it say?

**Comment by Sjengstah** [comment]
it says nothing shortly opens a window and then closes when I do start php.exe -v 

D:\xampp\php>start php.exe -v

**Comment by Sweepr** [comment]
just 'php.exe -v' not sure where 'start' come from

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Sjengstah** [comment]
PHP 8.0.28 (cli) (built: Feb 14 2023 12:12:55) ( ZTS Visual C++ 2019 x64 )
Copyright (c) The PHP Group
Zend Engine v4.0.28, Copyright (c) Zend Technologies

**Comment by Sjengstah** [comment]
my full paths are d:\xampp\php\php-win.exe d:\xampp\htdocs\spotweb\retrieve.php so how do I execute this instruction correctly?

**Comment by Sjengstah** [comment]
i will start from scartch. if i still run in to issues i will return.

**Comment by Sweepr** [comment]
Just run this 'd:\xampp\php\php-win.exe d:\xampp\htdocs\spotweb\retrieve.php'

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Sjengstah** [comment]
after reinstalling it works. before it was still giving errors. but it works now. thanks for the help @Sweepr
