### ISSUE TITLE
Local Blacklist

### ISSUE THREAD

**Issue by owanneke** [spotweb/spotweb#840]
Is it possible to add a local blacklist file and to add spotters to it from the web UI?

Is there any information available on the existing external blacklist format?
i.e. what is the value used to block a spotter?

e.g.
(Key name = "bla")
3aZW/B4RCV1I5bVNyvs3N10MbGgCYttvILMBUZM3SUelQgOcUxS/aFI8ZrAzHp7z <-- this thing
(/Key)

**Comment by mesa57** [comment]
No, the weblist you see is translated to internal spotweb format.

**Comment by owanneke** [comment]
That answer does not explain the format, nor does it prevent having a local file to be read.
