### ISSUE TITLE
SpotWeb webui not loading in Organizr

### ISSUE THREAD

**Issue by st0rm3rd** [spotweb/spotweb#841]
Running SpotWeb as a container on my QNAP NAS and all working fine. I now started using Organizr and can load all my other web app containers a iframes in Organizr except SpotWeb in my local network (I am not using a proxy manager as I use a VPN to access my NAS from outside world.

Is there a setting in SpotWeb that I am overlooking to allow it to work as an iFrame in Organizr?

**Comment by mesa57** [comment]
I far as i know, spotweb (template) was never designed to run in iFrame Orgnizer.
We invite you to develop a new template for that.
Also you could try to use the mobile template.

**Comment by st0rm3rd** [comment]
Thank you for the invitation. Unfortunately my skills are limited in this area. I guess I will just have use SpotWeb UI outside Organizr unless someone knows a workaround.
