### ISSUE TITLE
add support for docker secrets as env-variabls

### ISSUE THREAD

**Issue by Slevin90** [spotweb/spotweb#842]
**Is your feature request related to a problem? Please describe.**
a current docker compose+.env file shows the database username/password

**Describe the solution you'd like**
add support for docker secret files allowing variables   _FILE to read /run/secrets/supersecretdbpassword 
for DB_NAME, DB_USER, DB_PASS should be secret-enabled  _FILE alternatives

**Describe alternatives you've considered**

**Additional context**

**Comment by mesa57** [comment]
Please contact the docker package developer for that or clearly state what should be changed in spotweb.
Docker packages are not part of spotweb.
