### ISSUE TITLE
Something wrong in directory "/vendor/bin"

### ISSUE THREAD

**Issue by Marlat24** [spotweb/spotweb#845]
The master file which I downloaded on 17 June 2024 has some strange issues in the directory "/vendor/bin".
Some files there are symlinks, but instead of pointing to another filename, they point to a filename which is actually the files contents. See enclosed screenshot.
![Screenshot_20240623_152904](https://github.com/spotweb/spotweb/assets/97066035/1b2c8711-f430-4a37-8e4a-430c4dd5ae62)

**Comment by Sweepr** [comment]
As the comment in the files states: `Proxy PHP file generated by Composer` so is considered normal behavior.

/**
 * Proxy PHP file generated by Composer
 *
 * This file includes the referenced bin path (../php-coveralls/php-coveralls/bin/php-coveralls)
 * using a stream wrapper to prevent the shebang from being output on PHP<8
 *
 * @generated
 */
