### ISSUE TITLE
Spotweb is upset

### ISSUE THREAD

**Issue by ClubNZB** [spotweb/spotweb#847]
**Describe the bug/issue**
 - Since today I see that my index on spotweb is completely confused. 
All "new" spots are from days/months and years ago and still arrive "new".
Today's new spots / post are completely impossible to find and everything is mixed up. See clubnzb.com
Already restored yesterday's backup (nothing wrong) but after the first update everything was mixed up and out of whack again

I also see this with Spotnet, I use a different provider for that, but everything is mixed there too.

More people have this experience?

 - Spotweb Version [latest]
 - Which branch  (Develop)
-  PHP version   8.2
-  Device information Centos 8 server

**Comment by mesa57** [comment]
This is a known problem with USP's which derive from Abavia.
It under investigation with the USP.

**Comment by ClubNZB** [comment]
I see, issue is fixed.
Closed

**Comment by Rouzax** [comment]
> This is a known problem with USP's which derive from Abavia. It under investigation with the USP.

Is this still the case (I'm on Cheapnews) and would that explain why I'm not seeing a lot of spots in my DB anymore?
Looking at Dutch movies it just jumps from 2024 to 2023 to 2014
![image](https://github.com/user-attachments/assets/90e9cf95-ca1a-4863-a7ba-ff2d5f2a6bd0)

**Comment by Sweepr** [comment]
It can be, some USP just renumber their article count without further notice, when that happens, all articles stored in your DB can get messed up and could potentionally lead to DB corruption.

The only way to overcome this is to reset-db and restart retrieve from the beginning.

For example: https://www.eweka.nl/en/numbering_faq

**Comment by Sweepr** [comment]
> How would I know my provider is using Abavia as a source?

Cheapnews is a reseller of a provider that uses Abavia

@mesa57 

Do you have more info about the cause?
As i have seen such issue in the past, and DB reset would mostly solve this problem tho.

**Comment by ClubNZB** [comment]
On what site?
I see spots from yesterday are gone now.
Further no errors

Op di 30 jul 2024 14:51 schreef Rouzax ***@***.***>:

**Comment by mesa57** [comment]
@Sweepr : please look at trello. It is a real mess. Spots are out of order and there are even duplicate message-ids (duplicate spots). Luckely spoteb skips those.

**Comment by Sweepr** [comment]
> @Sweepr : please look at trello. It is a real mess. Spots are out of order and there are even duplicate message-ids (duplicate spots). Luckely spoteb skips those.

I'll have a look, thanks.

I am on the highwinds side, no issue's here.

**Comment by Rouzax** [comment]
> @Sweepr : please look at trello. It is a real mess. Spots are out of order and there are even duplicate message-ids (duplicate spots). Luckely spoteb skips those.

Is it expected to be fixed at one point, or would it be better to move to a different provider?

**Comment by Sweepr** [comment]
> > @Sweepr : please look at trello. It is a real mess. Spots are out of order and there are even duplicate message-ids (duplicate spots). Luckely spoteb skips those.
> 
> Is it expected to be fixed at one point, or would it be better to move to a different provider?

Not sure if it or when it might be resolved.

You can have a look here and pick whatever you like:

https://reddit.com/r/usenet/w/providers

**Comment by Sweepr** [comment]
> If I switch to Eweka, how would I fix the DB?

php upgrade-db.php --reset-db

Then run normal retrieve.

**Comment by Rouzax** [comment]
> > If I switch to Eweka, how would I fix the DB?
> 
> php upgrade-db.php --reset-db
> 
> Then run normal retrieve.

Thanks, filling back up 😄 
![image](https://github.com/user-attachments/assets/5b6c2f77-30d9-4d8b-b59b-cb172925de1c)

**Comment by Rouzax** [comment]
On a side note, the white and blacklist seems to be down
http://bit.do/sp4black
http://bit.do/sp4white

**Comment by mesa57** [comment]
change those to
https://spotlist.tk/spotnet/blacklist.xml
https://spotlist.tk/spotnet/whitelist.xml
