### ISSUE TITLE
Unable to post comment

### ISSUE THREAD

**Issue by Rouzax** [spotweb/spotweb#848]
**Describe the bug/issue**
 - Trying to post a comment and get this error
![image](https://github.com/user-attachments/assets/42ddf325-4f7a-4e05-a60a-f68803779995)

Have enabled Posting in my Eweka account
![image](https://github.com/user-attachments/assets/ee3a95e5-6716-4b94-b22a-91c82cf0999e)

Running latest Develop on Ubuntu 22.04.4 LTS

**Comment by Sweepr** [comment]
Could take a while for changes to take effect, if not consult your USP for help.

Does the user have correct permission?

**Comment by Rouzax** [comment]
Changed the setting in Eweka one day ago.
my spotweb user is Admin, is there anything else I should check?

**Comment by Sweepr** [comment]
Could take a while for changes to take effect, if not consult your USP for help.

Does the user have correct permission?

Try to contact your USP and ask them.if there is any issue.

**Comment by Rouzax** [comment]
Issue fixed, besides enabling the option to post with Eweka. I also needed to switch to a different server.
post.eweka.nl instead of the news.eweka.nl

**Comment by Sweepr** [comment]
> Issue fixed, besides enabling the option to post with Eweka. I also needed to switch to a different server. post.eweka.nl instead of the news.eweka.nl

Thank you for the feedback!
