### ISSUE TITLE
[New issue]Warning: Array to string conversion

### ISSUE THREAD

**Issue by SpIdErPiGgY1984** [spotweb/spotweb#856]
**Describe the bug/issue**
When you click on the edit spot icon in the overview

**To Reproduce**
1. Go to 'overview'
2. Click on 'Edit spot icon'
3 See error:

```
Warning: Array to string conversion in /var/www/vhosts/myarea51secrets.com/httpdocs/nzb/lib/page/SpotPage_editspot.php on line 39
Warning: Array to string conversion in /var/www/vhosts/myarea51secrets.com/httpdocs/nzb/lib/page/SpotPage_editspot.php on line 39
Warning: Array to string conversion in /var/www/vhosts/myarea51secrets.com/httpdocs/nzb/lib/page/SpotPage_editspot.php on line 39
Warning: Array to string conversion in /var/www/vhosts/myarea51secrets.com/httpdocs/nzb/lib/page/SpotPage_editspot.php on line 39
```

**Screenshots**
![2024-11-08 05 57 49](https://github.com/user-attachments/assets/51915f72-deac-4e6c-90e0-cc5fab7f2b8d)

Debian 12.7
PHP  8.3.13
MySQL(i) 11.4.4-MariaDB-deb12
FPM by Apache

**Comment by mesa57** [comment]
Iets eenvoudiger (regel 39)
`     $fullSpot['description'] = str_replace('[br]', "\n", $fullSpot['description']);`

**Comment by SpIdErPiGgY1984** [comment]
> Iets eenvoudiger (regel 39) ` $fullSpot['description'] = str_replace('[br]', "\n", $fullSpot['description']);`

Werkt ook 👌
