### ISSUE TITLE
To high load / spotweb down

### ISSUE THREAD

**Issue by ClubNZB** [spotweb/spotweb#857]
Hi, 
My spotweb servion is running on a:
- Ubuntu 22.04
- PHP 8.3.33
- MySQL 10.6.20
- Latest version of Spotweb

Somethimes my VPS server with 100GB disk and 10 GB Ram will be go offline / down with a extreamly high load.
See attach the generated load file.
What can I do to get this over?

Now I set the domain on a PHP version 7.3.33
Thanks for the help!

ClubNZB[
[spotweb.txt](https://github.com/user-attachments/files/17681004/spotweb.txt)
](url)

**Comment by mesa57** [comment]
Is response now better under php 7.3.33 ?
I have tested with php 8.1 with excellent response.

**Comment by ClubNZB** [comment]
> Is response now better under php 7.3.33 ? I have tested with php 8.1 with excellent response.

It is now for 2 hrs on 7.3 PHP but the 8.3.33 version was working fine for 16 hrs before the high load
I was hoping there is a small code fix, 
tcp   CLOSE-WAIT is a lot of lines

**Comment by ClubNZB** [comment]
> It's common with website's, this looks like typical crawler, bad bot behaviour:
> 
> https://stackoverflow.com/questions/37583451/cpu-high-load-because-of-search-engines-mass-crawling

robots.txt is there, disallow /

**Comment by ClubNZB** [comment]
I use: CSF+LFD, so Fail2Ban is almost the same.
Thanks Sweepr for your last commend, but the "fun" of Spotweb is OPEN and not closed.
I know what you meen, looking for the bad crawlers now

**Comment by mesa57** [comment]
@Sweepr Example for a fail2ban badbots jail filter.

```
# Fail2Ban configuration file
#
# Regexp to catch known spambots and software alike. Please verify
# that it is your intent to block IPs which were driven by
# above mentioned bots.


[Definition]

badbotscustom = EmailCollector|WebEMailExtrac|TrackBack/1\.02|sogou music spider|Bytespider|bytedance|(?:Mozilla/\d+\.\d+ )?Jorgee
badbots = Atomic_Email_Hunter/4\.0|atSpider/1\.0|autoemailspider|bwh3_user_agent|China Local Browse 2\.6|ContactBot/0\.2|ContentSmartz|DataCha0s/2\.0|DBrowse 1\.4b|DBrowse 1\.4d|Demo Bot DOT 16b|Demo Bot Z 16b|DSurf15a 01|DSurf15a 71|DSurf15a 81|DSurf15a VA|EBrowse 1\.4b|Educate Search VxB|EmailSiphon|EmailSpider|EmailWolf 1\.00|ESurf15a 15|ExtractorPro|Franklin Locator 1\.8|FSurf15a 01|Full Web Bot 0416B|Full Web Bot 0516B|Full Web Bot 2816B|Guestbook Auto Submitter|Industry Program 1\.0\.x|ISC Systems iRc Search 2\.1|IUPUI Research Bot v 1\.9a|LARBIN-EXPERIMENTAL \(efp@gmx\.net\)|LetsCrawl\.com/1\.0 \+http\://letscrawl\.com/|Lincoln State Web Browser|LMQueueBot/0\.2|LWP\:\:Simple/5\.803|Mac Finder 1\.0\.xx|MFC Foundation Class Library 4\.0|Microsoft URL Control - 6\.00\.8xxx|Missauga Locate 1\.0\.0|Missigua Locator 1\.9|Missouri College Browse|Mizzu Labs 2\.2|Mo College 1\.9|MVAClient|Mozilla/2\.0 \(compatible; NEWT ActiveX; Win32\)|Mozilla/3\.0 \(compatible; Indy Library\)|Mozilla/3\.0 \(compatible; scan4mail \(advanced version\) http\://www\.peterspages\.net/?scan4mail\)|Mozilla/4\.0 \(compatible; Advanced Email Extractor v2\.xx\)|Mozilla/4\.0 \(compatible; Iplexx Spider/1\.0 http\://www\.iplexx\.at\)|Mozilla/4\.0 \(compatible; MSIE 5\.0; Windows NT; DigExt; DTS Agent|Mozilla/4\.0 efp@gmx\.net|Mozilla/5\.0 \(Version\: xxxx Type\:xx\)|NameOfAgent \(CMS Spider\)|NASA Search 1\.0|Nsauditor/1\.x|PBrowse 1\.4b|PEval 1\.4b|Poirot|Port Huron Labs|Production Bot 0116B|Production Bot 2016B|Production Bot DOT 3016B|Program Shareware 1\.0\.2|PSurf15a 11|PSurf15a 51|PSurf15a VA|psycheclone|RSurf15a 41|RSurf15a 51|RSurf15a 81|searchbot admin@google\.com|ShablastBot 1\.0|snap\.com beta crawler v0|Snapbot/1\.0|Snapbot/1\.0 \(Snap Shots&#44; \+http\://www\.snap\.com\)|sogou develop spider|Sogou Orion spider/3\.0\(\+http\://www\.sogou\.com/docs/help/webmasters\.htm#07\)|sogou spider|Sogou web spider/3\.0\(\+http\://www\.sogou\.com/docs/help/webmasters\.htm#07\)|sohu agent|SSurf15a 11 |TSurf15a 11|Under the Rainbow 2\.2|User-Agent\: Mozilla/4\.0 \(compatible; MSIE 6\.0; Windows NT 5\.1\)|VadixBot|WebVulnCrawl\.unknown/1\.0 libwww-perl/5\.803|Wells Search II|WEP Search 00

failregex = ^<HOST> -.*"(GET|POST|HEAD).*HTTP.*(?:%(badbots)s|%(badbotscustom)s).*$

ignoreregex =

datepattern = ^[^\[]*\[({DATE})
              {^LN-BEG}

# DEV Notes:
# List of bad bots fetched from http://www.user-agents.org
# Generated on Thu Nov  7 14:23:35 PST 2013 by files/gen_badbots.
#
# Author: Yaroslav Halchenko

```

**Comment by Logic-7E8** [comment]
> fail2ban badbots jail filte

Ah cool, never look into F2B in depth as i thought it served it's purpose only to block executive failed login attempts.
But look promising, hopefully he can solve his problem using this.

**Comment by ClubNZB** [comment]
> @Sweepr Example for a fail2ban badbots jail filter.
> 
> ```
> # Fail2Ban configuration file
> #
> # Regexp to catch known spambots and software alike. Please verify
> # that it is your intent to block IPs which were driven by
> # above mentioned bots.
> 
> 
> [Definition]
> 
> badbotscustom = EmailCollector|WebEMailExtrac|TrackBack/1\.02|sogou music spider|Bytespider|bytedance|(?:Mozilla/\d+\.\d+ )?Jorgee
> badbots = Atomic_Email_Hunter/4\.0|atSpider/1\.0|autoemailspider|bwh3_user_agent|China Local Browse 2\.6|ContactBot/0\.2|ContentSmartz|DataCha0s/2\.0|DBrowse 1\.4b|DBrowse 1\.4d|Demo Bot DOT 16b|Demo Bot Z 16b|DSurf15a 01|DSurf15a 71|DSurf15a 81|DSurf15a VA|EBrowse 1\.4b|Educate Search VxB|EmailSiphon|EmailSpider|EmailWolf 1\.00|ESurf15a 15|ExtractorPro|Franklin Locator 1\.8|FSurf15a 01|Full Web Bot 0416B|Full Web Bot 0516B|Full Web Bot 2816B|Guestbook Auto Submitter|Industry Program 1\.0\.x|ISC Systems iRc Search 2\.1|IUPUI Research Bot v 1\.9a|LARBIN-EXPERIMENTAL \(efp@gmx\.net\)|LetsCrawl\.com/1\.0 \+http\://letscrawl\.com/|Lincoln State Web Browser|LMQueueBot/0\.2|LWP\:\:Simple/5\.803|Mac Finder 1\.0\.xx|MFC Foundation Class Library 4\.0|Microsoft URL Control - 6\.00\.8xxx|Missauga Locate 1\.0\.0|Missigua Locator 1\.9|Missouri College Browse|Mizzu Labs 2\.2|Mo College 1\.9|MVAClient|Mozilla/2\.0 \(compatible; NEWT ActiveX; Win32\)|Mozilla/3\.0 \(compatible; Indy Library\)|Mozilla/3\.0 \(compatible; scan4mail \(advanced version\) http\://www\.peterspages\.net/?scan4mail\)|Mozilla/4\.0 \(compatible; Advanced Email Extractor v2\.xx\)|Mozilla/4\.0 \(compatible; Iplexx Spider/1\.0 http\://www\.iplexx\.at\)|Mozilla/4\.0 \(compatible; MSIE 5\.0; Windows NT; DigExt; DTS Agent|Mozilla/4\.0 efp@gmx\.net|Mozilla/5\.0 \(Version\: xxxx Type\:xx\)|NameOfAgent \(CMS Spider\)|NASA Search 1\.0|Nsauditor/1\.x|PBrowse 1\.4b|PEval 1\.4b|Poirot|Port Huron Labs|Production Bot 0116B|Production Bot 2016B|Production Bot DOT 3016B|Program Shareware 1\.0\.2|PSurf15a 11|PSurf15a 51|PSurf15a VA|psycheclone|RSurf15a 41|RSurf15a 51|RSurf15a 81|searchbot admin@google\.com|ShablastBot 1\.0|snap\.com beta crawler v0|Snapbot/1\.0|Snapbot/1\.0 \(Snap Shots&#44; \+http\://www\.snap\.com\)|sogou develop spider|Sogou Orion spider/3\.0\(\+http\://www\.sogou\.com/docs/help/webmasters\.htm#07\)|sogou spider|Sogou web spider/3\.0\(\+http\://www\.sogou\.com/docs/help/webmasters\.htm#07\)|sohu agent|SSurf15a 11 |TSurf15a 11|Under the Rainbow 2\.2|User-Agent\: Mozilla/4\.0 \(compatible; MSIE 6\.0; Windows NT 5\.1\)|VadixBot|WebVulnCrawl\.unknown/1\.0 libwww-perl/5\.803|Wells Search II|WEP Search 00
> 
> failregex = ^<HOST> -.*"(GET|POST|HEAD).*HTTP.*(?:%(badbots)s|%(badbotscustom)s).*$
> 
> ignoreregex =
> 
> datepattern = ^[^\[]*\[({DATE})
>               {^LN-BEG}
> 
> # DEV Notes:
> # List of bad bots fetched from http://www.user-agents.org
> # Generated on Thu Nov  7 14:23:35 PST 2013 by files/gen_badbots.
> #
> # Author: Yaroslav Halchenko
> ```

for my information, I need to copy this code into the  /etc/fail2ban/jail.local?

**Comment by mesa57** [comment]
In my configuration it is in
![afbeelding](https://github.com/user-attachments/assets/73ae8be7-791a-49b7-99cf-878014d3b829)

**Comment by ClubNZB** [comment]
> In my configuration it is in ![afbeelding](https://private-user-images.githubusercontent.com/6350469/384506879-73ae8be7-791a-49b7-99cf-878014d3b829.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwOTg2NDMsIm5iZiI6MTczMTA5ODM0MywicGF0aCI6Ii82MzUwNDY5LzM4NDUwNjg3OS03M2FlOGJlNy03OTFhLTQ5YjctOTljZi04NzgwMTRkM2I4MjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDhUMjAzOTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDI3MzAzNzVjYTU0ZGZkNmY0N2JmNzExNTE5MzE3ZWRhZTQ5M2RiYWRhZGM3MDQ4MzdjNzVlZjEwYTg3MTZjZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.D4UiF1ogjhA36WpGaCXkdBUHOSeIC37CJL7dZbiLYDg)

Hi Mesa57,

I try to set-it-up but I got:
Nov 08 21:38:01 vps1.clubnzb.com systemd[1]: Started fail2ban.service - Fail2Ban Service.
Nov 08 21:38:01 vps1.clubnzb.com fail2ban-server[291919]: 2024-11-08 21:38:01,677 fail2ban.configreader   [291919]: WARNING 'allowipv6' not defined in 'Definition'. Using default one: 'auto'
Nov 08 21:38:01 vps1.clubnzb.com fail2ban-server[291919]: 2024-11-08 21:38:01,705 fail2ban.configreader   [291919]: ERROR   Found no accessible config files for 'filter.d/sasl' under /etc/fail2ban
Nov 08 21:38:01 vps1.clubnzb.com fail2ban-server[291919]: 2024-11-08 21:38:01,705 fail2ban.jailreader     [291919]: ERROR   Unable to read the filter 'sasl'
Nov 08 21:38:01 vps1.clubnzb.com fail2ban-server[291919]: 2024-11-08 21:38:01,705 fail2ban.jailsreader    [291919]: ERROR   Errors in jail 'sasl'. Skipping...
Nov 08 21:38:01 vps1.clubnzb.com fail2ban-server[291919]: 2024-11-08 21:38:01,706 fail2ban.configreader   [291919]: ERROR   Found no accessible config files for 'filter.d/badbots' under /etc/fail2ban
Nov 08 21:38:01 vps1.clubnzb.com fail2ban-server[291919]: 2024-11-08 21:38:01,706 fail2ban.jailreader     [291919]: ERROR   Unable to read the filter 'badbots'
Nov 08 21:38:01 vps1.clubnzb.com fail2ban-server[291919]: 2024-11-08 21:38:01,706 fail2ban.jailsreader    [291919]: ERROR   Errors in jail 'badbots'. Skipping...
Nov 08 21:38:02 vps1.clubnzb.com fail2ban-server[291919]: Server ready

Can you contact me at clubnzb at gmail dot com to help me witch the fix (by logging in as root)
Thanks

**Comment by mesa57** [comment]
Sorry, first this exceeds spotweb issues, second i am not a fail2ban specialist, 
third i use **virtualmin** on my vps which offers very easy fail2ban configuration via the webinterface with numerous predefined settings which you only have to set active.

**Comment by mesa57** [comment]
If you still want any help you can email me at mesa57 at protonmail dot com

**Comment by ClubNZB** [comment]
Issue is still here see att file. 
Fail2Ban is running incl BadBots filter
I can`t see the issue
[Uploading load.txt…]()
