### ISSUE TITLE
High Load part2

### ISSUE THREAD

**Issue by ClubNZB** [spotweb/spotweb#859]
See: https://github.com/spotweb/spotweb/issues/857
Hi,
My spotweb servion is running on a:
Ubuntu 24.04
PHP 7.3.33
MySQL 10.6.20
Latest version of Spotweb
Somethimes my VPS server with 100GB disk and 10 GB Ram will be go offline / down with a extreamly high load.
See attach the generated load file.

Fail2Ban is running incl BadBots filter
What can I do to get this over?

[load.txt](https://github.com/user-attachments/files/17751991/load.txt)

**Comment by mesa57** [comment]
I don't see much of a problem. However fail2banis using 11% cpu (which is in limits).

**Comment by ClubNZB** [comment]
Maybe it is a DirectAdmin thing?
On what VPS control panel is running spotweb at you??

**Comment by mesa57** [comment]
please pm me at mesa57 at protonmail.com or contact me via skype.

**Comment by ClubNZB** [comment]
> please pm me at mesa57 at protonmail.com or contact me via skype.

I will do later today... 
Now the server is reinstalled
