### ISSUE TITLE
Big screen == no infinite scroll

### ISSUE THREAD

**Issue by gijsroge** [spotweb/spotweb#88]
I have a 2260x1440 monitor and see this -> https://monosnap.com/file/zgT7PrwG9Of7u1RVjngebuPsvEi2Xp.png

The inifnite scroll function is not triggered.

**Comment by Sweepr** [comment]
Yes, did you try with the last spot falling
Off-screen at the bottom?

**Comment by gijsroge** [comment]
Yes if I decrease the window height so the last spot falls off viewport it works.

**Comment by Sweepr** [comment]
Ok, so its working.

Now if you set your window size as you desire and then set the amount of spots to 100, so the last spot is off screen it should be ok.

**Comment by gijsroge** [comment]
Yeah, i'm aware I can fix it like that. But that doesn't take away this is probably an issue that might affect more people than you think. You should check your analytics if lots of people are using 1440+ monitors. If so I think its important to fix an issue that blocks content from loading :D

**Comment by Sweepr** [comment]
I understand,

The next page is triggered by a jQuery function called .scroll(), in order for the function to work you need a scroll bar on the righthand side of your screen in your browser, and i don't see any.

Without a scroll bar on the right side the scroll is not triggered.

**Comment by xyanide** [comment]
@gijsroge #90 fixes the issue you had. I had the same problem when zoomed in.
Fixed it by rounding the value up because it didn't match exactly.

**Comment by gijsroge** [comment]
@xyanide +1

**Comment by xyanide** [comment]
Hmm wait, might not have exactly fixed your issue as it doens'nt work with big screens, you still need to be able to scroll.
I'll look into it.

**Comment by gijsroge** [comment]
Or do another check in the if statement that calculates the content height vs window height. 

Like this:
```
if($(document).scrollTop() >= $(document).height() - $(window).height() && $(document).height() >= $(window).height() && pagenr > 0 && $("#overlay").is(':hidden') || $('.spots').outerHeight() < $(window).height()) {
```

**Comment by mesa57** [comment]
Solved in latest commit
