### ISSUE TITLE
SpotWeb v0.67.28.31 on PHP v5.3.29 crashed object(SqlErrorException)#26 (8) { ["message":protected]=> string(80) "HY000: 126: Incorrect key file for table '/tmp/#sql_adf_0.MYI'; try to repair it

### ISSUE THREAD

**Issue by jurgen36** [spotweb/spotweb#95]
I succesfully installed Spotweb on a NAS269L and used it for years.

I now installed it on a NAS569L and got the following error after using it for three times in two days:

SpotWeb v0.67.28.31 on PHP v5.3.29 crashed object(SqlErrorException)#26 (8) { ["message":protected]=> string(80) "HY000: 126: Incorrect key file for table '/tmp/#sql_adf_0.MYI'; try to repair it"

Below the whole message.

I don't know what I need to do in order to get it to work again.

Thanks for the help!

Kind regards,

Jurgen

**Comment by jurgen36** [comment]
SpotWeb v0.67.28.31 on PHP v5.3.29 crashed object(SqlErrorException)#26 (8) { ["message":protected]=> string(80) "HY000: 126: Incorrect key file for table '/tmp/#sql_adf_0.MYI'; try to repair it" ["string":"CustomException":private]=> NULL ["code":protected]=> int(-1) ["file":protected]=> string(67) "/share/CACHEDEV1_DATA/.qpkg/spotweb/spotweb/lib/dbeng/dbeng_pdo.php" ["line":protected]=> int(59) ["string":"Exception":private]=> string(0) "" ["trace":"Exception":private]=> array(5) { [0]=> array(6) { ["file"]=> string(67) "/share/CACHEDEV1_DATA/.qpkg/spotweb/spotweb/lib/dbeng/dbeng_pdo.php" ["line"]=> int(146) ["function"]=> string(4) "exec" ["class"]=> string(9) "dbeng_pdo" ["type"]=> string(2) "->" ["args"]=> array(2) { [0]=> string(1576) "SELECT s.id AS id, s.messageid AS messageid, s.category AS category, s.poster AS poster, l.download as downloadstamp, l.watch as watchstamp, l.seen AS seenstamp, s.subcata AS subcata, s.subcatb AS subcatb, s.subcatc AS subcatc, s.subcatd AS subcatd, s.subcatz AS subcatz, s.title AS title, s.tag AS tag, s.stamp AS stamp, s.moderated AS moderated, s.filesize AS filesize, s.spotrating AS rating, s.commentcount AS commentcount, s.reportcount AS reportcount, s.spotterid AS spotterid, s.editstamp AS editstamp, s.editor AS editor, f.verified AS verified, COALESCE(bl.idtype, wl.idtype, gwl.idtype) AS idtype FROM spots AS s LEFT JOIN spotstatelist AS l on ((s.messageid = l.messageid) AND (l.ouruserid = 3)) LEFT JOIN spotsfull AS f ON (s.messageid = f.messageid) LEFT JOIN spotteridblacklist as bl ON ((bl.spotterid = s.spotterid) AND ((bl.ouruserid = 3) OR (bl.ouruserid = -1)) AND (bl.idtype = 1)) LEFT JOIN spotteridblacklist as wl on ((wl.spotterid = s.spotterid) AND ((wl.ouruserid = 3) AND (wl.idtype = 2))) LEFT JOIN spotteridblacklist as gwl on ((gwl.spotterid = s.spotterid) AND ((gwl.ouruserid = -1) AND (gwl.idtype = 2))) WHERE (bl.spotterid IS NULL) ORDER BY s.reversestamp ASC LIMIT 26 OFFSET 0" [1]=> array(0) { } } } [1]=> array(6) { ["file"]=> string(74) "/share/CACHEDEV1_DATA/.qpkg/spotweb/spotweb/lib/dao/Base/Dao_Base_Spot.php" ["line"]=> int(123) ["function"]=> string(10) "arrayQuery" ["class"]=> string(9) "dbeng_pdo" ["type"]=> string(2) "->" ["args"]=> array(1) { [0]=> string(1576) "SELECT s.id AS id, s.messageid AS messageid, s.category AS category, s.poster AS poster, l.download as downloadstamp, l.watch as watchstamp, l.seen AS seenstamp, s.subcata AS subcata, s.subcatb AS subcatb, s.subcatc AS subcatc, s.subcatd AS subcatd, s.subcatz AS subcatz, s.title AS title, s.tag AS tag, s.stamp AS stamp, s.moderated AS moderated, s.filesize AS filesize, s.spotrating AS rating, s.commentcount AS commentcount, s.reportcount AS reportcount, s.spotterid AS spotterid, s.editstamp AS editstamp, s.editor AS editor, f.verified AS verified, COALESCE(bl.idtype, wl.idtype, gwl.idtype) AS idtype FROM spots AS s LEFT JOIN spotstatelist AS l on ((s.messageid = l.messageid) AND (l.ouruserid = 3)) LEFT JOIN spotsfull AS f ON (s.messageid = f.messageid) LEFT JOIN spotteridblacklist as bl ON ((bl.spotterid = s.spotterid) AND ((bl.ouruserid = 3) OR (bl.ouruserid = -1)) AND (bl.idtype = 1)) LEFT JOIN spotteridblacklist as wl on ((wl.spotterid = s.spotterid) AND ((wl.ouruserid = 3) AND (wl.idtype = 2))) LEFT JOIN spotteridblacklist as gwl on ((gwl.spotterid = s.spotterid) AND ((gwl.ouruserid = -1) AND (gwl.idtype = 2))) WHERE (bl.spotterid IS NULL) ORDER BY s.reversestamp ASC LIMIT 26 OFFSET 0" } } [2]=> array(6) { ["file"]=> string(98) "/share/CACHEDEV1_DATA/.qpkg/spotweb/spotweb/lib/services/Providers/Services_Providers_SpotList.php" ["line"]=> int(23) ["function"]=> string(8) "getSpots" ["class"]=> string(13) "Dao_Base_Spot" ["type"]=> string(2) "->" ["args"]=> array(4) { [0]=> string(1) "3" [1]=> int(0) [2]=> int(25) [3]=> array(9) { ["filter"]=> string(0) "" ["categoryList"]=> array(0) { } ["unfiltered"]=> bool(false) ["strongNotList"]=> array(0) { } ["filterValueList"]=> array(0) { } ["additionalFields"]=> array(0) { } ["additionalTables"]=> array(0) { } ["additionalJoins"]=> array(0) { } ["sortFields"]=> array(1) { [0]=> array(4) { ["field"]=> string(7) "s.stamp" ["direction"]=> string(4) "DESC" ["autoadded"]=> bool(true) ["friendlyname"]=> NULL } } } } } [3]=> array(6) { ["file"]=> string(71) "/share/CACHEDEV1_DATA/.qpkg/spotweb/spotweb/lib/page/SpotPage_index.php" ["line"]=> int(101) ["function"]=> string(13) "fetchSpotList" ["class"]=> string(27) "Services_Providers_SpotList" ["type"]=> string(2) "->" ["args"]=> array(4) { [0]=> string(1) "3" [1]=> int(0) [2]=> int(25) [3]=> array(9) { ["filter"]=> string(0) "" ["categoryList"]=> array(0) { } ["unfiltered"]=> bool(false) ["strongNotList"]=> array(0) { } ["filterValueList"]=> array(0) { } ["additionalFields"]=> array(0) { } ["additionalTables"]=> array(0) { } ["additionalJoins"]=> array(0) { } ["sortFields"]=> array(1) { [0]=> array(4) { ["field"]=> string(7) "s.stamp" ["direction"]=> string(4) "DESC" ["autoadded"]=> bool(true) ["friendlyname"]=> NULL } } } } } [4]=> array(6) { ["file"]=> string(53) "/share/CACHEDEV1_DATA/.qpkg/spotweb/spotweb/index.php" ["line"]=> int(381) ["function"]=> string(6) "render" ["class"]=> string(14) "SpotPage_index" ["type"]=> string(2) "->" ["args"]=> array(0) { } } } ["previous":"Exception":private]=> NULL } HY000: 126: Incorrect key file for table '/tmp/#sql_adf_0.MYI'; try to repair it

**Comment by Sweepr** [comment]
Login to phpmyadmin and see if any table had been corrupted, if so try repair.

**Comment by jurgen36** [comment]
Okay thanks Sweepr. I checked and have no corrupted tables. Table: commentsxover is 2,6 GiB (of 2,8 GiB in total) and cannot be checked or it can but it will take a while I guess. Should I drop this table perhaps?

**Comment by Sweepr** [comment]
No NEVER ever drop tables, unless you wish to start over.

HY000: 126: Incorrect key file for table '/tmp/#sql_adf_0.MYI'; try to repair it 

Try running php upgrade-db.php and post the outcome please?

**Comment by jurgen36** [comment]
Ok I run the following line via putty:

/mnt/ext/opt/apache/bin/php /share/Web/spotweb/upgrade-db.php

It started to check and the following 'modify' in the log did the trick I guess:

Validating debuglog(microtime)
                Modifying column microtime (charset) on debuglog
        Validating debuglog(level)

Thanks Sweepr for your help!
