### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by dterweij** [spotweb/spotweb#96]
I think that spotweb needs to be refactored for PHP 7. Tho it works, but shows a lot warnings.
My old server died so i installed everything fresh and newer :)

**Comment by Wally73** [comment]
php 7??? last stable one is 5.6.14

**Comment by Sweepr** [comment]
PHP 7 is in RC stage, the release candidate features bug fixes and stability improvements, but it cannot be used in production yet

**Comment by futurevision** [comment]
PHP 7 is planned to arrive next month already. I'm not sure why this is closed since this can become an issue for a lot of users real fast.

**Comment by Sweepr** [comment]
It's not released officially, so no need to keep this open, will reopen when needed.

As it seems to run fine in php 7, but show warnings, could you maybe post the warnings so we can see whats happening?

**Comment by denniskrol** [comment]
```
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Net_NNTP_Client has a deprecated constructor in \spotweb\NNTP\Client.php on line 87
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Net_NNTP_Protocol_Client has a deprecated constructor in \spotweb\NNTP\Protocol\Client.php on line 131
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Crypt_Hash has a deprecated constructor in \spotweb\vendor\phpseclib\Crypt\Hash.php on line 85
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Crypt_RSA has a deprecated constructor in \spotweb\vendor\phpseclib\Crypt\RSA.php on line 251
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Math_BigInteger has a deprecated constructor in \spotweb\vendor\phpseclib\Math\BigInteger.php on line 193
```
It works, but it's gonna break some day.

**Comment by blaatpraat** [comment]
In the meantime PHP 7 is released, and already has received an update.

I think you should reopen this bug...

**Comment by mesa57** [comment]
This is not a bug, but a feature request. Spotweb was not designed for php 7.
And of cause you can create a branche and update the code accordingly.

**Comment by CptChaos** [comment]
Mesa is referring to this pull request:
https://github.com/spotweb/spotweb/pull/104
Where actually not much happened.
