### ISSUE TITLE
Connection timeout to news.newshosting.com

### ISSUE THREAD

**Issue by onitreb** [spotweb/spotweb#97]
Sorry, I do not know if this is a spotweb or newshosting issue (or my own :)

I run spotweb on dreamhost shared hosting, using newshosting.com (for about 4 years, no problem).

Recently I was having trouble with spotweb, git-pulled up to date, but no luck. So I reinstalled.
(I cleared my spotweb directory and dropped all tables from my mysql db.)
Install went fine, the install test is all OK's. php5.6 (was on 5.4).

But when I attempt to verify usenet server or retrieve spots after installation, it errors out:

stream_socket_client(): unable to connect to ssl://news.newshosting.com:563 (Connection timed out)
Error while connecting to server (server did not respond) [response: ""] [response: ""] 

I can ping news.newshosting.com from shell.
I've tried an alternate usenet host and that works. So is this a newhosting error?

**Comment by Sweepr** [comment]
This could be related to a known issue where a fix is not yet found.

Login as Admin, goto Config -> Settings -> change your USP to non-ssl, change the port to 119, and disable Encryption. (Don't forget to properly forward the port)

**Comment by onitreb** [comment]
Thanks for the reply. 

I have tried using 119 unencrypted, but I get the same error. I do not know if I can control any port forwarding from my hosting account.

**Comment by Sweepr** [comment]
Ok, that's strange, other usenet provider works, but this one does not?

Did you contact you hosting provider and ask them if port 119 is open?

**Comment by onitreb** [comment]
According to http://www.yougetsignal.com/tools/open-ports/ 119 is open.

I have emailed newshosting.com support as well.

Here is the entire error message I receive while trying to run retrieve.php:

Retrieving new Spots from server news.newshosting.com...

Warning: stream_socket_client(): unable to connect to tcp://news.newshosting.com:119 (Connection timed out) in /home/paulb/spotweb.stealmyideas.org/NNTP/Protocol/Client.php on line 693
SpotWeb v0.67.28.31 on PHP v5.4.42 crashed

Fatal error occured while connecting to the newsserver:
  (-1) Error while connecting to server (server did not respond) [response: ""] [response: ""]


#0 /home/paulb/spotweb.stealmyideas.org/lib/services/Nntp/Services_Nntp_Engine.php(120): Services_Nntp_Engine->connect()
#1 /home/paulb/spotweb.stealmyideas.org/lib/services/Retriever/Services_Retriever_Base.php(112): Services_Nntp_Engine->selectGroup('free.pt')
#2 /home/paulb/spotweb.stealmyideas.org/lib/services/Retriever/Services_Retriever_Base.php(280): Services_Retriever_Base->connect(Array)
#3 /home/paulb/spotweb.stealmyideas.org/retrieve.php(154): Services_Retriever_Base->perform()
#4 {main}

**Comment by Sweepr** [comment]
Could be a temporary issue at the USp, could you try port 9000?

**Comment by onitreb** [comment]
9000 is not supported by newshosting.
Hostname: news.newshosting.com
Port: 119
Additional NNTP Ports: 23, 25, 80, 3128
SSL Ports: 563, 443

I tried 3128 and it seemed to work. Then it stopped. Now I get a time out on that port. :/

**Comment by Sweepr** [comment]
Ok, are you sure you aren't using too many connections?

Is spotweb the only program you use that USP for?

It really looks like either the USP is throtheling, or blocking your hosts IP.

can you connect to the USP using spotnet frok your local PC?

**Comment by onitreb** [comment]
You may be right. It seems like they are blocking my connection. I've described the issue to newhosting, and will report back when I receive a reply from them.

I installed spotnet and it seems to be downloading fine.

**Comment by onitreb** [comment]
Just wanted to add some information. From the shell of the server of the spotweb install I did a port scan of news.newshosting.com. Here are the results. It seems that the ports are open.

Starting Nmap 5.21 ( http://nmap.org ) at 2015-10-14 22:41 PDT
Nmap scan report for news.newshosting.com (69.16.179.29)
Host is up (0.00088s latency).
Hostname news.newshosting.com resolves to 2 IPs. Only scanned 69.16.179.29
Not shown: 988 closed ports
PORT     STATE    SERVICE
23/tcp   open     telnet
25/tcp   filtered smtp
80/tcp   open     http
119/tcp  open     nntp
443/tcp  open     https
563/tcp  open     snews
3128/tcp open     squid-http
7000/tcp open     afs3-fileserver
8000/tcp open     http-alt
8080/tcp open     http-proxy
9000/tcp open     cslistener
9090/tcp open     zeus-admin

**Comment by Sweepr** [comment]
This does not mean your hosts IP is not blocked or blacklisted by the firewall of the USP for some reason, which i think is going on here.

I think your hosts IP got blacklisted on the USP, you need to wait for their reply

**Comment by onitreb** [comment]
I see. I appreciate your help. thanks.

**Comment by Sweepr** [comment]
No problem, keep us updated when you get the reply of your USP.

**Comment by onitreb** [comment]
Sorry, I never received a support reply from my USP. But I have a strong feeling they are the culprit.
