### ISSUE TITLE
No longer retrieves spots

### ISSUE THREAD

**Issue by Rheimans** [spotweb/spotweb#99]
Recently i forgot to extend my Usenet Subscription. I noticed it when spotweb no longer retrieved any spots.

Anyways, there lies my problem. For some reason spotweb refuses to retrieve spots ever since it could not connect to my usenet account.

Even after when i reactivated my usenet account, it still refuses to retrieve spots.

Is there a option to reconnect? What do i need to do, to make spotweb retrieve spots again? Because spotweb is really handy to have.

Thanks in advance for any help.

Kind Regards,

Remco

**Comment by Sweepr** [comment]
Could you post the exact PHP error message ?

**Comment by Rheimans** [comment]
It does not show any php error message. Can i retrieve this somewhere else?

**Comment by Sweepr** [comment]
Sure, goto the root dir of spotweb using commandline, and run php retrieve.php

**Comment by Rheimans** [comment]
I will do this the moment i get home. Currently at work. I will let you know here again what came out of running the retrieve.php file in command.

**Comment by Rheimans** [comment]
I ran de file via the webbrowser.

by going to my domainname then spotweb/retrieve.php.

it gives the following message:

SpotWeb v0.67.28.31 on PHP v5.5.29 crashed Fatal error occured retrieving reports: Permission denied [21] for objectid [] #0 {main}

**Comment by Sweepr** [comment]
Did you try to run this as root or as user?

**Comment by Rheimans** [comment]
I used chrome to open the php file and gave me that error. I did not use commandline to run it.

**Comment by Wally73** [comment]
you need to run it from command line in your spotweb root folder

**Comment by Rheimans** [comment]
Can you post the command i need to run normally i can manage to find it.  However my isp is down got not internet, phone and tv. And its difficult to search it on a phone.

**Comment by Sweepr** [comment]
From commandline, 

php retrieve.php

**Comment by Rheimans** [comment]
Finally internet is back so its bit easier to do thing now.

what is the best way to run this? i cna open command promt from the spotweb folder so the command prompt looks like this:

Y:\spotweb>

Thne i try and run "php retrieve.php" but says php is not a reconized as an internal or external command.

Gues im doing that wrong.

I downloaded PHP and put it somewhere easy, and also putting the retrieve.php there. but i take it that wont work. because it spits out this.

c:\php>php c:\php\retrieve.php

Warning: require_once(lib/SpotClassAutoload.php): failed to open stream: No such file or directory in C:\php\retrieve.php on line 13

Fatal error: require_once(): Failed opening required 'lib/SpotClassAutoload.php' (include_path='.;C:\php\pear') in C:\php\retrieve.php on line 13

**Comment by Sweepr** [comment]
Ah, your using Xammp or Wamp right.?
Did you follow this guide?

Youtube tutorial: https://www.youtube.com/watch?v=cgknOnS4EUg

http://discussie.afterdawn.com/t.cfm/f-229/handleiding_spotweb_op_windows-891384/

**Comment by Rheimans** [comment]
Does this help? I looked up an old code i used when the database was faulty. ran same code but with retrieve.php.


[~] # cd /share/Web/spotweb;/mnt/ext/opt/apache/bin/php -c /php.ini retrieve.php
Last retrieve at Mon 12 Oct 2015 06:05:03 AM CST
Retrieving new Spots from server reader.extremeusenet.nl...
Appr. Message count:    2689109
First message number:   2
Last message number:    2689111
Current article number: 2682636

Retrieving 2682636 till 2687637
getHeader(): Failed to retrieve article: <0rpY1sbFam07t0aVgrnO6@spot.net>

getHeader(): Failed to retrieve article: <87zeXuRxICgq9oaVgju30@spot.net>

getHeader(): Failed to retrieve article: <ALKS3MKD4sczd8aVgmX1Z@spot.net>

getHeader(): Failed to retrieve article: <kgjp6tyHSzY098aVgzAfz@spot.net>
SpotWeb v0.67.28.31 on PHP v5.5.29 crashed

Fatal error occured while connecting to the newsserver:
  (-1) Failed to read from socket...! [response: ""]


#0 /share/CACHEDEV1_DATA/.qpkg/spotweb/spotweb/NNTP/Protocol/Client.php(296): Ne                                                                               t_NNTP_Protocol_Client->throwError('Failed to read ...')
#1 /share/CACHEDEV1_DATA/.qpkg/spotweb/spotweb/NNTP/Protocol/Client.php(279): Ne                                                                               t_NNTP_Protocol_Client->_getStatusResponse()
#2 /share/CACHEDEV1_DATA/.qpkg/spotweb/spotweb/NNTP/Protocol/Client.php(1140): N                                                                               et_NNTP_Protocol_Client->_sendCommand('HEAD <kgjp6tyHS...')
#3 /share/CACHEDEV1_DATA/.qpkg/spotweb/spotweb/NNTP/Client.php(515): Net_NNTP_Pr                                                                               otocol_Client->cmdHead('<kgjp6tyHSzY098...')
#4 /share/CACHEDEV1_DATA/.qpkg/spotweb/spotweb/lib/services/Nntp/Services_Nntp_E                                                                               ngine.php(282): Net_NNTP_Client->getHeader('<kgjp6tyHSzY098...')
#5 /share/CACHEDEV1_DATA/.qpkg/spotweb/spotweb/lib/services/Nntp/Services_Nntp_S                                                                               potReading.php(160): Services_Nntp_Engine->getHeader('<kgjp6tyHSzY098...')
#6 /share/CACHEDEV1_DATA/.qpkg/spotweb/spotweb/lib/services/Retriever/Services_R                                                                               etriever_Spots.php(398): Services_Nntp_SpotReading->readFullSpot('kgjp6tyHSzY098                                                                               a...')
#7 /share/CACHEDEV1_DATA/.qpkg/spotweb/spotweb/lib/services/Retriever/Services_R                                                                               etriever_Base.php(227): Services_Retriever_Spots->process(Array, '2682636', 2687                                                                               637, 1445453581.5)
#8 /share/CACHEDEV1_DATA/.qpkg/spotweb/spotweb/lib/services/Retriever/Services_R                                                                               etriever_Base.php(319): Services_Retriever_Base->loopTillEnd('2682636', '5000')
#9 /share/CACHEDEV1_DATA/.qpkg/spotweb/spotweb/retrieve.php(154): Services_Retri                                                                               ever_Base->perform()
#10 {main}

Finished retrieving spots.

**Comment by mesa57** [comment]
Try to connect to you're provider without ssl.

**Comment by Rheimans** [comment]
I changed it to the normal port and TLS.

it now says this.

[~] # cd /share/Web/spotweb;/mnt/ext/opt/apache/bin/php -c /php.ini retrieve.php
Last retrieve at Mon 12 Oct 2015 06:05:03 AM CST
Retrieving new Spots from server reader.extremeusenet.nl...
SpotWeb v0.67.28.31 on PHP v5.5.29 crashed

Fatal error occured while connecting to the newsserver:
  (-1) Error while connecting to server (server did not respond) [response: ""] [response: ""]

#0 /share/CACHEDEV1_DATA/.qpkg/spotweb/spotweb/lib/services/Nntp/Services_Nntp_Engine.php(120): Services_Nntp_Engine->connect()
#1 /share/CACHEDEV1_DATA/.qpkg/spotweb/spotweb/lib/services/Retriever/Services_Retriever_Base.php(112): Services_Nntp_Engine->selectGroup('free.pt')
#2 /share/CACHEDEV1_DATA/.qpkg/spotweb/spotweb/lib/services/Retriever/Services_Retriever_Base.php(280): Services_Retriever_Base->connect(Array)
#3 /share/CACHEDEV1_DATA/.qpkg/spotweb/spotweb/retrieve.php(154): Services_Retriever_Base->perform()
#4 {main}

Finished retrieving spots.

Seems like it keeps crashing when its retrieving spots?

**Comment by mesa57** [comment]
Normal port (119) should not use TLS.

**Comment by Rheimans** [comment]
Hmmm, i can change from SSL to TLS. So i have to keep SSL switch on but put in the port 119?

**Comment by Rheimans** [comment]
Its possible its working. It takes longer to finish now, i tried running the following: cd /share/Web/spotweb;/mnt/ext/opt/apache/bin/php -c /php.ini retrieve.php and it said it was already running. So it could ne working now. It just has to retrieve over a week worth of spots.

**Comment by Sweepr** [comment]
119 is unencrypted , 443 or 563 depending on the USP is encrypted, (SSL), be sure to forward the ports in your firewall and router too.

SSL is broken and does give problems on some NAS devices.

**Comment by Rheimans** [comment]
Its working again. the 1 week posts are going away. and im now on 2 days ago posts.

Just have to run retrieve.php a few times to catch up. And wait for the database to show the changes.

Its weird that downloading spots for spotweb or spotnet or w/e software i cant use ssl to download. But when im downloading the actual files it does use ssl.

Thanks for all the support and help!

**Comment by Sweepr** [comment]
If you retrieve full comments, and full spots it takes longer, you can also set the start date for retrieval to one week in the past,

Not retrieve since 01/01/2009. ;-)

**Comment by Rheimans** [comment]
Heheh.

Anyways, it still shows a few errors and a crash still.

[/share/Web/spotweb] # cd /share/Web/spotweb;/mnt/ext/opt/apache/bin/php -c /php                            .ini retrieve.php
Last retrieve at Mon 12 Oct 2015 06:05:03 AM CST
Retrieving new Spots from server reader.extremeusenet.nl...
Appr. Message count:    2689370
First message number:   2
Last message number:    2689372
Current article number: 2682636

Retrieving 2682636 till 2687637
getBody(): Failed to retrieve article: <NV14vKqHsXgrIcfVgz0cw@spot.net>

getBody(): Failed to retrieve article: <SGbyfUGNHLkbJQfVg87UQ@spot.net>

getBody(): Failed to retrieve article: <4i4ashgoFPUqpUfVgHBna@spot.net>

getBody(): Failed to retrieve article: <hfrw9i1jlVswqwfVgaUR3@spot.net>

getBody(): Failed to retrieve article: <Xhr5NqgDAQQwK8fVgBP8s@spot.net>

getBody(): Failed to retrieve article: <YpCe7DummOgdK0fVg8vDj@spot.net>

getBody(): Failed to retrieve article: <EWuDypurMso0a8fVgWeh9@spot.net>

getBody(): Failed to retrieve article: <5SjzeeXDqLU57gfVgXS8J@spot.net>

getBody(): Failed to retrieve article: <qDSE4qmFsXEEN8fVgLRGt@spot.net>

getBody(): Failed to retrieve article: <bHignSscsFwvtsgVgImHi@spot.net>

getBody(): Failed to retrieve article: <BO5HNpg1IXw4p0gVgjQDA@spot.net>

getBody(): Failed to retrieve article: <pJjdE0KvMBoqPogVguxW2@spot.net>

getBody(): Failed to retrieve article: <sgPycZr3Qa0PjMhVgYcu7@spot.net>
 (parsed: 5000, in DB: 1, signed: 4954, invalid: 46, rtntn.skip: 0, mod: 0, full: 4954, total: 5001)

SpotWeb v0.67.28.31 on PHP v5.5.29 crashed

Fatal error occured retrieving reports:
  23000: 1062: Duplicate entry '0rpY1sbFam07t0aVgrnO6@spot.net' for key 'idx_spots_1'



#0 /share/CACHEDEV1_DATA/.qpkg/spotweb/spotweb/lib/dao/Base/Dao_Base_Spot.php(432): dbeng_pdo->batchInsert(Array, 'INSERT INTO spo...', Array, Array)
#1 /share/CACHEDEV1_DATA/.qpkg/spotweb/spotweb/lib/services/Retriever/Services_Retriever_Spots.php(605): Dao_Base_Spot->addSpots(Array, Array)
#2 /share/CACHEDEV1_DATA/.qpkg/spotweb/spotweb/lib/services/Retriever/Services_Retriever_Base.php(227): Services_Retriever_Spots->process(Array, '2682636', 2687637, 1445509223.56)
#3 /share/CACHEDEV1_DATA/.qpkg/spotweb/spotweb/lib/services/Retriever/Services_Retriever_Base.php(319): Services_Retriever_Base->loopTillEnd('2682636', '5000')
#4 /share/CACHEDEV1_DATA/.qpkg/spotweb/spotweb/retrieve.php(154): Services_Retriever_Base->perform()
#5 {main}

Finished retrieving spots

**Comment by Rheimans** [comment]
this part is new tough

(parsed: 5000, in DB: 1, signed: 4954, invalid: 46, rtntn.skip: 0, mod: 0, full: 4954, total: 5001)

**Comment by Rheimans** [comment]
i ran a --force command, its now showing all new spots from even today.

**Comment by mesa57** [comment]
Nice, looks again like the already reported SSL problem with higher php versions.

**Comment by Rheimans** [comment]
thanks for all your help! Its now working good again.

I do have one more question. How can i change the 1 hour retrieve time to say 5 minutes. Because 1 hour is really long to wait. And i dont want to keep doing a manual retrieve.

**Comment by Sweepr** [comment]
Setup a cronjob.. search how to on google
